#ifndef ALPHALAB_ACL07_GATE_STATUS_MQH
#define ALPHALAB_ACL07_GATE_STATUS_MQH
enum ENUM_ACL07_GATE_STATUS { ACL07_GATE_PASS=0, ACL07_GATE_FAIL=1, ACL07_GATE_UNKNOWN=2, ACL07_GATE_NOT_APPLICABLE=3 };
#endif
