#ifndef ALPHALAB_ACL07_CONSTANTS_MQH
#define ALPHALAB_ACL07_CONSTANTS_MQH
#define ACL07_PHASE_ID "ACL-07"
#define ACL07_CLAIM_CEILING "VALIDATION_DECISION_REFERENCE_ONLY"
#define ACL07_HANDOFF_IN "ACL06_TO_ACL07"
#define ACL07_HANDOFF_OUT "ACL07_TO_ACL08"
#endif
