#ifndef __SF10_RESEARCH_ENUMS_MQH__
#define __SF10_RESEARCH_ENUMS_MQH__
#include "../Outcome/SF09_OutcomeRecord.mqh"

enum ENUM_SF10_OBJECTIVE_MODE
{
   SF10_OBJECTIVE_EXPECTANCY=0,
   SF10_OBJECTIVE_CONSERVATIVE=1,
   SF10_OBJECTIVE_STABILITY_WEIGHTED=2,
   SF10_OBJECTIVE_TAIL_AWARE=3
};

enum ENUM_SF10_FIDELITY_PRESET
{
   SF10_FIDELITY_FAST_SCREEN=0,
   SF10_FIDELITY_BAR_VALIDATION=1,
   SF10_FIDELITY_EVERY_TICK=2,
   SF10_FIDELITY_REAL_TICKS=3
};

enum ENUM_SF10_EXPORT_DETAIL
{
   SF10_EXPORT_NONE=0,
   SF10_EXPORT_PASS_SUMMARY=1,
   SF10_EXPORT_SELECTED_FULL=2,
   SF10_EXPORT_ALWAYS_FULL=3
};

enum ENUM_SF10_PASS_STATUS
{
   SF10_PASS_VALID=0,
   SF10_PASS_REJECTED_MIN_SAMPLE=1,
   SF10_PASS_REJECTED_EXPECTANCY=2,
   SF10_PASS_REJECTED_FILL_RATE=3,
   SF10_PASS_REJECTED_RECONCILIATION=4,
   SF10_PASS_REJECTED_NONFINITE=5
};

enum ENUM_SF10_DIFFERENTIAL_STATUS
{
   SF10_DIFF_MATCH=0,
   SF10_DIFF_WITHIN_TOLERANCE=1,
   SF10_DIFF_MISMATCH=2,
   SF10_DIFF_MISSING_SIDE=3
};

string SF10_PassStatusName(const ENUM_SF10_PASS_STATUS status)
{
   switch(status)
   {
      case SF10_PASS_VALID:return "valid";
      case SF10_PASS_REJECTED_MIN_SAMPLE:return "rejected_min_sample";
      case SF10_PASS_REJECTED_EXPECTANCY:return "rejected_expectancy";
      case SF10_PASS_REJECTED_FILL_RATE:return "rejected_fill_rate";
      case SF10_PASS_REJECTED_RECONCILIATION:return "rejected_reconciliation";
      case SF10_PASS_REJECTED_NONFINITE:return "rejected_nonfinite";
   }
   return "unknown";
}
#endif
