#ifndef __SF11_STATISTICS_ENUMS_MQH__
#define __SF11_STATISTICS_ENUMS_MQH__
enum ENUM_SF11_REPORT_STATUS
{
   SF11_REPORT_VALID=1,
   SF11_REPORT_INSUFFICIENT_SAMPLE=2,
   SF11_REPORT_INVALID_LINEAGE=3,
   SF11_REPORT_INVALID_NONFINITE=4,
   SF11_REPORT_UNMATCHED=5,
   SF11_REPORT_PARTIAL_MATCH=6,
   SF11_REPORT_FAILED=7
};
enum ENUM_SF11_NULL_METHOD
{
   SF11_NULL_EXACT_STRATIFIED_CYCLIC=1,
   SF11_NULL_EXACT_STRATIFIED_HASHED=2,
   SF11_NULL_WITHIN_DAY_TIME_SHIFT=3,
   SF11_NULL_ROLE_RANDOMIZATION=4,
   SF11_NULL_MATCHED_RANDOM_ENTRY=5
};
enum ENUM_SF11_INTERVAL_KIND
{
   SF11_INTERVAL_NORMAL_MEAN=1,
   SF11_INTERVAL_WILSON_PROPORTION=2,
   SF11_INTERVAL_CLUSTER_BOOTSTRAP_PERCENTILE=3
};
#endif
