from tools.repository_paths import find_repository_root
from pathlib import Path
REPO_ROOT=find_repository_root(__file__)
REGISTRY_ROOT=REPO_ROOT/'registry/acl_os/acl_06'
SCHEMA_ROOT=REGISTRY_ROOT/'schemas/v1'
POLICY_ROOT=REGISTRY_ROOT/'policies/v1'
PHASE_ID='ACL-06'; PHASE_VERSION='1.0.0'; ORCHESTRATOR_VERSION='1.0.0'
CLAIM_CEILING='BOUNDED_RESEARCH_EXECUTION_REFERENCE_ONLY'
HANDOFF_IN='ACL05_TO_ACL06'; HANDOFF_OUT='ACL06_TO_ACL07'
AUTHORITY_ACTION='ACL06_EXECUTE_BOUNDED_RESEARCH'
REQUIRED_UPSTREAM_ACTIONS={'PLAN_RESEARCH_DAG','REGISTER_TASK_CONTRACTS','EXECUTE_BOUNDED_RESEARCH'}
FORBIDDEN_UPSTREAM_ACTIONS={'MUTATE_BATCH','MUTATE_SETUP_BEHAVIOR','PROMOTE_DIAGNOSTIC_CANDIDATE','INFER_ALPHA_FROM_FREEZE','AUTHORIZE_EXECUTION','ACTIVATE_CAPITAL'}
TASK_TYPES=('VERIFY_FROZEN_BATCH','MATERIALIZE_DATASET','COMPILE_MATURE_LABELS','ASSIGN_PURGED_SPLITS','EVALUATE_CANDIDATE_SEGMENT','AGGREGATE_CANDIDATE','PACKAGE_RESEARCH_RESULTS','BUILD_ACL07_HANDOFF')
SEGMENTS=('TRAIN','VALIDATION','TEST')
TASK_EXECUTOR_ID='ACL06_REFERENCE_EXECUTOR_V1'
