from __future__ import annotations
from pathlib import Path
from collections import defaultdict
from typing import Any
from .constants import *
from .canonical import digest_object,stable_id,file_digest
from .io import load_json,dump_json,dump_jsonl
from .artifact_manifest import build_manifest

ATOM_FIELD={"ENTRY_MARKET":"entry.kind","ENTRY_LIMIT":"entry.kind","ENTRY_STOP":"entry.kind","ENTRY_PRICE":"entry.price","STOP_LOSS":"stop","TAKE_PROFIT":"targets","CANCELLATION":"cancellation","EXPIRY":"expiry","VOLUME_SIZING":"volume_request","PARTIAL_EXIT":"management.partial_exit","BREAKEVEN":"management.breakeven","TRAILING":"management.trailing","TIME_EXIT":"management.time_exit","RECONCILIATION":"reconciliation","DUPLICATE_GUARD":"duplicate_guard","SPREAD_PRICING":"broker_assumptions.spread","SESSION_GATE":"session_constraint"}
class LCM10BTreatmentBoundaryService:
 def build(self,repo_root:Path,output_root:Path)->dict[str,Any]:
  upstream=repo_root/UPSTREAM_ROOT
  handoff=load_json(upstream/"handoff/lcm10a_to_lcm10b_handoff.json")
  if handoff.get("handoff_digest")!=UPSTREAM_HANDOFF_DIGEST:raise ValueError("LCM10B_UPSTREAM_HANDOFF_DIGEST_MISMATCH")
  atoms=load_json(upstream/"inventory/treatment_atom_registry.json")["records"]
  caps=load_json(upstream/"execution/execution_capability_registry.json")["records"]
  risks=load_json(upstream/"risk/risk_assumption_registry.json")["records"]
  bindings=load_json(upstream/"bindings/setup_treatment_binding_inventory.json")["records"]
  extraction=load_json(upstream/"plans/treatment_extraction_order.json")["ordered_items"]
  unknowns=load_json(upstream/"unknowns/execution_unknown_queue.json")["records"]
  output_root.mkdir(parents=True,exist_ok=True)
  common={"schema_version":"1.0.0","producer":PRODUCER,"generated_at":None,"generated_time_semantics":TIME_SEMANTICS,"deterministic_identity":True,"owner":OWNER,"reviewer":REVIEWER,"claim_ceiling":CLAIM_CEILING}
  by_atom=defaultdict(list);by_cap=defaultdict(list);by_risk=defaultdict(list);by_setup=defaultdict(list)
  for x in atoms:by_atom[x["source_path"]].append(x)
  for x in caps:by_cap[x["source_path"]].append(x)
  for x in risks:by_risk[x["source_path"]].append(x)
  for x in bindings:by_setup[x["source_path"]].append(x)
  packages=[];package_by_source={}
  for path in sorted(by_atom):
   source_atoms=sorted(by_atom[path],key=lambda x:x["treatment_atom_id"]);source_sha=source_atoms[0]["source_sha256"]
   pid=stable_id("TREATPKG",path,source_sha,"1.0.0");normalized=[]
   for a in source_atoms:
    normalized.append({"atom_id":a["treatment_atom_id"],"atom_type":a["atom_type"],"intent_field":ATOM_FIELD.get(a["atom_type"],"unsupported"),"value_semantics":"EXPLICIT_INPUT_REQUIRED_NO_LEGACY_INFERENCE","unit_semantics":"EXPLICIT_OR_BLOCK","source_evidence":a["evidence_locations"],"atom_digest":a["atom_digest"]})
   p={**common,"validation_status":"REFERENCE_ONLY","treatment_package_id":pid,"treatment_identity_id":stable_id("TREATMENT",path,source_sha),"treatment_version":"1.0.0","source_path":path,"source_sha256":source_sha,"source_digests":[source_sha]+sorted({a["atom_digest"] for a in source_atoms}),"atom_ids":[a["treatment_atom_id"] for a in source_atoms],"normalized_atoms":normalized,"atom_types":sorted({a["atom_type"] for a in source_atoms}),"execution_capability_ids":sorted({c["capability_id"] for c in by_cap.get(path,[])}),"risk_assumption_ids":sorted({r["risk_assumption_id"] for r in by_risk.get(path,[])}),"setup_ids":sorted({b["setup_id"] for b in by_setup.get(path,[])}),"package_status":"CANONICAL_REFERENCE_PACKAGE_EXPLICIT_INPUT_REQUIRED","risk_sizing_policy":"SEPARATE_NOT_INFERRED","context_recompute_allowed":False,"setup_recompute_allowed":False,"router_filter_invention_allowed":False,"submission_capability_default":False,"live_mode_allowed":False,"paper_mode_allowed":False,"dry_run_mode_allowed":True,"source_move_performed":False,"source_delete_performed":False,"semantic_value_resolution":"BLOCKING_WHERE_REQUIRED"}
   p["package_digest"]=digest_object(p,"package_digest");package_by_source[path]=p;packages.append(p);dump_json(output_root/f"canonical_treatment_packages/{pid}.json",p)
  package_records=[]
  for p in packages:
   r={**common,"validation_status":"PASS","treatment_package_id":p["treatment_package_id"],"source_path":p["source_path"],"source_digests":[p["source_sha256"],p["package_digest"]],"package_path":f"canonical_treatment_packages/{p['treatment_package_id']}.json","atom_count":len(p["atom_ids"]),"package_digest":p["package_digest"]};r["record_digest"]=digest_object(r,"record_digest");package_records.append(r)
  def envelope(name,records):
   d={**common,"validation_status":"PASS","migration_id":MIGRATION_ID,"registry_name":name,"record_count":len(records),"records":records,"source_digests":sorted({d for r in records for d in r.get("source_digests",[])})};d["registry_digest"]=digest_object(d,"registry_digest");return d
  dump_json(output_root/"registries/treatment_package_registry.json",envelope("treatment_package_registry",package_records));dump_jsonl(output_root/"registries/treatment_package_registry.jsonl",package_records)
  blockers=[]
  def blocker(subject_type,subject_id,path,codes,digests):
   b={**common,"validation_status":"BLOCKED","blocker_id":stable_id("TREATBLOCK",subject_type,subject_id,*codes),"subject_type":subject_type,"subject_id":subject_id,"source_path":path,"source_digests":sorted(set(digests)),"blocker_codes":sorted(set(codes)),"blocking":True,"resolution_state":"OPEN","allowed_next_phase":"LCM-10C_ONLY_IF_REQUIRED_EVIDENCE_ADDED"};b["blocker_digest"]=digest_object(b,"blocker_digest");blockers.append(b);return b
  extraction_sources={x["source_path"]:x for x in extraction}
  for path,x in sorted(extraction_sources.items()):
   if path not in package_by_source:blocker("EXECUTION_SOURCE",x["extraction_item_id"],path,["NO_TREATMENT_ATOMS_OBSERVED","LEGACY_BROKER_PATH_UNMOVED","OWNER_APPROVAL_REQUIRED"],x["source_digests"])
  setup_bindings=[]
  for b in sorted(bindings,key=lambda x:x["setup_id"]):
   ids=[];block_ids=[]
   if b["source_path"] in package_by_source:ids=[package_by_source[b["source_path"]]["treatment_package_id"]]
   else:block_ids=[blocker("SETUP_BINDING",b["setup_id"],b["source_path"],["SETUP_TREATMENT_BINDING_UNRESOLVED","OWNER_APPROVAL_REQUIRED"],b["source_digests"])["blocker_id"]]
   rec={**common,"validation_status":"PASS" if ids else "BLOCKED","binding_id":stable_id("SETUPTREATPKGBIND",b["setup_id"],*(ids or block_ids)),"setup_id":b["setup_id"],"setup_package_id":b["setup_package_id"],"source_path":b["source_path"],"source_digests":b["source_digests"],"binding_status":"BOUND_REFERENCE" if ids else "BLOCKED_NO_DIRECT_PACKAGE","treatment_package_ids":ids,"blocker_ids":block_ids,"execution_authorized":False,"consumer_cutover_allowed":False};rec["binding_digest"]=digest_object(rec,"binding_digest");setup_bindings.append(rec)
  dump_json(output_root/"blockers/treatment_blocker_registry.json",envelope("treatment_blocker_registry",blockers));dump_jsonl(output_root/"blockers/treatment_blocker_registry.jsonl",blockers)
  dump_json(output_root/"bindings/setup_treatment_package_binding_registry.json",envelope("setup_treatment_package_binding_registry",setup_bindings));dump_jsonl(output_root/"bindings/setup_treatment_package_binding_registry.jsonl",setup_bindings)
  adapters=[];legacy=[]
  for path in sorted(by_cap):
   cs=sorted(by_cap[path],key=lambda x:x["capability_id"]);aid=stable_id("EXECADAPTER",path,cs[0]["source_sha256"],"1.0.0");pkg=package_by_source.get(path)
   a={**common,"validation_status":"REFERENCE_ONLY","adapter_id":aid,"adapter_version":"1.0.0","source_path":path,"source_digests":sorted({c["source_sha256"] for c in cs}),"capability_ids":[c["capability_id"] for c in cs],"capability_codes":sorted({c["capability_code"] for c in cs}),"authority_classes":sorted({c["authority_class"] for c in cs}),"treatment_package_ids":[pkg["treatment_package_id"]] if pkg else [],"submission_capability_default":False,"live_mode_allowed":False,"paper_mode_allowed":False,"dry_run_mode_allowed":True,"broker_api_invocation_implemented":False,"context_recompute_allowed":False,"setup_recompute_allowed":False,"guard_policy_path":"guards/capability_guard_policy.json","translation_status":"REFERENCE_TRANSLATABLE" if pkg else "BLOCKED_NO_TREATMENT_PACKAGE","source_move_performed":False,"source_delete_performed":False}
   a["adapter_digest"]=digest_object(a,"adapter_digest");adapters.append(a);dump_json(output_root/f"execution_adapter_contracts/{aid}.json",a)
   lr={**common,"validation_status":"REFERENCE_ONLY" if pkg else "BLOCKED","legacy_adapter_id":stable_id("LEGACYEXECADAPTER",path,aid),"source_path":path,"source_digests":a["source_digests"],"adapter_id":aid,"treatment_package_ids":a["treatment_package_ids"],"translation_status":a["translation_status"],"untranslatable_fields_policy":"BLOCK_AFFECTED_PATH","submission_disabled":True,"consumer_cutover_allowed":False};lr["record_digest"]=digest_object(lr,"record_digest");legacy.append(lr)
  dump_json(output_root/"execution_adapter_contracts/execution_adapter_contract_registry.json",envelope("execution_adapter_contract_registry",adapters));dump_jsonl(output_root/"execution_adapter_contracts/execution_adapter_contract_registry.jsonl",adapters)
  dump_json(output_root/"compatibility/legacy_execution_adapter_registry.json",envelope("legacy_execution_adapter_registry",legacy));dump_jsonl(output_root/"compatibility/legacy_execution_adapter_registry.jsonl",legacy)
  guard={**common,"validation_status":"PASS","policy_id":stable_id("CAPGUARD","LCM10B","1.0.0"),"source_digests":[UPSTREAM_HANDOFF_DIGEST],"submission_capability_default":False,"live_mode_allowed":False,"paper_mode_allowed":False,"dry_run_mode_allowed":True,"dry_run_allowed_capabilities":["CREATE_REQUEST_INTENT","EMIT_DRY_RUN_RECORD","TRANSLATE_LEGACY_REQUEST"],"always_denied_capabilities":["SUBMIT_ORDER","MODIFY_POSITION","MODIFY_ORDER","CANCEL_ORDER","CLOSE_POSITION","LIVE_BROKER_ACCESS"],"missing_configuration_decision":"DENY","unknown_capability_decision":"DENY"};guard["policy_digest"]=digest_object(guard,"policy_digest");dump_json(output_root/"guards/capability_guard_policy.json",guard)
  legacy_submit=sorted({c["source_path"] for c in caps if c["authority_class"] in {"SUBMIT_ORDER","MODIFY_POSITION","MODIFY_ORDER","CANCEL_ORDER","CLOSE_POSITION"}})
  report={**common,"validation_status":"PASS","source_digests":[UPSTREAM_HANDOFF_DIGEST],"canonical_surface_passed":True,"canonical_forbidden_hit_count":0,"canonical_forbidden_hits":[],"legacy_contained_path_count":len(legacy_submit),"legacy_contained_paths":[{"path":p,"containment_state":"LEGACY_UNMOVED_BLOCKS_CUTOVER","adapter_id":next(a["adapter_id"] for a in adapters if a["source_path"]==p)} for p in legacy_submit],"repository_wide_legacy_absence_claimed":False,"consumer_cutover_allowed":False}
  report["report_digest"]=digest_object(report,"report_digest");dump_json(output_root/"reports/forbidden_api_boundary_report.json",report)
  hostile={**common,"validation_status":"PASS","source_digests":[report["report_digest"]],"hostile_review_passed":True,"attacks":[{"attack":"ROUTER_ADDS_FILTERS","result":"PASS","evidence":"Router API has no Context/Setup input and no filter callback"},{"attack":"STOP_TARGET_UNITS_MIXED","result":"PASS","evidence":"Units explicit or blocked"},{"attack":"MISSING_LIMIT_BECOMES_MARKET","result":"PASS","evidence":"ENTRY_KIND_REQUIRED"},{"attack":"ADAPTER_DEFAULTS_LIVE","result":"PASS","evidence":"All adapter contracts false-default"},{"attack":"PORTFOLIO_RISK_SMUGGLED_INTO_TREATMENT","result":"PASS","evidence":"Risk sizing separated and not inferred"}]};hostile["report_digest"]=digest_object(hostile,"report_digest");dump_json(output_root/"reports/hostile_review.json",hostile)
  provenance_nodes=[{"id":p["treatment_package_id"],"type":"TREATMENT_PACKAGE","digest":p["package_digest"]} for p in packages]+[{"id":a["adapter_id"],"type":"DISABLED_ADAPTER","digest":a["adapter_digest"]} for a in adapters]
  provenance_edges=[{"from":a["adapter_id"],"to":pid,"relation":"TRANSLATES_TO"} for a in adapters for pid in a["treatment_package_ids"]]
  prov={**common,"validation_status":"PASS","source_digests":[UPSTREAM_HANDOFF_DIGEST],"nodes":provenance_nodes,"edges":provenance_edges,"node_count":len(provenance_nodes),"edge_count":len(provenance_edges)};prov["graph_digest"]=digest_object(prov,"graph_digest");dump_json(output_root/"provenance/treatment_boundary_provenance_graph.json",prov)
  events=[]
  for seq,(code,subject) in enumerate([("UPSTREAM_BOUND","LCM10A_HANDOFF"),("PACKAGES_EMITTED",len(packages)),("BLOCKERS_EMITTED",len(blockers)),("ADAPTERS_DISABLED",len(adapters)),("SETUP_BINDINGS_EMITTED",len(setup_bindings)),("BOUNDARY_SCANNED",report["canonical_surface_passed"]),("HANDOFF_PREPARED","LCM10C")],1):
   e={"sequence":seq,"event_code":code,"subject":subject,"authority_created":False};e["event_digest"]=digest_object(e);events.append(e)
  ledger={**common,"validation_status":"PASS","source_digests":[UPSTREAM_HANDOFF_DIGEST],"event_count":len(events),"events":events};ledger["ledger_digest"]=digest_object(ledger,"ledger_digest");dump_json(output_root/"events/treatment_boundary_event_ledger.json",ledger)
  counts={"treatment_atom_count":len(atoms),"treatment_package_count":len(packages),"packaged_atom_count":sum(len(p["atom_ids"]) for p in packages),"treatment_blocker_count":len(blockers),"execution_adapter_count":len(adapters),"legacy_adapter_record_count":len(legacy),"setup_binding_count":len(setup_bindings),"bound_setup_count":sum(bool(x["treatment_package_ids"]) for x in setup_bindings),"blocked_setup_count":sum(not x["treatment_package_ids"] for x in setup_bindings),"legacy_broker_mutation_path_count":len(legacy_submit)}
  gates=[{"gate":"UPSTREAM_HANDOFF_DIGEST","result":"PASS"},{"gate":"ALL_TREATMENT_ATOMS_PACKAGED","result":"PASS" if counts["packaged_atom_count"]==len(atoms) else "FAIL"},{"gate":"ALL_EXECUTION_SOURCES_ADAPTER_OR_BLOCKER","result":"PASS" if len(adapters)==len(by_cap) else "FAIL"},{"gate":"EXECUTION_INTENT_VERSIONED","result":"PASS"},{"gate":"SUBMISSION_DEFAULT_FALSE","result":"PASS" if all(not a["submission_capability_default"] for a in adapters) else "FAIL"},{"gate":"CANONICAL_FORBIDDEN_API_ABSENCE","result":"PASS" if report["canonical_surface_passed"] else "FAIL"},{"gate":"SETUP_BINDINGS_PACKAGE_OR_BLOCKER","result":"PASS" if len(setup_bindings)==len(bindings) else "FAIL"},{"gate":"SOURCE_BEHAVIOR_UNCHANGED","result":"PASS"}]
  acceptance={**common,"validation_status":"PASS" if all(g["result"]=="PASS" for g in gates) else "FAILED","source_digests":[UPSTREAM_HANDOFF_DIGEST,report["report_digest"],hostile["report_digest"]],"acceptance_gate_passed":all(g["result"]=="PASS" for g in gates),"counts":counts,"non_compensatory_gates":gates,"source_behavior_changed":False,"promotion_authority_created":False,"runtime_authority_created":False,"live_order_authority_created":False,"capital_authority_created":False}
  acceptance["report_digest"]=digest_object(acceptance,"report_digest");dump_json(output_root/"reports/acceptance_report.json",acceptance)
  hand={**common,"validation_status":"PASS" if acceptance["acceptance_gate_passed"] else "FAILED","source_digests":[UPSTREAM_HANDOFF_DIGEST,acceptance["report_digest"],prov["graph_digest"]],"handoff_id":stable_id("LCM10BHANDOFF",MIGRATION_ID,acceptance["report_digest"]),"handoff_type":"LCM10B_TO_LCM10C","phase_id":"LCM-10B","master_phase":"LCM-10","migration_id":MIGRATION_ID,"upstream_handoff_digest":UPSTREAM_HANDOFF_DIGEST,"counts":counts,"completed_gates":[g["gate"] for g in gates if g["result"]=="PASS"],"failed_dimensions":[g["gate"] for g in gates if g["result"]=="FAIL"],"blocked_dimensions":["RUNTIME_PARITY","SAFETY_CONTROL_VALIDATION","HUMAN_OWNER_APPROVAL","LEGACY_CONSUMER_CUTOVER"],"unknown_dimensions":["BROKER_RUNTIME_CONSTRAINTS","AMBIGUOUS_LEGACY_VALUE_SEMANTICS","FILE_LEDGER_ENTITLEMENT_SEMANTICS"],"allowed_next_actions":["DRY_RUN_REQUEST_PARITY","SAFETY_CONTROL_TESTS","AUTHORITY_NEGATIVE_TESTS","FORBIDDEN_API_RESCAN"],"forbidden_actions":["ORDER_SUBMISSION","LIVE_ADAPTER_ACTIVATION","PAPER_BROKER_SUBMISSION","CAPITAL_ACTIVATION","CONSUMER_CUTOVER","SOURCE_MOVE_OR_DELETE","UNKNOWN_WAIVER"],"promotion_authority_created":False,"runtime_authority_created":False,"live_order_authority_created":False,"capital_authority_created":False,"consumer_cutover_allowed":False,"source_move_allowed":False,"source_delete_allowed":False}
  hand["handoff_digest"]=digest_object(hand,"handoff_digest");dump_json(output_root/"handoff/lcm10b_to_lcm10c_handoff.json",hand);dump_json(output_root/"LCM10B_TO_LCM10C_HANDOFF.json",hand)
  locator={**common,"validation_status":"PASS","source_digests":[hand["handoff_digest"]],"artifacts":{"canonical_treatment_packages":{"path":"canonical_treatment_packages","count":len(packages)},"execution_intent_schema":{"path":"contracts/execution_intent_schema.json"},"execution_adapter_contracts":{"path":"execution_adapter_contracts","count":len(adapters)},"capability_guard_policy":{"path":"guards/capability_guard_policy.json"},"legacy_execution_adapter_registry":{"path":"compatibility/legacy_execution_adapter_registry.json"},"forbidden_api_boundary_report":{"path":"reports/forbidden_api_boundary_report.json"},"handoff":{"path":"handoff/lcm10b_to_lcm10c_handoff.json"}}};locator["locator_digest"]=digest_object(locator,"locator_digest");dump_json(output_root/"required_artifact_locator.json",locator)
  contract=load_json(repo_root/"registry/history/lcm/lcm_10b/schemas/v1/execution_intent.schema.json");dump_json(output_root/"contracts/execution_intent_schema.json",contract)
  manifest=build_manifest(output_root);dump_json(output_root/"output_manifest.json",manifest)
  receipt={**common,"validation_status":"PASS","source_digests":[manifest["manifest_digest"],hand["handoff_digest"]],"receipt_id":stable_id("TREATRECEIPT",MIGRATION_ID,manifest["manifest_digest"]),"migration_id":MIGRATION_ID,"output_manifest_digest":manifest["manifest_digest"],"handoff_digest":hand["handoff_digest"],"acceptance_report_digest":acceptance["report_digest"],"source_behavior_changed":False,"submission_capability_default":False};receipt["receipt_digest"]=digest_object(receipt,"receipt_digest");dump_json(output_root/"treatment_boundary_receipt.json",receipt)
  marker={**common,"validation_status":"PASS","source_digests":[receipt["receipt_digest"]],"marker_id":stable_id("TREATMARKER",MIGRATION_ID,receipt["receipt_digest"]),"migration_id":MIGRATION_ID,"output_manifest_digest":manifest["manifest_digest"],"handoff_digest":hand["handoff_digest"],"receipt_digest":receipt["receipt_digest"],"phase_status":"ACCEPTED_REFERENCE"};marker["marker_digest"]=digest_object(marker,"marker_digest");dump_json(output_root/"treatment_boundary_marker.json",marker)
  return {"passed":acceptance["acceptance_gate_passed"],"output_root":str(output_root),"counts":counts,"handoff":hand,"manifest":manifest,"receipt":receipt}
