from .constants import *
from .channels import buffer_mapping

REASON_CODES=(
'FP_IND_INIT_STARTED','FP_IND_INPUT_VALIDATED','FP_IND_UPSTREAM_VALIDATED','FP_IND_INSTANCE_CREATED','FP_IND_CHECKPOINT_ABSENT','FP_IND_CHECKPOINT_RESTORED','FP_IND_CHECKPOINT_VERSION_MISMATCH','FP_IND_CHECKPOINT_INSTANCE_MISMATCH','FP_IND_CHECKPOINT_CONFIG_MISMATCH','FP_IND_CHECKPOINT_COMPOSITION_MISMATCH','FP_IND_CHECKPOINT_PAYLOAD_MISMATCH','FP_IND_REBUILD_REQUIRED','FP_IND_ENGINE_READY','FP_IND_INCREMENTAL_PROCESSED','FP_IND_INCREMENTAL_CHUNK_REMAINING','FP_IND_INCREMENTAL_LAG','FP_IND_TIMER_HEARTBEAT','FP_IND_CHART_EVENT_OBSERVED','FP_IND_HISTORY_NOT_READY','FP_IND_DATA_BLOCKED','FP_IND_UPSTREAM_BLOCKED','FP_IND_DEINIT_REQUESTED','FP_IND_DEINIT_COMPLETED','FP_IND_UPSTREAM_STATUS_MISSING','FP_IND_RUNTIME_AUTHORITY_NONE')

def contract_registry():
    return {'phase_id':PHASE_ID,'phase_version':PHASE_VERSION,'indicator_product_id':INDICATOR_PRODUCT_ID,'schema_version':INDICATOR_SCHEMA_VERSION,'composition_version':COMPOSITION_VERSION,'checkpoint_version':CHECKPOINT_VERSION,'output_version':OUTPUT_VERSION,'runtime_authority':NO_RUNTIME_AUTHORITY,'upstream':EXPECTED_UPSTREAM,'buffers':buffer_mapping(),'reason_codes':REASON_CODES}
