from enum import Enum
class StrEnum(str,Enum):
    def __str__(self): return self.value
class LedgerEventType(StrEnum):
    SIGNAL_INGESTED="SIGNAL_INGESTED"; DUPLICATE_SIGNAL_IGNORED="DUPLICATE_SIGNAL_IGNORED"; SIGNAL_COLLISION_BLOCKED="SIGNAL_COLLISION_BLOCKED"
    GATE_DECISION_ATTACHED="GATE_DECISION_ATTACHED"; ELIGIBILITY_EVALUATED="ELIGIBILITY_EVALUATED"; CONTENDER_REGISTERED="CONTENDER_REGISTERED"
    QUOTA_RESERVED="QUOTA_RESERVED"; RESERVATION_SUPERSEDED="RESERVATION_SUPERSEDED"; SIGNAL_SUPPRESSED_BY_QUOTA="SIGNAL_SUPPRESSED_BY_QUOTA"
    SIGNAL_SUPPRESSED_BY_WW="SIGNAL_SUPPRESSED_BY_WW"; SIGNAL_BLOCKED="SIGNAL_BLOCKED"; SESSION_SEALED="SESSION_SEALED"
    CHECKPOINT_CREATED="CHECKPOINT_CREATED"; CHECKPOINT_REJECTED="CHECKPOINT_REJECTED"; REBUILD_COMPLETED="REBUILD_COMPLETED"
class LedgerDisposition(StrEnum):
    OBSERVED="OBSERVED"; ELIGIBLE_CONTENDER="ELIGIBLE_CONTENDER"; QUOTA_WINNER="QUOTA_WINNER"; SUPPRESSED_BY_QUOTA="SUPPRESSED_BY_QUOTA"
    SUPPRESSED_BY_WW="SUPPRESSED_BY_WW"; BLOCKED="BLOCKED"; NOT_APPLICABLE="NOT_APPLICABLE"
class EligibilityOutcome(StrEnum):
    ELIGIBLE="ELIGIBLE"; SUPPRESSED_BY_WW="SUPPRESSED_BY_WW"; BLOCKED_DATA="BLOCKED_DATA"; BLOCKED_RELATION_DISABLED="BLOCKED_RELATION_DISABLED"; BLOCKED_PRECHECK="BLOCKED_PRECHECK"
class PrecheckState(StrEnum):
    PASSED="PASSED"; BLOCKED="BLOCKED"; NOT_REQUIRED="NOT_REQUIRED"
class ReservationFinality(StrEnum):
    PROVISIONAL="PROVISIONAL"; FINAL="FINAL"
class SessionSealState(StrEnum):
    OPEN="OPEN"; SEALED="SEALED"
class ReservationState(StrEnum):
    AVAILABLE="AVAILABLE"; RESERVED="RESERVED"
class CheckpointDecision(StrEnum):
    ACCEPT="ACCEPT"; REJECT_VERSION="REJECT_VERSION"; REJECT_CONFIG="REJECT_CONFIG"; REJECT_HASH="REJECT_HASH"; REJECT_CHAIN_HEAD="REJECT_CHAIN_HEAD"; REBUILD_REQUIRED="REBUILD_REQUIRED"
class EngineHealth(StrEnum):
    READY="READY"; DEGRADED="DEGRADED"; BLOCKED="BLOCKED"
