from .constants import *
from .enums import *
REASON_CODES=(
"FP_LDG_SIGNAL_INGESTED","FP_LDG_DUPLICATE_SIGNAL_IGNORED","FP_LDG_SIGNAL_ID_COLLISION","FP_LDG_GATE_DECISION_ATTACHED",
"FP_LDG_ELIGIBLE","FP_LDG_SUPPRESSED_BY_WW","FP_LDG_BLOCKED_DATA","FP_LDG_BLOCKED_RELATION_DISABLED","FP_LDG_BLOCKED_PRECHECK",
"FP_LDG_CONTENDER_REGISTERED","FP_LDG_QUOTA_RESERVED_EARLIEST_HUNT","FP_LDG_RESERVATION_STABLE","FP_LDG_RESERVATION_SUPERSEDED_BY_EARLIER_HUNT",
"FP_LDG_SUPPRESSED_BY_QUOTA","FP_LDG_NO_ELIGIBLE_CONTENDER","FP_LDG_SESSION_SEALED","FP_LDG_CONSUMPTION_POLICY_UNSET",
"FP_LDG_CHECKPOINT_ACCEPTED","FP_LDG_CHECKPOINT_VERSION_MISMATCH","FP_LDG_CHECKPOINT_CONFIG_MISMATCH","FP_LDG_CHECKPOINT_CHAIN_HEAD_MISMATCH","FP_LDG_CHECKPOINT_PAYLOAD_HASH_MISMATCH",
"FP_LDG_REBUILD_COMPLETED","FP_LDG_EVENT_CHAIN_INVALID"
)
CONTRACTS=("LedgerConfig","PairSessionQuotaKey","EligibilityEvidence","ArbitrationContender","QuotaReservation","ArbitrationDecision","LedgerEvent","SignalLedgerRecord","LedgerSnapshot","LedgerCheckpoint","CheckpointValidation")
