#ifndef __SF02_RUNTIME_ENUMS_MQH__
#define __SF02_RUNTIME_ENUMS_MQH__

enum ENUM_SF02_RUN_MODE
{
   SF02_MODE_VISUAL_ANATOMY = 0,
   SF02_MODE_ANATOMY_AUDIT = 1,
   SF02_MODE_OUTCOME_STUDY = 2,
   SF02_MODE_CANDIDATE_MATRIX = 3,
   SF02_MODE_TESTER_EXECUTION = 4,
   SF02_MODE_PAPER = 5,
   SF02_MODE_LIVE_DISABLED = 6,
   SF02_MODE_EXPORT_TRAINING_DATA = 7,
   SF02_MODE_ONNX_INFERENCE = 8
};

enum ENUM_SF02_RUNTIME_STATE
{
   SF02_STATE_CREATED = 0,
   SF02_STATE_INITIALIZING = 1,
   SF02_STATE_READY = 2,
   SF02_STATE_RUNNING = 3,
   SF02_STATE_DEGRADED = 4,
   SF02_STATE_STOPPING = 5,
   SF02_STATE_STOPPED = 6,
   SF02_STATE_FAILED = 7
};

enum ENUM_SF02_HEALTH_STATUS
{
   SF02_HEALTH_UNKNOWN = 0,
   SF02_HEALTH_HEALTHY = 1,
   SF02_HEALTH_DEGRADED = 2,
   SF02_HEALTH_UNHEALTHY = 3
};

enum ENUM_SF02_EVENT_TYPE
{
   SF02_EVENT_NONE = 0,
   SF02_EVENT_RUNTIME_INITIALIZED = 1,
   SF02_EVENT_RUNTIME_STARTED = 2,
   SF02_EVENT_RUNTIME_STOPPED = 3,
   SF02_EVENT_RUNTIME_FAILED = 4,
   SF02_EVENT_HEARTBEAT = 5,
   SF02_EVENT_ANATOMY_DETECTED = 10,
   SF02_EVENT_ANATOMY_REJECTED = 11,
   SF02_EVENT_SNAPSHOT_CREATED = 20,
   SF02_EVENT_SNAPSHOT_REJECTED = 21,
   SF02_EVENT_AUDIT_DROPPED = 90
};

enum ENUM_SF02_BUS_OVERFLOW_POLICY
{
   SF02_BUS_REJECT_NEW = 0,
   SF02_BUS_DROP_OLDEST = 1
};

enum ENUM_SF02_SERVICE_KIND
{
   SF02_SERVICE_UNKNOWN = 0,
   SF02_SERVICE_CLOCK = 1,
   SF02_SERVICE_MARKET_DATA = 2,
   SF02_SERVICE_SYMBOL_SPEC = 3,
   SF02_SERVICE_ANATOMY = 4,
   SF02_SERVICE_FEATURES = 5,
   SF02_SERVICE_RESULT_SINK = 6,
   SF02_SERVICE_EXECUTION_BOUNDARY = 7
};

string SF02_RunModeToString(const ENUM_SF02_RUN_MODE value)
{
   if(value == SF02_MODE_VISUAL_ANATOMY) return "VISUAL_ANATOMY";
   if(value == SF02_MODE_ANATOMY_AUDIT) return "ANATOMY_AUDIT";
   if(value == SF02_MODE_OUTCOME_STUDY) return "OUTCOME_STUDY";
   if(value == SF02_MODE_CANDIDATE_MATRIX) return "CANDIDATE_MATRIX";
   if(value == SF02_MODE_TESTER_EXECUTION) return "TESTER_EXECUTION";
   if(value == SF02_MODE_PAPER) return "PAPER";
   if(value == SF02_MODE_LIVE_DISABLED) return "LIVE_DISABLED";
   if(value == SF02_MODE_EXPORT_TRAINING_DATA) return "EXPORT_TRAINING_DATA";
   if(value == SF02_MODE_ONNX_INFERENCE) return "ONNX_INFERENCE";
   return "UNKNOWN";
}

string SF02_RuntimeStateToString(const ENUM_SF02_RUNTIME_STATE value)
{
   if(value == SF02_STATE_CREATED) return "CREATED";
   if(value == SF02_STATE_INITIALIZING) return "INITIALIZING";
   if(value == SF02_STATE_READY) return "READY";
   if(value == SF02_STATE_RUNNING) return "RUNNING";
   if(value == SF02_STATE_DEGRADED) return "DEGRADED";
   if(value == SF02_STATE_STOPPING) return "STOPPING";
   if(value == SF02_STATE_STOPPED) return "STOPPED";
   if(value == SF02_STATE_FAILED) return "FAILED";
   return "UNKNOWN";
}

#endif
