#ifndef __SF04_PLUGIN_DESCRIPTOR_MQH__
#define __SF04_PLUGIN_DESCRIPTOR_MQH__
#include "../Contracts/SF01_StringCodec.mqh"
#include "../Contracts/SF01_Hash.mqh"
#include "SF04_PluginEnums.mqh"
struct SF04_PluginDescriptor{string descriptor_schema;string plugin_id;string display_name;string version;ENUM_SF04_PLUGIN_KIND kind;string provider_id;string provider_version;ulong capability_mask;int update_scope_mask;int event_queue_capacity;ENUM_SF04_QUEUE_OVERFLOW_POLICY queue_overflow_policy;bool deterministic;bool replay_safe;bool fast_path_safe;bool stateful;string description;string configuration_schema_hash;};
bool SF04_IsNumericToken(const string v){if(StringLen(v)<=0)return false;for(int i=0;i<StringLen(v);i++){int c=StringGetCharacter(v,i);if(c<'0'||c>'9')return false;}return true;}
bool SF04_IsSemanticVersion(const string v){string p[];if(StringSplit(v,'.',p)!=3)return false;for(int i=0;i<3;i++)if(!SF04_IsNumericToken(p[i]))return false;return true;}
string SF04_PluginDescriptorCanonical(const SF04_PluginDescriptor &v){return v.descriptor_schema+"|"+v.plugin_id+"|"+v.display_name+"|"+v.version+"|"+IntegerToString((int)v.kind)+"|"+v.provider_id+"|"+v.provider_version+"|"+IntegerToString((long)v.capability_mask)+"|"+IntegerToString(v.update_scope_mask)+"|"+IntegerToString(v.event_queue_capacity)+"|"+IntegerToString((int)v.queue_overflow_policy)+"|"+SF01_CanonicalBool(v.deterministic)+"|"+SF01_CanonicalBool(v.replay_safe)+"|"+SF01_CanonicalBool(v.fast_path_safe)+"|"+SF01_CanonicalBool(v.stateful)+"|"+v.configuration_schema_hash;}
string SF04_PluginDescriptorHash(const SF04_PluginDescriptor &v){return SF01_StableId("plg",SF04_PluginDescriptorCanonical(v));}
bool SF04_ValidatePluginDescriptor(const SF04_PluginDescriptor &v,string &e){if(v.descriptor_schema!="alpha_lab.strategy_factory/plugin_descriptor@1.0.0"){e="unsupported descriptor schema";return false;}if(!SF01_IsSafeIdentifier(v.plugin_id,128)){e="invalid plugin_id";return false;}if(StringLen(v.display_name)<=0||StringLen(v.display_name)>128){e="invalid display_name";return false;}if(!SF04_IsSemanticVersion(v.version)){e="invalid semantic version";return false;}if(v.kind==SF04_PLUGIN_UNKNOWN){e="unknown plugin kind";return false;}if(!SF01_IsSafeIdentifier(v.provider_id,128)||!SF04_IsSemanticVersion(v.provider_version)){e="invalid provider identity";return false;}if(v.update_scope_mask<=0){e="missing update scope";return false;}if(v.event_queue_capacity<1||v.event_queue_capacity>65536){e="queue capacity out of range";return false;}if(v.fast_path_safe&&!v.deterministic){e="fast path requires deterministic";return false;}if(v.replay_safe&&!v.deterministic){e="replay requires deterministic";return false;}if(v.configuration_schema_hash==""){e="configuration schema hash required";return false;}e="";return true;}
SF04_PluginDescriptor SF04_DefaultAnatomyDescriptor(void){SF04_PluginDescriptor v;v.descriptor_schema="alpha_lab.strategy_factory/plugin_descriptor@1.0.0";v.plugin_id="unbound.anatomy";v.display_name="Unbound Anatomy";v.version="0.0.0";v.kind=SF04_PLUGIN_ANATOMY;v.provider_id="alpha_lab";v.provider_version="1.0.0";v.capability_mask=SF04_CAP_NONE;v.update_scope_mask=SF04_UPDATE_TICK;v.event_queue_capacity=64;v.queue_overflow_policy=SF04_QUEUE_REJECT_NEW;v.deterministic=true;v.replay_safe=true;v.fast_path_safe=true;v.stateful=true;v.description="";v.configuration_schema_hash="cfg_unbound";return v;}
#endif
