#ifndef __SF04_PLUGIN_ENUMS_MQH__
#define __SF04_PLUGIN_ENUMS_MQH__
enum ENUM_SF04_PLUGIN_KIND{SF04_PLUGIN_UNKNOWN=0,SF04_PLUGIN_ANATOMY=1,SF04_PLUGIN_FEATURE=2,SF04_PLUGIN_CANDIDATE=3,SF04_PLUGIN_MODEL=4,SF04_PLUGIN_RISK=5,SF04_PLUGIN_EXECUTION=6};
enum ENUM_SF04_UPDATE_SCOPE{SF04_UPDATE_NONE=0,SF04_UPDATE_TICK=1,SF04_UPDATE_NEW_BAR=2,SF04_UPDATE_TIMER=4,SF04_UPDATE_HISTORY_REBUILD=8,SF04_UPDATE_REPLAY=16};
enum ENUM_SF04_REQUIREMENT_KIND{SF04_REQUIREMENT_UNKNOWN=0,SF04_REQUIREMENT_TICK=1,SF04_REQUIREMENT_CLOSED_BARS=2,SF04_REQUIREMENT_SYMBOL_SPEC=3};
enum ENUM_SF04_REQUIREMENT_STRENGTH{SF04_REQUIREMENT_OPTIONAL=0,SF04_REQUIREMENT_REQUIRED=1};
enum ENUM_SF04_QUEUE_OVERFLOW_POLICY{SF04_QUEUE_REJECT_NEW=0,SF04_QUEUE_DROP_OLDEST=1,SF04_QUEUE_FAIL_PLUGIN=2};
enum ENUM_SF04_PLUGIN_STATUS{SF04_PLUGIN_STATUS_CREATED=0,SF04_PLUGIN_STATUS_BOUND=1,SF04_PLUGIN_STATUS_INITIALIZED=2,SF04_PLUGIN_STATUS_RUNNING=3,SF04_PLUGIN_STATUS_STOPPED=4,SF04_PLUGIN_STATUS_FAILED=5};
#define SF04_CAP_NONE ((ulong)0)
#define SF04_CAP_TICK_INPUT ((ulong)1)
#define SF04_CAP_CLOSED_BAR_INPUT ((ulong)2)
#define SF04_CAP_MULTI_SYMBOL ((ulong)4)
#define SF04_CAP_MULTI_TIMEFRAME ((ulong)8)
#define SF04_CAP_TIMER_INPUT ((ulong)16)
#define SF04_CAP_HISTORY_REBUILD ((ulong)32)
#define SF04_CAP_REPLAY_SAFE ((ulong)64)
#define SF04_CAP_DETERMINISTIC ((ulong)128)
#define SF04_CAP_FAST_PATH_SAFE ((ulong)256)
#define SF04_CAP_STATEFUL ((ulong)512)
#define SF04_CAP_EMITS_PARENT_LINKS ((ulong)1024)
#define SF04_CAP_EMITS_CLUSTER_ID ((ulong)2048)
#define SF04_CAP_REQUIRES_SYMBOL_SPEC ((ulong)4096)
#define SF04_CAP_REQUIRES_SYNCHRONIZATION ((ulong)8192)
bool SF04_HasCapability(const ulong mask,const ulong capability){return (mask&capability)==capability;}
string SF04_PluginKindToString(const ENUM_SF04_PLUGIN_KIND v){if(v==SF04_PLUGIN_ANATOMY)return "ANATOMY";if(v==SF04_PLUGIN_FEATURE)return "FEATURE";if(v==SF04_PLUGIN_CANDIDATE)return "CANDIDATE";if(v==SF04_PLUGIN_MODEL)return "MODEL";if(v==SF04_PLUGIN_RISK)return "RISK";if(v==SF04_PLUGIN_EXECUTION)return "EXECUTION";return "UNKNOWN";}
#endif
