class SAEDV439Error(Exception): pass
class ContractError(SAEDV439Error): pass
class UpstreamError(SAEDV439Error): pass
class ConstitutionError(SAEDV439Error): pass
class CohortError(SAEDV439Error): pass
class ModeError(SAEDV439Error): pass
class BrokerError(SAEDV439Error): pass
class RiskError(SAEDV439Error): pass
class PaperError(SAEDV439Error): pass
class ShadowError(SAEDV439Error): pass
class IntentError(SAEDV439Error): pass
class ReconciliationError(SAEDV439Error): pass
class SurveillanceError(SAEDV439Error): pass
class IncidentError(SAEDV439Error): pass
class ExternalEvidenceError(SAEDV439Error): pass
class StageGateError(SAEDV439Error): pass
class GovernanceError(SAEDV439Error): pass
class AuthorityError(SAEDV439Error): pass
