from __future__ import annotations
from .canonical import seal

def qualify(cohort:dict,paper:dict,shadow:dict,reconciliation:dict,surveillance:dict,drills:dict,external:dict,broker_matrix:dict)->dict:
 paper_checks={"minimum_observations":paper["metrics"]["observation_count"]>=cohort["minimum_observations"],"zero_order_submission":paper["metrics"]["order_submission_count"]==0,"zero_broker_side_effect":paper["metrics"]["broker_side_effect_count"]==0,"reconciliation_complete":reconciliation["unmatched_count"]==0,"no_hard_surveillance_breach":surveillance["hard_breach"] is False,"actual_period_evidence":external["actual_prospective_paper_passed"]}
 shadow_checks={"minimum_observations":shadow["metrics"]["observation_count"]>=cohort["minimum_observations"],"zero_order_submission":shadow["metrics"]["order_submission_count"]==0,"zero_broker_side_effect":shadow["metrics"]["broker_side_effect_count"]==0,"future_suffix_unused":shadow["metrics"]["future_suffix_used"] is False,"drills_passed":drills["passed"] is True,"actual_period_evidence":external["actual_prospective_shadow_passed"]}
 micro_checks={"metaeditor_compile":external["actual_metaeditor_compile_passed"],"terminal_parity":external["actual_terminal_parity_passed"],"demo_connectivity":external["actual_demo_connectivity_passed"],"live_connectivity":external["actual_live_connectivity_passed"],"paper_external":external["actual_prospective_paper_passed"],"shadow_external":external["actual_prospective_shadow_passed"],"broker_live_qualified":broker_matrix["live_qualified"],"micro_live_authorization":external["actual_micro_live_authorized"],"kill_switch_live_drill":any(x["evidence_type"]=="KILL_SWITCH_LIVE_DRILL" and x["status"]=="PASSED" and x["actual_external_evidence"] for x in external["items"])}
 paper_internal=all(v for k,v in paper_checks.items() if k!="actual_period_evidence");shadow_internal=all(v for k,v in shadow_checks.items() if k!="actual_period_evidence")
 stages=[{"stage":"PAPER","internal_reference_passed":paper_internal,"actual_external_passed":all(paper_checks.values()),"checks":paper_checks,"decision":"ACCEPT_REFERENCE_EXTERNAL_PERIOD_PENDING" if paper_internal and not all(paper_checks.values()) else "PASS" if all(paper_checks.values()) else "FAIL"},{"stage":"SHADOW","internal_reference_passed":shadow_internal,"actual_external_passed":all(shadow_checks.values()),"checks":shadow_checks,"decision":"ACCEPT_REFERENCE_EXTERNAL_PERIOD_PENDING" if shadow_internal and not all(shadow_checks.values()) else "PASS" if all(shadow_checks.values()) else "FAIL"},{"stage":"MICRO_LIVE","internal_reference_passed":False,"actual_external_passed":all(micro_checks.values()),"checks":micro_checks,"decision":"BLOCKED_EXTERNAL_GATES" if not all(micro_checks.values()) else "ELIGIBLE_FOR_MANUAL_AUTHORIZATION"}]
 return seal({"phase":"SAED_V4_39","stages":stages,"highest_reference_stage":"SHADOW","highest_actual_stage":"OFF" if not external["actual_prospective_paper_passed"] else "PAPER" if not external["actual_prospective_shadow_passed"] else "SHADOW" if not all(micro_checks.values()) else "MICRO_LIVE_QUALIFICATION","micro_live_eligible":all(micro_checks.values()),"automatic_transition_allowed":False,"capital_activation_allowed":False,"production_authorized":False,"research_only":True},"v439_qualification","qualification_id","qualification_hash")
