#ifndef __FP_I06_CONTRACTS_MQH__
#define __FP_I06_CONTRACTS_MQH__
#include "FP_I06_Enums.mqh"
struct FP_I06_RelationDescriptor { FP_I06_RELATION relation; string reference_kind; string check_kind; bool historical_selector_required; bool supported_in_phase; string version; bool Valid() const { return version!="" && reference_kind!="" && check_kind!="" && !(relation==FP_I06_WW && supported_in_phase); } };
struct FP_I06_RelationInstance { string relation_instance_id; FP_I06_RELATION relation; string pair_id; string anchor_trading_date; int calendar_offset; string reference_pair_window_id; string check_pair_window_id; long check_start_utc_ms; long check_end_utc_ms; string source_store_snapshot_hash; string source_revision_id; string semantic_hash; bool Valid() const { return relation_instance_id!="" && pair_id!="" && check_end_utc_ms>check_start_utc_ms && semantic_hash!=""; } };
struct FP_I06_RelationSidePlan { string side_plan_id; string relation_instance_id; FP_I06_RELATION relation; FP_I06_PRICE_SIDE side; string left_reference_id; string left_symbol; double left_reference_price; string right_reference_id; string right_symbol; double right_reference_price; long check_start_utc_ms; long check_end_utc_ms; FP_I06_PLAN_STATE state; string semantic_hash; bool Valid() const { return side_plan_id!="" && relation_instance_id!="" && left_symbol!="" && right_symbol!="" && left_symbol!=right_symbol && MathIsValidNumber(left_reference_price) && MathIsValidNumber(right_reference_price) && semantic_hash!=""; } };
struct FP_I06_HuntFact { string hunt_fact_id; string side_plan_id; string canonical_symbol; FP_I06_PRICE_SIDE side; string reference_id; double reference_price; long hunt_minute_utc_ms; string bar_hash; double observed_extreme; string source_revision_id; string evidence_hash; bool Valid() const { return hunt_fact_id!="" && side_plan_id!="" && canonical_symbol!="" && reference_id!="" && hunt_minute_utc_ms>=0 && MathIsValidNumber(reference_price) && MathIsValidNumber(observed_extreme) && evidence_hash!=""; } };
struct FP_I06_MinuteContactObservation { string observation_id; string side_plan_id; long minute_utc_ms; FP_I06_CONTACT_STATE contact_state; string left_hunt_fact_id; string right_hunt_fact_id; string source_row_id; string source_revision_hash; string reason_code; string evidence_hash; bool Valid() const { return observation_id!="" && side_plan_id!="" && minute_utc_ms>=0 && source_row_id!="" && evidence_hash!=""; } };
struct FP_I06_FirstSweepClassification { string classification_id; string side_plan_id; FP_I06_SWEEP_OUTCOME outcome; long first_hunt_minute_utc_ms; string hunter_symbol; string protected_symbol; string hunter_hunt_fact_id; long data_block_minute_utc_ms; string reason_code; string evidence_hash; bool Valid() const { if(classification_id=="" || side_plan_id=="" || evidence_hash=="") return false; if((outcome==FP_I06_LEFT_FIRST || outcome==FP_I06_RIGHT_FIRST) && (hunter_symbol=="" || protected_symbol=="" || hunter_symbol==protected_symbol)) return false; return true; } };
struct FP_I06_RawCandidate { string candidate_id; string side_plan_id; string relation_instance_id; FP_I06_RELATION relation; FP_I06_DIRECTION direction; FP_I06_PRICE_SIDE side; string hunter_symbol; string protected_symbol; long first_hunt_minute_utc_ms; string hunter_hunt_fact_id; FP_I06_CANDIDATE_STATE state; int state_sequence; long second_touch_minute_utc_ms; string second_touch_fact_id; long check_end_utc_ms; string source_revision_id; string reason_code; string semantic_hash; bool Valid() const { return candidate_id!="" && side_plan_id!="" && hunter_symbol!="" && protected_symbol!="" && hunter_symbol!=protected_symbol && first_hunt_minute_utc_ms>=0 && check_end_utc_ms>first_hunt_minute_utc_ms && semantic_hash!=""; } };
struct FP_I06_ScanCursor { string side_plan_id; long next_open_utc_ms; string source_revision_id; string source_rows_hash; string candidate_id; FP_I06_CANDIDATE_STATE candidate_state; string cursor_hash; bool Valid() const { return side_plan_id!="" && next_open_utc_ms>=0 && source_revision_id!="" && source_rows_hash!="" && cursor_hash!=""; } };
#endif
