#ifndef __UCEI09_ENUMS_MQH__
#define __UCEI09_ENUMS_MQH__
enum UCEI09_TASK_FAMILY{UCEI09_RANKING=0,UCEI09_TREATMENT_SELECTION=1,UCEI09_SURVIVAL=2,UCEI09_COMPETING_RISK=3,UCEI09_DISTRIBUTIONAL=4,UCEI09_MULTI_TASK=5,UCEI09_REGIME_GATING=6,UCEI09_BOUNDED_POLICY=7};
enum UCEI09_SUPPORT_STATE{UCEI09_SUPPORTED=0,UCEI09_WEAK=1,UCEI09_UNSUPPORTED=2,UCEI09_MASKED=3};
enum UCEI09_POLICY_DECISION{UCEI09_ACTION=0,UCEI09_ABSTAIN=1,UCEI09_BASELINE=2,UCEI09_REJECTED=3};
enum UCEI09_GATE_DECISION{UCEI09_ACCEPT=0,UCEI09_WARN=1,UCEI09_REJECT=2};
string UCEI09TaskFamilyName(const UCEI09_TASK_FAMILY v){switch(v){case UCEI09_RANKING:return "ranking";case UCEI09_TREATMENT_SELECTION:return "treatment_selection";case UCEI09_SURVIVAL:return "survival";case UCEI09_COMPETING_RISK:return "competing_risk";case UCEI09_DISTRIBUTIONAL:return "distributional";case UCEI09_MULTI_TASK:return "multi_task";case UCEI09_REGIME_GATING:return "regime_gating";case UCEI09_BOUNDED_POLICY:return "bounded_policy";}return "unknown";}
#endif
