from enum import IntEnum

class LiveMode(IntEnum):
    DISABLED = 0
    DRY_RUN = 1
    MICRO_LIVE = 2

class AuthorizationState(IntEnum):
    LOCKED = 0
    ARMED = 1
    CONSUMED = 2
    EXPIRED = 3
    REVOKED = 4

class KillSwitchState(IntEnum):
    ENGAGED = 1
    DISARMED = 2

class CircuitState(IntEnum):
    CLOSED = 1
    OPEN = 2
    HALF_OPEN = 3

class LiveDecision(IntEnum):
    REJECT = 1
    CHECK_ONLY = 2
    SEND = 3
    ACCEPTED = 4
    PENDING = 5
    FILLED = 6
    PARTIAL = 7
    CANCELED = 8

class LiveRejectReason(IntEnum):
    NONE = 0
    MODE_DISABLED = 1
    KILL_SWITCH_ENGAGED = 2
    CIRCUIT_OPEN = 3
    INVALID_INTENT = 4
    INTENT_NOT_PAPER_ELIGIBLE = 5
    INTENT_EXPIRED = 6
    DUPLICATE_HASH_CONFLICT = 7
    AUTHORIZATION_MISSING = 8
    AUTHORIZATION_INVALID = 9
    AUTHORIZATION_EXPIRED = 10
    AUTHORIZATION_CONSUMED = 11
    RELEASE_MISMATCH = 12
    ACCOUNT_MISMATCH = 13
    SERVER_MISMATCH = 14
    SYMBOL_NOT_ALLOWED = 15
    TERMINAL_TRADE_DISABLED = 16
    ACCOUNT_TRADE_DISABLED = 17
    STALE_ACCOUNT_SNAPSHOT = 18
    STALE_QUOTE = 19
    SPREAD_LIMIT = 20
    VOLUME_LIMIT = 21
    RISK_LIMIT = 22
    DAILY_LOSS_LIMIT = 23
    EQUITY_FLOOR = 24
    FREE_MARGIN_FLOOR = 25
    MARGIN_LEVEL_FLOOR = 26
    EXPOSURE_LIMIT = 27
    SESSION_ORDER_LIMIT = 28
    CONCURRENT_ORDER_LIMIT = 29
    POSITION_LIMIT = 30
    COOLDOWN_ACTIVE = 31
    ORDER_CHECK_FAILED = 32
    ORDER_CHECK_REJECTED = 33
    ORDER_SEND_FAILED = 34
    BROKER_RETCODE_REJECTED = 35
    CAPACITY_EXCEEDED = 36
    NON_FINITE = 37
    INVALID_SYMBOL_SPEC = 38
    IDEMPOTENT_REPLAY = 39

class RetcodeClass(IntEnum):
    SUCCESS = 1
    TRANSIENT = 2
    POLICY_REJECT = 3
    MARKET_STATE = 4
    ACCOUNT_STATE = 5
    REQUEST_INVALID = 6
    CONNECTION = 7
    UNKNOWN = 8

class LiveTransactionType(IntEnum):
    INTENT_RECEIVED = 1
    PREFLIGHT_REJECTED = 2
    PREFLIGHT_PASSED = 3
    ORDER_CHECK_REQUESTED = 4
    ORDER_CHECK_ACCEPTED = 5
    ORDER_CHECK_REJECTED = 6
    ORDER_SEND_REQUESTED = 7
    ORDER_SEND_ACCEPTED = 8
    ORDER_SEND_REJECTED = 9
    AUTHORIZATION_CONSUMED = 10
    CIRCUIT_OPENED = 11
    CIRCUIT_RESET = 12
    KILL_SWITCH_ENGAGED = 13
    KILL_SWITCH_DISARMED = 14
    BROKER_TRANSACTION_OBSERVED = 15
    RECONCILIATION = 16
    EMERGENCY_ACTION_REJECTED = 17

class BrokerAction(IntEnum):
    OPEN = 1
    CANCEL_PENDING = 2
    CLOSE_POSITION = 3

class OrderKind(IntEnum):
    MARKET = 1
    LIMIT = 2
    STOP = 3
