from __future__ import annotations
from .canonical import seal,content_hash
def compile_release(evidence:dict,review:dict,verification:dict,dashboard:dict)->dict:
 internal=evidence["synthetic_reference_complete"] and verification["all_verified"] and review["accepted_reference"]
 return seal({"phase":"SAED_V4_41","status":"ACCEPTED_REFERENCE_PROGRAM_ROADMAP_COMPLETE_EXTERNAL_OPERATIONS_GATES_OPEN" if internal else "REJECTED","internal_reference_gates_passed":internal,"continuous_surveillance_reference_ready":internal,"retirement_reference_ready":internal,"roadmap_phase_complete":internal,"saed_v4_reference_program_complete":internal,"actual_external_surveillance_evidence_complete":False,"actual_retirement_drill_complete":False,"actual_metaeditor_matrix_complete":False,"actual_broker_route_revocation_complete":False,"actual_operator_runbook_drill_complete":False,"live_order_submission_allowed":False,"capital_activation_allowed":False,"automatic_live_action_allowed":False,"production_authorized":False,"claim_ceiling":"deterministic synthetic continuous-surveillance, incident-containment and retirement reference only","dashboard_hash":dashboard["dashboard_hash"],"evidence_hash":evidence["evidence_bundle_hash"],"review_hash":review["review_bundle_hash"],"verification_hash":verification["verification_hash"],"research_only":True},"v441_release","release_id","release_hash")
def compile_certificate(release:dict,evidence:dict)->dict:
 return seal({"phase":"SAED_V4_41","next_phase":None,"program_state":"REFERENCE_ROADMAP_COMPLETE_CONTINUOUS_OPERATIONS_REQUIRED","status":release["status"],"release_hash":release["release_hash"],"evidence_hash":evidence["evidence_bundle_hash"],"surveillance_reference_ready":release["continuous_surveillance_reference_ready"],"retirement_reference_ready":release["retirement_reference_ready"],"saed_v4_reference_program_complete":release["saed_v4_reference_program_complete"],"actual_external_operations_evidence_complete":False,"live_order_submission_allowed":False,"capital_activation_allowed":False,"production_authorized":False,"claim_ceiling":release["claim_ceiling"],"research_only":True},"v441_certificate","certificate_id","certificate_hash")
def compile_operations_handoff(certificate:dict,release:dict)->dict:
 return seal({"phase":"SAED_V4_41","kind":"v4_41_program_closure_and_continuous_operations_handoff","next_phase":None,"program_state":"CONTINUOUS_OPERATIONS_AND_EXTERNAL_QUALIFICATION","certificate_hash":certificate["certificate_hash"],"release_hash":release["release_hash"],"allowed_next_work":["attach_actual_surveillance_telemetry","execute_metaeditor_and_mt5_retirement_drills","operate_alert_and_incident_runbooks","perform_broker_route_revocation_reconciliation","complete_external_sre_and_model_risk_approval","run_continuous_drift_degradation_and_retirement_governance"],"forbidden_next_work":["inventing_new_roadmap_phase_to_bypass_external_gates","live_order_submission_without_signed_authority","capital_activation_without_authorization","reinstating_retired_artifact_without_new_qualification","silent_threshold_change","deleting_retirement_tombstone","claiming_external_evidence_from_synthetic_fixture"],"required_external_gates":["ACTUAL_PRODUCTION_TELEMETRY_BINDING","METAEDITOR_COMPILE_MATRIX","MT5_ROUTE_REVOCATION_REPLAY","BROKER_RETIREMENT_RECONCILIATION","INCIDENT_RUNBOOK_DRILL","RETIREMENT_AND_ROLLBACK_DRILL","KEY_CUSTODY_AND_SIGNING","INDEPENDENT_SRE_APPROVAL","INDEPENDENT_MODEL_RISK_APPROVAL"],"roadmap_complete":True,"continuous_operations_required":True,"research_only":True,"production_authorized":False},"v441_handoff","handoff_id","handoff_hash")
