#ifndef __ALPHALAB_SAEDV4ACTIONLATTICETYPES_MQH__
#define __ALPHALAB_SAEDV4ACTIONLATTICETYPES_MQH__

// SAED V4-07 diagnostic-only mirror. No trading, file, socket or network authority.
enum ENUM_SAED_V4_07_ACTION_CLASS { SAED_V4_07_ORDINARY=0, SAED_V4_07_ABSTAIN=1, SAED_V4_07_SKIP=2 };
enum ENUM_SAED_V4_07_EDGE_KIND { SAED_V4_07_ATOMIC_STEP=0, SAED_V4_07_FALLBACK_ABSTAIN=1, SAED_V4_07_FALLBACK_SKIP=2 };

#endif // __ALPHALAB_SAEDV4ACTIONLATTICETYPES_MQH__
