#ifndef __SF05_GENERATION_MANAGER_MQH__
#define __SF05_GENERATION_MANAGER_MQH__
#include "SF05_GenerationBundle.mqh"
class CSF05GenerationManager
{
private:CSF05GenerationBundle *m_staged;CSF05GenerationBundle *m_active;CSF05GenerationBundle *m_previous;bool m_switching;long m_activation_count;long m_rollback_count;
public:CSF05GenerationManager(void){m_staged=NULL;m_active=NULL;m_previous=NULL;m_switching=false;m_activation_count=0;m_rollback_count=0;}~CSF05GenerationManager(void){Clear();}
void Clear(void){if(CheckPointer(m_staged)!=POINTER_INVALID)delete m_staged;if(CheckPointer(m_active)!=POINTER_INVALID)delete m_active;if(CheckPointer(m_previous)!=POINTER_INVALID)delete m_previous;m_staged=NULL;m_active=NULL;m_previous=NULL;}
bool Stage(CSF05GenerationBundle *b,string &e){if(m_switching){e="generation switch in progress";return false;}if(CheckPointer(b)==POINTER_INVALID||!b.IsValid()){e="invalid generation bundle";return false;}SF05_RuntimeGenerationRecord g=b.Generation();if(g.state!=SF05_GENERATION_WARMED){e="only WARMED generation may be staged";return false;}if(CheckPointer(m_staged)!=POINTER_INVALID)delete m_staged;m_staged=b;e="";return true;}
bool Activate(const SF01_MarketTimestamp &now,string &e){if(m_switching){e="generation switch in progress";return false;}if(CheckPointer(m_staged)==POINTER_INVALID){e="no staged generation";return false;}m_switching=true;SF05_RuntimeGenerationRecord next=m_staged.Generation();if(!SF05_TransitionGeneration(next,SF05_GENERATION_ACTIVE,now,"activate",e)){m_switching=false;return false;}m_staged.SetGeneration(next);if(CheckPointer(m_previous)!=POINTER_INVALID)delete m_previous;m_previous=m_active;m_active=m_staged;m_staged=NULL;m_activation_count++;m_switching=false;e="";return true;}
bool RetireActive(const SF01_MarketTimestamp &now,string &e){if(CheckPointer(m_active)==POINTER_INVALID){e="no active generation";return false;}SF05_RuntimeGenerationRecord g=m_active.Generation();if(!SF05_TransitionGeneration(g,SF05_GENERATION_RETIRED,now,"retire",e))return false;m_active.SetGeneration(g);e="";return true;}
bool Rollback(const SF01_MarketTimestamp &now,string &e){if(m_switching){e="generation switch in progress";return false;}if(CheckPointer(m_previous)==POINTER_INVALID){e="no previous generation";return false;}m_switching=true;if(CheckPointer(m_active)!=POINTER_INVALID){SF05_RuntimeGenerationRecord cur=m_active.Generation();if(cur.state==SF05_GENERATION_ACTIVE)SF05_TransitionGeneration(cur,SF05_GENERATION_RETIRED,now,"rollback",e);m_active.SetGeneration(cur);}CSF05GenerationBundle *tmp=m_active;m_active=m_previous;m_previous=tmp;SF05_RuntimeGenerationRecord restored=m_active.Generation();if(restored.state==SF05_GENERATION_RETIRED){restored.state=SF05_GENERATION_WARMED;if(!SF05_TransitionGeneration(restored,SF05_GENERATION_ACTIVE,now,"rollback_activate",e)){m_switching=false;return false;}m_active.SetGeneration(restored);}m_rollback_count++;m_switching=false;e="";return true;}
CSF05GenerationBundle *Active(void){return m_active;}CSF05GenerationBundle *Previous(void){return m_previous;}CSF05GenerationBundle *Staged(void){return m_staged;}long ActivationCount(void)const{return m_activation_count;}long RollbackCount(void)const{return m_rollback_count;}
};
#endif
