#ifndef __SF05_GENERATION_ENUMS_MQH__
#define __SF05_GENERATION_ENUMS_MQH__

enum ENUM_SF05_GENERATION_STATE
{
   SF05_GENERATION_DRAFT = 0,
   SF05_GENERATION_COMPILED = 1,
   SF05_GENERATION_VALIDATED = 2,
   SF05_GENERATION_WARMED = 3,
   SF05_GENERATION_ACTIVE = 4,
   SF05_GENERATION_RETIRED = 5,
   SF05_GENERATION_FAILED = 6
};

enum ENUM_SF05_SINK_MODE
{
   SF05_SINK_MEMORY = 0,
   SF05_SINK_JSONL = 1,
   SF05_SINK_COMPOSITE = 2
};

enum ENUM_SF05_FILE_SCOPE
{
   SF05_FILE_TERMINAL_LOCAL = 0,
   SF05_FILE_COMMON = 1
};

enum ENUM_SF05_RECORD_TYPE
{
   SF05_RECORD_UNKNOWN = 0,
   SF05_RECORD_RUN_MANIFEST = 1,
   SF05_RECORD_GENERATION = 2,
   SF05_RECORD_ANATOMY_EVENT = 10,
   SF05_RECORD_FEATURE_SNAPSHOT = 20,
   SF05_RECORD_HEARTBEAT = 30,
   SF05_RECORD_GENERATION_ACTIVATED = 40,
   SF05_RECORD_GENERATION_RETIRED = 41,
   SF05_RECORD_GENERATION_ROLLBACK = 42,
   SF05_RECORD_SINK_ERROR = 90
};

string SF05_GenerationStateToString(const ENUM_SF05_GENERATION_STATE v)
{
   if(v==SF05_GENERATION_DRAFT) return "DRAFT";
   if(v==SF05_GENERATION_COMPILED) return "COMPILED";
   if(v==SF05_GENERATION_VALIDATED) return "VALIDATED";
   if(v==SF05_GENERATION_WARMED) return "WARMED";
   if(v==SF05_GENERATION_ACTIVE) return "ACTIVE";
   if(v==SF05_GENERATION_RETIRED) return "RETIRED";
   if(v==SF05_GENERATION_FAILED) return "FAILED";
   return "UNKNOWN";
}

string SF05_RecordTypeToString(const ENUM_SF05_RECORD_TYPE v)
{
   if(v==SF05_RECORD_RUN_MANIFEST) return "RUN_MANIFEST";
   if(v==SF05_RECORD_GENERATION) return "GENERATION";
   if(v==SF05_RECORD_ANATOMY_EVENT) return "ANATOMY_EVENT";
   if(v==SF05_RECORD_FEATURE_SNAPSHOT) return "FEATURE_SNAPSHOT";
   if(v==SF05_RECORD_HEARTBEAT) return "HEARTBEAT";
   if(v==SF05_RECORD_GENERATION_ACTIVATED) return "GENERATION_ACTIVATED";
   if(v==SF05_RECORD_GENERATION_RETIRED) return "GENERATION_RETIRED";
   if(v==SF05_RECORD_GENERATION_ROLLBACK) return "GENERATION_ROLLBACK";
   if(v==SF05_RECORD_SINK_ERROR) return "SINK_ERROR";
   return "UNKNOWN";
}

#endif
