from __future__ import annotations

SCHEMA_VERSION = "1.0.0"
PHASE_ID = "LCM-13B"
MASTER_PHASE = "LCM-13"
CLAIM_CEILING = "LCM_13B_REFERENCE_ONLY"
OWNER = "ALPHA_LAB_MIGRATION_OWNER"
REVIEWER = "INDEPENDENT_MIGRATION_REVIEWER"
PRODUCER = "src.engine.tooling.strategy_factory.lcm.lcm_13b.service:LCM13BConsumerWaveCutoverService"
GENERATED_TIME_SEMANTICS = "DETERMINISTIC_FROM_BOUND_INPUTS_NO_WALL_CLOCK_IDENTITY"

DOMAIN_ORDER = (
    "DOCUMENTATION",
    "VISUAL",
    "CONTEXT",
    "TREATMENT",
)

WAVE_SIZE_LIMITS = {
    "DOCUMENTATION": 32,
    "VISUAL": 18,
    "CONTEXT": 1,
    "TREATMENT": 24,
}

BLAST_RADIUS = {
    "DOCUMENTATION": "LOW",
    "VISUAL": "MEDIUM",
    "CONTEXT": "MEDIUM_HIGH",
    "TREATMENT": "HIGH_BUT_REFERENCE_ONLY",
}

ROLLBACK_TRIGGERS = (
    "ANY_NEW_HIGH_OR_CRITICAL_MISMATCH",
    "INPUT_DIGEST_DIVERGENCE",
    "SIDE_EFFECT_FENCE_BREACH",
    "LOCATOR_RESOLUTION_FAILURE",
    "PARTIAL_WAVE_APPLICATION",
    "CANONICAL_TARGET_MISSING",
)

HEALTH_CHECKS = (
    "EXACT_CONSUMER_SET",
    "CANONICAL_LOCATOR_RESOLVES",
    "LEGACY_FALLBACK_RETAINED",
    "DUAL_RUN_EVIDENCE_BOUND",
    "ZERO_NEW_HIGH_CRITICAL_MISMATCH",
    "ZERO_SIDE_EFFECT_AUTHORITY",
    "ZERO_SOURCE_DELETION",
    "WAVE_ATOMICITY",
)

EVENT_TYPES = (
    "WAVE_PLANNED",
    "PRE_CUTOVER_VALIDATION_PASSED",
    "LOCATOR_SWITCH_APPLIED",
    "POST_CUTOVER_HEALTH_PASSED",
    "WAVE_COMMITTED",
)
