from __future__ import annotations
from .canonical import merkle_root,seal

def baseline_receipt(release:dict)->dict:return seal({"phase":"SAED_V4_38","baseline_id":"BASELINE_MANUAL_POLICY_V1","baseline_preserved":True,"automatic_replacement":False,"release_hash":release["release_candidate_hash"],"research_only":True},"v438_baseline","receipt_id","receipt_hash")
def evidence_bundle(items:list[dict],release:dict,reviews:dict,baseline:dict)->dict:
 hashes=sorted([x["hash"] for x in items]+[release["release_candidate_hash"],reviews["review_bundle_hash"],baseline["receipt_hash"]])
 return seal({"phase":"SAED_V4_38","evidence_items":sorted(items,key=lambda x:x["kind"]),"evidence_hashes":hashes,"evidence_merkle_root":merkle_root(hashes),"release_hash":release["release_candidate_hash"],"review_hash":reviews["review_bundle_hash"],"baseline_hash":baseline["receipt_hash"],"external_runtime_evidence_complete":release["external_runtime_qualified"],"research_only":True},"v438_evidence","evidence_bundle_id","evidence_bundle_hash")
def certificate(bundle:dict,parity:dict,external:dict,release:dict,evidence:dict)->dict:
 return seal({"phase":"SAED_V4_38","status":"ACCEPTED_REFERENCE_EXTERNAL_GATES_OPEN","bundle_hash":bundle["bundle_hash"],"synthetic_parity_passed":parity["passed"],"actual_metaeditor_compile_passed":external["actual_metaeditor_compile_passed"],"actual_terminal_parity_passed":external["actual_terminal_parity_passed"],"release_hash":release["release_candidate_hash"],"evidence_hash":evidence["evidence_bundle_hash"],"next_phase":"SAED_V4_39","research_only":True,"production_authorized":False,"capital_activation_allowed":False,"order_submission_allowed":False,"claim_ceiling":"immutable runtime compilation and synthetic MQL5 semantic parity reference; actual MetaEditor and terminal evidence pending"},"v438_certificate","certificate_id","certificate_hash")
def handoff(cert:dict,bundle:dict,external:dict)->dict:
 return seal({"kind":"v4_38_handoff","phase":"SAED_V4_38","certificate_hash":cert["certificate_hash"],"bundle_hash":bundle["bundle_hash"],"next_phase":"SAED_V4_39","required_external_gates":["METAEDITOR_COMPILE","TERMINAL_VECTOR_REPLAY","CROSS_RUNTIME_STATE_REPLAY","WINDOWS_DLL_BOUNDARY"],"external_runtime_evidence_complete":external["external_runtime_evidence_complete"],"allowed_next_work":["prospective_paper","shadow_replay","micro_live_qualification_only_after_external_gates"],"forbidden_next_work":["capital_activation_without_authorization","live_order_submission_without_release","silent_bundle_mutation"],"research_only":True,"production_authorized":False},"v438_handoff","handoff_id","handoff_hash")
