#ifndef __UCE02_LIFECYCLE_MQH__
#define __UCE02_LIFECYCLE_MQH__
#include "UCE02_Observation.mqh"
struct UCE02_ObservationTransition{string transition_id;string observation_id;ENUM_UCE02_CONTEXT_STATE from_state;ENUM_UCE02_CONTEXT_STATE to_state;long known_time_ms;string reason_code;string evidence_hash;long sequence;};
bool UCE02_IsTransitionAllowed(const ENUM_UCE02_CONTEXT_STATE from_state,const ENUM_UCE02_CONTEXT_STATE to_state){if(from_state==to_state)return true;if(from_state==UCE02_CONTEXT_DETECTED)return to_state==UCE02_CONTEXT_CONFIRMED||to_state==UCE02_CONTEXT_INVALIDATED||to_state==UCE02_CONTEXT_EXPIRED||to_state==UCE02_CONTEXT_SUPERSEDED||to_state==UCE02_CONTEXT_RETIRED;if(from_state==UCE02_CONTEXT_CONFIRMED)return to_state==UCE02_CONTEXT_ACTIVE||to_state==UCE02_CONTEXT_INVALIDATED||to_state==UCE02_CONTEXT_EXPIRED||to_state==UCE02_CONTEXT_SUPERSEDED||to_state==UCE02_CONTEXT_RETIRED;if(from_state==UCE02_CONTEXT_ACTIVE)return to_state==UCE02_CONTEXT_INVALIDATED||to_state==UCE02_CONTEXT_EXPIRED||to_state==UCE02_CONTEXT_SUPERSEDED||to_state==UCE02_CONTEXT_RETIRED;if(from_state==UCE02_CONTEXT_INVALIDATED||from_state==UCE02_CONTEXT_EXPIRED||from_state==UCE02_CONTEXT_SUPERSEDED)return to_state==UCE02_CONTEXT_RETIRED;return false;}
class CUCE02LifecycleEngine{
private:UCE02_ContextObservation m_records[];UCE02_ObservationTransition m_transitions[];int m_capacity;long m_duplicates;
int Find(const string id)const{for(int i=0;i<ArraySize(m_records);i++)if(m_records[i].observation_id==id)return i;return -1;}
public:CUCE02LifecycleEngine(){m_capacity=4096;m_duplicates=0;}bool Configure(const int capacity,string &error){if(capacity<1){error="invalid lifecycle capacity";return false;}m_capacity=capacity;ArrayResize(m_records,0);ArrayResize(m_transitions,0);m_duplicates=0;error="";return true;}
bool Register(const UCE02_ContextObservation &value,bool &is_new,string &error){int index=Find(value.observation_id);if(index>=0){if(m_records[index].observation_hash!=value.observation_hash){error="observation identity collision";return false;}m_duplicates++;is_new=false;error="";return true;}if(ArraySize(m_records)>=m_capacity){error="lifecycle capacity exceeded";return false;}int n=ArraySize(m_records);ArrayResize(m_records,n+1);m_records[n]=value;is_new=true;error="";return true;}
bool Transition(const string observation_id,const ENUM_UCE02_CONTEXT_STATE to_state,const long known_time_ms,const string reason_code,UCE02_ObservationTransition &transition,string &error){int index=Find(observation_id);if(index<0){error="unknown observation";return false;}UCE02_ContextObservation current=m_records[index];if(!UCE02_IsTransitionAllowed(current.lifecycle_state,to_state)){error="illegal lifecycle transition";return false;}if(known_time_ms<current.time_chain.known_time.epoch_ms){error="transition time reversal";return false;}if(current.lifecycle_state==to_state){transition.transition_id="";error="";return true;}transition.observation_id=observation_id;transition.from_state=current.lifecycle_state;transition.to_state=to_state;transition.known_time_ms=known_time_ms;transition.reason_code=reason_code;transition.sequence=current.sequence+1;CUCE03CanonicalObject o;o.AddString("from",UCE02_ContextStateName(transition.from_state));o.AddLong("known_time_ms",known_time_ms);o.AddString("observation_id",observation_id);o.AddString("reason_code",reason_code);o.AddLong("sequence",transition.sequence);o.AddString("to",UCE02_ContextStateName(to_state));string material=o.Serialize();transition.evidence_hash=UCE02_EvidenceHash(material);transition.transition_id="uce_transition_"+UCE03_Fnv1a64HexUtf8(material);current.lifecycle_state=to_state;current.sequence=transition.sequence;current.observation_hash=UCE02_EvidenceHash(UCE02_ObservationMaterial(current));m_records[index]=current;int n=ArraySize(m_transitions);ArrayResize(m_transitions,n+1);m_transitions[n]=transition;error="";return true;}
int RecordCount()const{return ArraySize(m_records);}int TransitionCount()const{return ArraySize(m_transitions);}long DuplicatesSuppressed()const{return m_duplicates;}bool Get(const string id,UCE02_ContextObservation &out)const{int index=Find(id);if(index<0)return false;out=m_records[index];return true;}
};
#endif
