#ifndef __UCE02_OBSERVATION_MQH__
#define __UCE02_OBSERVATION_MQH__
#include "UCE02_Manifest.mqh"
struct UCE02_ContextObservation{string package_id;string package_version;string source_event_ids_csv;string symbol_scope_csv;string timeframe_scope_csv;ENUM_UCE02_CONTEXT_STATE lifecycle_state;UCE03_KnownTimeChain time_chain;string payload_json;string parent_observation_id;string supersedes_observation_id;long sequence;string observation_id;string observation_hash;};
bool UCE02_ValidateObservation(const UCE02_ContextObservation &value,string &error){if(!UCE03_IsSafeIdentifier(value.package_id)||!UCE03_IsSafeIdentifier(value.package_version)){error="invalid observation package identity";return false;}if(value.source_event_ids_csv==""||value.symbol_scope_csv==""||value.timeframe_scope_csv==""){error="observation scope is incomplete";return false;}if(value.sequence<0){error="negative observation sequence";return false;}if(!UCE03_ValidateKnownTimeChain(value.time_chain,error))return false;if(value.payload_json==""||StringSubstr(value.payload_json,0,1)!="{"){error="payload_json must be a canonical object";return false;}error="";return true;}
string UCE02_ObservationIdentityMaterial(const UCE02_ContextObservation &value){CUCE03CanonicalObject o;o.AddLong("event_time_ms",value.time_chain.event_time.epoch_ms);o.AddString("package_id",value.package_id);o.AddString("package_version",value.package_version);o.AddString("parent_observation_id",value.parent_observation_id);o.AddString("source_event_ids_csv",value.source_event_ids_csv);o.AddString("symbol_scope_csv",value.symbol_scope_csv);o.AddString("timeframe_scope_csv",value.timeframe_scope_csv);return o.Serialize();}
string UCE02_ObservationMaterial(const UCE02_ContextObservation &value){CUCE03CanonicalObject o;o.AddString("lifecycle_state",UCE02_ContextStateName(value.lifecycle_state));o.AddString("observation_id",value.observation_id);o.AddString("package_id",value.package_id);o.AddString("package_version",value.package_version);o.AddString("parent_observation_id",value.parent_observation_id);o.AddJson("payload",value.payload_json);o.AddLong("sequence",value.sequence);o.AddString("source_event_ids_csv",value.source_event_ids_csv);o.AddString("supersedes_observation_id",value.supersedes_observation_id);o.AddString("symbol_scope_csv",value.symbol_scope_csv);o.AddLong("event_time_ms",value.time_chain.event_time.epoch_ms);o.AddLong("known_time_ms",value.time_chain.known_time.epoch_ms);o.AddLong("confirmation_time_ms",value.time_chain.confirmation_time.epoch_ms);o.AddLong("observation_cut_ms",value.time_chain.observation_cut.epoch_ms);o.AddString("timeframe_scope_csv",value.timeframe_scope_csv);return o.Serialize();}
bool UCE02_SealObservation(UCE02_ContextObservation &value,string &error){if(!UCE02_ValidateObservation(value,error))return false;UCE03_IdentityKey key;key.kind=UCE03_ID_CONTEXT_OCCURRENCE;key.semantic_namespace="ucee.context_observation";key.semantic_version=value.package_version;key.owner_id=value.package_id;key.dimensions_json=UCE02_ObservationIdentityMaterial(value);value.observation_id=UCE03_StableIdentity(key);value.observation_hash=UCE02_EvidenceHash(UCE02_ObservationMaterial(value));error="";return true;}
#endif
