#ifndef __UCE02_FEATURE_MQH__
#define __UCE02_FEATURE_MQH__
#include "UCE02_Lifecycle.mqh"
struct UCE02_FeatureDescriptor{string feature_id;string version;string owner_id;ENUM_UCE02_FEATURE_TYPE data_type;string units;string shape_csv;ENUM_UCE02_MISSING_POLICY missingness_policy;ENUM_UCE02_STALE_POLICY staleness_policy;long max_staleness_ms;string dependencies_csv;int availability_mode_mask;bool runtime_exportable;string category_values_csv;string description;string descriptor_hash;};
struct UCE02_FeatureValue{string feature_id;string feature_version;string value_json;long known_time_ms;long source_time_ms;bool is_missing;string missing_reason;};
struct UCE02_FeatureFrame{string context_observation_id;string context_package_id;string context_package_version;long observation_cut_ms;string frame_id;string frame_hash;};
bool UCE02_ValidateFeatureDescriptor(const UCE02_FeatureDescriptor &value,string &error){if(!UCE03_IsSafeIdentifier(value.feature_id)||!UCE03_IsSafeIdentifier(value.version)||!UCE03_IsSafeIdentifier(value.owner_id)||!UCE03_IsSafeIdentifier(value.units)){error="invalid feature descriptor identifier";return false;}if(value.max_staleness_ms<0){error="negative feature staleness";return false;}if(value.availability_mode_mask==0){error="empty feature availability";return false;}if(value.data_type==UCE02_FEATURE_CATEGORY&&value.category_values_csv==""){error="categorical feature needs domain";return false;}error="";return true;}
string UCE02_FeatureDescriptorMaterial(const UCE02_FeatureDescriptor &value){CUCE03CanonicalObject o;o.AddLong("availability_mode_mask",value.availability_mode_mask);o.AddString("category_values_csv",value.category_values_csv);o.AddLong("data_type",value.data_type);o.AddString("dependencies_csv",value.dependencies_csv);o.AddString("description",value.description);o.AddString("feature_id",value.feature_id);o.AddLong("max_staleness_ms",value.max_staleness_ms);o.AddLong("missingness_policy",value.missingness_policy);o.AddString("owner_id",value.owner_id);o.AddBool("runtime_exportable",value.runtime_exportable);o.AddString("shape_csv",value.shape_csv);o.AddLong("staleness_policy",value.staleness_policy);o.AddString("units",value.units);o.AddString("version",value.version);return o.Serialize();}
void UCE02_SealFeatureDescriptor(UCE02_FeatureDescriptor &value){value.descriptor_hash=UCE02_EvidenceHash(UCE02_FeatureDescriptorMaterial(value));}
class CUCE02FeatureFrameBuilder{
private:UCE02_FeatureDescriptor m_descriptors[];UCE02_FeatureValue m_values[];UCE02_FeatureFrame m_frame;
public:void Reset(const string observation_id,const string package_id,const string package_version,const long observation_cut_ms){ArrayResize(m_descriptors,0);ArrayResize(m_values,0);m_frame.context_observation_id=observation_id;m_frame.context_package_id=package_id;m_frame.context_package_version=package_version;m_frame.observation_cut_ms=observation_cut_ms;m_frame.frame_id="";m_frame.frame_hash="";}
bool Add(const UCE02_FeatureDescriptor &descriptor,const UCE02_FeatureValue &value,string &error){if(ArraySize(m_descriptors)>0&&m_descriptors[ArraySize(m_descriptors)-1].feature_id>=descriptor.feature_id){error="features must be added in strict feature_id order";return false;}if(descriptor.feature_id!=value.feature_id||descriptor.version!=value.feature_version){error="feature descriptor/value mismatch";return false;}if(value.known_time_ms>m_frame.observation_cut_ms){error="future feature";return false;}long age=m_frame.observation_cut_ms-value.known_time_ms;if(age>descriptor.max_staleness_ms&&descriptor.staleness_policy==UCE02_STALE_REJECT){error="stale feature";return false;}if(value.is_missing&&descriptor.missingness_policy==UCE02_MISSING_REJECT){error="missing required feature";return false;}int n=ArraySize(m_descriptors);ArrayResize(m_descriptors,n+1);ArrayResize(m_values,n+1);m_descriptors[n]=descriptor;m_values[n]=value;error="";return true;}
bool Seal(UCE02_FeatureFrame &frame,string &error){if(ArraySize(m_descriptors)<1){error="empty feature frame";return false;}string rows="[";for(int i=0;i<ArraySize(m_values);i++){if(i>0)rows+=",";CUCE03CanonicalObject r;r.AddString("descriptor_hash",m_descriptors[i].descriptor_hash);r.AddString("feature_id",m_values[i].feature_id);r.AddString("feature_version",m_values[i].feature_version);r.AddBool("is_missing",m_values[i].is_missing);r.AddLong("known_time_ms",m_values[i].known_time_ms);r.AddString("missing_reason",m_values[i].missing_reason);r.AddLong("source_time_ms",m_values[i].source_time_ms);r.AddJson("value",m_values[i].value_json);rows+=r.Serialize();}rows+="]";CUCE03CanonicalObject o;o.AddString("context_observation_id",m_frame.context_observation_id);o.AddString("context_package_id",m_frame.context_package_id);o.AddString("context_package_version",m_frame.context_package_version);o.AddJson("features",rows);o.AddLong("observation_cut_ms",m_frame.observation_cut_ms);m_frame.frame_hash=UCE02_EvidenceHash(o.Serialize());m_frame.frame_id="uce_feature_"+UCE03_Fnv1a64HexUtf8(m_frame.context_observation_id+"|"+m_frame.frame_hash);frame=m_frame;error="";return true;}
int Count()const{return ArraySize(m_descriptors);}bool ValueAt(const int index,UCE02_FeatureValue &value)const{if(index<0||index>=ArraySize(m_values))return false;value=m_values[index];return true;}
};
#endif
