#ifndef __UCE02_CLUSTER_MQH__
#define __UCE02_CLUSTER_MQH__
#include "UCE02_Representation.mqh"
struct UCE02_ClusterRule{string rule_id;string version;string owner_id;ENUM_UCE02_CLUSTER_KIND kind;string dimensions_csv;string parameters_json;string rule_hash;};
struct UCE02_ClusterAssignment{string rule_id;string rule_version;ENUM_UCE02_CLUSTER_KIND kind;string context_observation_id;string cluster_id;string dimensions_json;string evidence_hash;};
bool UCE02_ValidateClusterRule(const UCE02_ClusterRule &value,string &error){if(!UCE03_IsSafeIdentifier(value.rule_id)||!UCE03_IsSafeIdentifier(value.version)||!UCE03_IsSafeIdentifier(value.owner_id)){error="invalid cluster rule identifier";return false;}if(value.dimensions_csv==""){error="cluster dimensions are required";return false;}if(value.parameters_json==""||StringSubstr(value.parameters_json,0,1)!="{"){error="cluster parameters must be canonical object";return false;}error="";return true;}
void UCE02_SealClusterRule(UCE02_ClusterRule &value){CUCE03CanonicalObject o;o.AddString("dimensions_csv",value.dimensions_csv);o.AddString("kind",UCE02_ClusterKindName(value.kind));o.AddString("owner_id",value.owner_id);o.AddJson("parameters",value.parameters_json);o.AddString("rule_id",value.rule_id);o.AddString("version",value.version);value.rule_hash=UCE02_EvidenceHash(o.Serialize());}
bool UCE02_CompileCluster(const UCE02_ClusterRule &rule,const UCE02_ContextObservation &observation,const string dimensions_json,UCE02_ClusterAssignment &assignment,string &error){if(dimensions_json==""||StringSubstr(dimensions_json,0,1)!="{"){error="cluster dimensions must be canonical object";return false;}assignment.rule_id=rule.rule_id;assignment.rule_version=rule.version;assignment.kind=rule.kind;assignment.context_observation_id=observation.observation_id;assignment.dimensions_json=dimensions_json;string material=rule.rule_id+"|"+rule.version+"|"+UCE02_ClusterKindName(rule.kind)+"|"+dimensions_json;assignment.cluster_id="uce_cluster_"+UCE03_Fnv1a64HexUtf8(material);assignment.evidence_hash=UCE02_EvidenceHash(observation.observation_id+"|"+rule.rule_hash+"|"+dimensions_json);error="";return true;}
#endif
