#ifndef __UCE02_CONTEXT_PACKAGE_MQH__
#define __UCE02_CONTEXT_PACKAGE_MQH__
#include "UCE02_Cluster.mqh"
class IUCE02ContextPackage{
public:virtual ~IUCE02ContextPackage(){}virtual void GetManifest(UCE02_ContextPackageManifest &manifest)const=0;virtual int FeatureCount()const=0;virtual bool GetFeatureDescriptor(const int index,UCE02_FeatureDescriptor &descriptor)const=0;virtual int ViewCount()const=0;virtual bool GetViewDescriptor(const int index,UCE02_ViewDescriptor &descriptor)const=0;virtual int ClusterRuleCount()const=0;virtual bool GetClusterRule(const int index,UCE02_ClusterRule &rule)const=0;virtual bool ValidatePackage(string &error)const=0;};
class CUCE02ContextPackageBase:public IUCE02ContextPackage{
protected:UCE02_ContextPackageManifest m_manifest;UCE02_FeatureDescriptor m_features[];UCE02_ViewDescriptor m_views[];UCE02_ClusterRule m_clusters[];
bool AddFeature(UCE02_FeatureDescriptor &value,string &error){if(!UCE02_ValidateFeatureDescriptor(value,error))return false;UCE02_SealFeatureDescriptor(value);for(int i=0;i<ArraySize(m_features);i++)if(m_features[i].feature_id==value.feature_id){error="duplicate feature_id";return false;}int n=ArraySize(m_features);ArrayResize(m_features,n+1);m_features[n]=value;error="";return true;}
bool AddView(UCE02_ViewDescriptor &value,string &error){if(!UCE02_ValidateViewDescriptor(value,error))return false;UCE02_SealViewDescriptor(value);for(int i=0;i<ArraySize(m_views);i++)if(m_views[i].view_id==value.view_id){error="duplicate view_id";return false;}int n=ArraySize(m_views);ArrayResize(m_views,n+1);m_views[n]=value;error="";return true;}
bool AddCluster(UCE02_ClusterRule &value,string &error){if(!UCE02_ValidateClusterRule(value,error))return false;UCE02_SealClusterRule(value);for(int i=0;i<ArraySize(m_clusters);i++)if(m_clusters[i].rule_id==value.rule_id){error="duplicate cluster rule_id";return false;}int n=ArraySize(m_clusters);ArrayResize(m_clusters,n+1);m_clusters[n]=value;error="";return true;}
public:CUCE02ContextPackageBase(){ArrayResize(m_features,0);ArrayResize(m_views,0);ArrayResize(m_clusters,0);}void GetManifest(UCE02_ContextPackageManifest &manifest)const{manifest=m_manifest;}int FeatureCount()const{return ArraySize(m_features);}bool GetFeatureDescriptor(const int index,UCE02_FeatureDescriptor &descriptor)const{if(index<0||index>=ArraySize(m_features))return false;descriptor=m_features[index];return true;}int ViewCount()const{return ArraySize(m_views);}bool GetViewDescriptor(const int index,UCE02_ViewDescriptor &descriptor)const{if(index<0||index>=ArraySize(m_views))return false;descriptor=m_views[index];return true;}int ClusterRuleCount()const{return ArraySize(m_clusters);}bool GetClusterRule(const int index,UCE02_ClusterRule &rule)const{if(index<0||index>=ArraySize(m_clusters))return false;rule=m_clusters[index];return true;}bool ValidatePackage(string &error)const{if(!UCE02_ValidateManifest(m_manifest,error))return false;if(ArraySize(m_features)<1){error="package has no features";return false;}if(ArraySize(m_views)<1){error="package has no views";return false;}if(ArraySize(m_clusters)<1){error="package has no cluster rules";return false;}error="";return true;}
};
#endif
