#ifndef __UCE02_REFERENCE_SYNTHETIC_MQH__
#define __UCE02_REFERENCE_SYNTHETIC_MQH__
#include "UCE02_Registry.mqh"
struct UCE02_SyntheticBreakInput{string source_event_id;string symbol;int timeframe_seconds;long signal_bar_open_ms;long event_time_ms;long known_time_ms;long confirmation_time_ms;long observation_cut_ms;long decision_time_ms;double prior_high;double prior_low;double close;double atr;double spread_points;string session;string trading_day;};
class CUCE02SyntheticBreakPackage:public CUCE02ContextPackageBase{
private:void AddCoreDescriptors(){string e="";UCE02_FeatureDescriptor f;f.version="1.0.0";f.owner_id="alpha_lab";f.shape_csv="scalar";f.missingness_policy=UCE02_MISSING_REJECT;f.staleness_policy=UCE02_STALE_REJECT;f.max_staleness_ms=0;f.dependencies_csv="";f.availability_mode_mask=31;f.runtime_exportable=true;f.category_values_csv="";f.description="";f.feature_id="break.direction";f.data_type=UCE02_FEATURE_CATEGORY;f.units="side";f.category_values_csv="long,short";AddFeature(f,e);f.feature_id="break.distance_atr";f.data_type=UCE02_FEATURE_FLOAT64;f.units="atr";f.category_values_csv="";AddFeature(f,e);f.feature_id="break.range_atr";AddFeature(f,e);f.feature_id="market.spread_points";f.units="points";f.missingness_policy=UCE02_MISSING_EXPLICIT;f.staleness_policy=UCE02_STALE_MARK;f.max_staleness_ms=2000;AddFeature(f,e);f.feature_id="time.session";f.data_type=UCE02_FEATURE_CATEGORY;f.units="session";f.missingness_policy=UCE02_MISSING_REJECT;f.staleness_policy=UCE02_STALE_ALLOW_WITH_AGE;f.max_staleness_ms=86400000;f.category_values_csv="asia,london,new_york,off_hours";AddFeature(f,e);UCE02_ViewDescriptor v;v.view_id="break.tabular";v.version="1.0.0";v.owner_id="alpha_lab";v.kind=UCE02_VIEW_TABULAR;v.feature_ids_csv="break.direction,break.distance_atr,break.range_atr,market.spread_points,time.session";v.shape_csv="5";v.availability_mode_mask=31;v.runtime_exportable=true;v.parameters_json="{\"ordering\":\"lexicographic\"}";AddView(v,e);UCE02_ClusterRule c;c.rule_id="break.opportunity";c.version="1.0.0";c.owner_id="alpha_lab";c.kind=UCE02_CLUSTER_OPPORTUNITY;c.dimensions_csv="symbol,timeframe_seconds,signal_bar_open_ms,direction";c.parameters_json="{}";AddCluster(c,e);}
public:CUCE02SyntheticBreakPackage(){m_manifest.package_id="ucee.reference.synthetic_break";m_manifest.version="1.0.0";m_manifest.owner_id="alpha_lab";m_manifest.doctrine_id="doctrine.synthetic_break";m_manifest.doctrine_version="1.0.0";m_manifest.anatomy_adapter_id="ucee.reference.break_adapter";m_manifest.anatomy_adapter_version="1.0.0";m_manifest.update_scope_mask=UCE02_UPDATE_NEW_BAR|UCE02_UPDATE_REPLAY|UCE02_UPDATE_HISTORY_REBUILD;m_manifest.runtime_mode_mask=31;m_manifest.parent_package_id="none";m_manifest.description="Synthetic causal reference context";m_manifest.metadata_json="{}";UCE02_SealManifest(m_manifest);AddCoreDescriptors();}
bool Observe(const UCE02_SyntheticBreakInput &input,UCE02_ContextObservation &observation,bool &emitted,string &error)const{emitted=false;if(input.close<=input.prior_high&&input.close>=input.prior_low){error="";return true;}if(input.atr<=0.0){error="invalid ATR";return false;}string direction=input.close>input.prior_high?"long":"short";CUCE03CanonicalObject p;p.AddString("direction",direction);p.AddJson("prior_high",UCE03_CanonicalScaledInteger((long)MathRound((input.prior_high)*100000000.0),8));p.AddJson("prior_low",UCE03_CanonicalScaledInteger((long)MathRound((input.prior_low)*100000000.0),8));p.AddJson("close",UCE03_CanonicalScaledInteger((long)MathRound((input.close)*100000000.0),8));p.AddJson("atr",UCE03_CanonicalScaledInteger((long)MathRound((input.atr)*100000000.0),8));p.AddJson("spread_points",UCE03_CanonicalScaledInteger((long)MathRound((input.spread_points)*10000.0),4));p.AddString("session",input.session);p.AddString("trading_day",input.trading_day);p.AddLong("signal_bar_open_ms",input.signal_bar_open_ms);observation.package_id=m_manifest.package_id;observation.package_version=m_manifest.version;observation.source_event_ids_csv=input.source_event_id;observation.symbol_scope_csv=input.symbol;observation.timeframe_scope_csv=IntegerToString(input.timeframe_seconds);observation.lifecycle_state=UCE02_CONTEXT_CONFIRMED;observation.time_chain.event_time=UCE03_MakeUtcInstant(input.event_time_ms,"fixture.utc");observation.time_chain.known_time=UCE03_MakeUtcInstant(input.known_time_ms,"fixture.utc");observation.time_chain.confirmation_time=UCE03_MakeUtcInstant(input.confirmation_time_ms,"fixture.utc");observation.time_chain.observation_cut=UCE03_MakeUtcInstant(input.observation_cut_ms,"fixture.utc");observation.time_chain.decision_time=UCE03_MakeUtcInstant(input.decision_time_ms,"fixture.utc");observation.time_chain.has_action_time=false;observation.time_chain.has_fill_time=false;observation.time_chain.has_label_maturity_time=false;observation.payload_json=p.Serialize();observation.parent_observation_id="none";observation.supersedes_observation_id="none";observation.sequence=0;if(!UCE02_SealObservation(observation,error))return false;emitted=true;return true;}
};
#endif
