#ifndef __UCE02_REPRESENTATION_MQH__
#define __UCE02_REPRESENTATION_MQH__
#include "UCE02_Feature.mqh"
struct UCE02_ViewDescriptor{string view_id;string version;string owner_id;ENUM_UCE02_VIEW_KIND kind;string feature_ids_csv;string shape_csv;int availability_mode_mask;bool runtime_exportable;string parameters_json;string descriptor_hash;};
struct UCE02_RepresentationView{string view_id;string version;string context_observation_id;string feature_frame_hash;string payload_json;string view_instance_id;string view_hash;};
bool UCE02_ValidateViewDescriptor(const UCE02_ViewDescriptor &value,string &error){if(!UCE03_IsSafeIdentifier(value.view_id)||!UCE03_IsSafeIdentifier(value.version)||!UCE03_IsSafeIdentifier(value.owner_id)){error="invalid view descriptor identifier";return false;}if(value.feature_ids_csv==""||value.shape_csv==""){error="view features and shape are required";return false;}if(value.availability_mode_mask==0){error="empty view availability";return false;}if(value.parameters_json==""||StringSubstr(value.parameters_json,0,1)!="{"){error="view parameters must be canonical object";return false;}error="";return true;}
string UCE02_ViewDescriptorMaterial(const UCE02_ViewDescriptor &value){CUCE03CanonicalObject o;o.AddLong("availability_mode_mask",value.availability_mode_mask);o.AddString("feature_ids_csv",value.feature_ids_csv);o.AddString("kind",UCE02_ViewKindName(value.kind));o.AddString("owner_id",value.owner_id);o.AddJson("parameters",value.parameters_json);o.AddBool("runtime_exportable",value.runtime_exportable);o.AddString("shape_csv",value.shape_csv);o.AddString("version",value.version);o.AddString("view_id",value.view_id);return o.Serialize();}
void UCE02_SealViewDescriptor(UCE02_ViewDescriptor &value){value.descriptor_hash=UCE02_EvidenceHash(UCE02_ViewDescriptorMaterial(value));}
class CUCE02ViewRegistry{
private:UCE02_ViewDescriptor m_items[];
public:void Clear(){ArrayResize(m_items,0);}bool Register(const UCE02_ViewDescriptor &value,string &error){for(int i=0;i<ArraySize(m_items);i++)if(m_items[i].view_id==value.view_id&&m_items[i].version==value.version){error="duplicate view descriptor";return false;}int n=ArraySize(m_items);ArrayResize(m_items,n+1);m_items[n]=value;error="";return true;}bool Resolve(const string id,const string version,UCE02_ViewDescriptor &value)const{for(int i=0;i<ArraySize(m_items);i++)if(m_items[i].view_id==id&&m_items[i].version==version){value=m_items[i];return true;}return false;}int Count()const{return ArraySize(m_items);}
bool CompileTabular(const UCE02_ViewDescriptor &descriptor,const UCE02_FeatureFrame &frame,const string columns_json,const string values_json,UCE02_RepresentationView &view,string &error)const{if(descriptor.kind!=UCE02_VIEW_TABULAR){error="descriptor is not tabular";return false;}view.view_id=descriptor.view_id;view.version=descriptor.version;view.context_observation_id=frame.context_observation_id;view.feature_frame_hash=frame.frame_hash;CUCE03CanonicalObject p;p.AddJson("columns",columns_json);p.AddJson("values",values_json);view.payload_json=p.Serialize();CUCE03CanonicalObject m;m.AddString("context_observation_id",view.context_observation_id);m.AddString("descriptor_hash",descriptor.descriptor_hash);m.AddString("feature_frame_hash",view.feature_frame_hash);m.AddJson("payload",view.payload_json);m.AddString("view_id",view.view_id);m.AddString("version",view.version);view.view_hash=UCE02_EvidenceHash(m.Serialize());view.view_instance_id="uce_view_"+UCE03_Fnv1a64HexUtf8(view.context_observation_id+"|"+view.view_id+"|"+view.view_hash);error="";return true;}
};
#endif
