#ifndef __UCE02_MANIFEST_MQH__
#define __UCE02_MANIFEST_MQH__
#include "../Contracts/UCE03_AllContracts.mqh"
#include "UCE02_Enums.mqh"
struct UCE02_SourceRequirement{string requirement_id;ENUM_UCE02_SOURCE_KIND kind;ENUM_UCE02_REQUIREMENT_STRENGTH strength;string symbols_csv;int timeframe_seconds;int lookback;long max_staleness_ms;string synchronization_group_id;string purpose;};
struct UCE02_ComponentReference{string component_id;string version;string schema_hash;bool required;};
struct UCE02_ContextPackageManifest{string package_id;string version;string owner_id;string doctrine_id;string doctrine_version;string anatomy_adapter_id;string anatomy_adapter_version;int update_scope_mask;int runtime_mode_mask;string parent_package_id;string description;string metadata_json;string manifest_hash;};
string UCE02_EvidenceHash(const string material){return "fnv1a64:"+UCE03_Fnv1a64HexUtf8(material);}
bool UCE02_ValidateSourceRequirement(const UCE02_SourceRequirement &value,string &error){if(!UCE03_IsSafeIdentifier(value.requirement_id)){error="invalid requirement_id";return false;}if(value.symbols_csv==""){error="source symbols are required";return false;}if(value.timeframe_seconds<0||value.lookback<0||value.max_staleness_ms<0){error="negative source requirement limit";return false;}if(!UCE03_IsSafeIdentifier(value.synchronization_group_id)){error="invalid synchronization_group_id";return false;}error="";return true;}
bool UCE02_ValidateManifest(const UCE02_ContextPackageManifest &value,string &error){if(!UCE03_IsSafeIdentifier(value.package_id)||!UCE03_IsSafeIdentifier(value.version)||!UCE03_IsSafeIdentifier(value.owner_id)||!UCE03_IsSafeIdentifier(value.doctrine_id)||!UCE03_IsSafeIdentifier(value.doctrine_version)||!UCE03_IsSafeIdentifier(value.anatomy_adapter_id)||!UCE03_IsSafeIdentifier(value.anatomy_adapter_version)){error="invalid package manifest identifier";return false;}if(value.update_scope_mask==0){error="empty update scope";return false;}if(value.runtime_mode_mask==0){error="empty runtime mode";return false;}if(value.parent_package_id==""){error="parent_package_id is required; use none explicitly";return false;}error="";return true;}
string UCE02_ManifestMaterial(const UCE02_ContextPackageManifest &value){CUCE03CanonicalObject o;o.AddString("anatomy_adapter_id",value.anatomy_adapter_id);o.AddString("anatomy_adapter_version",value.anatomy_adapter_version);o.AddString("description",value.description);o.AddString("doctrine_id",value.doctrine_id);o.AddString("doctrine_version",value.doctrine_version);o.AddJson("metadata",value.metadata_json==""?"{}":value.metadata_json);o.AddString("owner_id",value.owner_id);o.AddString("package_id",value.package_id);o.AddString("parent_package_id",value.parent_package_id);o.AddLong("runtime_mode_mask",value.runtime_mode_mask);o.AddLong("update_scope_mask",value.update_scope_mask);o.AddString("version",value.version);return o.Serialize();}
void UCE02_SealManifest(UCE02_ContextPackageManifest &value){value.manifest_hash=UCE02_EvidenceHash(UCE02_ManifestMaterial(value));}
string UCE02_PackageIdentity(const UCE02_ContextPackageManifest &value){UCE03_IdentityKey key;key.kind=UCE03_ID_CONTEXT_OCCURRENCE;key.semantic_namespace="ucee.context_package";key.semantic_version=value.version;key.owner_id=value.owner_id;CUCE03CanonicalObject d;d.AddString("manifest_hash",value.manifest_hash);d.AddString("package_id",value.package_id);key.dimensions_json=d.Serialize();return UCE03_StableIdentity(key);}
#endif
