#ifndef __UCE02_ENUMS_MQH__
#define __UCE02_ENUMS_MQH__
enum ENUM_UCE02_CONTEXT_STATE{UCE02_CONTEXT_DETECTED=0,UCE02_CONTEXT_CONFIRMED=1,UCE02_CONTEXT_ACTIVE=2,UCE02_CONTEXT_INVALIDATED=3,UCE02_CONTEXT_EXPIRED=4,UCE02_CONTEXT_SUPERSEDED=5,UCE02_CONTEXT_RETIRED=6};
enum ENUM_UCE02_SOURCE_KIND{UCE02_SOURCE_CLOSED_BARS=0,UCE02_SOURCE_TICKS=1,UCE02_SOURCE_SYMBOL_SPEC=2,UCE02_SOURCE_ACCOUNT=3,UCE02_SOURCE_CALENDAR=4,UCE02_SOURCE_EXTERNAL_LEDGER=5,UCE02_SOURCE_ANATOMY_EVENT=6};
enum ENUM_UCE02_REQUIREMENT_STRENGTH{UCE02_REQUIREMENT_REQUIRED=0,UCE02_REQUIREMENT_OPTIONAL=1};
enum ENUM_UCE02_FEATURE_TYPE{UCE02_FEATURE_BOOL=0,UCE02_FEATURE_INT64=1,UCE02_FEATURE_FLOAT64=2,UCE02_FEATURE_CATEGORY=3,UCE02_FEATURE_STRING=4,UCE02_FEATURE_VECTOR_FLOAT64=5};
enum ENUM_UCE02_MISSING_POLICY{UCE02_MISSING_REJECT=0,UCE02_MISSING_EXPLICIT=1,UCE02_MISSING_ZERO_VALID=2,UCE02_MISSING_FORWARD_FILL_BOUNDED=3,UCE02_MISSING_NOT_APPLICABLE=4};
enum ENUM_UCE02_STALE_POLICY{UCE02_STALE_REJECT=0,UCE02_STALE_MARK=1,UCE02_STALE_ALLOW_WITH_AGE=2};
enum ENUM_UCE02_VIEW_KIND{UCE02_VIEW_TABULAR=0,UCE02_VIEW_SEQUENCE=1,UCE02_VIEW_GRAPH=2,UCE02_VIEW_INTERMARKET=3,UCE02_VIEW_RASTER=4,UCE02_VIEW_SPARSE_EVENT=5,UCE02_VIEW_PATH_SIGNATURE=6,UCE02_VIEW_EXECUTION=7,UCE02_VIEW_PORTFOLIO=8,UCE02_VIEW_FUSED=9};
enum ENUM_UCE02_CLUSTER_KIND{UCE02_CLUSTER_OPPORTUNITY=0,UCE02_CLUSTER_OVERLAPPING_PATH=1,UCE02_CLUSTER_PARENT_CHILD=2,UCE02_CLUSTER_SYMBOL_SESSION_DAY=3,UCE02_CLUSTER_TREATMENT_SIBLING=4,UCE02_CLUSTER_CUSTOM=5};
enum ENUM_UCE02_FRESHNESS_STATE{UCE02_FRESH=0,UCE02_STALE=1,UCE02_MISSING=2,UCE02_INVALID=3};
#define UCE02_UPDATE_TICK 1
#define UCE02_UPDATE_NEW_BAR 2
#define UCE02_UPDATE_TIMER 4
#define UCE02_UPDATE_REPLAY 8
#define UCE02_UPDATE_HISTORY_REBUILD 16
#define UCE02_UPDATE_MANUAL 32
#define UCE02_MODE_RESEARCH 1
#define UCE02_MODE_TESTER 2
#define UCE02_MODE_PAPER 4
#define UCE02_MODE_SHADOW 8
#define UCE02_MODE_LIVE 16
string UCE02_ContextStateName(const ENUM_UCE02_CONTEXT_STATE value){switch(value){case UCE02_CONTEXT_DETECTED:return "detected";case UCE02_CONTEXT_CONFIRMED:return "confirmed";case UCE02_CONTEXT_ACTIVE:return "active";case UCE02_CONTEXT_INVALIDATED:return "invalidated";case UCE02_CONTEXT_EXPIRED:return "expired";case UCE02_CONTEXT_SUPERSEDED:return "superseded";default:return "retired";}}
string UCE02_ViewKindName(const ENUM_UCE02_VIEW_KIND value){switch(value){case UCE02_VIEW_TABULAR:return "tabular";case UCE02_VIEW_SEQUENCE:return "sequence";case UCE02_VIEW_GRAPH:return "graph";case UCE02_VIEW_INTERMARKET:return "intermarket";case UCE02_VIEW_RASTER:return "raster";case UCE02_VIEW_SPARSE_EVENT:return "sparse_event";case UCE02_VIEW_PATH_SIGNATURE:return "path_signature";case UCE02_VIEW_EXECUTION:return "execution";case UCE02_VIEW_PORTFOLIO:return "portfolio";default:return "fused";}}
string UCE02_ClusterKindName(const ENUM_UCE02_CLUSTER_KIND value){switch(value){case UCE02_CLUSTER_OPPORTUNITY:return "opportunity";case UCE02_CLUSTER_OVERLAPPING_PATH:return "overlapping_path";case UCE02_CLUSTER_PARENT_CHILD:return "parent_child";case UCE02_CLUSTER_SYMBOL_SESSION_DAY:return "symbol_session_day";case UCE02_CLUSTER_TREATMENT_SIBLING:return "treatment_sibling";default:return "custom";}}
#endif
