#ifndef __UCE02_EXP0017_REFERENCE_MQH__
#define __UCE02_EXP0017_REFERENCE_MQH__
#include "UCE02_ReferenceSynthetic.mqh"
#include "../Integration/EXP0017/SF20_EXP0017Contracts.mqh"
struct UCE02_EXP0017ContextInput{string canonical_event_id;string parent_event_id;long event_time_ms;long known_time_ms;long confirmation_time_ms;long observation_cut_ms;long decision_time_ms;string hunter_symbol;string clean_symbol;int group_minutes;string direction;double hunter_reference_price;double clean_reference_price;double hunter_current_extreme;double clean_current_extreme;string trading_day;long current_cycle_start_ms;};
class CUCE02EXP0017ReferencePackage:public CUCE02ContextPackageBase{
private:void AddCoreDescriptors(){string e="";UCE02_FeatureDescriptor f;f.version="1.0.0";f.owner_id="alpha_lab";f.shape_csv="scalar";f.missingness_policy=UCE02_MISSING_REJECT;f.staleness_policy=UCE02_STALE_REJECT;f.max_staleness_ms=0;f.dependencies_csv="";f.availability_mode_mask=31;f.runtime_exportable=true;f.category_values_csv="";f.description="";f.feature_id="exp0017.clean_displacement";f.data_type=UCE02_FEATURE_FLOAT64;f.units="price";AddFeature(f,e);f.feature_id="exp0017.direction";f.data_type=UCE02_FEATURE_CATEGORY;f.units="side";f.category_values_csv="long,short";AddFeature(f,e);f.feature_id="exp0017.divergence_gap";f.data_type=UCE02_FEATURE_FLOAT64;f.units="price";f.category_values_csv="";AddFeature(f,e);f.feature_id="exp0017.group_minutes";f.data_type=UCE02_FEATURE_INT64;f.units="minutes";f.staleness_policy=UCE02_STALE_ALLOW_WITH_AGE;f.max_staleness_ms=86400000;AddFeature(f,e);f.feature_id="exp0017.hunter_displacement";f.data_type=UCE02_FEATURE_FLOAT64;f.units="price";f.staleness_policy=UCE02_STALE_REJECT;f.max_staleness_ms=0;AddFeature(f,e);UCE02_ViewDescriptor v;v.view_id="exp0017.tabular";v.version="1.0.0";v.owner_id="alpha_lab";v.kind=UCE02_VIEW_TABULAR;v.feature_ids_csv="exp0017.clean_displacement,exp0017.direction,exp0017.divergence_gap,exp0017.group_minutes,exp0017.hunter_displacement";v.shape_csv="5";v.availability_mode_mask=31;v.runtime_exportable=true;v.parameters_json="{\"ordering\":\"lexicographic\"}";AddView(v,e);UCE02_ClusterRule c;c.rule_id="exp0017.opportunity";c.version="1.0.0";c.owner_id="alpha_lab";c.kind=UCE02_CLUSTER_OPPORTUNITY;c.dimensions_csv="trading_day,group_minutes,direction,hunter_symbol,clean_symbol";c.parameters_json="{}";AddCluster(c,e);}
public:CUCE02EXP0017ReferencePackage(){m_manifest.package_id="ucee.reference.exp0017";m_manifest.version="1.0.0";m_manifest.owner_id="alpha_lab";m_manifest.doctrine_id="exp0017.temporal_intermarket_divergence";m_manifest.doctrine_version="1.0.0";m_manifest.anatomy_adapter_id=SF20_EXP0017_PLUGIN_ID;m_manifest.anatomy_adapter_version=SF20_EXP0017_PLUGIN_VERSION;m_manifest.update_scope_mask=UCE02_UPDATE_TIMER|UCE02_UPDATE_REPLAY|UCE02_UPDATE_HISTORY_REBUILD;m_manifest.runtime_mode_mask=31;m_manifest.parent_package_id="none";m_manifest.description="Reference package consuming SF20 EXP0017 adapter events";m_manifest.metadata_json="{}";UCE02_SealManifest(m_manifest);AddCoreDescriptors();}
bool Observe(const UCE02_EXP0017ContextInput &input,UCE02_ContextObservation &observation,string &error)const{if(input.canonical_event_id==""||input.hunter_symbol==""||input.clean_symbol==""){error="incomplete EXP0017 source";return false;}CUCE03CanonicalObject p;p.AddString("direction",input.direction);p.AddLong("group_minutes",input.group_minutes);p.AddString("hunter_symbol",input.hunter_symbol);p.AddString("clean_symbol",input.clean_symbol);p.AddJson("hunter_reference_price",UCE03_CanonicalScaledInteger((long)MathRound((input.hunter_reference_price)*100000000.0),8));p.AddJson("clean_reference_price",UCE03_CanonicalScaledInteger((long)MathRound((input.clean_reference_price)*100000000.0),8));p.AddJson("hunter_current_extreme",UCE03_CanonicalScaledInteger((long)MathRound((input.hunter_current_extreme)*100000000.0),8));p.AddJson("clean_current_extreme",UCE03_CanonicalScaledInteger((long)MathRound((input.clean_current_extreme)*100000000.0),8));p.AddString("trading_day",input.trading_day);p.AddLong("current_cycle_start_ms",input.current_cycle_start_ms);observation.package_id=m_manifest.package_id;observation.package_version=m_manifest.version;observation.source_event_ids_csv=input.canonical_event_id;observation.symbol_scope_csv=input.hunter_symbol+","+input.clean_symbol;observation.timeframe_scope_csv="60";observation.lifecycle_state=UCE02_CONTEXT_CONFIRMED;observation.time_chain.event_time=UCE03_MakeUtcInstant(input.event_time_ms,"utc");observation.time_chain.known_time=UCE03_MakeUtcInstant(input.known_time_ms,"utc");observation.time_chain.confirmation_time=UCE03_MakeUtcInstant(input.confirmation_time_ms,"utc");observation.time_chain.observation_cut=UCE03_MakeUtcInstant(input.observation_cut_ms,"utc");observation.time_chain.decision_time=UCE03_MakeUtcInstant(input.decision_time_ms,"utc");observation.time_chain.has_action_time=false;observation.time_chain.has_fill_time=false;observation.time_chain.has_label_maturity_time=false;observation.payload_json=p.Serialize();observation.parent_observation_id=input.parent_event_id==""?"none":input.parent_event_id;observation.supersedes_observation_id="none";observation.sequence=0;return UCE02_SealObservation(observation,error);}
};
#endif
