#ifndef ALPHALAB_ACL08_CONSTANTS_MQH
#define ALPHALAB_ACL08_CONSTANTS_MQH
#define ACL08_SCHEMA_VERSION "1.0.0"
#define ACL08_CLAIM_CEILING "REPORTING_AND_EXPERIENCE_REFERENCE_ONLY"
#define ACL08_LIVE_ORDER_SUBMISSION_ALLOWED false
#define ACL08_CAPITAL_ACTIVATION_ALLOWED false
#define ACL08_PROMOTION_ALLOWED false
#endif
