from pathlib import Path
BASE=Path(__file__).resolve().parents[4]
REGISTRY_ROOT=BASE/'registry/acl_os/acl_08'
SCHEMA_ROOT=REGISTRY_ROOT/'schemas/v1'
POLICY_ROOT=REGISTRY_ROOT/'policies/v1'
HANDOFF_IN='ACL07_TO_ACL08'
HANDOFF_OUT='ACL08_TO_ACL09'
REQUIRED_UPSTREAM_ACTIONS={'BUILD_BATCH_REPORT','PROJECT_VALIDATION_EVIDENCE','CAPTURE_NON_PROMOTIONAL_EXPERIENCE'}
FORBIDDEN_UPSTREAM_ACTIONS={'MUTATE_VALIDATION_DECISIONS','INFER_ALPHA_FROM_REPORTING','PROMOTE_DIAGNOSTIC_LANE','AUTHORIZE_EXECUTION','ACTIVATE_CAPITAL'}
REQUIRED_ACTION='ACL08_BUILD_REPORT_AND_EXPERIENCE'
CLAIM_CEILING='REPORTING_AND_EXPERIENCE_REFERENCE_ONLY'
REPORTER_VERSION='1.0.0'
AUDIENCES={'INTERNAL_RESEARCH','EXECUTIVE','EXTERNAL_RESTRICTED'}
EXPERIENCE_CLASSES={'BASELINE_REFERENCE','INSUFFICIENT_EVIDENCE','NEGATIVE_VALIDATION','REPORTABLE_EVIDENCE','DIAGNOSTIC_EXCLUSION'}
