#ifndef FP_I15_POLICY_MQH
#define FP_I15_POLICY_MQH
#include "FP_I15_Enums.mqh"
enum FP_I15_POLICY_PROFILE { FP_I15_POLICY_UNSET=0, FP_I15_POLICY_PLAN_CREATED=1, FP_I15_POLICY_ORDER_ATTEMPTED=2, FP_I15_POLICY_ORDER_ACCEPTED=3, FP_I15_POLICY_FILLED=4, FP_I15_POLICY_TWO_STAGE_ACCEPTED=5, FP_I15_POLICY_TWO_STAGE_FILLED=6 };
FP_I15_CONSUME_EVENT FP_I15_PolicyConsumeEvent(const FP_I15_POLICY_PROFILE p){ if(p==FP_I15_POLICY_PLAN_CREATED)return FP_I15_CONSUME_PLAN; if(p==FP_I15_POLICY_ORDER_ATTEMPTED)return FP_I15_CONSUME_ATTEMPT; if(p==FP_I15_POLICY_ORDER_ACCEPTED||p==FP_I15_POLICY_TWO_STAGE_ACCEPTED)return FP_I15_CONSUME_ACCEPTED; if(p==FP_I15_POLICY_FILLED||p==FP_I15_POLICY_TWO_STAGE_FILLED)return FP_I15_CONSUME_FIRST_FILL; return FP_I15_CONSUME_UNSET; }
#endif
