from __future__ import annotations
import json,os,re,runpy,subprocess,sys,time
from _common import ROOT,AR,SC,DOC,PY_ROOT,MQL_INCLUDE,MQL_EXPERT
started=time.perf_counter();tool=ROOT/"src/engine/tooling/strategy_factory/saed_v4_33";env=dict(os.environ);env["PYTHONPATH"]=str(PY_ROOT)+os.pathsep+env.get("PYTHONPATH","")
c=subprocess.run([sys.executable,"-m","pytest","-q",str(ROOT/"tests/legacy/strategy_factory/v1/phase_saed_v4_33_federated_confidential_research")],cwd=ROOT,env=env,text=True,capture_output=True);print(c.stdout,end="");print(c.stderr,end="",file=sys.stderr)
if c.returncode:raise SystemExit(c.returncode)
m=re.search(r"(\d+) passed",c.stdout);assert m;python_tests=int(m.group(1))
for name in ["validate_saed_v4_33_contracts.py","validate_saed_v4_33_governance.py","check_saed_v4_33_boundaries.py","validate_saed_v4_33_replay.py","validate_saed_v4_33_obsidian.py","validate_saed_v4_33_mql5_static.py"]:runpy.run_path(str(tool/name),run_name="__main__")
cert=json.loads((AR/"GOLDEN_FEDERATED_CONFIDENTIAL_RESEARCH_CERTIFICATE.JSON").read_text());handoff=json.loads((AR/"V4_33_TO_V4_34_HANDOFF.JSON").read_text());phase_notes=len(list((DOC/"62_PHASE_DELIVERIES_V4/V4_33").glob("*.md")));atomic_notes=len(list((DOC/"63_ATOMIC_CONCEPTS_V4/V4_33").glob("*.md")));obsidian_notes=phase_notes+atomic_notes+1;mql5_files=len(list(MQL_INCLUDE.glob("*.mqh")))+len(list(MQL_EXPERT.glob("*.mq5")))
status={"phase":"SAED_V4_33","title":"Federated Confidential Research","version":"1.0.0","status":"accepted_reference","qa_passed":True,"python_tests":python_tests,"closed_schemas":len(list(SC.glob("*.SCHEMA.JSON"))),"closed_schema_pairs":len(list(SC.glob("*.SCHEMA.JSON"))),"golden_exact_artifacts":len(list(AR.glob("*.JSON"))),"obsidian_notes":obsidian_notes,"phase_delivery_notes":phase_notes,"atomic_notes":atomic_notes,"mql5_static_files":mql5_files,"certificate_id":cert["certificate_id"],"certificate_hash":cert["certificate_hash"],"handoff_id":handoff["handoff_id"],"handoff_hash":handoff["handoff_hash"],"raw_data_local_verified":True,"cross_cell_identity_attestation_verified":True,"privacy_budget_accounting_verified":True,"secure_update_envelope_reference_verified":True,"aggregation_threshold_verified":True,"byzantine_screening_reference_verified":True,"complete_federated_provenance":True,"complete_exposure_accounting":True,"synthetic_fixture_only":True,"real_federated_runtime":"not_claimed","real_cryptographic_confidentiality":"not_claimed","formal_differential_privacy":"not_claimed","real_byzantine_resistance":"not_claimed","metaeditor_compile":"pending_local_windows","runtime_parity":"not_claimed","broker_qualification":"not_claimed","prospective_shadow":"not_claimed","real_alpha":"not_claimed","promotion_authority":False,"runtime_executable":False,"risk_allocation_authority":False,"execution_authority":False,"production_authorization":False,"online_learning_authority":False,"live_trading_authority":False,"next_phase":"SAED_V4_34","claim_ceiling":cert["claim_ceiling"]}
sp=ROOT/"releases/history/strategy_factory/program/status/SAED_V4_33.json";sp.parent.mkdir(parents=True,exist_ok=True);sp.write_text(json.dumps(status,indent=2,sort_keys=True)+"\n")
qa={"phase":"SAED_V4_33","title":"Federated Confidential Research","version":"1.0.0","passed":True,"python_tests":python_tests,"closed_schema_pairs":status["closed_schema_pairs"],"golden_artifacts":status["golden_exact_artifacts"],"obsidian_notes":obsidian_notes,"phase_delivery_notes":phase_notes,"atomic_notes":atomic_notes,"mql5_static_files":mql5_files,"upstream_binding_passed":True,"raw_data_residency_passed":True,"identity_attestation_passed":True,"privacy_budget_passed":True,"future_suffix_invariance_passed":True,"deterministic_replay_passed":True,"aggregation_threshold_passed":True,"outlier_quarantine_passed":True,"provenance_passed":True,"zero_authority_passed":True,"elapsed_seconds":round(time.perf_counter()-started,6),"external_evidence":{"real_federated_runtime":"not_claimed","real_cryptography":"not_claimed","formal_differential_privacy":"not_claimed","hardware_attestation":"not_claimed","metaeditor_compile":"pending_local_windows","python_mql5_runtime_parity":"not_claimed","broker_qualification":"not_claimed","prospective_shadow":"not_claimed","production_authorization":"not_claimed"}}
(ROOT/"releases/history/saed/reports/SAED_V4_33_QA_REPORT.json").write_text(json.dumps(qa,indent=2,sort_keys=True)+"\n");runpy.run_path(str(tool/"validate_saed_v4_33_status.py"),run_name="__main__");print(f"V4-33 full QA passed: {python_tests} tests, {status['closed_schema_pairs']} schema pairs, {obsidian_notes} notes, {mql5_files} MQL5 static files")
