#ifndef __UCEI10_ENUMS_MQH__
#define __UCEI10_ENUMS_MQH__

enum UCEI10_DEEP_FAMILY
  {
   UCEI10_SEQUENCE=0,
   UCEI10_VISION=1,
   UCEI10_GRAPH=2,
   UCEI10_REGIME_ANOMALY=3,
   UCEI10_MULTI_VIEW_FUSION=4,
   UCEI10_TRANSFER_COMPRESSION=5,
   UCEI10_QUALIFICATION=6
  };

enum UCEI10_ADMISSION_DECISION
  {
   UCEI10_ADMIT_ACCEPT=0,
   UCEI10_ADMIT_WARN=1,
   UCEI10_ADMIT_REJECT=2
  };

enum UCEI10_QUALIFICATION_DECISION
  {
   UCEI10_PROMOTABLE=0,
   UCEI10_CHALLENGER_ONLY=1,
   UCEI10_REJECTED=2
  };

enum UCEI10_REGIME_GATE_DECISION
  {
   UCEI10_EXPERT=0,
   UCEI10_GLOBAL=1,
   UCEI10_ABSTAIN=2
  };

enum UCEI10_EXPORT_PATH
  {
   UCEI10_EXPORT_NONE=0,
   UCEI10_EXPORT_NATIVE_JSON=1,
   UCEI10_EXPORT_ONNX=2,
   UCEI10_EXPORT_DISTILLED_MQL5=3
  };

enum UCEI10_MISSING_VIEW_POLICY
  {
   UCEI10_MISSING_REJECT=0,
   UCEI10_MISSING_ABSTAIN=1,
   UCEI10_MISSING_ZERO_FILL=2,
   UCEI10_MISSING_GLOBAL_FALLBACK=3
  };

enum UCEI10_FUSION_KIND
  {
   UCEI10_FUSION_LATE_WEIGHTED=0,
   UCEI10_FUSION_GATED=1,
   UCEI10_FUSION_STACKED=2
  };

enum UCEI10_DEPENDENCY_STATUS
  {
   UCEI10_DEP_AVAILABLE=0,
   UCEI10_DEP_MISSING=1,
   UCEI10_DEP_INCOMPATIBLE=2
  };

enum UCEI10_TRANSFER_DECISION
  {
   UCEI10_TRANSFER_ACCEPT=0,
   UCEI10_TRANSFER_REJECT=1
  };

#endif
