#ifndef FP_I07_LIFECYCLE_ENGINE_MQH
#define FP_I07_LIFECYCLE_ENGINE_MQH
ENUM_FP_I07_CONFIRMATION_STATE FP_I07_StateForOutcome(const ENUM_FP_I07_OUTCOME outcome)
{
   if(outcome==FP_I07_OUT_CONFIRMED) return FP_I07_CONFIRMED;
   if(outcome==FP_I07_OUT_DOUBLE_HUNT) return FP_I07_CANCELLED_SECOND_TOUCH;
   if(outcome==FP_I07_OUT_ROLE_CHANGED) return FP_I07_CANCELLED_ROLE_CHANGED;
   if(outcome==FP_I07_OUT_NO_SIGNAL) return FP_I07_NO_SIGNAL_AT_CLOSE;
   if(outcome==FP_I07_OUT_DEADLINE_MISSED) return FP_I07_EXPIRED_DEADLINE;
   if(outcome==FP_I07_OUT_REPLAY_REQUIRED) return FP_I07_MISSED_CLOSE_REPLAY_REQUIRED;
   return FP_I07_INVALID_DATA;
}
bool FP_I07_IsTerminal(const ENUM_FP_I07_CONFIRMATION_STATE state) { return state!=FP_I07_PENDING; }
#endif
