from __future__ import annotations
from .canonical import stable_id,with_digest
def build_contracts(binding:dict,policy:dict,auth:dict,closed_at:str)->dict:
    fleet_id=stable_id('FLEET',binding['pilot_contract_id'],policy['fleet_namespace'],length=32)
    ownership=with_digest({'schema_version':'1.0.0','ownership_contract_id':stable_id('OWNER',fleet_id),'fleet_id':fleet_id,'roles':policy['lifecycle_owners'],'minimum_independent_roles':3,'self_approval_allowed':False,'role_collapse_allowed':False,'owner_change_requires_event':True},'ownership_contract_digest')
    retention=with_digest({'schema_version':'1.0.0','retention_contract_id':stable_id('RETENTION',fleet_id),'fleet_id':fleet_id,'retention_class':policy['retention']['retention_class'],'minimum_days':policy['retention']['minimum_days'],'immutable_history_required':True,'deletion_allowed':False,'legal_hold_supported':True,'archive_digest_required':True},'retention_contract_digest')
    surveillance=with_digest({'schema_version':'1.0.0','surveillance_contract_id':stable_id('SURVEIL',fleet_id),'fleet_id':fleet_id,'mode':'REFERENCE_PACKAGE_SURVEILLANCE','checks':policy['surveillance_checks'],'cadence':policy['surveillance_cadence'],'automatic_runtime_action_allowed':False,'automatic_order_action_allowed':False,'automatic_capital_action_allowed':False,'production_monitoring_claimed':False},'surveillance_contract_digest')
    migration=with_digest({'schema_version':'1.0.0','migration_contract_id':stable_id('MIGRATE',fleet_id),'fleet_id':fleet_id,'allowed_migrations':policy['allowed_migrations'],'new_version_required':True,'human_review_required':True,'source_history_mutation_allowed':False,'evidence_reclassification_allowed':False},'migration_contract_digest')
    reopen=with_digest({'schema_version':'1.0.0','reopen_policy_id':stable_id('REOPEN',fleet_id),'fleet_id':fleet_id,'allowed_actions':policy['allowed_reopen_actions'],'new_authority_permit_required':True,'new_real_evidence_required_for_pilot':True,'new_frozen_package_required':True,'closed_history_mutation_allowed':False,'automatic_reopen_allowed':False},'reopen_policy_digest')
    closure_policy=with_digest({'schema_version':'1.0.0','closure_policy_id':stable_id('CLOSEPOL',fleet_id),'fleet_id':fleet_id,'close_reference_lifecycle':True,'preserve_unknowns':True,'preserve_failures':True,'preserve_unexecuted_state':True,'prospective_outcome_invention_allowed':False,'validation_bypass_allowed':False,'promotion_bypass_allowed':False,'runtime_generation_allowed':False,'live_order_submission_allowed':False,'capital_activation_allowed':False},'closure_policy_digest')
    fleet=with_digest({'schema_version':'1.0.0','fleet_registration_id':stable_id('FLEETREG',fleet_id),'fleet_id':fleet_id,'fleet_namespace':policy['fleet_namespace'],'package_type':'FIRST_REAL_CONTEXT_PILOT_REFERENCE_PACKAGE','pilot_run_id':binding['pilot_run_id'],'pilot_contract_id':binding['pilot_contract_id'],'acl14_binding_digest':binding['acl14_binding_digest'],'registered_at':closed_at,'fleet_status':'REGISTERED_REFERENCE_NON_EXECUTED','evidence_classification':'REFERENCE_DESIGN_NOT_PROSPECTIVE_EVIDENCE','ownership_contract_digest':ownership['ownership_contract_digest'],'retention_contract_digest':retention['retention_contract_digest'],'surveillance_contract_digest':surveillance['surveillance_contract_digest'],'migration_contract_digest':migration['migration_contract_digest'],'reopen_policy_digest':reopen['reopen_policy_digest'],'closure_policy_digest':closure_policy['closure_policy_digest'],'runtime_generation_allowed':False,'live_order_submission_allowed':False,'capital_activation_allowed':False},'fleet_registration_digest')
    return {'fleet':fleet,'ownership':ownership,'retention':retention,'surveillance':surveillance,'migration':migration,'reopen':reopen,'closure_policy':closure_policy}
