from __future__ import annotations
from pathlib import Path
from .canonical import with_digest
from .io import dump_json
def project(root:Path,run:dict,report:dict,executive:dict,support:dict,baselines:dict,catalog:dict,uncertainty:dict,handoff:dict)->dict:
    docs=root/'docs'; docs.mkdir(parents=True,exist_ok=True)
    summary=f"""---\ntitle: ACL-13 One-Hour Assessment Summary\nstatus: generated-reference\nversion: 1.0.0\ntags: [acl-os, acl-13, one-hour-assessment]\n---\n# ACL-13 One-Hour Assessment Summary\n\n- Run: `{run['assessment_run_id']}`\n- Report: `{report['report_id']}`\n- Decision: `{run['decision']}`\n- Context occurrences: **{support['context_occurrences']}**\n- Conditioned mean: **{baselines['conditioned_mean']:.4f}**\n- Random p90: **{baselines['random_p90']:.4f}**\n- Pilot design allowed: **{str(run['first_real_context_pilot_design_allowed']).lower()}**\n- Pilot execution allowed: **false**\n- Validation claim: **false**\n- Alpha claim: **false**\n- Live order authority: **false**\n- Capital authority: **false**\n\n## Interpretation\n\nThe fixture demonstrates the bounded one-hour triage mechanics. It is synthetic reference evidence and may only justify design of a first real non-capital pilot.\n\n## Next phase\n\n[[ACL_14_FIRST_REAL_CONTEXT_PILOT]] must replace the synthetic fixture with an approved real Context package and precommitted pilot contract.\n"""
    (docs/'ACL13_ONE_HOUR_ASSESSMENT_SUMMARY.md').write_text(summary,encoding='utf-8',newline='\n')
    (docs/'ACL13_EXECUTIVE_BRIEF.md').write_text('---\ntitle: ACL-13 Executive Brief\nstatus: generated-reference\nversion: 1.0.0\ntags: [acl-os, acl-13, executive]\n---\n# Executive Brief\n\n'+executive['answer_first']+'\n\n## Findings\n\n'+'\n'.join('- '+x for x in executive['key_findings'])+'\n',encoding='utf-8',newline='\n')
    (docs/'ACL13_SETUP_FAMILY_CATALOG.md').write_text('---\ntitle: ACL-13 Setup Family Catalog\nstatus: generated-reference\nversion: 1.0.0\ntags: [acl-os, acl-13, setup-families]\n---\n# Setup Family Catalog\n\n'+'\n'.join(f"- `{x['family_id']}` — support **{x['support']}**, mean **{x['mean_forward_delta']:.4f}**, hit rate **{x['hit_rate']:.2%}**" for x in catalog['families'])+'\n',encoding='utf-8',newline='\n')
    (docs/'ACL13_LIMITATIONS_AND_ESCALATION.md').write_text('---\ntitle: ACL-13 Limitations and Escalation\nstatus: generated-reference\nversion: 1.0.0\ntags: [acl-os, acl-13, limitations]\n---\n# Limitations and Escalation\n\n'+'\n'.join('- '+x for x in uncertainty['limitations'])+'\n\n## Evidence gaps\n\n'+'\n'.join(f"- `{g['gap_id']}` — **{g['status']}** — `{g['next_action']}`" for g in uncertainty['gaps'])+'\n',encoding='utf-8',newline='\n')
    m=with_digest({'schema_version':'1.0.0','documents':['docs/ACL13_ONE_HOUR_ASSESSMENT_SUMMARY.md','docs/ACL13_EXECUTIVE_BRIEF.md','docs/ACL13_SETUP_FAMILY_CATALOG.md','docs/ACL13_LIMITATIONS_AND_ESCALATION.md'],'handoff_digest':handoff['handoff_digest']},'projection_manifest_digest'); dump_json(docs/'obsidian_projection_manifest.json',m); return m
