from tools.repository_paths import find_repository_root
from pathlib import Path
BASE=find_repository_root(__file__)
REGISTRY_ROOT=BASE/'registry/acl_os/acl_13'
SCHEMA_ROOT=REGISTRY_ROOT/'schemas/v1'
POLICY_ROOT=REGISTRY_ROOT/'policies/v1'
HANDOFF_IN='ACL12_TO_ACL13'
HANDOFF_OUT='ACL13_TO_ACL14'
REQUIRED_UPSTREAM_ACTIONS={'VERIFY_SECURITY_READINESS_PACKAGE','BUILD_ONE_HOUR_ASSESSMENT_PRODUCT','ISSUE_NON_CAPITAL_ASSESSMENT_RESULT'}
FORBIDDEN_UPSTREAM_ACTIONS={'INVENT_PRODUCTION_SECURITY_EVIDENCE','AUTHORIZE_RUNTIME_ACTIVATION','AUTHORIZE_LIVE_ORDER','ACTIVATE_CAPITAL','ACCESS_PRODUCTION_KEYS'}
REQUIRED_ACTION='ACL13_BUILD_ONE_HOUR_ASSESSMENT'
CLAIM_CEILING='RESEARCH_TRIAGE_REFERENCE_ONLY'
SERVICE_VERSION='1.0.0'
ASSESSMENT_STATES={'INPUT_REJECTED','BOUNDED_TRIAGE_COMPLETE_PILOT_DESIGN_ELIGIBLE_NON_CAPITAL','BOUNDED_TRIAGE_COMPLETE_ESCALATION_REQUIRED','INSUFFICIENT_INPUT_FOR_TRIAGE'}
SECTION_IDS=['IDENTITY_AND_SCOPE','INPUT_COMPLETENESS','SECURITY_READINESS','FAST_DATA_SLICE','SUPPORT_DIAGNOSTICS','CONSTRAINED_BASELINES','SETUP_FAMILY_DISCOVERY','VALUE_DECOMPOSITION','UNCERTAINTY','FAILURE_SIGNATURES','LIMITATIONS','NEXT_ALLOWED_ACTIONS']
