from pathlib import Path

PACKAGE_ROOT=Path(__file__).resolve().parent
REPO_ROOT=Path(__file__).resolve().parents[4]
REGISTRY_ROOT=REPO_ROOT/"registry/acl_os/acl_05"
SCHEMA_ROOT=REGISTRY_ROOT/"schemas/v1"
POLICY_ROOT=REGISTRY_ROOT/"policies/v1"
CLAIM_CEILING="RESEARCH_BATCH_FREEZE_REFERENCE_ONLY"
PHASE_ID="ACL-05"
PHASE_VERSION="1.0.0"
FACTORY_VERSION="1.0.0"
HANDOFF_IN="ACL04_TO_ACL05"
HANDOFF_OUT="ACL05_TO_ACL06"
AUTHORITY_ACTION="ACL05_FREEZE_RESEARCH_BATCH"
REQUIRED_UPSTREAM_ACTIONS={"FREEZE_SETUP_UNIVERSE","FREEZE_SEARCH_EXPOSURE","CREATE_IMMUTABLE_RESEARCH_BATCH"}
FORBIDDEN_UPSTREAM_INFERENCES={"INFER_ALPHA","AUTHORIZE_EXECUTION","ACTIVATE_CAPITAL","MUTATE_SETUP_BEHAVIOR"}
ELIGIBLE_STATUS="ELIGIBLE_FOR_BATCH_DEFINITION"
DIAGNOSTIC_STATUS="DIAGNOSTIC_ONLY"
MAX_CANDIDATES=10000
MAX_OBJECTS=50000
MAX_TOTAL_BYTES=2*1024*1024*1024
