from enum import IntEnum
class ObjectiveMode(IntEnum): EXPECTANCY=0; CONSERVATIVE=1; STABILITY_WEIGHTED=2; TAIL_AWARE=3
class FidelityPresetKind(IntEnum): FAST_SCREEN=0; BAR_VALIDATION=1; EVERY_TICK=2; REAL_TICKS=3
class PassStatus(IntEnum): VALID=0; REJECTED_MIN_SAMPLE=1; REJECTED_EXPECTANCY=2; REJECTED_FILL_RATE=3; REJECTED_RECONCILIATION=4; REJECTED_NONFINITE=5
class DifferentialStatus(IntEnum): MATCH=0; WITHIN_TOLERANCE=1; MISMATCH=2; MISSING_SIDE=3
