from __future__ import annotations
from .canonical import digest_object

CASE_TYPES=[
 'POSITIVE','NEGATIVE','NO_TRADE','INVALIDATION','EXPIRY','RESTART',
 'HISTORY_EXPANSION','MISSING_BAR','DST_TRANSITION','SESSION_BOUNDARY',
 'TIMEFRAME_CHANGE','SYMBOL_CHANGE','MULTI_INSTANCE','DUPLICATE_TICK',
 'CURRENT_BAR_INTRABAR','CLOSED_BAR_CONFIRMATION','DRAWING_LIFECYCLE',
 'DRY_EXECUTION_REQUEST'
]
EVENT_TYPES=[
 'CASE_STARTED','INPUT_ACCEPTED','DATA_AVAILABLE','BAR_OBSERVED','STATE_EVALUATED',
 'CONTEXT_EMITTED','SETUP_EMITTED','NO_TRADE_EMITTED','INVALIDATION_EMITTED',
 'EXPIRY_EMITTED','DRAWING_INTENT_EMITTED','DRY_REQUEST_EMITTED',
 'ERROR_RECORDED','CASE_COMPLETED'
]
PACKET_STATUSES=[
 'EXCLUDED_PROTECTED_PLATFORM','BLOCKED_SECURITY_REVIEW','BLOCKED_OWNER_APPROVAL',
 'BLOCKED_IDENTITY_AMBIGUITY','READY_FOR_INSTRUMENTATION','LEGACY_TRACE_CAPTURED',
 'REPLAY_STABLE'
]
TRACE_EVIDENCE_STATUSES=['REFERENCE_FIXTURE_ONLY','LEGACY_OBSERVED','OWNER_REVIEWED','UNKNOWN']
KNOWN_TIME_STATUSES=['PASS','FAIL','UNKNOWN','NOT_APPLICABLE']
DEFECT_STATUSES=['OBSERVED_NOT_ADJUDICATED','INTENDED_CORRECTION_APPROVED','REJECTED_AS_NON_DEFECT','UNKNOWN']
BAR_STATUSES=['CURRENT_OPEN','CLOSED','MISSING','NOT_APPLICABLE']
ENVIRONMENT_KINDS=['REFERENCE_SYNTHETIC','PYTHON_LEGACY','MQL5_TESTER','MQL5_CHART','UNKNOWN']
AUTHORITY_ACTION='LCM04_BUILD_CHARACTERIZATION_FOUNDATION'

def registry(registry_id,key,values,extra=None):
    obj={'schema_version':'1.0.0','phase_id':'LCM-04','registry_id':registry_id,'closed':True,key:values}
    obj.update(extra or {});obj['registry_digest']=digest_object(obj,'registry_digest');return obj
