#ifndef __SF03_MARKET_ENUMS_MQH__
#define __SF03_MARKET_ENUMS_MQH__
enum ENUM_SF03_DATA_QUALITY
{
   SF03_QUALITY_UNKNOWN=0,
   SF03_QUALITY_VALID=1,
   SF03_QUALITY_STALE=2,
   SF03_QUALITY_MISSING=3,
   SF03_QUALITY_GAPPED=4,
   SF03_QUALITY_DESYNCHRONIZED=5,
   SF03_QUALITY_INVALID=6
};
enum ENUM_SF03_CLOCK_MODE
{
   SF03_CLOCK_GMT_NATIVE=0,
   SF03_CLOCK_SERVER_FIXED_OFFSET=1,
   SF03_CLOCK_SERVER_INFERRED_OFFSET=2,
   SF03_CLOCK_FIXTURE=3
};
enum ENUM_SF03_TIMEZONE_KIND
{
   SF03_TZ_UTC=0,
   SF03_TZ_BROKER=1,
   SF03_TZ_NEW_YORK=2,
   SF03_TZ_FIXED_OFFSET=3
};
enum ENUM_SF03_MISSING_BAR_POLICY
{
   SF03_MISSING_FAIL_CLOSED=0,
   SF03_MISSING_MARK_GAPPED=1,
   SF03_MISSING_FORWARD_FILL_CONTEXT_ONLY=2,
   SF03_MISSING_IGNORE_WITH_AUDIT=3
};
enum ENUM_SF03_SYNC_STATUS
{
   SF03_SYNC_UNKNOWN=0,
   SF03_SYNC_READY=1,
   SF03_SYNC_WAITING=2,
   SF03_SYNC_STALE=3,
   SF03_SYNC_GAPPED=4,
   SF03_SYNC_FAILED=5
};
enum ENUM_SF03_BAR_UPDATE_RESULT
{
   SF03_BAR_REJECTED=0,
   SF03_BAR_INSERTED=1,
   SF03_BAR_REPLACED=2,
   SF03_BAR_DUPLICATE=3,
   SF03_BAR_GAP_INSERTED=4
};
string SF03_DataQualityToString(const ENUM_SF03_DATA_QUALITY value)
{
   if(value==SF03_QUALITY_VALID) return "VALID";
   if(value==SF03_QUALITY_STALE) return "STALE";
   if(value==SF03_QUALITY_MISSING) return "MISSING";
   if(value==SF03_QUALITY_GAPPED) return "GAPPED";
   if(value==SF03_QUALITY_DESYNCHRONIZED) return "DESYNCHRONIZED";
   if(value==SF03_QUALITY_INVALID) return "INVALID";
   return "UNKNOWN";
}
#endif
