from __future__ import annotations
import json, os, tempfile
from pathlib import Path
from typing import Any
import yaml
from .errors import SecurityBoundaryError

def load_json(path:Path)->Any: return json.loads(path.read_text(encoding="utf-8"))
def load_yaml(path:Path)->Any: return yaml.safe_load(path.read_text(encoding="utf-8"))
def ensure_contained(root:Path,path:Path)->Path:
    root=root.resolve(); path=path.resolve()
    if path!=root and root not in path.parents: raise SecurityBoundaryError(f"path escapes root: {path}")
    if path.is_symlink(): raise SecurityBoundaryError(f"symlink is not allowed: {path}")
    return path
def atomic_write(path:Path,data:bytes)->None:
    path.parent.mkdir(parents=True,exist_ok=True)
    fd,tmp=tempfile.mkstemp(prefix=f".{path.name}.",dir=path.parent)
    try:
        with os.fdopen(fd,"wb") as f: f.write(data); f.flush(); os.fsync(f.fileno())
        os.replace(tmp,path)
    finally:
        if os.path.exists(tmp): os.unlink(tmp)
def dump_json(path:Path,obj:Any)->None: atomic_write(path,json.dumps(obj,indent=2,sort_keys=True,ensure_ascii=False).encode("utf-8")+b"\n")
def dump_yaml(path:Path,obj:Any)->None: atomic_write(path,yaml.safe_dump(obj,sort_keys=False,allow_unicode=True).encode("utf-8"))
def generated_header(source_digest:str,compiler_version:str)->str:
    return f"# GENERATED BY ACL-03; DO NOT EDIT. source={source_digest} compiler={compiler_version}\n"
