#ifndef ALPHA_LAB_LCM11A_VISUAL_TYPES_MQH
#define ALPHA_LAB_LCM11A_VISUAL_TYPES_MQH
#define LCM11A_PHASE_VERSION "1.0.0"
#define LCM11A_CLAIM_CEILING "LCM_11A_REFERENCE_ONLY"
enum ENUM_LCM11A_ANCHOR_KIND{LCM11A_ANCHOR_UNKNOWN=0,LCM11A_ANCHOR_TIME_PRICE=1,LCM11A_ANCHOR_TIME_ONLY=2,LCM11A_ANCHOR_PRICE_ONLY=3,LCM11A_ANCHOR_PIXEL_CORNER=4,LCM11A_ANCHOR_SERIES_INDEX=5};
enum ENUM_LCM11A_LIFECYCLE_STATE{LCM11A_VIS_UNINITIALIZED=0,LCM11A_VIS_INITIALIZED=1,LCM11A_VIS_BACKFILLED=2,LCM11A_VIS_INCREMENTAL=3,LCM11A_VIS_RECONCILED=4,LCM11A_VIS_CLEANED=5};
struct SLCM11A_VisualIdentity{string owner;string subsystem;string instance_id;long chart_id;string symbol;ENUM_TIMEFRAMES timeframe;string event_id;string role;};
struct SLCM11A_AnchorContract{ENUM_LCM11A_ANCHOR_KIND kind;datetime time1;double price1;datetime time2;double price2;bool availability_confirmed;};
#endif
