#ifndef __SF06_REFERENCE_SWEEP_PLUGIN_MQH__
#define __SF06_REFERENCE_SWEEP_PLUGIN_MQH__
#include "../../Plugins/SF04_AnatomyPluginBase.mqh"
#include "../SF06_GoldenLedger.mqh"
class CSF06ReferenceSweepPlugin:public CSF04AnatomyPluginBase
{
private:string m_symbol;int m_tf,m_lookback;long m_last_processed_close;double m_min_penetration_points;bool m_require_close_back_inside;
bool EvaluateLatest(string &error)
{
   SF01_BarRecord bars[];int n=m_market.CopyRecentClosedBars(m_symbol,m_tf,3,bars);if(n<3){error="insufficient closed bars";return false;}
   SF01_BarRecord prior=bars[n-2];SF01_BarRecord current=bars[n-1];if(current.close_time.utc_epoch_milliseconds<=m_last_processed_close){error="";return true;}
   m_last_processed_close=current.close_time.utc_epoch_milliseconds;
   SF03_SymbolSpecSnapshot spec;if(!m_specs.GetSnapshot(m_symbol,spec,error))return false;double threshold=MathMax(spec.point*m_min_penetration_points,spec.tick_size);
   bool high_sweep=current.high_price>prior.high_price+threshold*0.5 && (!m_require_close_back_inside||current.close_price<prior.high_price);
   bool low_sweep=current.low_price<prior.low_price-threshold*0.5 && (!m_require_close_back_inside||current.close_price>prior.low_price);
   if(high_sweep==low_sweep){error="";return true;}
   SF06_AnatomyObservation obs;obs.schema="alpha_lab.strategy_factory/anatomy_observation@1.0.0";obs.observation_id="";obs.plugin_id=m_descriptor.plugin_id;obs.plugin_version=m_descriptor.version;obs.symbol=m_symbol;obs.timeframe_seconds=m_tf;obs.kind=high_sweep?SF06_OBS_REFERENCE_SWEEP_HIGH:SF06_OBS_REFERENCE_SWEEP_LOW;obs.occurred_at=current.close_time;obs.known_at=current.close_time;obs.reference_price=high_sweep?prior.high_price:prior.low_price;obs.extreme_price=high_sweep?current.high_price:current.low_price;obs.close_price=current.close_price;obs.source_bar_id=SF01_BarId(current);obs.source_hash=SF01_StableId("src",SF01_BarCanonicalIdentity(prior)+"|"+SF01_BarCanonicalIdentity(current));obs.market_event_cluster_id=SF01_StableId("cluster",m_symbol+"|"+IntegerToString(m_tf)+"|"+LongToString(current.close_time.utc_epoch_milliseconds));obs.observation_id=SF06_DeriveObservationId(obs);if(!SF06_ValidateObservation(obs,error))return false;
   SF06_EventBuildInput in;in.strategy_id=m_runtime_config.strategy_id;in.strategy_version=m_runtime_config.strategy_version;in.producer_id=m_descriptor.plugin_id;in.producer_version=m_descriptor.version;in.symbol=m_symbol;in.reference_symbol=m_symbol;in.direction=high_sweep?SF01_DIRECTION_SHORT:SF01_DIRECTION_LONG;in.timeframe_seconds=m_tf;in.event_time=current.close_time;in.known_time=current.close_time;in.confirmation_time=current.close_time;in.reference_price=obs.reference_price;in.invalidation_price=obs.extreme_price;in.session_id="shared_session_unassigned";in.parent_event_id="none";in.market_event_cluster_id=obs.market_event_cluster_id;in.source_hash=obs.source_hash;in.anatomy_state="confirmed";SF01_AnatomyEvent event;if(!SF06_BuildCanonicalEvent(in,event,error))return false;return EmitEvent(event,error);
}
protected:bool OnPluginInitialize(string &e){m_last_processed_close=0;e="";return true;}bool OnPluginStart(string &e){e="";return true;}void OnPluginStop(void){}void OnPluginShutdown(void){}void OnPluginTick(const MqlTick &tick){}void OnPluginTimer(const long now){string e="";if(!m_market.RefreshSeries(m_symbol,m_tf,m_lookback,e))return;EvaluateLatest(e);}
public:CSF06ReferenceSweepPlugin(const string symbol,const int tf,const int lookback,const double min_points,const bool require_inside){m_symbol=symbol;m_tf=tf;m_lookback=lookback;m_min_penetration_points=min_points;m_require_close_back_inside=require_inside;m_last_processed_close=0;m_descriptor=SF04_DefaultAnatomyDescriptor();m_descriptor.plugin_id="sf06.reference.sweep_rejection";m_descriptor.display_name="SF06 Reference Sweep Rejection";m_descriptor.version="1.0.0";m_descriptor.provider_id="alpha_lab.strategy_factory";m_descriptor.provider_version="1.0.0";m_descriptor.capability_mask=SF04_CAP_CLOSED_BAR_INPUT|SF04_CAP_TIMER_INPUT|SF04_CAP_REPLAY_SAFE|SF04_CAP_DETERMINISTIC|SF04_CAP_STATEFUL|SF04_CAP_EMITS_CLUSTER_ID|SF04_CAP_REQUIRES_SYMBOL_SPEC;m_descriptor.update_scope_mask=SF04_UPDATE_NEW_BAR|SF04_UPDATE_TIMER|SF04_UPDATE_REPLAY;m_descriptor.event_queue_capacity=256;m_descriptor.queue_overflow_policy=SF04_QUEUE_FAIL_PLUGIN;m_descriptor.deterministic=true;m_descriptor.replay_safe=true;m_descriptor.fast_path_safe=false;m_descriptor.stateful=true;m_descriptor.description="Central-engine reference anatomy proving closed-bar event production without legacy strategy integration.";m_descriptor.configuration_schema_hash=SF01_StableId("cfg",symbol+"|"+IntegerToString(tf)+"|"+IntegerToString(lookback)+"|"+SF01_CanonicalDouble(min_points)+"|"+SF01_CanonicalBool(require_inside));string x="";SF04_DataRequirement bars;bars.requirement_id="reference_closed_bars";bars.kind=SF04_REQUIREMENT_CLOSED_BARS;bars.strength=SF04_REQUIREMENT_REQUIRED;bars.symbol=symbol;bars.timeframe_seconds=tf;bars.lookback_bars=lookback;bars.max_staleness_msc=(long)tf*3000;bars.max_close_skew_msc=0;bars.synchronization_group_id="reference_primary";bars.purpose="reference sweep detection";AddRequirement(bars,x);SF04_DataRequirement spec;spec.requirement_id="reference_symbol_spec";spec.kind=SF04_REQUIREMENT_SYMBOL_SPEC;spec.strength=SF04_REQUIREMENT_REQUIRED;spec.symbol=symbol;spec.timeframe_seconds=0;spec.lookback_bars=0;spec.max_staleness_msc=0;spec.max_close_skew_msc=0;spec.synchronization_group_id="";spec.purpose="price geometry";AddRequirement(spec,x);}
};
#endif
