from enum import Enum
class ProductKind(str, Enum):
    INDICATOR="INDICATOR"; DIAGNOSTIC_EA="DIAGNOSTIC_EA"; PYTHON_REFERENCE="PYTHON_REFERENCE"
class TraceEventType(str, Enum):
    CONFIG="CONFIG"; TIME="TIME"; DATA="DATA"; WINDOW="WINDOW"; REFERENCE="REFERENCE"; HUNT="HUNT"; CANDIDATE="CANDIDATE"; CONFIRMATION="CONFIRMATION"; SIGNAL="SIGNAL"; WW_CONTEXT="WW_CONTEXT"; DIRECTION_GATE="DIRECTION_GATE"; LEDGER="LEDGER"; QUOTA="QUOTA"; BUFFER="BUFFER"; VISUAL="VISUAL"; ALERT="ALERT"; EXPORT="EXPORT"; HEALTH="HEALTH"; CHECKPOINT="CHECKPOINT"
class DifferentialStatus(str, Enum): PASS="PASS"; FAIL="FAIL"; BLOCKED="BLOCKED"
class MismatchKind(str, Enum):
    PRODUCT_MISSING="PRODUCT_MISSING"; MANIFEST_MISMATCH="MANIFEST_MISMATCH"; CONFIG_MISMATCH="CONFIG_MISMATCH"; SOURCE_REVISION_MISMATCH="SOURCE_REVISION_MISMATCH"; MODULE_VERSION_MISMATCH="MODULE_VERSION_MISMATCH"; EVENT_MISSING_LEFT="EVENT_MISSING_LEFT"; EVENT_MISSING_RIGHT="EVENT_MISSING_RIGHT"; SEMANTIC_ID_MISMATCH="SEMANTIC_ID_MISMATCH"; PAYLOAD_MISMATCH="PAYLOAD_MISMATCH"; STATE_MISMATCH="STATE_MISMATCH"; SEQUENCE_MISMATCH="SEQUENCE_MISMATCH"; CHAIN_MISMATCH="CHAIN_MISMATCH"; BUFFER_MISMATCH="BUFFER_MISMATCH"; VISUAL_INVENTORY_MISMATCH="VISUAL_INVENTORY_MISMATCH"; DUPLICATE_COLLISION="DUPLICATE_COLLISION"
class TraceDisposition(str, Enum): APPLIED="APPLIED"; DUPLICATE_IGNORED="DUPLICATE_IGNORED"
class HealthState(str, Enum): READY="READY"; DEGRADED="DEGRADED"; BLOCKED="BLOCKED"
class ScenarioKind(str, Enum): BASELINE="BASELINE"; DUPLICATE_DELIVERY="DUPLICATE_DELIVERY"; RECONNECT="RECONNECT"; RESTART="RESTART"; SYMBOL_STAGGER="SYMBOL_STAGGER"; LATE_REVISION="LATE_REVISION"; TIMEFRAME_SWITCH="TIMEFRAME_SWITCH"; TRACE_TRUNCATION="TRACE_TRUNCATION"
class ExportFormat(str, Enum): JSONL="JSONL"; CSV="CSV"; BOTH="BOTH"
class CheckpointDisposition(str, Enum): ACCEPTED="ACCEPTED"; REJECT_VERSION="REJECT_VERSION"; REJECT_CONFIG="REJECT_CONFIG"; REJECT_PRODUCT="REJECT_PRODUCT"; REJECT_HASH="REJECT_HASH"; REBUILD_REQUIRED="REBUILD_REQUIRED"
class GateStatus(str, Enum): PASS="PASS"; FAIL="FAIL"; PENDING="PENDING"; BLOCKED="BLOCKED"
