from .constants import PHASE_ID,PHASE_VERSION,TRACE_CONTRACT_VERSION
PUBLIC_CONTRACTS=(
 'ProductManifest','TraceEvent','TraceInventory','TraceRun','DifferentialMismatch','PairwiseDifferentialReport','CrossProductReport','TraceCheckpoint','StressScenario','StressResult','ExportReceipt','HealthSnapshot','DiagnosticAcceptance'
)
REASON_CODES=(
 'FP_DIAG_READY','FP_DIAG_BLOCKED','FP_DIAG_MANIFEST_MISMATCH','FP_DIAG_CONFIG_MISMATCH','FP_DIAG_SOURCE_REVISION_MISMATCH','FP_DIAG_MODULE_VERSION_MISMATCH','FP_DIAG_EVENT_MISSING_LEFT','FP_DIAG_EVENT_MISSING_RIGHT','FP_DIAG_SEMANTIC_ID_MISMATCH','FP_DIAG_PAYLOAD_MISMATCH','FP_DIAG_STATE_MISMATCH','FP_DIAG_SEQUENCE_MISMATCH','FP_DIAG_BUFFER_MISMATCH','FP_DIAG_VISUAL_INVENTORY_MISMATCH','FP_DIAG_DUPLICATE_COLLISION','FP_DIAG_CHECKPOINT_ACCEPTED','FP_DIAG_CHECKPOINT_VERSION_MISMATCH','FP_DIAG_CHECKPOINT_CONFIG_MISMATCH','FP_DIAG_CHECKPOINT_PRODUCT_MISMATCH','FP_DIAG_CHECKPOINT_HASH_MISMATCH','FP_DIAG_HEALTH_READY','FP_DIAG_HEALTH_DEGRADED','FP_DIAG_HEALTH_BLOCKED','FP_DIAG_METAEDITOR_PENDING','FP_DIAG_RUNTIME_DIFFERENTIAL_PENDING','FP_DIAG_RUNTIME_AUTHORITY_NONE'
)
def registry(): return {'phase_id':PHASE_ID,'phase_version':PHASE_VERSION,'trace_contract_version':TRACE_CONTRACT_VERSION,'public_contracts':PUBLIC_CONTRACTS,'reason_codes':REASON_CODES,'runtime_authority':'NONE'}
