PHASE_ID = "FP-I15"
PHASE_VERSION = "1.0.0"
PLAN_CONTRACT_VERSION = "FP-I15-PLAN-1"
PAPER_LEDGER_VERSION = "FP-I15-PAPER-LEDGER-1"
CHECKPOINT_VERSION = "FP-I15-CHECKPOINT-1"
ZERO_HASH = "0" * 64
MAX_REASON_CODES = 32
RISK_TOLERANCE = 1e-8
MAX_LEDGER_EVENTS = 2_000_000
LIVE_QUOTA_POLICY = "UNSET"
LIVE_EXECUTION_ENABLED = False
PAPER_RUNTIME_AUTHORITY = "SYNTHETIC_EXECUTION_ONLY"
FORBIDDEN_LIVE_TOKENS = (
    "OrderSend(", "CTrade ", "PositionOpen(", "PositionClose(",
    ".Buy(", ".Sell(", "WebRequest("
)
