#ifndef ALPHA_LAB_SAED_V4_HYPERGRAPH_ENUMS_MQH
#define ALPHA_LAB_SAED_V4_HYPERGRAPH_ENUMS_MQH

enum ENUM_SAED_HYPERGRAPH_NODE_KIND
  {
   SAED_HNODE_CONTEXT=0,
   SAED_HNODE_VIEW=1,
   SAED_HNODE_FEATURE=2,
   SAED_HNODE_SOURCE_ARTIFACT=3,
   SAED_HNODE_TEMPORAL_ANCHOR=4,
   SAED_HNODE_EXTERNAL_CONTEXT_REFERENCE=5,
   SAED_HNODE_TREATMENT_DESCRIPTOR=6
  };

enum ENUM_SAED_HYPERGRAPH_RELATION_KIND
  {
   SAED_HREL_CONTEXT_COMPOSITION=0,
   SAED_HREL_VIEW_COMPOSITION=1,
   SAED_HREL_SOURCE_PROVENANCE=2,
   SAED_HREL_TEMPORAL_COHORT=3,
   SAED_HREL_CROSS_VIEW_ALIGNMENT=4,
   SAED_HREL_SEMANTIC_FAMILY=5,
   SAED_HREL_CONTEXT_ANCESTRY=6,
   SAED_HREL_TREATMENT_DESCRIPTOR_BINDING=7
  };

enum ENUM_SAED_HYPERGRAPH_STATUS
  {
   SAED_HGRAPH_COMPLETE=0,
   SAED_HGRAPH_DEGRADED=1,
   SAED_HGRAPH_UNSUPPORTED=2,
   SAED_HGRAPH_QUARANTINED=3
  };

#endif
