from enum import Enum,IntEnum
class VisualMode(str,Enum): STANDARD='STANDARD'; AUDIT='AUDIT'; MINIMAL='MINIMAL'
class ObjectKind(str,Enum):
 SESSION_BOX='SESSION_BOX'; WEEK_BOX='WEEK_BOX'; REFERENCE_LINE='REFERENCE_LINE'; REFERENCE_LABEL='REFERENCE_LABEL'; HUNT_MARKER='HUNT_MARKER'; ROLE_BADGE='ROLE_BADGE'; CANDIDATE_SIGNAL='CANDIDATE_SIGNAL'; CONFIRMED_SIGNAL='CONFIRMED_SIGNAL'; INVALIDATION_MARKER='INVALIDATION_MARKER'; WW_CONTEXT='WW_CONTEXT'; SUPPRESSION_OVERLAY='SUPPRESSION_OVERLAY'; QUOTA_WINNER_BADGE='QUOTA_WINNER_BADGE'; HEALTH_BADGE='HEALTH_BADGE'
class Layer(IntEnum): BACKGROUND=10; SESSIONS=20; REFERENCES=30; HUNTS=40; SIGNALS=50; SUPPRESSION=60; BADGES=70; HEALTH=80
class Mutation(str,Enum): CREATE='CREATE'; UPDATE='UPDATE'; DELETE='DELETE'; NOOP='NOOP'
class VisualState(str,Enum): VISIBLE='VISIBLE'; HIDDEN='HIDDEN'; STALE='STALE'; DEGRADED='DEGRADED'
class SignalDisposition(str,Enum): OBSERVED='OBSERVED'; ELIGIBLE_CONTENDER='ELIGIBLE_CONTENDER'; QUOTA_WINNER='QUOTA_WINNER'; SUPPRESSED_BY_QUOTA='SUPPRESSED_BY_QUOTA'; SUPPRESSED_BY_WW='SUPPRESSED_BY_WW'; BLOCKED='BLOCKED'; NOT_APPLICABLE='NOT_APPLICABLE'
class SemanticState(str,Enum): ACTIVE='ACTIVE'; COMPLETE='COMPLETE'; FRESH='FRESH'; HUNTER_SEEN='HUNTER_SEEN'; CONSUMED='CONSUMED'; CANDIDATE='CANDIDATE'; CONFIRMED='CONFIRMED'; INVALIDATED='INVALIDATED'; NEUTRALIZED='NEUTRALIZED'; EXPIRED='EXPIRED'
class AnchorType(str,Enum): TIME_PRICE='TIME_PRICE'; TIME_RANGE='TIME_RANGE'; PRICE_LEVEL='PRICE_LEVEL'; SCREEN_CORNER='SCREEN_CORNER'
