from enum import Enum
class ExecutionRole(str,Enum): ENTRY='entry'; STOP_EXIT='stop_exit'; TARGET_EXIT='target_exit'; TRAIL_EXIT='trail_exit'; MANAGEMENT_EXIT='management_exit'; MARK='mark'; LIQUIDATION='liquidation'
class OrderKind(str,Enum): MARKET='market'; LIMIT='limit'; STOP='stop'; STOP_LIMIT='stop_limit'; CLOSE='close'
class CommissionBasis(str,Enum): PER_LOT_PER_SIDE='per_lot_per_side'; PER_LOT_ROUND_TURN='per_lot_round_turn'; PER_NOTIONAL_BPS='per_notional_bps'; FIXED_PER_TRANSACTION='fixed_per_transaction'; HYBRID='hybrid'
class SpreadSource(str,Enum): OBSERVED='observed'; FIXED_POINTS='fixed_points'; PERCENTILE_POINTS='percentile_points'; MAX_OBSERVED_AND_FLOOR='max_observed_and_floor'
class SlippageModelKind(str,Enum): FIXED_POINTS='fixed_points'; ORDER_SIDE_POINTS='order_side_points'; VOLATILITY_SCALED='volatility_scaled'; EMPIRICAL_PERCENTILE='empirical_percentile'
class FinancingBasis(str,Enum): NONE='none'; PER_LOT_PER_DAY='per_lot_per_day'; NOTIONAL_ANNUAL_RATE='notional_annual_rate'
class TradeStatus(str,Enum): ENABLED='enabled'; CLOSE_ONLY='close_only'; DISABLED='disabled'
class MarginMode(str,Enum): FIXED_PER_LOT='fixed_per_lot'; NOTIONAL_RATE='notional_rate'; LEVERAGE='leverage'
class ConstraintDecision(str,Enum): ACCEPT='accept'; ADJUST='adjust'; REJECT='reject'
class PriceRoundingRole(str,Enum): ENTRY='entry'; PROTECTIVE_STOP='protective_stop'; PROFIT_TARGET='profit_target'; TRAILING_STOP='trailing_stop'
class CapitalPolicyKind(str,Enum): FIXED_CASH='fixed_cash'; EQUITY_FRACTION='equity_fraction'; BALANCE_FRACTION='balance_fraction'; RISK_TIER='risk_tier'; VOLATILITY_TARGET='volatility_target'; DRAWDOWN_SCALED='drawdown_scaled'; CONFIDENCE_SCALED='confidence_scaled'; CAPPED_KELLY='capped_kelly'; PORTFOLIO_BUDGET='portfolio_budget'; COMPOSITE='composite'
class ReservationState(str,Enum): RESERVED='reserved'; ADJUSTED='adjusted'; PARTIALLY_CONSUMED='partially_consumed'; CONSUMED='consumed'; RELEASED='released'; CANCELLED='cancelled'; RECONCILED='reconciled'
class LedgerAction(str,Enum): RESERVE='reserve'; ADJUST='adjust'; CONSUME='consume'; RELEASE='release'; CANCEL='cancel'; RECONCILE='reconcile'
class StressKind(str,Enum): SPREAD_MULTIPLIER='spread_multiplier'; COMMISSION_MULTIPLIER='commission_multiplier'; SLIPPAGE_POINTS='slippage_points'; GAP_POINTS='gap_points'; CONVERSION_SHOCK='conversion_shock'; STALE_QUOTE='stale_quote'; STALE_SPEC='stale_spec'; TICK_VALUE_SHOCK='tick_value_shock'; MARGIN_SHOCK='margin_shock'; VOLUME_REJECT='volume_reject'; ASYMMETRY='asymmetry'
