#ifndef __UCEI03_ENUMS_MQH__
#define __UCEI03_ENUMS_MQH__
enum ENUM_UCEI03_ATOM_KIND{UCEI03_ENTRY=0,UCEI03_STOP=1,UCEI03_TARGET=2,UCEI03_TRAILING=3,UCEI03_MANAGEMENT=4,UCEI03_SIZING=5};
enum ENUM_UCEI03_SIDE{UCEI03_LONG=1,UCEI03_SHORT=-1};
enum ENUM_UCEI03_ORDER_TYPE{UCEI03_ORDER_NONE=0,UCEI03_ORDER_MARKET=1,UCEI03_ORDER_LIMIT=2,UCEI03_ORDER_STOP=3,UCEI03_ORDER_STOP_LIMIT=4};
enum ENUM_UCEI03_PRICE_ROLE{UCEI03_PRICE_ENTRY=0,UCEI03_PRICE_STOP=1,UCEI03_PRICE_TARGET=2,UCEI03_PRICE_TRAIL=3};
enum ENUM_UCEI03_PARAM_TYPE{UCEI03_PARAM_DECIMAL=0,UCEI03_PARAM_INTEGER=1,UCEI03_PARAM_BOOLEAN=2,UCEI03_PARAM_STRING=3,UCEI03_PARAM_ENUM=4};
string UCEI03_KindName(const ENUM_UCEI03_ATOM_KIND v){switch(v){case UCEI03_ENTRY:return "entry";case UCEI03_STOP:return "stop";case UCEI03_TARGET:return "target";case UCEI03_TRAILING:return "trailing";case UCEI03_MANAGEMENT:return "management";case UCEI03_SIZING:return "sizing";}return "unknown";}
string UCEI03_SideName(const ENUM_UCEI03_SIDE v){return v==UCEI03_LONG?"long":"short";}
#endif
