from tools.repository_paths import find_repository_root
from pathlib import Path
BASE = find_repository_root(__file__)
REGISTRY_ROOT = BASE/'registry/acl_os/acl_10'
SCHEMA_ROOT = REGISTRY_ROOT/'schemas/v1'
POLICY_ROOT = REGISTRY_ROOT/'policies/v1'
HANDOFF_IN = 'ACL09_TO_ACL10'
HANDOFF_OUT = 'ACL10_TO_ACL11'
REQUIRED_UPSTREAM_ACTIONS = {'VERIFY_MEMORY_AND_PLANNER_PACKAGE','EVALUATE_PROMOTION_PREREQUISITES','ISSUE_NON_PROMOTIONAL_STATE_DECISION'}
FORBIDDEN_UPSTREAM_ACTIONS = {'EXECUTE_RESEARCH_PLAN','MUTATE_MEMORY_HISTORY','PROMOTE_WITHOUT_VALIDATED_EVIDENCE','AUTHORIZE_EXECUTION','ACTIVATE_CAPITAL'}
REQUIRED_ACTION = 'ACL10_EVALUATE_PROMOTION_STATE'
CLAIM_CEILING = 'PROMOTION_STATE_DECISION_REFERENCE_ONLY'
SERVICE_VERSION = '1.0.0'
PREREQUISITE_STATUSES = {'SATISFIED','UNSATISFIED','UNKNOWN','NOT_APPLICABLE'}
DECISION_STATUSES = {'RESEARCH_HOLD','VALIDATION_FAILED_ARCHIVED','BASELINE_REFERENCE_ONLY','DIAGNOSTIC_QUARANTINED','PROMOTION_REVIEW_ELIGIBLE'}
TRANSITION_STATUSES = {'ALLOWED_NOT_EXECUTED','DENIED','NOT_APPLICABLE'}
