from enum import IntEnum
class ObservationKind(IntEnum): TICK=1; CLOSED_BAR=2
class DataFidelity(IntEnum): UNKNOWN=0; BAR_APPROXIMATION=1; SYNTHETIC_TICK=2; REAL_TICK=3
class RuntimeState(IntEnum): EMPTY=0; REGISTERED=1; WAITING_ACTIVATION=2; PENDING_FILL=3; FILLED=4; PARTIAL=5; CLOSED=6; EXPIRED=7; INVALIDATED=8; AMBIGUOUS=9; REJECTED=10
class ExitReason(IntEnum): NONE=0; TARGET=1; STOP=2; TIME=3; ENTRY_EXPIRED=4; INVALIDATED_BEFORE_FILL=5; AMBIGUOUS_BAR=6; DATA_FAILURE=7; MANUAL_TEST=8; PARTIAL_TARGET_THEN_STOP=9; PARTIAL_TARGET_THEN_TIME=10
class AmbiguityPolicy(IntEnum): STOP_FIRST=1; TARGET_FIRST=2; EXCLUDE=3; REQUIRE_LOWER_FIDELITY=4
class GapPolicy(IntEnum): AT_TRIGGER=1; AT_OBSERVED_OPEN_CONSERVATIVE=2; REJECT=3
class MarketFillPolicy(IntEnum): FIRST_OBSERVATION=1; REQUESTED_PRICE=2; CONSERVATIVE_SIDE=3
class PathEventKind(IntEnum): REGISTERED=1; ACTIVATED=2; FILLED=3; FAVORABLE_EXTREME=4; ADVERSE_EXTREME=5; TARGET_TOUCH=6; STOP_TOUCH=7; PARTIAL_EXIT=8; TIME_EXIT=9; EXPIRED=10; AMBIGUOUS=11; CLOSED=12
