from __future__ import annotations

SCHEMA_VERSION = "1.0.0"
PHASE_ID = "LCM-13A"
MASTER_PHASE = "LCM-13"
CLAIM_CEILING = "LCM_13A_REFERENCE_ONLY"
OWNER = "ALPHA_LAB_MIGRATION_OWNER"
REVIEWER = "INDEPENDENT_MIGRATION_REVIEWER"
PRODUCER = "src.engine.tooling.strategy_factory.lcm.lcm_13a.service:LCM13ADualRunService"
GENERATED_TIME_SEMANTICS = "DETERMINISTIC_FROM_BOUND_INPUTS_NO_WALL_CLOCK_IDENTITY"
SCENARIO_KINDS = (
    "HISTORICAL_REPLAY",
    "CONTROLLED_LIVE_LIKE",
    "RESTART_REPLAY",
)
HARD_DIMENSIONS = (
    "INPUT_DIGEST",
    "KNOWN_TIME",
    "STATE",
    "EVENT",
    "DECISION",
    "REQUEST",
    "VISUAL_ANCHOR",
    "REASON_CODE",
    "RESOLVED_LOCATOR",
    "SIDE_EFFECT_AUTHORITY",
)
NO_TOLERANCE_DIMENSIONS = (
    "INPUT_DIGEST",
    "KNOWN_TIME",
    "STATE",
    "EVENT",
    "DECISION",
    "REQUEST",
    "REASON_CODE",
    "RESOLVED_LOCATOR",
    "SIDE_EFFECT_AUTHORITY",
)
