from __future__ import annotations
import shutil
from pathlib import Path
from typing import Any
from .artifact_manifest import build_manifest
from .canonical import digest_object,stable_id
from .constants import CLAIM_CEILING,FREEZE_ROOT,MIGRATION_ID,SCHEMA_VERSION,UPSTREAM_HANDOFF_DIGEST
from .handoff import build_handoff
from .io import dump_json,dump_jsonl,load_json,load_jsonl
from .parity import compare_traces
from .provenance import build_provenance

PRODUCER="tools.strategy_factory.lcm.lcm_09b.service:LCM09BSetupMigrationService"
TIME_SEMANTICS="DETERMINISTIC_FROM_BOUND_INPUTS_NO_WALL_CLOCK_IDENTITY"
def meta(*digests:str,status:str="BLOCKED")->dict[str,Any]:return {"schema_version":SCHEMA_VERSION,"producer":PRODUCER,"source_digests":list(digests),"generated_time_semantics":TIME_SEMANTICS,"owner":"ALPHA_LAB_MIGRATION_OWNER","claim_ceiling":CLAIM_CEILING,"validation_status":status}
class LCM09BSetupMigrationService:
    def build(self,repo_root:Path,output_root:Path)->dict[str,Any]:
        freeze=repo_root/FREEZE_ROOT;handoff=load_json(freeze/"handoff/lcm09a_to_lcm09b_handoff.json")
        if handoff["handoff_digest"]!=UPSTREAM_HANDOFF_DIGEST:raise ValueError("LCM09B_UPSTREAM_HANDOFF_MISMATCH")
        inventory=load_jsonl(freeze/"inventory/setup_inventory.jsonl")
        contracts={p.stem:load_json(p) for p in sorted((freeze/"setup_contracts").glob("*.json"))}
        if len(inventory)!=60 or len(contracts)!=60:raise ValueError("LCM09B_UPSTREAM_PORTFOLIO_COUNT_MISMATCH")
        if output_root.exists():shutil.rmtree(output_root)
        output_root.mkdir(parents=True)
        binding_body={**meta(handoff["handoff_digest"]),"binding_id":stable_id("LCM09ABIND",handoff["handoff_digest"]),"freeze_id":handoff["freeze_id"],"handoff_digest":handoff["handoff_digest"],"contract_registry_digest":handoff["contract_registry_digest"],"implementation_authorized_setup_ids":handoff["implementation_authorized_setup_ids"],"forbidden_actions":handoff["forbidden_actions"]}
        binding={**binding_body,"binding_digest":digest_object(binding_body)};dump_json(output_root/"input/lcm09a_binding.json",binding)
        packages=[];adapters=[];registrations=[];cases=[];traces=[];parity=[];blockers=[];deps=[];events=[]
        sequence=0
        for row in sorted(inventory,key=lambda x:x["setup_id"]):
            c=contracts[row["setup_id"]];setup_id=row["setup_id"];source_digest=row["source_artifact_sha256"]
            blocker_codes=sorted(set(row["blocking_reasons"]+["LCM09B_UPSTREAM_IMPLEMENTATION_NOT_AUTHORIZED"]))
            blocker_ids=[]
            for code in blocker_codes:
                bid=stable_id("SETUPBLOCKER",setup_id,code);blocker_ids.append(bid)
                bbody={**meta(handoff["handoff_digest"],source_digest),"blocker_id":bid,"setup_id":setup_id,"blocker_code":code,"severity":"BLOCKER","source_phase":"LCM-09A" if not code.startswith("LCM09B_") else "LCM-09B","resolution_owner":row["semantic_owner_role"],"resolution_state":"DEFERRED_TO_LCM10" if code=="CANONICAL_TREATMENT_BINDING_PENDING_LCM10" else "OPEN","details":{"source_artifact_path":row["source_artifact_path"],"owner_resolution_status":row["owner_resolution_status"],"characterization_packet_status":row["characterization_packet_status"]}}
                blockers.append({**bbody,"blocker_digest":digest_object(bbody)})
            pbody={**meta(handoff["handoff_digest"],source_digest,c["contract_digest"]),"package_id":stable_id("SETUPPKG",setup_id,c["contract_digest"]),"setup_id":setup_id,"family_id":"SETUPFAMILY_"+row["family_candidate"],"package_version":"1.0.0","package_status":"REFERENCE_BLOCKED","executable_reference":False,"source_binding":{"path":row["source_artifact_path"],"sha256":source_digest,"identity_digest":row["identity_digest"],"contract_id":row["contract_id"],"contract_digest":c["contract_digest"],"source_move_performed":False,"source_delete_performed":False},"context_binding":{"state":c["context_binding"]["state"],"allowed_context_identity_ids":[] if c["context_binding"]["canonical_context_identity_id"] is None else [c["context_binding"]["canonical_context_identity_id"]],"independent_context_clock":False,"context_recomputation":False},"treatment_binding":{"state":"PENDING_LCM10","canonical_treatment_identity_id":None,"treatment_semantics_in_setup_core":False},"rules":{k:None for k in ("eligibility","trigger","confirmation","invalidation","cancellation","expiry","abstention","entitlement")},"reason_codes":blocker_codes,"blocker_ids":blocker_ids,"authority_boundary":{"promotion_authority":False,"runtime_authority":False,"live_order_authority":False,"capital_authority":False,"consumer_cutover_authorized":False}}
            pkg={**pbody,"package_digest":digest_object(pbody)};packages.append(pkg)
            rel=f"canonical_setup_packages/{setup_id}.json";dump_json(output_root/rel,pkg)
            abody={**meta(handoff["handoff_digest"],source_digest),"adapter_id":stable_id("SETUPADAPTER",setup_id,source_digest),"setup_id":setup_id,"source_artifact_path":row["source_artifact_path"],"source_artifact_sha256":source_digest,"adapter_status":"REFERENCE_BLOCKED","input_contract":"LEGACY_EVIDENCE_RECORD_V1","output_contract":"LCM09B_SETUP_DECISION_V1","executes_legacy_source":False,"reason_codes":blocker_codes}
            adapter={**abody,"adapter_digest":digest_object(abody)};adapters.append(adapter)
            registrations.append({"registration_id":stable_id("FACTORYREF",setup_id,pkg["package_digest"]),"setup_id":setup_id,"package_id":pkg["package_id"],"package_path":rel,"package_digest":pkg["package_digest"],"registration_status":"REFERENCE_BLOCKED","candidate_visibility":"DIAGNOSTIC_REFERENCE_ONLY","blocker_ids":blocker_ids,"promotion_authority":False,"runtime_authority":False,"live_order_authority":False,"capital_authority":False})
            snapshot_body={"schema_version":"1.0.0","context_identity_id":"UNRESOLVED_CONTEXT","context_version":"0.0.0","occurrence_id":stable_id("OCC",setup_id,"BLOCKED_CASE"),"observed_at":"1970-01-01T00:00:00Z","available_at":"1970-01-01T00:00:00Z","features":{},"states":["BLOCKED_UPSTREAM"],"known_time_complete":True,"source_digest":source_digest}
            snapshot={**snapshot_body,"snapshot_digest":digest_object(snapshot_body)}
            expected={"decision_state":"BLOCKED","no_trade":True,"reason_codes":sorted(set(blocker_codes+["LCM09B_FAIL_CLOSED_BLOCKED_PACKAGE"]))}
            case_body={**meta(handoff["handoff_digest"],source_digest),"case_id":stable_id("SETUPCASE",setup_id,"BLOCKED"),"setup_id":setup_id,"case_status":"BLOCKED","input_snapshot":snapshot,"expected_decision":expected,"blocker_ids":blocker_ids}
            cases.append({**case_body,"case_digest":digest_object(case_body)})
            checkpoint_body={"schema_version":"1.0.0","setup_id":setup_id,"occurrence_id":snapshot["occurrence_id"],"last_sequence":0,"decision_state":"BLOCKED","last_decision_digest":None,"reason_codes":expected["reason_codes"]};checkpoint={**checkpoint_body,"checkpoint_digest":digest_object(checkpoint_body)}
            trace_body={**meta(handoff["handoff_digest"],source_digest),"trace_id":stable_id("SETUPTRACE",setup_id,"BLOCKED"),"setup_id":setup_id,"trace_status":"BLOCKED","events":[],"restart_checkpoint":checkpoint,"blocker_ids":blocker_ids}
            traces.append({**trace_body,"trace_digest":digest_object(trace_body)})
            parity.append(compare_traces(setup_id=setup_id,legacy=None,canonical=None,blockers=blocker_codes))
            dbody={**meta(handoff["handoff_digest"],source_digest),"dependency_id":stable_id("TREATDEP",setup_id,"LCM10"),"setup_id":setup_id,"canonical_treatment_identity_id":None,"dependency_state":"PENDING_LCM10","required_capabilities":["TREATMENT_IDENTITY_RESOLUTION","ACTION_SEMANTICS","RISK_ENVELOPE","EXECUTION_BOUNDARY"],"forbidden_in_setup_core":["ORDER_ROUTING","POSITION_SIZING","BROKER_STATE","CHART_OBJECT_MUTATION"]}
            deps.append({**dbody,"dependency_digest":digest_object(dbody)})
            sequence+=1;ebody={**meta(handoff["handoff_digest"],source_digest),"event_id":stable_id("SETUPMIGEVENT",MIGRATION_ID,sequence),"sequence":sequence,"event_type":"REFERENCE_PACKAGE_MATERIALIZED_BLOCKED","subject_id":setup_id,"payload_digest":pkg["package_digest"]};events.append({**ebody,"event_digest":digest_object(ebody)})
        package_rows=[{"setup_id":p["setup_id"],"package_id":p["package_id"],"package_path":f"canonical_setup_packages/{p['setup_id']}.json","package_status":p["package_status"],"package_digest":p["package_digest"]} for p in packages]
        reg_body={**meta(handoff["handoff_digest"]),"migration_id":MIGRATION_ID,"packages":package_rows,"package_count":len(package_rows)};registry={**reg_body,"registry_digest":digest_object(reg_body)};dump_json(output_root/"canonical_setup_registry.json",registry)
        adapter_body={**meta(handoff["handoff_digest"]),"migration_id":MIGRATION_ID,"adapter_count":len(adapters),"adapters":adapters};adapter_doc={**adapter_body,"registry_digest":digest_object(adapter_body)};dump_json(output_root/"adapters/setup_adapter_registry.json",adapter_doc)
        factory_body={**meta(handoff["handoff_digest"],registry["registry_digest"]),"migration_id":MIGRATION_ID,"factory_port":"ACL04_LEGACY_REFERENCE_PORT_V1","registrations":registrations};factory={**factory_body,"registration_digest":digest_object(factory_body)};dump_json(output_root/"factory/setup_factory_registration.json",factory)
        dump_jsonl(output_root/"golden/setup_golden_cases.jsonl",cases);dump_jsonl(output_root/"golden/setup_golden_traces.jsonl",traces);dump_jsonl(output_root/"parity/setup_parity_registry.jsonl",parity);dump_jsonl(output_root/"blockers/setup_blocker_registry.jsonl",blockers);dump_jsonl(output_root/"dependencies/treatment_dependency_inventory_seed.jsonl",deps)
        parity_digest=digest_object(parity);dep_digest=digest_object(deps)
        parity_registry_body={**meta(handoff["handoff_digest"],parity_digest),"migration_id":MIGRATION_ID,"record_count":len(parity),"records":parity}
        parity_registry={**parity_registry_body,"registry_digest":digest_object(parity_registry_body)};dump_json(output_root/"parity/setup_parity_registry.json",parity_registry)
        variance_body={**meta(handoff["handoff_digest"],parity_digest),"decisions":[],"hard_mismatch_count":0,"blocked_count":len(parity),"unknown_count":0};dump_json(output_root/"parity/setup_variance_decisions.json",{**variance_body,"decision_digest":digest_object(variance_body)})
        event_body={**meta(handoff["handoff_digest"]),"migration_id":MIGRATION_ID,"event_count":len(events),"events":events};dump_json(output_root/"events/setup_migration_event_ledger.json",{**event_body,"ledger_digest":digest_object(event_body)})
        dump_json(output_root/"provenance/setup_migration_provenance_graph.json",build_provenance(packages,handoff["handoff_digest"]))
        closure_body={**meta(handoff["handoff_digest"],registry["registry_digest"]),"migration_id":MIGRATION_ID,"setup_identity_count":60,"canonical_reference_package_count":60,"reference_ready_count":0,"explicitly_blocked_count":60,"unaccounted_count":0,"closure_status":"CLOSED_REFERENCE_ACCOUNTING"};dump_json(output_root/"reports/portfolio_closure_report.json",{**closure_body,"report_digest":digest_object(closure_body)})
        attacks=[{"attack":"FACTORY_DEFAULT_CHANGES_SEMANTICS","result":"PASS","evidence":"All registrations are reference-blocked and no candidate compiler path is invoked."},{"attack":"MISSING_NO_TRADE_RECORD","result":"PASS","evidence":"Each blocked package has a deterministic BLOCKED/no-trade golden case."},{"attack":"SETUP_RECOMPUTES_CONTEXT","result":"PASS","evidence":"Evaluator accepts caller-supplied snapshots only and owns no clock."},{"attack":"SUPPRESSION_DELETES_EVIDENCE","result":"PASS","evidence":"Blockers, cases, traces and parity dispositions remain explicit."},{"attack":"EXPIRY_RESTORED_INCORRECTLY","result":"PASS","evidence":"Checkpoint restore is digest-bound; wall-clock reconstruction is absent."},{"attack":"ORDER_OR_DRAWING_AUTHORITY_LEAK","result":"PASS","evidence":"Static boundary scan and false authority fields close these surfaces."}]
        hostile_body={**meta(handoff["handoff_digest"]),"migration_id":MIGRATION_ID,"hostile_review_passed":True,"attacks":attacks,"unresolved_risks":["All 60 identities remain blocked for semantic owner approval, observed characterization and canonical Context binding.","MQL5 compiler and runtime parity are not claimed."]};dump_json(output_root/"reports/hostile_review.json",{**hostile_body,"report_digest":digest_object(hostile_body)})
        gates=[{"gate":"PORTFOLIO_ACCOUNTING","result":"PASS"},{"gate":"REFERENCE_PACKAGE_MATERIALIZATION","result":"PASS"},{"gate":"FACTORY_AUTHORITY_NEGATIVE","result":"PASS"},{"gate":"PARITY_DISPOSITION","result":"PASS_BLOCKED_NONCOMPENSATORY"},{"gate":"CONTEXT_CLOCK_NEGATIVE","result":"PASS"},{"gate":"ORDER_DRAWING_NEGATIVE","result":"PASS"},{"gate":"TREATMENT_DEPENDENCY_EXPLICIT","result":"PASS"}]
        acceptance_body={**meta(handoff["handoff_digest"],registry["registry_digest"],parity_digest),"migration_id":MIGRATION_ID,"acceptance_gate_passed":True,"package_count":60,"reference_ready_count":0,"explicitly_blocked_count":60,"factory_registration_count":60,"parity_pass_count":0,"parity_blocked_count":60,"hard_mismatch_count":0,"non_compensatory_gates":gates};acceptance={**acceptance_body,"report_digest":digest_object(acceptance_body)};dump_json(output_root/"reports/acceptance_report.json",acceptance)
        hand=build_handoff(migration_id=MIGRATION_ID,upstream_digest=handoff["handoff_digest"],package_registry_digest=registry["registry_digest"],parity_registry_digest=parity_digest,treatment_seed_digest=dep_digest,blocked_ids=[p["setup_id"] for p in packages],ready_ids=[]);dump_json(output_root/"handoff/lcm09b_to_lcm10a_handoff.json",hand);dump_json(output_root/"LCM09B_TO_LCM10A_HANDOFF.json",hand)
        locator_body={**meta(handoff["handoff_digest"],registry["registry_digest"],factory["registration_digest"],parity_registry["registry_digest"],hand["handoff_digest"],status="PASS"),"migration_id":MIGRATION_ID,"artifacts":{"canonical_setup_packages":"canonical_setup_packages/","setup_adapter_registry.json":{"path":"adapters/setup_adapter_registry.json","digest":adapter_doc["registry_digest"]},"setup_factory_registration.json":{"path":"factory/setup_factory_registration.json","digest":factory["registration_digest"]},"setup_golden_cases.jsonl":{"path":"golden/setup_golden_cases.jsonl","digest":digest_object(cases)},"setup_golden_traces.jsonl":{"path":"golden/setup_golden_traces.jsonl","digest":digest_object(traces)},"setup_parity_registry.json":{"path":"parity/setup_parity_registry.json","digest":parity_registry["registry_digest"]},"setup_variance_decisions.json":{"path":"parity/setup_variance_decisions.json","digest":digest_object(variance_body)},"LCM09B_TO_LCM10A_HANDOFF.json":{"path":"LCM09B_TO_LCM10A_HANDOFF.json","digest":hand["handoff_digest"]}}}
        locator={**locator_body,"locator_digest":digest_object(locator_body)};dump_json(output_root/"required_artifact_locator.json",locator)
        marker_body={**meta(handoff["handoff_digest"],registry["registry_digest"]),"migration_id":MIGRATION_ID,"phase_id":"LCM-09B","master_phase":"LCM-09","status":"ACCEPTED_REFERENCE","package_count":60,"reference_ready_count":0,"explicitly_blocked_count":60};dump_json(output_root/"setup_migration_marker.json",{**marker_body,"marker_digest":digest_object(marker_body)})
        manifest=build_manifest(output_root);dump_json(output_root/"output_manifest.json",manifest)
        receipt_body={**meta(handoff["handoff_digest"],manifest["manifest_digest"],hand["handoff_digest"],status="PASS"),"migration_id":MIGRATION_ID,"upstream_handoff_digest":handoff["handoff_digest"],"output_manifest_digest":manifest["manifest_digest"],"handoff_digest":hand["handoff_digest"],"package_count":60,"factory_registration_count":60,"source_move_performed":False,"source_delete_performed":False,"consumer_cutover_performed":False,"semantic_refactor_performed":False};receipt={**receipt_body,"receipt_digest":digest_object(receipt_body)};dump_json(output_root/"setup_migration_receipt.json",receipt)
        manifest=build_manifest(output_root);dump_json(output_root/"output_manifest.json",manifest)
        return {"passed":True,"migration_id":MIGRATION_ID,"package_count":60,"reference_ready_count":0,"explicitly_blocked_count":60,"factory_registration_count":60,"handoff_digest":hand["handoff_digest"],"manifest_digest":manifest["manifest_digest"]}
