#ifndef __LCM10B_STATIC_CONTRACT_MQH__
#define __LCM10B_STATIC_CONTRACT_MQH__
#define LCM10B_SCHEMA_VERSION "1.0.0"
#define LCM10B_CLAIM_CEILING "LCM_10B_REFERENCE_ONLY"
#define LCM10B_LIVE_MODE_ALLOWED false
#define LCM10B_PAPER_MODE_ALLOWED false
#define LCM10B_SUBMISSION_DEFAULT false
#endif
