#ifndef UCEI08_CATALOG_MQH
#define UCEI08_CATALOG_MQH
#include "UCEI08_Registry.mqh"
void UCEI08_Add(CUCEI08_Registry &r,const string id,const UCEI08_AlgorithmFamily family,const string tasks,const bool probability,const string deps,const string tags){UCEI08_AlgorithmDescriptor d;d.algorithm_id=id;d.algorithm_version="1.0.0";d.trainer_id="uce.classical."+id;d.trainer_version="1.0.0";d.family=family;d.task_csv=tasks;d.probability_output=probability;d.supports_sample_weight=true;d.supports_missing_values=false;d.supports_multiclass=(StringFind(tasks,"multiclass")>=0);d.determinism="numeric_tolerance";d.portability="parameter_snapshot";d.export_csv="native_json";d.dependency_csv=deps;d.tags_csv=tags;d.limitations_csv="";r.Register(d);}
void UCEI08_RegisterCatalog(CUCEI08_Registry &r){
 UCEI08_Add(r,"never_trade",UCEI08_FAMILY_BASELINE,"binary_classification",true,"builtin","naive,mandatory");UCEI08_Add(r,"always_trade",UCEI08_FAMILY_BASELINE,"binary_classification",true,"builtin","naive,mandatory");UCEI08_Add(r,"prevalence",UCEI08_FAMILY_BASELINE,"binary_classification",true,"builtin","naive,mandatory");UCEI08_Add(r,"manual_threshold",UCEI08_FAMILY_BASELINE,"binary_classification",true,"builtin","manual,mandatory");UCEI08_Add(r,"single_feature_search",UCEI08_FAMILY_BASELINE,"binary_classification",true,"builtin","transparent,mandatory");UCEI08_Add(r,"rate_matched_null",UCEI08_FAMILY_BASELINE,"binary_classification",true,"builtin","null,mandatory");UCEI08_Add(r,"random_null",UCEI08_FAMILY_BASELINE,"binary_classification",true,"builtin","null");
 UCEI08_Add(r,"linear_regression",UCEI08_FAMILY_LINEAR,"regression",false,"scikit-learn>=1.4","linear");UCEI08_Add(r,"ridge_regression",UCEI08_FAMILY_LINEAR,"regression",false,"scikit-learn>=1.4","linear,mandatory");UCEI08_Add(r,"logistic_regression",UCEI08_FAMILY_LINEAR,"binary_classification,multiclass_classification",true,"scikit-learn>=1.4","linear,mandatory");UCEI08_Add(r,"elastic_net",UCEI08_FAMILY_LINEAR,"regression",false,"scikit-learn>=1.4","sparse");UCEI08_Add(r,"huber_regression",UCEI08_FAMILY_LINEAR,"regression",false,"scikit-learn>=1.4","robust");UCEI08_Add(r,"linear_svm",UCEI08_FAMILY_KERNEL,"binary_classification,multiclass_classification",false,"scikit-learn>=1.4","margin");UCEI08_Add(r,"rbf_svm",UCEI08_FAMILY_KERNEL,"binary_classification,multiclass_classification",true,"scikit-learn>=1.4","kernel,compute_gated");UCEI08_Add(r,"knn_classifier",UCEI08_FAMILY_NEIGHBORHOOD,"binary_classification,multiclass_classification",true,"scikit-learn>=1.4","distance");UCEI08_Add(r,"nearest_centroid",UCEI08_FAMILY_NEIGHBORHOOD,"binary_classification,multiclass_classification",false,"scikit-learn>=1.4","distance,transparent");
 UCEI08_Add(r,"decision_tree_classifier",UCEI08_FAMILY_TREE,"binary_classification,multiclass_classification",true,"scikit-learn>=1.4","tree,mandatory");UCEI08_Add(r,"random_forest_classifier",UCEI08_FAMILY_TREE,"binary_classification,multiclass_classification",true,"scikit-learn>=1.4","ensemble,mandatory");UCEI08_Add(r,"extra_trees_classifier",UCEI08_FAMILY_TREE,"binary_classification,multiclass_classification",true,"scikit-learn>=1.4","ensemble");UCEI08_Add(r,"gradient_boosting_classifier",UCEI08_FAMILY_BOOSTING,"binary_classification,multiclass_classification",true,"scikit-learn>=1.4","boosting");UCEI08_Add(r,"hist_gradient_boosting_classifier",UCEI08_FAMILY_BOOSTING,"binary_classification,multiclass_classification",true,"scikit-learn>=1.4","boosting,histogram");UCEI08_Add(r,"gaussian_nb",UCEI08_FAMILY_PROBABILISTIC,"binary_classification,multiclass_classification",true,"scikit-learn>=1.4","bayesian");UCEI08_Add(r,"bernoulli_nb",UCEI08_FAMILY_PROBABILISTIC,"binary_classification,multiclass_classification",true,"scikit-learn>=1.4","bayesian");UCEI08_Add(r,"spline_logistic_gam",UCEI08_FAMILY_ADDITIVE,"binary_classification",true,"scikit-learn>=1.4","gam,additive");
 UCEI08_Add(r,"xgboost_classifier",UCEI08_FAMILY_OPTIONAL_EXTERNAL,"binary_classification,multiclass_classification",true,"xgboost>=2.0","optional,boosting");UCEI08_Add(r,"lightgbm_classifier",UCEI08_FAMILY_OPTIONAL_EXTERNAL,"binary_classification,multiclass_classification",true,"lightgbm>=4.0","optional,boosting");UCEI08_Add(r,"catboost_classifier",UCEI08_FAMILY_OPTIONAL_EXTERNAL,"binary_classification,multiclass_classification",true,"catboost>=1.2","optional,boosting");r.Freeze();}
#endif
