#ifndef ALPHALAB_ACL01_AUTHORITY_ENVELOPE_MQH
#define ALPHALAB_ACL01_AUTHORITY_ENVELOPE_MQH
#define ACL01_LIVE_ORDER_SUBMISSION_ALLOWED false
#define ACL01_CAPITAL_ACTIVATION_ALLOWED false
#define ACL01_CLAIM_CEILING "REFERENCE_REPOSITORY_CONTROL_PLANE"
bool ACL01AuthorityBoundarySafe() { return ACL01_LIVE_ORDER_SUBMISSION_ALLOWED==false && ACL01_CAPITAL_ACTIVATION_ALLOWED==false; }
#endif
