from enum import Enum,IntEnum

class LifecycleState(IntEnum):
    CREATED=0; INITIALIZING=1; READY=2; DEGRADED=3; BLOCKED=4; STOPPING=5; STOPPED=6
class HealthState(IntEnum):
    BLOCKED=0; DEGRADED=1; READY=2
class DataReadiness(IntEnum):
    BLOCKED=0; PARTIAL=1; READY=2
class ActiveWWDirection(IntEnum):
    BEARISH=-1; NONE=0; BULLISH=1; DATA_BLOCKED=2
class CheckpointDisposition(str,Enum):
    ABSENT="ABSENT"; RESTORED="RESTORED"; REBUILD_REQUIRED="REBUILD_REQUIRED"; REJECT_CONFIG="REJECT_CONFIG"; REJECT_INSTANCE="REJECT_INSTANCE"; REJECT_VERSION="REJECT_VERSION"; REJECT_HASH="REJECT_HASH"
class WorkMode(str,Enum):
    NOOP="NOOP"; INITIAL_BACKFILL="INITIAL_BACKFILL"; INCREMENTAL="INCREMENTAL"; CHUNKED_CATCHUP="CHUNKED_CATCHUP"; REBUILD="REBUILD"
class LifecycleEventType(str,Enum):
    INIT_STARTED="INIT_STARTED"; INPUT_VALIDATED="INPUT_VALIDATED"; UPSTREAM_VALIDATED="UPSTREAM_VALIDATED"; INSTANCE_CREATED="INSTANCE_CREATED"; CHECKPOINT_RESTORED="CHECKPOINT_RESTORED"; REBUILD_STARTED="REBUILD_STARTED"; ENGINE_READY="ENGINE_READY"; CALCULATE_INCREMENTAL="CALCULATE_INCREMENTAL"; TIMER_HEARTBEAT="TIMER_HEARTBEAT"; CHART_EVENT="CHART_EVENT"; HEALTH_CHANGED="HEALTH_CHANGED"; DEINIT_STARTED="DEINIT_STARTED"; DEINIT_COMPLETED="DEINIT_COMPLETED"; BLOCKED="BLOCKED"
class ModuleStatus(str,Enum):
    READY="READY"; DEGRADED="DEGRADED"; BLOCKED="BLOCKED"
class ProcessTrigger(str,Enum):
    INIT="INIT"; CALCULATE="CALCULATE"; TIMER="TIMER"; CHART_EVENT="CHART_EVENT"; RESTART="RESTART"
