#ifndef AL_SAED_V4_02_TWIN_ENUMS_MQH
#define AL_SAED_V4_02_TWIN_ENUMS_MQH
enum AL_TWIN_STATE { AL_TWIN_SEEDED=0, AL_TWIN_INITIALIZED=1, AL_TWIN_OBSERVING=2, AL_TWIN_DEGRADED=3, AL_TWIN_CONFLICTED=4, AL_TWIN_QUARANTINED=5, AL_TWIN_RETIRED=6 };
enum AL_SUPPORT_STATUS { AL_SUPPORT_SUPPORTED=0, AL_SUPPORT_DEGRADED=1, AL_SUPPORT_UNSUPPORTED=2, AL_SUPPORT_UNKNOWN=3 };
enum AL_TRANSITION_DISPOSITION { AL_TRANSITION_APPLIED=0, AL_TRANSITION_REJECTED=1, AL_TRANSITION_REVIEW=2, AL_TRANSITION_NOOP=3 };
#endif
