#ifndef AL_SAED_V4_02_TWIN_AUTHORITY_MQH
#define AL_SAED_V4_02_TWIN_AUTHORITY_MQH
#define AL_TWIN_READ_UCEE_TRUTH true
#define AL_TWIN_COMPILE_AUTHORITY true
#define AL_TWIN_ORDER_AUTHORITY false
#define AL_TWIN_BROKER_AUTHORITY false
#define AL_TWIN_NETWORK_AUTHORITY false
#define AL_TWIN_CONTEXT_MUTATION_AUTHORITY false
#define AL_TWIN_TREATMENT_SELECTION_AUTHORITY false
#define AL_TWIN_RISK_AUTHORITY false
#define AL_TWIN_PORTFOLIO_AUTHORITY false
#define AL_TWIN_RUNTIME_ACTIVATION_AUTHORITY false
bool ALTwinAuthoritySafe(){return AL_TWIN_READ_UCEE_TRUTH && AL_TWIN_COMPILE_AUTHORITY && !AL_TWIN_ORDER_AUTHORITY && !AL_TWIN_BROKER_AUTHORITY && !AL_TWIN_NETWORK_AUTHORITY && !AL_TWIN_CONTEXT_MUTATION_AUTHORITY && !AL_TWIN_TREATMENT_SELECTION_AUTHORITY && !AL_TWIN_RISK_AUTHORITY && !AL_TWIN_PORTFOLIO_AUTHORITY && !AL_TWIN_RUNTIME_ACTIVATION_AUTHORITY;}
#endif
