#ifndef ALPHALAB_ACL_OS_LCM08A_TYPES_MQH
#define ALPHALAB_ACL_OS_LCM08A_TYPES_MQH
enum ENUM_LCM08A_RISK_CLASS{LCM08A_RISK_LOW=0,LCM08A_RISK_MODERATE=1,LCM08A_RISK_HIGH=2,LCM08A_RISK_CRITICAL=3,LCM08A_RISK_UNKNOWN=4};
enum ENUM_LCM08A_AUTHORITY{LCM08A_REFERENCE_ONLY=0};
#endif
