#ifndef ALPHA_LAB_SAED_V4_VIEW_ENUMS_MQH
#define ALPHA_LAB_SAED_V4_VIEW_ENUMS_MQH
enum ENUM_SAED_VIEW_KIND { SAED_VIEW_PRICE=0, SAED_VIEW_STRUCTURE=1, SAED_VIEW_TIME=2, SAED_VIEW_HIGHER_TIMEFRAME=3, SAED_VIEW_INTERMARKET=4, SAED_VIEW_LIQUIDITY=5, SAED_VIEW_SESSION=6, SAED_VIEW_EXECUTION=7, SAED_VIEW_CONTEXT_ANCESTRY=8, SAED_VIEW_TREATMENT_DESCRIPTOR=9 };
enum ENUM_SAED_VIEW_STATUS { SAED_VIEW_COMPLETE=0, SAED_VIEW_DEGRADED=1, SAED_VIEW_UNKNOWN=2, SAED_VIEW_CONFLICTED=3, SAED_VIEW_QUARANTINED=4 };
enum ENUM_SAED_MISSING_POLICY { SAED_MISSING_PROHIBIT=0, SAED_MISSING_MASK=1, SAED_MISSING_UNKNOWN=2, SAED_MISSING_EXPLICIT_DEFAULT=3 };
#endif
