#ifndef ALPHA_LAB_SAED_V4_VIEW_DIAGNOSTICS_MQH
#define ALPHA_LAB_SAED_V4_VIEW_DIAGNOSTICS_MQH
#include "ViewAuthority.mqh"
bool SAEDViewAuthoritySafe(){ return SAED_VIEW_READ_TWIN_AUTHORITY && SAED_VIEW_READ_EVENT_PROJECTION_AUTHORITY && SAED_VIEW_BUILD_AUTHORITY && !SAED_VIEW_TRAIN_MODEL_AUTHORITY && !SAED_VIEW_TREATMENT_SELECTION_AUTHORITY && !SAED_VIEW_RISK_AUTHORITY && !SAED_VIEW_RUNTIME_AUTHORITY && !SAED_VIEW_ORDER_AUTHORITY && !SAED_VIEW_BROKER_AUTHORITY && !SAED_VIEW_NETWORK_AUTHORITY && !SAED_VIEW_CONTEXT_MUTATION_AUTHORITY; }
#endif
