from __future__ import annotations
from .canonical import stable_id,with_digest
def build_operations(binding:dict,contracts:dict,policy:dict,closed_at:str)->dict:
    fleet_id=contracts['fleet']['fleet_id']
    evidence=with_digest({'schema_version':'1.0.0','evidence_inventory_id':stable_id('EVID',fleet_id),'fleet_id':fleet_id,'pilot_design_present':True,'pilot_contract_authored':True,'real_context_evidence_present':False,'prospective_evidence_present':False,'prospective_observation_rows':0,'pilot_outcomes_present':False,'validation_evidence_present':False,'runtime_parity_evidence_present':False,'production_security_evidence_present':False,'reference_material_misclassified':False},'evidence_inventory_digest')
    retention_status=with_digest({'schema_version':'1.0.0','status_id':stable_id('RETSTATUS',fleet_id),'fleet_id':fleet_id,'retention_contract_digest':contracts['retention']['retention_contract_digest'],'status':'RETENTION_CONTRACT_REGISTERED','archive_materialized':False,'deletion_allowed':False,'next_review_at':policy['retention']['next_review_at']},'retention_status_digest')
    surveillance_status=with_digest({'schema_version':'1.0.0','status_id':stable_id('SURVSTATUS',fleet_id),'fleet_id':fleet_id,'surveillance_contract_digest':contracts['surveillance']['surveillance_contract_digest'],'status':'SURVEILLANCE_CONTRACT_REGISTERED','production_monitoring_active':False,'reference_integrity_monitoring_registered':True,'observed_pilot_metrics_count':0,'alerts_count':0},'surveillance_status_digest')
    package_status=with_digest({'schema_version':'1.0.0','package_status_id':stable_id('PKGSTATUS',fleet_id),'fleet_id':fleet_id,'pilot_run_id':binding['pilot_run_id'],'pilot_readiness_state':binding['pilot_readiness_state'],'fleet_statuses':['REGISTERED_REFERENCE_NON_EXECUTED','SURVEILLANCE_CONTRACT_REGISTERED','RETENTION_CONTRACT_REGISTERED'],'pilot_execution_materialized':False,'prospective_evidence_present':False,'unknowns_preserved':True,'unexecuted_state_preserved':True,'closed_history_mutation_allowed':False},'package_status_digest')
    manifest=with_digest({'schema_version':'1.0.0','fleet_operations_manifest_id':stable_id('FLEETOPS',fleet_id),'fleet_id':fleet_id,'package_count':1,'packages':[{'pilot_run_id':binding['pilot_run_id'],'pilot_contract_id':binding['pilot_contract_id'],'package_status_digest':package_status['package_status_digest'],'evidence_inventory_digest':evidence['evidence_inventory_digest']}],'runtime_count':0,'order_route_count':0,'capital_allocation_count':0,'fleet_operations_materialized':True,'production_fleet_active':False},'fleet_operations_manifest_digest')
    execution=with_digest({'schema_version':'1.0.0','execution_manifest_id':stable_id('NOEXEC',fleet_id),'fleet_id':fleet_id,'pilot_execution_count':0,'runtime_generation_count':0,'runtime_activation_count':0,'live_order_count':0,'capital_activation_count':0,'pilot_execution_materialized':False,'runtime_generation_allowed':False,'runtime_activation_allowed':False,'live_order_submission_allowed':False,'capital_activation_allowed':False},'execution_manifest_digest')
    return {'evidence':evidence,'retention_status':retention_status,'surveillance_status':surveillance_status,'package_status':package_status,'manifest':manifest,'execution':execution}
