from __future__ import annotations
CLAIM_CEILING='FLEET_OPERATIONS_AND_CLOSURE_REFERENCE_ONLY'
HANDOFF_IN='ACL14_TO_ACL15'
HANDOFF_OUT='ACL15_LIFECYCLE_CLOSURE'
ACTION='ACL15_REGISTER_FLEET_AND_CLOSE_REFERENCE_LIFECYCLE'
REQUIRED_UPSTREAM_ACTIONS={'VERIFY_FIRST_REAL_CONTEXT_PILOT_PACKAGE','REGISTER_FLEET_OPERATIONS_CONTRACT','ISSUE_NON_CAPITAL_CLOSURE_DECISION'}
FORBIDDEN_UPSTREAM_ACTIONS={'TREAT_PILOT_DESIGN_AS_PROSPECTIVE_EVIDENCE','INVENT_PILOT_OUTCOMES','BYPASS_VALIDATION_OR_PROMOTION','AUTHORIZE_RUNTIME_OR_LIVE_ORDER','ACTIVATE_CAPITAL'}
FLEET_STATUSES=['REGISTERED_REFERENCE_NON_EXECUTED','SURVEILLANCE_CONTRACT_REGISTERED','RETENTION_CONTRACT_REGISTERED','CLOSED_NON_CAPITAL_REFERENCE','REOPEN_REQUIRES_NEW_AUTHORIZED_EVIDENCE']
CLOSURE_STATES=['REFERENCE_LIFECYCLE_CLOSED_NON_CAPITAL','MIGRATION_PENDING_REVIEW','REOPEN_PENDING_NEW_EVIDENCE','RETIRED_IMMUTABLE']
ALLOWED_REOPEN_ACTIONS=['AUTHOR_NEW_REAL_CONTEXT_PILOT_PACKAGE','MIGRATE_CONTRACT_VERSION_WITH_REVIEW','RESTORE_ARCHIVED_PACKAGE_FOR_AUDIT']
FORBIDDEN_ACTIONS=['INVENT_PROSPECTIVE_OUTCOMES','TREAT_REFERENCE_AS_REAL_EVIDENCE','BYPASS_UNIFIED_VALIDATION','BYPASS_PROMOTION_STATE_MACHINE','GENERATE_OR_ACTIVATE_RUNTIME','AUTHORIZE_LIVE_ORDER','ACTIVATE_CAPITAL','MUTATE_CLOSED_HISTORY']
REPORT_SECTIONS=['IDENTITY_AND_SCOPE','UPSTREAM_PILOT_STATUS','FLEET_REGISTRATION','LIFECYCLE_OWNERSHIP','RETENTION','SURVEILLANCE','EVIDENCE_INVENTORY','CLOSURE_DECISION','REOPEN_AND_MIGRATION','SECURITY_AND_AUTHORITY','RESIDUAL_RISK','FINAL_PROGRAM_STATUS']
