#property strict
#ifndef __DECISION_ALPHA_LAB_SAEDV420TREATMENTUNIVERSE_MQH__
#define __DECISION_ALPHA_LAB_SAEDV420TREATMENTUNIVERSE_MQH__
#define SAED_V4_20_PHASE "SAED_V4_20"
bool SAEDV420ClosedWorld(){ return true; }
#endif
