from __future__ import annotations

SCHEMA_VERSION = "1.0.0"
PHASE_ID = "LCM-13C"
MASTER_PHASE = "LCM-13"
CLAIM_CEILING = "LCM_13C_REFERENCE_ONLY"
OWNER = "ALPHA_LAB_MIGRATION_OWNER"
REVIEWER = "INDEPENDENT_MIGRATION_REVIEWER"
PRODUCER = "tools.strategy_factory.lcm.lcm_13c.service:LCM13CRollbackClosureService"
GENERATED_TIME_SEMANTICS = "DETERMINISTIC_FROM_BOUND_INPUTS_NO_WALL_CLOCK_IDENTITY"

CLOSURE_STATES = (
    "CLOSED",
    "CLOSED_WITH_RESIDUAL_RISK",
    "REOPEN_REQUIRED",
)

EVENT_TYPES = (
    "ROLLBACK_REHEARSAL_STARTED",
    "LEGACY_LOCATOR_RESTORED",
    "STATE_OWNERSHIP_VERIFIED",
    "LEGACY_REPLAY_PASSED",
    "CANONICAL_SWITCH_REAPPLIED",
    "FORWARD_RECOVERY_PASSED",
    "WAVE_CLOSED",
)

STATE_PLANES = (
    "PERSISTENT_FILES",
    "GLOBAL_VARIABLES",
    "CHART_OBJECTS",
    "CACHES",
    "GENERATED_REGISTRIES",
    "ENTITLEMENTS",
)

RESIDUAL_RISKS = (
    "LIVE_PLATFORM_ENVIRONMENTAL_PARITY_NOT_OBSERVED",
    "COMPATIBILITY_ADAPTER_WINDOW_REMAINS_OPEN",
)

UPSTREAM_CUTOVER_ROOT = (
    "registry/legacy_context_migration/consumer_wave_cutovers/"
    "CUTOVER_E38BEC955210CE172483EE47AA2D9E8C"
)
