#ifndef __SF08_CANDIDATE_ENUMS_MQH__
#define __SF08_CANDIDATE_ENUMS_MQH__

enum ENUM_SF08_POLICY_KIND
{
   SF08_POLICY_ENTRY=1,
   SF08_POLICY_STOP=2,
   SF08_POLICY_EXIT=3,
   SF08_POLICY_GATE=4
};

enum ENUM_SF08_ORDER_KIND
{
   SF08_ORDER_UNSPECIFIED=0,
   SF08_ORDER_MARKET=1,
   SF08_ORDER_LIMIT=2,
   SF08_ORDER_STOP=3
};

enum ENUM_SF08_EXIT_KIND
{
   SF08_EXIT_UNSPECIFIED=0,
   SF08_EXIT_PRICE_TARGET=1,
   SF08_EXIT_TIME_ONLY=2,
   SF08_EXIT_PRICE_OR_TIME=3,
   SF08_EXIT_STRUCTURAL=4
};

enum ENUM_SF08_POLICY_DECISION
{
   SF08_POLICY_ADMIT=1,
   SF08_POLICY_SKIP=2,
   SF08_POLICY_ERROR=3
};

enum ENUM_SF08_CANDIDATE_STATUS
{
   SF08_CANDIDATE_EMPTY=0,
   SF08_CANDIDATE_VALID=1,
   SF08_CANDIDATE_SKIPPED=2,
   SF08_CANDIDATE_REJECTED=3
};

enum ENUM_SF08_QUEUE_OVERFLOW_POLICY
{
   SF08_QUEUE_REJECT_NEW=1,
   SF08_QUEUE_DROP_OLDEST=2,
   SF08_QUEUE_FAIL_ENGINE=3
};

enum ENUM_SF08_SKIP_REASON
{
   SF08_SKIP_NONE=0,
   SF08_SKIP_TEMPLATE_DISABLED=1,
   SF08_SKIP_POLICY_NOT_FOUND=2,
   SF08_SKIP_POLICY_VERSION_MISMATCH=3,
   SF08_SKIP_ENTRY_INADMISSIBLE=4,
   SF08_SKIP_STOP_INADMISSIBLE=5,
   SF08_SKIP_EXIT_INADMISSIBLE=6,
   SF08_SKIP_GEOMETRY_INVALID=7,
   SF08_SKIP_DUPLICATE=8,
   SF08_SKIP_CAPACITY=9,
   SF08_SKIP_CONTEXT_MISMATCH=10,
   SF08_SKIP_POLICY_ERROR=11
};

#define SF08_MAX_POLICY_PARAMS 8
#define SF08_MAX_POLICY_REGISTRY 128
#define SF08_MAX_MATRIX_TEMPLATES 256
#define SF08_MAX_CANDIDATES_PER_EVENT 256

#endif
