#ifndef __AL_SAED_V4_DATA_FOUNDATION_ENUMS_MQH__
#define __AL_SAED_V4_DATA_FOUNDATION_ENUMS_MQH__
enum AL_DATA_ROLE { AL_ROLE_DEVELOPMENT=0, AL_ROLE_CALIBRATION=1, AL_ROLE_SELECTION_VALIDATION=2, AL_ROLE_LOCKED_FINAL=3, AL_ROLE_PROSPECTIVE=4, AL_ROLE_SHADOW=5, AL_ROLE_MICRO_LIVE=6, AL_ROLE_LIVE=7, AL_ROLE_SYNTHETIC_STRESS=8, AL_ROLE_EXTERNAL_STATIC=9, AL_ROLE_EXTERNAL_ACTUAL=10 };
enum AL_DATA_OPERATION { AL_OP_READ=0, AL_OP_WRITE=1, AL_OP_TRAIN=2, AL_OP_TUNE=3, AL_OP_CALIBRATE=4, AL_OP_SELECT=5, AL_OP_REPORT=6, AL_OP_PROMOTE=7, AL_OP_REPLAY=8, AL_OP_DELETE=9 };
enum AL_INTEGRITY_STATUS { AL_INTEGRITY_UNKNOWN=0, AL_INTEGRITY_PASS=1, AL_INTEGRITY_FAIL=2 };
#endif
