#ifndef __ALPHALAB_LCM06_PARITY_STATUS_MQH__
#define __ALPHALAB_LCM06_PARITY_STATUS_MQH__
enum AL_LCM06_PARITY_STATUS { AL_LCM06_PARITY_PASS=0, AL_LCM06_HARD_MISMATCH, AL_LCM06_SOFT_MISMATCH, AL_LCM06_UNKNOWN_EVIDENCE };
#endif
