from __future__ import annotations
from .errors import ContractViolation
IDENTITY_KINDS={
 'CONTEXT':('CTX','context'), 'SETUP':('STP','setup'), 'TREATMENT':('TRT','treatment'),
 'VISUALIZER':('VIS','visualizer'), 'ENGINE':('ENG','engine'), 'ADAPTER':('ADP','adapter'),
 'SUPPORT_ARTIFACT':('ART','artifact')}
ROLE_TO_KIND={
 'CONTEXT':'CONTEXT','SETUP':'SETUP','TREATMENT':'TREATMENT','VISUALIZER':'VISUALIZER',
 'SHARED_PRIMITIVE':'ENGINE','PLATFORM_KERNEL':'ENGINE','PLATFORM_ADAPTER':'ADAPTER',
 'EXECUTION_ADAPTER':'ADAPTER','RESEARCH':'SUPPORT_ARTIFACT','DIAGNOSTIC':'SUPPORT_ARTIFACT'}
ALIAS_TYPES=['LEGACY_PATH','FILE_BASENAME','MQL5_INCLUDE','PYTHON_IMPORT','OBSIDIAN_WIKILINK','CONFIG_REFERENCE','FUNCTION_NAME','INPUT_NAME','OBJECT_PREFIX','EXPERIMENT_CODE','DOCUMENT_SLUG']
ALIAS_STATUSES=['ACTIVE_REFERENCE','REDIRECT_PROPOSED','DEPRECATED','QUARANTINED','RETIRED','AMBIGUOUS_BLOCKED']
IDENTITY_STATUSES=['PROVISIONAL_UNMERGED_IDENTITY_CANDIDATE','PROTECTED_PLATFORM_TECHNICAL_IDENTITY','SECURITY_REVIEW_BLOCKED','AMBIGUOUS_ROLE_BLOCKED']
LOCATOR_STATUSES=['CURRENT_ARTIFACT_BOUND','PROPOSED_NOT_MATERIALIZED','AMBIGUOUS_BLOCKED','RETIRED']
RESOLUTION_STATUSES=['RESOLVABLE','AMBIGUOUS_BLOCKED','UNKNOWN_IDENTITY_BLOCKED','UNKNOWN_VERSION_BLOCKED','MISSING_TARGET_BLOCKED']
ACTIVE_STATUSES={'ACTIVE_PLATFORM','ACTIVE_RESEARCH','ACTIVE_RUNTIME_CANDIDATE'}
EDGE_TO_ALIAS={'MQL5_INCLUDE':'MQL5_INCLUDE','PYTHON_IMPORT':'PYTHON_IMPORT','PYTHON_FROM_IMPORT':'PYTHON_IMPORT','OBSIDIAN_WIKILINK':'OBSIDIAN_WIKILINK','MARKDOWN_LINK':'OBSIDIAN_WIKILINK','CONFIG_PATH_REFERENCE':'CONFIG_REFERENCE'}

def require(value, registry, label):
    if value not in registry: raise ContractViolation(f'unknown {label}: {value}')
    return value
