from .canonical import digest_object
PACKAGE_ROOTS={
"CONTEXT":"contexts/legacy/strategy_factory/authored","SETUP":"lab/11_strategy_factory/setups","TREATMENT":"lab/11_strategy_factory/treatments","VISUALIZER":"lab/11_strategy_factory/visualizers","ENGINE":"lab/11_strategy_factory/shared_engines","ADAPTER":"lab/11_strategy_factory/adapters","SUPPORT_ARTIFACT":"registry/history/lcm/support_artifacts","PLATFORM_KERNEL":"__RETAIN_CURRENT__","DOCUMENTATION":"docs/architecture/master","GENERATED_PROJECTION":"registry/generated_projections","RELEASE_METADATA":"registry/history/releases","SOURCE_EVIDENCE":"registry/source_evidence","TEST_CODE":"tests/legacy/strategy_factory/migration/tests","TEST_FIXTURE":"tests/legacy/strategy_factory/migration/fixtures","CONFIGURATION_CONTRACT":"registry/configuration_contracts","EXECUTION_ADAPTER":"lab/11_strategy_factory/adapters/mql5/execution","PLATFORM_ADAPTER":"lab/11_strategy_factory/adapters","SHARED_PRIMITIVE":"lab/11_strategy_factory/shared_engines","GOVERNANCE_CONTROL":"registry/governance","RESEARCH":"lab/11_strategy_factory/research","DIAGNOSTIC":"lab/11_strategy_factory/diagnostics","ARCHIVE":"registry/archives","UNKNOWN_ROLE":"tests/legacy/strategy_factory/migration/quarantine/unknown_role"}
TARGET_OUTCOMES=["RETAIN_CURRENT","PROPOSE_CANONICAL_PACKAGE","PROPOSE_COMPATIBILITY_WRAPPER","PROPOSE_ARCHIVE","PROPOSE_QUARANTINE","PROPOSE_SECURITY_RESTRICTED","PROPOSE_GENERATED_PROJECTION","BLOCKED_EQUIVALENCE_REVIEW"]
MATERIALIZATION_STATUSES=["NOT_MATERIALIZED","RETAINED_IN_PLACE","BLOCKED_OWNER_APPROVAL","BLOCKED_SECURITY_REVIEW","BLOCKED_IDENTITY_AMBIGUITY","BLOCKED_PARITY","BLOCKED_EQUIVALENCE_REVIEW"]
LAYERS=["EVIDENCE","SHARED_ENGINE","CONTEXT","SETUP","TREATMENT","VISUALIZER","PLATFORM_ADAPTER","EXECUTION_ADAPTER","APPLICATION","GENERATED","MIGRATION_CONTROL","RELEASE"]
ALLOWED_EDGES={"EVIDENCE":{"EVIDENCE"},"SHARED_ENGINE":{"EVIDENCE","SHARED_ENGINE"},"CONTEXT":{"EVIDENCE","SHARED_ENGINE","CONTEXT"},"SETUP":{"EVIDENCE","SHARED_ENGINE","CONTEXT","SETUP"},"TREATMENT":{"EVIDENCE","SHARED_ENGINE","CONTEXT","SETUP","TREATMENT"},"VISUALIZER":{"EVIDENCE","SHARED_ENGINE","CONTEXT","SETUP","TREATMENT","VISUALIZER"},"PLATFORM_ADAPTER":{"EVIDENCE","SHARED_ENGINE","CONTEXT","SETUP","TREATMENT","PLATFORM_ADAPTER"},"EXECUTION_ADAPTER":{"EVIDENCE","SHARED_ENGINE","CONTEXT","SETUP","TREATMENT","PLATFORM_ADAPTER","EXECUTION_ADAPTER"},"APPLICATION":set(LAYERS[:9]),"GENERATED":{"EVIDENCE","SHARED_ENGINE","CONTEXT","SETUP","TREATMENT","VISUALIZER","PLATFORM_ADAPTER","EXECUTION_ADAPTER","APPLICATION","GENERATED"},"MIGRATION_CONTROL":set(LAYERS),"RELEASE":{"EVIDENCE","GENERATED","RELEASE"}}
def registry(registry_id,field,values,policy=None):
    obj={"schema_version":"1.0.0","registry_id":registry_id,field:list(values),"policy":policy or {},"registry_digest":None};obj["registry_digest"]=digest_object(obj,"registry_digest");return obj
