#ifndef SAED_V4_39_AUTHORITY_MQH
#define SAED_V4_39_AUTHORITY_MQH
// SAEDV439 closed authority boundary.
#define SAED_V4_39_RESEARCH_ONLY 1
#define SAED_V4_39_LIVE_ORDER_SUBMISSION_ALLOWED 0
#define SAED_V4_39_CAPITAL_ACTIVATION_ALLOWED 0
#define SAED_V4_39_SELF_AUTHORIZATION_ALLOWED 0
#define SAED_V4_39_PRODUCTION_AUTHORIZED 0
#endif
