#property strict
#property version "1.00"
#include <AlphaLab\StrategyFactory\Testing\SF02_Assert.mqh>
#include <AlphaLab\StrategyFactory\Testing\SF02_FixtureServices.mqh>
#include <AlphaLab\StrategyFactory\Testing\SF03_FixtureMarketSource.mqh>
#include <AlphaLab\StrategyFactory\Market\SF03_AllMarket.mqh>
#include <AlphaLab\StrategyFactory\Plugins\SF04_AllPlugins.mqh>
#include <AlphaLab\StrategyFactory\Generation\SF05_AllGeneration.mqh>

SF05_RunManifest BuildManifest(CSF02FixtureClock &clock)
{
   SF05_RunManifest m;m.schema="alpha_lab.strategy_factory/run_manifest@1.0.0";m.manifest_id="";m.run_id="sf05_self_test_run";m.strategy_id="sf05_self_test";m.strategy_version="1.0.0";m.run_mode=SF02_MODE_ANATOMY_AUDIT;m.requested_generation_id=5;m.plugin_selection.plugin_id="sf04.fixture.pulse";m.plugin_selection.exact_version="1.0.0";m.plugin_selection.required_capabilities=SF04_CAP_DETERMINISTIC|SF04_CAP_TICK_INPUT;m.plugin_selection.expected_descriptor_hash="";m.plugin_configuration_hash="cfg_fixture_001";m.market_configuration_hash="mkt_fixture_001";m.sink_config=SF05_DefaultResultSinkConfig();m.sink_config.mode=SF05_SINK_MEMORY;m.sink_config.sink_id="sf05.memory";m.git_commit="git_fixture";m.build_id="build_fixture";m.environment_id="test";m.terminal_instance_id="fixture_terminal";m.strict_fail_closed=true;m.created_at=SF01_MakeUtcMilliseconds(clock.UtcNowMilliseconds(),"UTC",0,"fixture",SF01_TIME_MILLISECONDS);m.manifest_id=SF05_DeriveRunManifestId(m);return m;
}

int OnInit()
{
   CSF02Assert a;string e="";SF02_RuntimeConfig c=SF02_DefaultRuntimeConfig();c.strategy_id="sf05_self_test";c.strategy_version="1.0.0";c.run_id="sf05_self_test_run";c.generation_id=5;
   CSF02FixtureClock clock;CSF03FixtureMarketSource source;CSF03MarketDataService market;CSF03SymbolSpecCache specs;market.BindSource(&source);market.BindClock(&clock);specs.BindSource(&source);
   MqlTick tick;tick.time=(datetime)1783771260;tick.time_msc=1783771260000;tick.bid=1.1;tick.ask=1.1002;tick.last=1.1001;tick.volume=1;source.PutTick("EURUSD",tick,e);
   SF03_SymbolSpecSnapshot spec;spec.symbol="EURUSD";spec.digits=5;spec.point=0.00001;spec.tick_size=0.00001;spec.tick_value=1.0;spec.contract_size=100000;spec.volume_min=0.01;spec.volume_max=100;spec.volume_step=0.01;spec.stops_level_points=0;spec.freeze_level_points=0;spec.filling_mode=0;spec.order_mode=0;spec.trade_mode=0;spec.observed_at_utc_msc=clock.UtcNowMilliseconds();spec.specification_generation=1;source.PutSpec(spec,e);
   SF01_BarRecord bars[3];for(int i=0;i<3;i++){long t=1783771020000+(long)i*60000;bars[i].schema=SF01_BarRecordSchema();bars[i].symbol="EURUSD";bars[i].timeframe_seconds=60;bars[i].open_time=SF01_MakeUtcMilliseconds(t,"UTC",0,"fixture",SF01_TIME_MILLISECONDS);bars[i].close_time=SF01_MakeUtcMilliseconds(t+60000,"UTC",0,"fixture",SF01_TIME_MILLISECONDS);bars[i].open=1.1+i*0.0001;bars[i].high=bars[i].open+0.0003;bars[i].low=bars[i].open-0.0002;bars[i].close=bars[i].open+0.0001;bars[i].tick_volume=100;bars[i].real_volume=0;bars[i].bid_close=bars[i].close;bars[i].ask_close=bars[i].close+0.00002;bars[i].spread_points=2;bars[i].source_id="fixture";bars[i].source_bar_id=SF01_StableId("bar",IntegerToString(t));}source.PutBars("EURUSD",60,bars,e);
   a.True(market.Initialize(c,e),"market init");a.True(specs.Initialize(c,e),"spec init");a.True(market.Start(e),"market start");a.True(specs.Start(e),"spec start");
   CSF04FixturePulseFactory factory;factory.Configure("EURUSD",60,3,1);CSF04PluginRegistry registry;a.True(registry.RegisterFactory(&factory,e),"factory registered");CSF04PluginStartupValidator validator;validator.Bind(&market,&specs,&clock);CSF05GenerationCompiler compiler;compiler.Bind(&registry,&validator,&clock,&market,&specs);
   SF05_RunManifest manifest=BuildManifest(clock);a.True(SF05_ValidateRunManifest(manifest,e),"manifest valid");ISF04AnatomyPlugin *plugin=NULL;SF04_PluginDescriptor descriptor;SF04_StartupValidationReport startup;SF05_RuntimeGenerationRecord generation;SF05_CompilationReport report;a.True(compiler.Compile(manifest,plugin,descriptor,startup,generation,report,e),"generation compiled");a.True(generation.state==SF05_GENERATION_WARMED,"generation warmed");a.True(generation.generation_uid!="","generation uid");
   CSF05AppendOnlyMemorySink *sink=new CSF05AppendOnlyMemorySink();CSF05GenerationBundle *bundle=new CSF05GenerationBundle();bundle.Adopt(manifest,generation,descriptor,plugin,sink,true,true);CSF05GenerationManager manager;a.True(manager.Stage(bundle,e),"bundle staged");SF01_MarketTimestamp now=SF01_MakeUtcMilliseconds(clock.UtcNowMilliseconds(),"UTC",0,"fixture",SF01_TIME_MILLISECONDS);a.True(manager.Activate(now,e),"generation active");a.True(manager.Active()!=NULL,"active exists");SF05_RuntimeGenerationRecord active=manager.Active().Generation();a.True(active.state==SF05_GENERATION_ACTIVE,"active state");a.True(sink.Configure(manifest,active,manifest.sink_config,e),"sink configured");
   a.True(sink.Initialize(c,e),"sink init");a.True(sink.Start(e),"sink start");a.True(plugin.Initialize(c,e),"plugin init");a.True(plugin.Start(e),"plugin start");plugin.ProcessTick(tick);SF01_AnatomyEvent event;a.True(plugin.PopEvent(event),"event pop");a.True(sink.WriteEvent(event,e),"event written");a.True(sink.Count()==3,"bootstrap plus event count");SF05_ResultEnvelope env;a.True(sink.At(2,env),"event record at");a.True(env.sequence==3,"event sequence three");a.True(env.generation_uid==active.generation_uid,"generation lineage");a.True(sink.Seal(now,e),"sink sealed");a.True(!sink.WriteEvent(event,e),"sealed reject");plugin.Stop();plugin.Shutdown();market.Stop();specs.Stop();market.Shutdown();specs.Shutdown();Print("SF05 checks=",a.Passed()+a.Failed()," failed=",a.Failed());return a.Failed()==0?INIT_SUCCEEDED:INIT_FAILED;
}
