#property strict
#property version "1.00"
#include <AlphaLab\StrategyFactory\Context\SF07_AllContext.mqh>
#include <AlphaLab\StrategyFactory\Core\SF02_RuntimeConfig.mqh>
int OnInit()
{
   string e="";CSF07ContextEngine engine;CSF07FixtureFeaturePack pack;if(!pack.RegisterAll(engine.Registry(),e)){Print(e);return INIT_FAILED;}CSF07FeatureVectorSchema schema;if(!pack.BuildDefaultVectorSchema(schema,e)||!engine.ConfigureVectorSchema(schema,e)){Print(e);return INIT_FAILED;}SF02_RuntimeConfig config=SF02_DefaultRuntimeConfig();config.strategy_id="sf07_fixture";config.strategy_version="1.0.0";config.run_id="sf07_selftest";config.generation_id=7;if(!engine.Initialize(config,e)||!engine.Start(e)){Print(e);return INIT_FAILED;}
   SF01_MarketTimestamp t=SF01_MakeUtcMilliseconds(1783771260000,"UTC",0,"fixture",SF01_TIME_MILLISECONDS);SF01_AnatomyEvent event;event.schema=SF01_AnatomyEventSchema();event.event_id="";event.strategy_id="sf07_fixture";event.strategy_version="1.0.0";event.producer_id="sf06.reference.sweep_rejection";event.producer_version="1.0.0";event.symbol="EURUSD";event.reference_symbol="EURUSD";event.direction=SF01_DIRECTION_LONG;event.event_time=t;event.known_time=t;event.confirmation_time=t;event.reference_price=1.1000;event.invalidation_price=1.0990;event.timeframe_seconds=60;event.session_id="fixture";event.parent_event_id="none";event.market_event_cluster_id="cluster_fixture_007";event.source_hash="source_fixture_007";event.anatomy_state="confirmed";event.event_id=SF01_DeriveAnatomyEventId(event);
   CSF01FeatureSnapshot snapshot;if(!engine.BuildSnapshot(event,7,snapshot,e)){Print(e);return INIT_FAILED;}if(snapshot.Size()!=5){Print("unexpected feature count");return INIT_FAILED;}SF07_ContextFrame frame=engine.LastFrame();if(frame.frame_id==""||frame.vector_id==""){Print("frame missing identity");return INIT_FAILED;}CSF07FixedFeatureVector vector=engine.LastVector();if(vector.Size()!=4){Print("unexpected vector size");return INIT_FAILED;}double value;ENUM_SF01_FEATURE_QUALITY quality;string id;if(!vector.At(0,value,quality,id)||id!="event_direction"||value!=1.0){Print("vector order mismatch");return INIT_FAILED;}SF07_ContextTelemetry telemetry=engine.Telemetry();if(telemetry.build_count!=1||telemetry.feature_computations!=5){Print("telemetry mismatch");return INIT_FAILED;}Print("SF07 self-test PASS frame=",frame.frame_id," vector=",frame.vector_id," graph=",engine.Registry().GraphHash());return INIT_SUCCEEDED;
}
