#property strict
#include <AlphaLab/StrategyFactory/Governance/SF14_AllGovernance.mqh>
int OnInit()
{
 string error;SF14_ArtifactDigest digest;digest.logical_name="model";digest.relative_path="artifacts/model.bin";digest.role=SF14_ARTIFACT_MODEL;digest.media_type="application/octet-stream";digest.byte_size=128;digest.sha256="0000000000000000000000000000000000000000000000000000000000000000";digest.schema_id="";digest.required=true;digest.digest_id=SF14_DeriveArtifactDigestId(digest);if(!SF14_ValidateArtifactDigest(digest,error)){Print(error);return INIT_FAILED;}SF14_ArtifactInventory inventory;inventory.inventory_id="sf14_selftest_inventory";inventory.inventory_version="1.0.0";inventory.digest_count=1;inventory.digests[0]=digest;inventory.generated_at_utc_msc=900;inventory.inventory_hash="1111111111111111111111111111111111111111111111111111111111111111";if(!SF14_ValidateArtifactInventory(inventory,error)){Print(error);return INIT_FAILED;}SF14_AuthenticityAttestation attestation;attestation.kind=SF14_ATTESTATION_NONE;attestation.subject_inventory_hash=inventory.inventory_hash;attestation.signer_id="";attestation.algorithm="";attestation.key_id="";attestation.signature_reference="";attestation.verifier_id="";attestation.verified=false;attestation.signed_at_utc_msc=950;attestation.attestation_hash=SF14_DeriveAttestationHash(attestation);if(!SF14_ValidateAuthenticityAttestation(attestation,error)){Print(error);return INIT_FAILED;}SF14_RegistryScope scope;scope.strategy_id="reference_strategy";scope.anatomy_plugin_id="sf06.reference_sweep";scope.anatomy_plugin_version="1.0.0";scope.symbol_universe_id="major_indices";scope.timeframe_profile_id="m5_h1";scope.deployment_profile_id="research_default";scope.feature_schema_hash="feature_schema_hash";scope.label_contract_hash="label_contract_hash";scope.scope_id=SF14_DeriveScopeId(scope);if(!SF14_ValidateRegistryScope(scope,error)){Print(error);return INIT_FAILED;}
 SF14_ModelEvidenceBundle e;e.bundle_id="sf14_selftest";e.model_id="reference_logistic";e.model_version="1.0.0";e.model_artifact_hash="model_hash";e.transform_hash="transform_hash";e.calibration_hash="calibration_hash";e.feature_schema_hash=scope.feature_schema_hash;e.label_contract_hash=scope.label_contract_hash;e.dataset_hash="dataset_hash";e.training_plan_hash="training_plan_hash";e.training_report_hash="training_report_hash";e.model_card_hash="model_card_hash";e.prediction_rowset_hash="prediction_hash";e.anti_overfit_report_hash="anti_overfit_hash";e.phase12_promotion_decision_hash="phase12_decision_hash";e.code_revision="revision";e.artifact_inventory_hash="inventory_hash";e.attestation_hash="";e.created_at_utc_msc=1000;e.no_execution_authority=true;e.bundle_hash=SF14_DeriveEvidenceBundleHash(e);if(!SF14_ValidateModelEvidence(e,error)){Print(error);return INIT_FAILED;}
 SF14_PromotionPolicy p;p.policy_id="default";p.policy_version="1.0.0";p.min_test_samples=100;p.min_validation_score=0.52;p.min_test_score=0.50;p.max_generalization_gap=0.10;p.max_calibration_error=0.08;p.min_stress_pass_ratio=0.75;p.require_phase12_acceptance=true;p.require_test_oos_only=true;p.require_lineage_valid=true;p.require_inventory_valid=true;p.require_model_card_no_capital_authority=true;p.require_verified_attestation=false;p.max_challengers_per_scope=4;p.policy_hash=SF14_DerivePromotionPolicyHash(p);
 SF14_PromotionMeasurements m;m.phase12_accepted=true;m.test_oos_only=true;m.test_sample_count=240;m.validation_score=0.61;m.test_score=0.57;m.calibration_error=0.035;m.stress_pass_ratio=0.875;m.lineage_valid=true;m.inventory_valid=true;m.model_card_no_capital_authority=true;m.attestation_verified=false;SF14_PromotionEvaluation eval;if(!SF14_EvaluatePromotion(e,scope,p,m,1100,"sf14_selftest",eval,error)||eval.verdict!=SF14_VERDICT_ELIGIBLE){Print(error);return INIT_FAILED;}
 CSF14ModelRegistry registry;SF14_ModelRegistryEntry entry;if(!registry.Register(e,scope,1200,entry,error)){Print(error);return INIT_FAILED;}if(!registry.Transition(entry.entry_id,SF14_STATE_EVIDENCE_VALIDATED,SF14_DECISION_VALIDATE_EVIDENCE,"governance","EVIDENCE_VALIDATED",eval.evaluation_hash,1300,eval.evaluation_hash,error)){Print(error);return INIT_FAILED;}if(!registry.Transition(entry.entry_id,SF14_STATE_CANDIDATE,SF14_DECISION_NOMINATE,"governance","CANDIDATE_NOMINATED",eval.evaluation_hash,1400,"",error)){Print(error);return INIT_FAILED;}if(!registry.Transition(entry.entry_id,SF14_STATE_CHALLENGER,SF14_DECISION_ASSIGN_CHALLENGER,"governance","CHALLENGER_ASSIGNED",eval.evaluation_hash,1500,"",error)){Print(error);return INIT_FAILED;}if(!registry.PromoteChampion(entry.entry_id,1600,error)){Print(error);return INIT_FAILED;}if(registry.EntryCount()!=1||registry.DecisionCount()!=5||registry.ChampionIndex(scope.scope_id)<0){Print("registry invariant failure");return INIT_FAILED;}
 Print("SF14 self-test PASS chain=",registry.DecisionChainHash());return INIT_SUCCEEDED;
}
void OnTick(){}
