#ifndef ALPHALAB_QUALIFICATION_ENUMS_MQH
#define ALPHALAB_QUALIFICATION_ENUMS_MQH
enum ALQualificationStatus { AL_Q_PENDING=0, AL_Q_PASS=1, AL_Q_FAIL=2 };
enum ALReleaseStage { AL_STAGE_FROZEN=0, AL_STAGE_TESTER=1, AL_STAGE_PAPER=2, AL_STAGE_SHADOW=3, AL_STAGE_MICRO_LIVE=4, AL_STAGE_LIMITED_LIVE=5, AL_STAGE_PRODUCTION=6, AL_STAGE_ROLLED_BACK=7, AL_STAGE_BLOCKED=8 };
#endif
