from __future__ import annotations
from .canonical import stable_id,with_digest
def build_contracts(req:dict,policy:dict,auth:dict)->dict:
    owner=with_digest({'schema_version':'1.0.0','bundle_id':stable_id('OWNERAPP',req['pilot_request_id']),'pilot_request_id':req['pilot_request_id'],'approvals':req['owner_approvals'],'required_roles':policy['required_owner_roles'],'independent_approval_required':True,'self_approval_allowed':False},'owner_approval_bundle_digest')
    mapping=with_digest({'schema_version':'1.0.0','mapping_contract_id':req['data_mapping']['mapping_id'],'context_id':req['context_id'],'fields':req['data_mapping']['fields'],'event_time_field':req['data_mapping']['event_time_field'],'availability_time_field':req['data_mapping']['availability_time_field'],'label_availability_field':req['data_mapping']['label_availability_field'],'timezone':req['data_mapping']['timezone'],'mapping_complete':req['data_mapping']['mapping_complete']},'data_mapping_contract_digest')
    avail=with_digest({'schema_version':'1.0.0','availability_contract_id':req['availability_semantics']['contract_id'],'context_id':req['context_id'],'known_time_enforced':req['availability_semantics']['known_time_enforced'],'future_data_allowed':False,'rules':req['availability_semantics']['rules'],'externally_verified':req['availability_semantics']['externally_verified']},'availability_contract_digest')
    freeze=with_digest({'schema_version':'1.0.0','evaluation_freeze_id':stable_id('EVALFREEZE',req['pilot_request_id']),'pilot_request_id':req['pilot_request_id'],'primary_outcome':req['evaluation_rules']['primary_outcome'],'secondary_outcomes':req['evaluation_rules']['secondary_outcomes'],'metrics':req['evaluation_rules']['metrics'],'evaluation_windows':req['evaluation_rules']['evaluation_windows'],'frozen':True,'post_outcome_change_allowed':False,'frozen_at':req['pilot_period']['precommitted_at']},'evaluation_freeze_digest')
    search=with_digest({'schema_version':'1.0.0','search_space_freeze_id':stable_id('SEARCHFREEZE',req['pilot_request_id']),'pilot_request_id':req['pilot_request_id'],'families':req['setup_search_space']['families'],'family_count':len(req['setup_search_space']['families']),'frozen':True,'dynamic_generation_allowed':False,'ai_generation_allowed':False,'broadening_after_outcome_allowed':False},'search_space_freeze_digest')
    support=with_digest({'schema_version':'1.0.0','support_contract_id':stable_id('SUPPORT',req['pilot_request_id']),'minimum_occurrences':req['support_targets']['minimum_occurrences'],'minimum_mature_outcomes':req['support_targets']['minimum_mature_outcomes'],'minimum_distinct_days':req['support_targets']['minimum_distinct_days'],'minimum_state_support':req['support_targets']['minimum_state_support'],'target_is_validation_claim':False},'support_contract_digest')
    stop=with_digest({'schema_version':'1.0.0','stop_contract_id':stable_id('STOP',req['pilot_request_id']),'conditions':req['stop_conditions'],'automatic_order_action_allowed':False,'terminal_on_breach':True},'stop_contract_digest')
    failure=with_digest({'schema_version':'1.0.0','failure_contract_id':stable_id('FAIL',req['pilot_request_id']),'conditions':req['failure_conditions'],'failure_preservation_required':True,'post_hoc_repair_allowed':False},'failure_contract_digest')
    boundary=with_digest({'schema_version':'1.0.0','boundary_contract_id':stable_id('NONCAP',req['pilot_request_id']),'pilot_mode':'NO_SEND_PROSPECTIVE_OBSERVATION','order_submission_allowed':False,'broker_connection_allowed':False,'runtime_activation_allowed':False,'capital_allocation_allowed':False,'manual_trade_instruction_allowed':False,'external_signal_distribution_allowed':False},'non_capital_boundary_digest')
    contract=with_digest({'schema_version':'1.0.0','pilot_contract_id':stable_id('PILOT',req['pilot_request_id'],req['context_id'],req['context_version'],length=32),'pilot_request_id':req['pilot_request_id'],'context_id':req['context_id'],'context_version':req['context_version'],'context_title':req['context_title'],'doctrine_summary':req['doctrine_summary'],'evidence_classification':req['evidence_classification'],'real_context_evidence_present':req['real_context_evidence_present'],'pilot_period':req['pilot_period'],'owner_approval_bundle_digest':owner['owner_approval_bundle_digest'],'data_mapping_contract_digest':mapping['data_mapping_contract_digest'],'availability_contract_digest':avail['availability_contract_digest'],'evaluation_freeze_digest':freeze['evaluation_freeze_digest'],'search_space_freeze_digest':search['search_space_freeze_digest'],'support_contract_digest':support['support_contract_digest'],'stop_contract_digest':stop['stop_contract_digest'],'failure_contract_digest':failure['failure_contract_digest'],'non_capital_boundary_digest':boundary['non_capital_boundary_digest'],'authority_report_digest':auth['authority_report_digest'],'pilot_execution_allowed':False,'runtime_generation_allowed':False,'live_order_submission_allowed':False,'capital_activation_allowed':False},'pilot_contract_digest')
    return {'owner':owner,'mapping':mapping,'availability':avail,'evaluation':freeze,'search':search,'support':support,'stop':stop,'failure':failure,'boundary':boundary,'contract':contract}
