from tools.repository_paths import find_repository_root
from pathlib import Path
BASE=find_repository_root(__file__)
REGISTRY_ROOT=BASE/'registry/history/acl/acl_14'
SCHEMA_ROOT=REGISTRY_ROOT/'schemas/v1'
POLICY_ROOT=REGISTRY_ROOT/'policies/v1'
HANDOFF_IN='ACL13_TO_ACL14'
HANDOFF_OUT='ACL14_TO_ACL15'
REQUIRED_UPSTREAM_ACTIONS={'VERIFY_ONE_HOUR_ASSESSMENT_PACKAGE','AUTHOR_FIRST_REAL_CONTEXT_PILOT_CONTRACT','ISSUE_NON_CAPITAL_PILOT_READINESS_DECISION'}
FORBIDDEN_UPSTREAM_ACTIONS={'TREAT_TRIAGE_AS_VALIDATION','INVENT_PROSPECTIVE_EVIDENCE','REUSE_SYNTHETIC_DATA_AS_REAL_CONTEXT','AUTHORIZE_RUNTIME_OR_LIVE_ORDER','ACTIVATE_CAPITAL'}
REQUIRED_ACTION='ACL14_AUTHOR_AND_ASSESS_FIRST_REAL_CONTEXT_PILOT'
CLAIM_CEILING='FIRST_REAL_CONTEXT_PILOT_REFERENCE_ONLY'
SERVICE_VERSION='1.0.0'
READINESS_STATES={'INPUT_REJECTED','PILOT_CONTRACT_AUTHORED_REAL_EVIDENCE_REQUIRED','PILOT_READY_NON_CAPITAL_NOT_EXECUTED','PILOT_BLOCKED_POLICY_OR_INTEGRITY'}
GATE_STATUSES={'SATISFIED','UNSATISFIED','UNKNOWN','NOT_APPLICABLE'}
GATE_IDS=[
'ACL13_PACKAGE_INTEGRITY','ACL13_PILOT_DESIGN_ELIGIBLE','REAL_CONTEXT_IDENTITY','INDEPENDENT_OWNER_APPROVAL','DOCTRINE_APPROVAL','REAL_DATA_SOURCE_APPROVAL','DATA_MAPPING_COMPLETE','AVAILABILITY_SEMANTICS_COMPLETE','KNOWN_TIME_GUARD','PILOT_PERIOD_PRECOMMITTED','EVALUATION_RULES_FROZEN','SETUP_SEARCH_SPACE_FROZEN','SUPPORT_TARGETS_PRECOMMITTED','STOP_CONDITIONS_FROZEN','FAILURE_CONDITIONS_FROZEN','NON_CAPITAL_BOUNDARY','SYNTHETIC_REUSE_DENIED','PROSPECTIVE_EVIDENCE_NOT_INVENTED','SECURITY_STATUS_PRESERVED','RUNTIME_AUTHORITY_DENIED','LIVE_ORDER_AUTHORITY_DENIED','CAPITAL_AUTHORITY_DENIED','OPERATOR_SEPARATION','AUDIT_AND_PROVENANCE']
SECTION_IDS=['IDENTITY_AND_SCOPE','UPSTREAM_TRIAGE','REAL_CONTEXT_EVIDENCE','OWNER_AND_DOCTRINE','DATA_MAPPING','KNOWN_TIME_AND_AVAILABILITY','PILOT_PERIOD','EVALUATION_FREEZE','SEARCH_SPACE_FREEZE','SUPPORT_AND_STOP_RULES','READINESS_MATRIX','NON_CAPITAL_BOUNDARY','LIMITATIONS','NEXT_ALLOWED_ACTIONS']
