#ifndef ALPHALAB_OPERATIONS_ENUMS_MQH
#define ALPHALAB_OPERATIONS_ENUMS_MQH
enum ALOperationsStage { AL_OPS_FROZEN=0, AL_OPS_PAPER=1, AL_OPS_SHADOW=2, AL_OPS_MICRO_LIVE=3, AL_OPS_LIMITED_LIVE=4, AL_OPS_PRODUCTION=5, AL_OPS_SAFE_HALT=6, AL_OPS_ROLLED_BACK=7, AL_OPS_RETIRED=8 };
enum ALOperationsStatus { AL_OPS_PASS=0, AL_OPS_DEGRADED=1, AL_OPS_FAIL=2, AL_OPS_PENDING=3 };
enum ALOperationsDecision { AL_OPS_BLOCK=0, AL_OPS_HOLD=1, AL_OPS_ALLOW_NO_SEND=2, AL_OPS_ALLOW_BOUNDED=3, AL_OPS_DERISK=4, AL_OPS_HALT=5, AL_OPS_ROLLBACK=6, AL_OPS_RETIRE=7 };
#endif
