#ifndef ALPHALAB_OPERATIONS_CATALOG_MQH
#define ALPHALAB_OPERATIONS_CATALOG_MQH
#define AL_OPERATIONS_SCHEMA_VERSION "1.0.0"
#define AL_OPERATIONS_ORDER_AUTHORITY false
#define AL_OPERATIONS_BROKER_AUTHORITY false
#define AL_OPERATIONS_NETWORK_AUTHORITY false
#define AL_OPERATIONS_REFERENCE_ACTIVATION false
#define AL_OPERATIONS_DEFAULT_MAX_RISK 0.0
#endif
