from enum import Enum
class StrEnum(str, Enum):
    def __str__(self): return self.value
class HostTimeframe(StrEnum):
    M1="M1"; M2="M2"; M3="M3"; M4="M4"; M5="M5"; M6="M6"; M10="M10"; M12="M12"; M15="M15"; M20="M20"; M30="M30"; H1="H1"; H2="H2"; H3="H3"; H4="H4"; H6="H6"; H8="H8"; H12="H12"; D1="D1"
class ClosePairState(StrEnum):
    HUNTER_ONLY="HUNTER_ONLY"; PROTECTED_ONLY="PROTECTED_ONLY"; BOTH="BOTH"; NONE="NONE"; DATA_INCOMPLETE="DATA_INCOMPLETE"
class ConfirmationState(StrEnum):
    PENDING="PENDING"; CONFIRMED="CONFIRMED"; CANCELLED_SECOND_TOUCH="CANCELLED_SECOND_TOUCH"; CANCELLED_ROLE_CHANGED="CANCELLED_ROLE_CHANGED"; NO_SIGNAL_AT_CLOSE="NO_SIGNAL_AT_CLOSE"; INVALID_DATA="INVALID_DATA"; EXPIRED_DEADLINE="EXPIRED_DEADLINE"; MISSED_CLOSE_REPLAY_REQUIRED="MISSED_CLOSE_REPLAY_REQUIRED"; SUPERSEDED="SUPERSEDED"
class ConfirmationOutcome(StrEnum):
    CONFIRMED="CONFIRMED"; INVALIDATED_DOUBLE_HUNT="INVALIDATED_DOUBLE_HUNT"; INVALIDATED_ROLE_CHANGED="INVALIDATED_ROLE_CHANGED"; NO_SIGNAL_AT_CLOSE="NO_SIGNAL_AT_CLOSE"; UNAVAILABLE_AT_CLOSE="UNAVAILABLE_AT_CLOSE"; CONFIRMATION_DEADLINE_MISSED="CONFIRMATION_DEADLINE_MISSED"; MISSED_CLOSE_REPLAY_REQUIRED="MISSED_CLOSE_REPLAY_REQUIRED"
class ConfirmationTransition(StrEnum):
    ADMITTED="ADMITTED"; CONFIRMED="CONFIRMED"; SECOND_TOUCH_CANCELLED="SECOND_TOUCH_CANCELLED"; ROLE_CHANGED_CANCELLED="ROLE_CHANGED_CANCELLED"; NO_SIGNAL_FINALIZED="NO_SIGNAL_FINALIZED"; DATA_INVALIDATED="DATA_INVALIDATED"; DEADLINE_EXPIRED="DEADLINE_EXPIRED"; MISSED_CLOSE_BLOCKED="MISSED_CLOSE_BLOCKED"; SUPERSEDED="SUPERSEDED"
class EngineHealth(StrEnum):
    READY="READY"; DEGRADED="DEGRADED"; BLOCKED="BLOCKED"
class RevisionDisposition(StrEnum):
    UNAFFECTED="UNAFFECTED"; PENDING_INVALIDATED="PENDING_INVALIDATED"; CONFIRMED_PRESERVED="CONFIRMED_PRESERVED"
