#ifndef __DAL_STC_ENUMS_MQH__
#define __DAL_STC_ENUMS_MQH__
#property strict

enum STC_RuntimeMode
{
   STC_MODE_RESEARCH_BACKTEST = 0,
   STC_MODE_PAPER_LIVE        = 1,
   STC_MODE_AUTO_TRADE        = 2
};

enum STC_CandleCheckTf
{
   STC_CHECK_M1  = 1,
   STC_CHECK_M3  = 3,
   STC_CHECK_M5  = 5,
   STC_CHECK_M10 = 10,
   STC_CHECK_M15 = 15,
   STC_CHECK_M30 = 30
};

enum STC_Direction
{
   STC_DIR_NONE = 0,
   STC_DIR_BUY  = 1,
   STC_DIR_SELL = 2
};

enum STC_Side
{
   STC_SIDE_NONE = 0,
   STC_SIDE_HIGH = 1,
   STC_SIDE_LOW  = 2
};

enum STC_InitStatus
{
   STC_INIT_OK = 0,
   STC_INIT_CONFIG_ERROR = 1,
   STC_INIT_SYMBOL_ERROR = 2,
   STC_INIT_FOLDER_ERROR = 3,
   STC_INIT_INSTANCE_LOCK_ERROR = 4
};

enum STC_MCycle
{
   STC_M_NONE = 0,
   STC_M1     = 1,
   STC_M2     = 2,
   STC_M3     = 3
};

enum STC_WCycle
{
   STC_W_NONE = 0,
   STC_W1     = 1,
   STC_W2     = 2,
   STC_W3     = 3,
   STC_W4     = 4
};

enum STC_TimePhase
{
   STC_PHASE_PRE_DAY_OR_POST_CLOSE = 0,
   STC_PHASE_ACTIVE_M              = 1,
   STC_PHASE_M_GAP                 = 2,
   STC_PHASE_HARD_CLOSE_ZONE       = 3
};

enum STC_HuntPattern
{
   STC_HUNT_NONE         = 0,
   STC_HUNT_SYMBOL1_ONLY = 1,
   STC_HUNT_SYMBOL2_ONLY = 2,
   STC_HUNT_BOTH         = 3
};

enum STC_CandidateStatus
{
   STC_CANDIDATE_NONE = 0,
   STC_CANDIDATE_VALID_AUDIT_ONLY = 1,
   STC_CANDIDATE_FORGOTTEN_SIMULTANEOUS_BUY_SELL = 2,
   STC_CANDIDATE_REJECTED_NO_REFERENCE = 3,
   STC_CANDIDATE_REJECTED_INCOMPLETE_DATA = 4,
   STC_CANDIDATE_REJECTED_NOT_DETECTION_ELIGIBLE = 5,
   STC_CANDIDATE_REJECTED_NO_EXACTLY_ONE_HUNT = 6,
   STC_CANDIDATE_REJECTED_INVALID_STOP_DISTANCE = 7
};




enum STC_PaperEntryStatus
{
   STC_PAPER_NONE = 0,
   STC_PAPER_PLANNED = 1,
   STC_PAPER_REJECTED_SIGNAL_NOT_CONFIRMED = 2,
   STC_PAPER_REJECTED_ENTRY_OFF = 3,
   STC_PAPER_REJECTED_MISSED_OR_LATE = 4,
   STC_PAPER_REJECTED_NEXT_CHECK_UNAVAILABLE = 5,
   STC_PAPER_REJECTED_NEXT_CHECK_INCOMPLETE = 6,
   STC_PAPER_REJECTED_INVALID_RISK_DISTANCE = 7,
   STC_PAPER_REJECTED_MAX_TRADES_PER_M = 8,
   STC_PAPER_REJECTED_DIRECTION_LOCK = 9,
   STC_PAPER_REJECTED_BROKER_MIN_VOLUME = 10,
   STC_PAPER_PLANNED_SPLIT_REQUIRED = 11
};



enum STC_PaperOutcomeStatus
{
   STC_OUTCOME_NONE = 0,
   STC_OUTCOME_NO_PAPER_ENTRY = 1,
   STC_OUTCOME_OPEN_UNRESOLVED = 2,
   STC_OUTCOME_TP_HIT = 3,
   STC_OUTCOME_SL_HIT = 4,
   STC_OUTCOME_AMBIGUOUS_SL_TP_SAME_CHECK = 5,
   STC_OUTCOME_REJECTED_DATA_INCOMPLETE = 6,
   STC_OUTCOME_REJECTED_ENTRY_NOT_PLANNED = 7
};

enum STC_SignalStatus
{
   STC_SIGNAL_NONE = 0,
   STC_SIGNAL_CONFIRMED_AUDIT_ONLY = 1,
   STC_SIGNAL_CONFIRMED_ENTRY_OFF_CONSUMED = 2,
   STC_SIGNAL_FORGOTTEN_SIMULTANEOUS_BUY_SELL = 3,
   STC_SIGNAL_REJECTED_NO_CANDIDATE = 4,
   STC_SIGNAL_REJECTED_NOT_ENTRY_ELIGIBLE = 5,
   STC_SIGNAL_REJECTED_FINAL_CHECK_NO_ENTRY = 6,
   STC_SIGNAL_REJECTED_INCOMPLETE_DATA = 7,
   STC_SIGNAL_REJECTED_INVALID_STOP_DISTANCE = 8,
   STC_SIGNAL_REJECTED_ORDER_NOT_ATTEMPTED_LEVEL08 = 9
};

string STC_RuntimeModeText(const STC_RuntimeMode mode)
{
   if(mode == STC_MODE_RESEARCH_BACKTEST) return "RESEARCH_BACKTEST";
   if(mode == STC_MODE_PAPER_LIVE)        return "PAPER_LIVE";
   if(mode == STC_MODE_AUTO_TRADE)        return "AUTO_TRADE";
   return "UNKNOWN";
}

string STC_CheckTfText(const STC_CandleCheckTf tf)
{
   if(tf == STC_CHECK_M1)  return "M1";
   if(tf == STC_CHECK_M3)  return "M3";
   if(tf == STC_CHECK_M5)  return "M5";
   if(tf == STC_CHECK_M10) return "M10";
   if(tf == STC_CHECK_M15) return "M15";
   if(tf == STC_CHECK_M30) return "M30";
   return "UNKNOWN";
}

string STC_DirectionText(const STC_Direction direction)
{
   if(direction == STC_DIR_BUY)  return "BUY";
   if(direction == STC_DIR_SELL) return "SELL";
   return "NONE";
}

string STC_SideText(const STC_Side side)
{
   if(side == STC_SIDE_HIGH) return "HIGH";
   if(side == STC_SIDE_LOW)  return "LOW";
   return "NONE";
}

string STC_MCycleText(const STC_MCycle cycle)
{
   if(cycle == STC_M1) return "M1";
   if(cycle == STC_M2) return "M2";
   if(cycle == STC_M3) return "M3";
   return "NONE";
}

string STC_WCycleText(const STC_WCycle cycle)
{
   if(cycle == STC_W1) return "W1";
   if(cycle == STC_W2) return "W2";
   if(cycle == STC_W3) return "W3";
   if(cycle == STC_W4) return "W4";
   return "NONE";
}

string STC_TimePhaseText(const STC_TimePhase phase)
{
   if(phase == STC_PHASE_ACTIVE_M) return "ACTIVE_M";
   if(phase == STC_PHASE_M_GAP) return "M_GAP_NO_ENTRY_NO_DETECTION";
   if(phase == STC_PHASE_HARD_CLOSE_ZONE) return "HARD_CLOSE_ZONE";
   return "PRE_DAY_OR_POST_CLOSE";
}

string STC_HuntPatternText(const STC_HuntPattern pattern)
{
   if(pattern == STC_HUNT_SYMBOL1_ONLY) return "SYMBOL1_ONLY";
   if(pattern == STC_HUNT_SYMBOL2_ONLY) return "SYMBOL2_ONLY";
   if(pattern == STC_HUNT_BOTH)         return "BOTH";
   return "NONE";
}


string STC_CandidateStatusText(const STC_CandidateStatus status)
{
   if(status == STC_CANDIDATE_VALID_AUDIT_ONLY) return "VALID_AUDIT_ONLY";
   if(status == STC_CANDIDATE_FORGOTTEN_SIMULTANEOUS_BUY_SELL) return "FORGOTTEN_SIMULTANEOUS_BUY_SELL";
   if(status == STC_CANDIDATE_REJECTED_NO_REFERENCE) return "REJECTED_NO_REFERENCE";
   if(status == STC_CANDIDATE_REJECTED_INCOMPLETE_DATA) return "REJECTED_INCOMPLETE_DATA";
   if(status == STC_CANDIDATE_REJECTED_NOT_DETECTION_ELIGIBLE) return "REJECTED_NOT_DETECTION_ELIGIBLE";
   if(status == STC_CANDIDATE_REJECTED_NO_EXACTLY_ONE_HUNT) return "REJECTED_NO_EXACTLY_ONE_HUNT";
   if(status == STC_CANDIDATE_REJECTED_INVALID_STOP_DISTANCE) return "REJECTED_INVALID_STOP_DISTANCE";
   return "NONE";
}


string STC_SignalStatusText(const STC_SignalStatus status)
{
   if(status == STC_SIGNAL_CONFIRMED_AUDIT_ONLY) return "CONFIRMED_AUDIT_ONLY";
   if(status == STC_SIGNAL_CONFIRMED_ENTRY_OFF_CONSUMED) return "CONFIRMED_ENTRY_OFF_CONSUMED";
   if(status == STC_SIGNAL_FORGOTTEN_SIMULTANEOUS_BUY_SELL) return "FORGOTTEN_SIMULTANEOUS_BUY_SELL";
   if(status == STC_SIGNAL_REJECTED_NO_CANDIDATE) return "REJECTED_NO_CANDIDATE";
   if(status == STC_SIGNAL_REJECTED_NOT_ENTRY_ELIGIBLE) return "REJECTED_NOT_ENTRY_ELIGIBLE";
   if(status == STC_SIGNAL_REJECTED_FINAL_CHECK_NO_ENTRY) return "REJECTED_FINAL_CHECK_NO_ENTRY";
   if(status == STC_SIGNAL_REJECTED_INCOMPLETE_DATA) return "REJECTED_INCOMPLETE_DATA";
   if(status == STC_SIGNAL_REJECTED_INVALID_STOP_DISTANCE) return "REJECTED_INVALID_STOP_DISTANCE";
   if(status == STC_SIGNAL_REJECTED_ORDER_NOT_ATTEMPTED_LEVEL08) return "REJECTED_ORDER_NOT_ATTEMPTED_LEVEL08";
   return "NONE";
}


string STC_PaperEntryStatusText(const STC_PaperEntryStatus status)
{
   if(status == STC_PAPER_PLANNED) return "PLANNED";
   if(status == STC_PAPER_REJECTED_SIGNAL_NOT_CONFIRMED) return "REJECTED_SIGNAL_NOT_CONFIRMED";
   if(status == STC_PAPER_REJECTED_ENTRY_OFF) return "REJECTED_ENTRY_OFF";
   if(status == STC_PAPER_REJECTED_MISSED_OR_LATE) return "REJECTED_MISSED_OR_LATE";
   if(status == STC_PAPER_REJECTED_NEXT_CHECK_UNAVAILABLE) return "REJECTED_NEXT_CHECK_UNAVAILABLE";
   if(status == STC_PAPER_REJECTED_NEXT_CHECK_INCOMPLETE) return "REJECTED_NEXT_CHECK_INCOMPLETE";
   if(status == STC_PAPER_REJECTED_INVALID_RISK_DISTANCE) return "REJECTED_INVALID_RISK_DISTANCE";
   if(status == STC_PAPER_REJECTED_MAX_TRADES_PER_M) return "REJECTED_MAX_TRADES_PER_M";
   if(status == STC_PAPER_REJECTED_DIRECTION_LOCK) return "REJECTED_DIRECTION_LOCK";
   if(status == STC_PAPER_REJECTED_BROKER_MIN_VOLUME) return "REJECTED_BROKER_MIN_VOLUME";
   if(status == STC_PAPER_PLANNED_SPLIT_REQUIRED) return "PLANNED_SPLIT_REQUIRED";
   return "NONE";
}


string STC_PaperOutcomeStatusText(const STC_PaperOutcomeStatus status)
{
   if(status == STC_OUTCOME_NO_PAPER_ENTRY) return "NO_PAPER_ENTRY";
   if(status == STC_OUTCOME_OPEN_UNRESOLVED) return "OPEN_UNRESOLVED";
   if(status == STC_OUTCOME_TP_HIT) return "TP_HIT";
   if(status == STC_OUTCOME_SL_HIT) return "SL_HIT";
   if(status == STC_OUTCOME_AMBIGUOUS_SL_TP_SAME_CHECK) return "AMBIGUOUS_SL_TP_SAME_CHECK";
   if(status == STC_OUTCOME_REJECTED_DATA_INCOMPLETE) return "REJECTED_DATA_INCOMPLETE";
   if(status == STC_OUTCOME_REJECTED_ENTRY_NOT_PLANNED) return "REJECTED_ENTRY_NOT_PLANNED";
   return "NONE";
}

#endif
