#ifndef __SF20_EXP0017_ENUMS_MQH__
#define __SF20_EXP0017_ENUMS_MQH__
enum ENUM_SF20_INTEGRATION_MODE{SF20_MODE_AUDIT_ONLY=0,SF20_MODE_PILOT_SHADOW=1};
enum ENUM_SF20_STAGE_STATUS{SF20_STAGE_NOT_RUN=0,SF20_STAGE_PASSED=1,SF20_STAGE_GATED=2,SF20_STAGE_FAILED=3};
enum ENUM_SF20_LIFECYCLE_STATE{SF20_LIFECYCLE_FIRST_SEEN=0,SF20_LIFECYCLE_ACTIVE=1,SF20_LIFECYCLE_RETIRED=2};
enum ENUM_SF20_DIFFERENTIAL_STATUS{SF20_DIFF_MATCH=0,SF20_DIFF_MISSING_CANONICAL=1,SF20_DIFF_EXTRA_CANONICAL=2,SF20_DIFF_FIELD_MISMATCH=3};
string SF20_StageStatusText(const ENUM_SF20_STAGE_STATUS v){if(v==SF20_STAGE_PASSED)return "PASSED";if(v==SF20_STAGE_GATED)return "GATED";if(v==SF20_STAGE_FAILED)return "FAILED";return "NOT_RUN";}
#endif
