#ifndef __FP_I10_REGISTRY_MQH__
#define __FP_I10_REGISTRY_MQH__
#define FP_I10_PHASE_VERSION "1.0.0"
#define FP_I10_COMPOSITION_VERSION "1.0.0"
#define FP_I10_OUTPUT_VERSION "1.0.0"
#define FP_I10_RUNTIME_AUTHORITY "NONE"
#define FP_I10_BUFFER_COUNT 12
#endif
