from __future__ import annotations
PHASE_ID='LCM-11B'
MASTER_PHASE='LCM-11'
CLAIM_CEILING='LCM_11B_REFERENCE_ONLY'
SCHEMA_VERSION='1.0.0'
PRODUCER='tools.strategy_factory.lcm.lcm_11b.service:LCM11BVisualizerService'
OWNER='ALPHA_LAB_MIGRATION_OWNER'
REVIEWER='INDEPENDENT_MIGRATION_REVIEWER'
GENERATED_TIME_SEMANTICS='DETERMINISTIC_FROM_BOUND_INPUTS_NO_WALL_CLOCK_IDENTITY'
CANONICAL_NAMESPACE_VERSION="ALV1"
VISUALIZER_VERSION="ALVIZ1"
FORBIDDEN_AUTHORITY_TOKENS=("Order"+"Send(","Order"+"SendAsync(","C"+"Trade","trade."+"Buy(","trade."+"Sell(")
ISOLATION_SCENARIOS=("SAME_CHART_DIFFERENT_INSTANCE","SAME_SYMBOL_DIFFERENT_TIMEFRAME","DIFFERENT_CHART_SAME_INSTANCE","DIFFERENT_SYMBOL_EXPLICIT_CHART")
LIFECYCLE_SCENARIOS=("COLD_START_BACKFILL","INCREMENTAL_UPDATE","PROCESS_RESTART_REHYDRATE","CHART_CHANGE_RECONCILE","OWNED_CLEANUP","SECOND_RESTART_IDEMPOTENCY")
