#ifndef ALPHALAB_UCEI07_CONTRACTS_MQH
#define ALPHALAB_UCEI07_CONTRACTS_MQH
#include "UCEI07_Enums.mqh"
struct UCEI07_TrainerCapability{string trainer_id;string trainer_version;string family;string supported_tasks;string supported_views;string supported_target_shapes;string supported_tensors;string missingness_support;string calibration_kinds;string explainability_kinds;string export_formats;string devices;string precisions;int determinism;bool sample_weight;bool multi_output;bool warm_start;bool checkpoint;bool cancel;long min_rows;long max_features;long max_outputs;string descriptor_hash;};
struct UCEI07_TaskContract{string task_id;string task_version;int task_kind;int view_kind;string target_shape;string prediction_kind;string primary_metric;bool maximize_metric;string output_names;bool sample_weight_required;bool calibration_required;bool threshold_required;bool ranking_group_required;bool treatment_set_required;string contract_hash;};
struct UCEI07_DatasetSchema{string dataset_id;string dataset_manifest_hash;string feature_order;int view_kind;string tensor_kind;string target_shape;long row_count;long feature_count;long output_count;bool has_missing;bool has_weights;bool has_censoring;string schema_hash;};
struct UCEI07_TrainerConfig{string trainer_id;string trainer_version;string hyperparameters_json;long seed;string calibration_kind;string threshold_metric;string threshold_grid;string config_hash;};
struct UCEI07_ResourceBudget{long seed;long max_rows;long max_features;long max_outputs;long max_memory_mb;long max_wall_ms;int max_workers;string device;string precision;bool deterministic_required;long checkpoint_interval_ms;double numeric_tolerance;string budget_hash;};
struct UCEI07_PredictionLineage{string dataset_id;string dataset_manifest_hash;string task_key;string trainer_key;string trainer_config_hash;string fold_id;long seed;string model_state_hash;int role;string orchestration_phase;};
struct UCEI07_TrialLedgerEntry{string trial_id;string plan_hash;string trainer_key;string fold_id;int status;long started_sequence;long finished_sequence;long elapsed_ms;string metrics_json;string model_state_hash;string prediction_batch_hash;string error_code;string error_message;string checkpoint_hash;};
struct UCEI07_AccessAuditRecord{long sequence;string row_ids_hash;int role;int purpose;string phase;string trainer_key;bool allowed;string reason;};
struct UCEI07_ModelStateBundle{string trainer_key;string state_format;string state_payload;string state_hash;string feature_order;string output_names;};
struct UCEI07_ArtifactManifest{string artifact_id;string artifact_version;string trainer_descriptor_hash;string trainer_config_hash;string task_contract_hash;string dataset_manifest_hash;string oof_protocol_hash;string resource_budget_hash;string feature_order;string output_names;string state_hash;string calibration_hash;string threshold_hash;string environment_hash;string code_hash;string metrics_json;string limitations;string export_formats;string risk_level;string manifest_hash;};
struct UCEI07_TelemetryEvent{long sequence;string phase;string trainer_key;string fold_id;string event_code;string severity;long elapsed_ms;long row_count;long feature_count;double memory_estimate_mb;string details_json;};
#endif
