#ifndef __FP_I11_PROJECTION_MQH__
#define __FP_I11_PROJECTION_MQH__
#include "FP_I11_ObjectManager.mqh"
#include "FP_I11_StyleRegistry.mqh"
#include "FP_I11_ResponsiveLayout.mqh"
class FP_I11_Projection {
private:
 static void Base(SFP_I11_ObjectSpec &s,string ns,string semantic,ENUM_FP_I11_OBJECT_KIND kind,int layer,string semantic_hash){s.semantic_id=semantic;s.kind=kind;s.layer=layer;s.state=FP_I11_VISIBLE;s.semantic_hash=semantic_hash;s.object_id=FP_I11_ObjectId(ns,kind,semantic);s.text="";s.tooltip="";s.reason_code="";s.corner=0;s.x=0;s.y=0;s.immutable=false;}
public:
 static SFP_I11_ObjectSpec Window(string ns,const SFP_I11_WindowFact &f){SFP_I11_ObjectSpec s;ENUM_FP_I11_OBJECT_KIND k=f.kind=="W"?FP_I11_WEEK_BOX:FP_I11_SESSION_BOX;Base(s,ns,f.window_id,k,f.kind=="W"?10:20,f.semantic_hash);s.time1=f.start_time;s.time2=f.end_time;s.price1=f.high_price;s.price2=f.low_price;s.text=f.kind;s.tooltip=f.kind+" "+f.state;s.style=FP_I11_StyleRegistry::Session(f.kind);s.immutable=f.state=="COMPLETE";return s;}
 static SFP_I11_ObjectSpec ReferenceLine(string ns,const SFP_I11_ReferenceFact &f){SFP_I11_ObjectSpec s;Base(s,ns,f.reference_id,FP_I11_REFERENCE_LINE,30,f.semantic_hash);s.time1=f.start_time;s.time2=f.end_time;s.price1=f.price;s.price2=f.price;s.tooltip=f.symbol+" "+f.side;s.style=FP_I11_StyleRegistry::Reference(f.side);s.immutable=(f.state=="CONSUMED"||f.state=="EXPIRED");return s;}
 static SFP_I11_ObjectSpec ReferenceLabel(string ns,const SFP_I11_ReferenceFact &f){SFP_I11_ObjectSpec s;Base(s,ns,f.reference_id+"-LBL",FP_I11_REFERENCE_LABEL,30,f.semantic_hash);s.time1=f.end_time;s.price1=f.price;s.text=f.symbol+" "+f.side;s.tooltip=s.text;s.style=FP_I11_StyleRegistry::Reference(f.side);s.immutable=(f.state=="CONSUMED"||f.state=="EXPIRED");return s;}
 static SFP_I11_ObjectSpec Hunt(string ns,const SFP_I11_HuntFact &f,long chart_id,int lane_count){SFP_I11_ObjectSpec s;Base(s,ns,f.hunt_id,FP_I11_HUNT_MARKER,40,f.semantic_hash);int lane=FP_I11_ResponsiveLayout::StableLane(f.hunt_id,lane_count)+1;s.time1=f.hunt_time;s.price1=FP_I11_ResponsiveLayout::LanePrice(chart_id,f.symbol,f.price,lane,f.side=="HIGH");s.text="H";s.tooltip=f.role+" "+f.symbol+" "+f.side;s.style=FP_I11_StyleRegistry::Hunt();s.immutable=true;return s;}
 static SFP_I11_ObjectSpec Role(string ns,const SFP_I11_HuntFact &f,long chart_id,int lane_count){SFP_I11_ObjectSpec s=Hunt(ns,f,chart_id,lane_count);s.semantic_id=f.hunt_id+"-ROLE";s.kind=FP_I11_ROLE_BADGE;s.object_id=FP_I11_ObjectId(ns,s.kind,s.semantic_id);s.text=StringSubstr(f.role,0,1);return s;}
 static SFP_I11_ObjectSpec Signal(string ns,const SFP_I11_SignalFact &f,long chart_id,int lane_count){SFP_I11_ObjectSpec s;ENUM_FP_I11_OBJECT_KIND k=f.state=="CONFIRMED"?FP_I11_CONFIRMED_SIGNAL:(f.state=="INVALIDATED"?FP_I11_INVALIDATION_MARKER:FP_I11_CANDIDATE_SIGNAL);Base(s,ns,f.signal_id,k,50,f.semantic_hash);int lane=FP_I11_ResponsiveLayout::StableLane(f.signal_id,lane_count)+1;s.time1=f.first_hunt_time;s.time2=(f.confirmation_time>f.first_hunt_time?f.confirmation_time:f.first_hunt_time+60);s.price1=f.hunter_price;s.price2=FP_I11_ResponsiveLayout::LanePrice(chart_id,f.protected_symbol,f.protected_price,lane,f.direction=="BEARISH");s.text=f.relation+" "+StringSubstr(f.direction,0,1);s.tooltip=EnumToString(f.disposition)+" "+f.hunter_symbol+"->"+f.protected_symbol;s.style=FP_I11_StyleRegistry::Signal(f.direction,f.state,f.disposition);s.immutable=(f.state=="CONFIRMED"||f.state=="INVALIDATED");s.reason_code=f.reason_code;return s;}
 static SFP_I11_ObjectSpec Suppression(string ns,const SFP_I11_SignalFact &f,long chart_id,int lane_count){SFP_I11_ObjectSpec s=Signal(ns,f,chart_id,lane_count);s.semantic_id=f.signal_id+"-SUP";s.kind=FP_I11_SUPPRESSION_OVERLAY;s.object_id=FP_I11_ObjectId(ns,s.kind,s.semantic_id);s.time1=(f.confirmation_time>f.first_hunt_time?f.confirmation_time:f.first_hunt_time);s.price1=s.price2;s.text=f.disposition==FP_I11_SUPPRESSED_BY_WW?"WW":"Q";s.immutable=true;return s;}
 static SFP_I11_ObjectSpec Winner(string ns,const SFP_I11_SignalFact &f,long chart_id,int lane_count){SFP_I11_ObjectSpec s=Suppression(ns,f,chart_id,lane_count);s.semantic_id=f.signal_id+"-WIN";s.kind=FP_I11_QUOTA_WINNER_BADGE;s.object_id=FP_I11_ObjectId(ns,s.kind,s.semantic_id);s.text="1ST";s.style=FP_I11_StyleRegistry::Signal(f.direction,f.state,FP_I11_QUOTA_WINNER);return s;}
 static SFP_I11_ObjectSpec WW(string ns,const SFP_I11_WWFact &f,double high,double low){SFP_I11_ObjectSpec s;Base(s,ns,f.context_id,FP_I11_WW_CONTEXT,15,f.semantic_hash);s.time1=f.start_time;s.time2=f.end_time;s.price1=high;s.price2=low;s.text="WW "+StringSubstr(f.direction,0,1);s.tooltip=f.hunter_symbol+"->"+f.protected_symbol+" "+f.state;s.style=FP_I11_StyleRegistry::WW(f.direction);s.immutable=true;return s;}
 static SFP_I11_ObjectSpec Health(string ns,string semantic_id,int state,string text,string semantic_hash){SFP_I11_ObjectSpec s;Base(s,ns,semantic_id,FP_I11_HEALTH_BADGE,80,semantic_hash);s.corner=CORNER_LEFT_UPPER;s.x=10;s.y=20;s.text=text;s.tooltip=text;s.style=FP_I11_StyleRegistry::Health(state);return s;}
};
#endif
