from pathlib import Path
import json,sys
ROOT=Path(__file__).resolve().parents[3];sys.path.insert(0,str(ROOT/'lab/11_strategy_factory/python'))
from saed_v4_causal_mechanism_discovery.service import build_reference_bundle
load=lambda p:json.loads((ROOT/p).read_text(encoding='utf-8'))
b=build_reference_bundle(*[load(p) for p in ['lab/11_strategy_factory/artifacts/saed_v4_16/V4_16_TO_V4_17_HANDOFF.JSON','lab/11_strategy_factory/artifacts/saed_v4_16/GOLDEN_SURVIVAL_DATASET.JSON','lab/11_strategy_factory/artifacts/saed_v4_16/GOLDEN_CHECKPOINT_REGISTRY.JSON','lab/11_strategy_factory/artifacts/saed_v4_16/GOLDEN_INTEGRITY_RECEIPT.JSON','lab/11_strategy_factory/artifacts/saed_v4_16/GOLDEN_TAIL_CALIBRATION_REPORT.JSON','lab/11_strategy_factory/artifacts/saed_v4_16/GOLDEN_TIME_CALIBRATION_REPORT.JSON','lab/11_strategy_factory/examples/saed_v4_17/reference_variable_registry.json','lab/11_strategy_factory/examples/saed_v4_17/reference_environment_registry.json','lab/11_strategy_factory/examples/saed_v4_17/reference_graph_constraints.json','lab/11_strategy_factory/examples/saed_v4_17/reference_discovery_config.json','lab/11_strategy_factory/examples/saed_v4_17/reference_candidate_catalog.json','lab/11_strategy_factory/examples/saed_v4_17/reference_compute_exposure_budget.json']])
checks={'causal_benchmark_dataset':('GOLDEN_CAUSAL_BENCHMARK_DATASET.JSON','dataset_hash'),'temporal_candidate_graph':('GOLDEN_TEMPORAL_CANDIDATE_GRAPH.JSON','report_hash'),'invariant_mechanism_report':('GOLDEN_INVARIANT_MECHANISM_REPORT.JSON','report_hash'),'negative_control_audit':('GOLDEN_NEGATIVE_CONTROL_AUDIT.JSON','report_hash'),'tournament':('GOLDEN_TOURNAMENT.JSON','tournament_hash'),'checkpoint_registry':('GOLDEN_CHECKPOINT_REGISTRY.JSON','registry_hash'),'integrity_receipt':('GOLDEN_INTEGRITY_RECEIPT.JSON','receipt_hash'),'handoff':('V4_17_TO_V4_18_HANDOFF.JSON','handoff_hash')}
for key,(name,h) in checks.items():assert b[key][h]==load('lab/11_strategy_factory/artifacts/saed_v4_17/'+name)[h],key
print(f'SAED V4-17 golden reproduction passed: {len(checks)} content-addressed outputs')
