"""Golden source snapshots used for adapter and differential compatibility evidence."""
from __future__ import annotations

def fixtures():
 return {
 'CGT_TIME_READY':('FP_CGT_TIME_ADAPTER@1.0.0',{'broker_now':1000,'utc_now':900,'new_york_now':500,'trading_day_start_ny':0,'trading_day_end_ny':1380,'inside_trading_day':True,'new_york_utc_offset_hours':-4,'trading_day_label':'2026-07-13'}),
 'CGR_REFERENCE_READY':('FP_CGR_REFERENCE_ADAPTER@1.0.0',{'group_name':'CG60M','reference_cycle_index':4,'cycle_start_ny':100,'cycle_end_ny':160,'complete_cycle':True,'ready':True,'symbol_a':{'symbol':'US500','data_ok':True,'high':6300.0,'low':6280.0,'high_time_broker':101,'low_time_broker':120},'symbol_b':{'symbol':'USTEC','data_ok':True,'high':23100.0,'low':23000.0,'high_time_broker':104,'low_time_broker':130}}),
 'CGH_HIGH_A_ONLY':('FP_CGH_HUNT_ADAPTER@1.0.0',{'group_name':'CG60M','reference_cycle_index':4,'reference_cycle_start_ny':100,'current_cycle_start_ny':160,'reference_ready':True,'current_range_ready':True,'symbol_a':{'symbol':'US500','reference_high':6300.0,'reference_low':6280.0,'current_high':6301.0,'current_low':6285.0,'high_hunted':True,'low_hunted':False},'symbol_b':{'symbol':'USTEC','reference_high':23100.0,'reference_low':23000.0,'current_high':23099.0,'current_low':23020.0,'high_hunted':False,'low_hunted':False}}),
 'CGD_BUY':('FP_CGD_DIVERGENCE_ADAPTER@1.0.0',{'divergence_id':'CGD-1','group_name':'CG60M','reference_cycle_index':4,'current_cycle_index':5,'direction':1,'side':1,'hunter_symbol':'US500','clean_symbol':'USTEC','one_sided_hunt':True,'both_symbols_hunted_same_side':False,'data_ready':True,'hunter_reference_price':6280.0,'clean_reference_price':23000.0,'current_cycle_start_ny':160,'reference_cycle_start_ny':100}),
 'CGC_CONFIRMED':('FP_CGC_CONFIRMATION_ADAPTER@1.0.0',{'signal_id':'CGC-1','direction':1,'side':1,'status':1,'hunter_symbol':'US500','clean_symbol':'USTEC','confirmation_timeframe_seconds':3600,'confirmation_time_utc':10000,'confirmation_time_broker':11000,'clean_stop_reference_price':23000.0,'one_sided_hunt':True,'double_hunt_invalidated':False,'data_ready':True}),
 'DAYE_HUNT_B_ONLY_LOW':('FP_DAYE_HUNT_ADAPTER@1.0.0',{'observation_id':'DHO-1','opportunity_id':'OP-1','relationship_id':'REL-1','side':2,'pair_state':3,'hunter_canonical_symbol':'USTEC','protected_canonical_symbol':'US500','reference_price_a':6300.0,'reference_price_b':23000.0,'current_extreme_a':6301.0,'current_extreme_b':22999.0,'event_time_utc':20000,'availability_time_utc':20060,'is_replay_safe':True,'status':1}),
 'DAYE_CONFIRM_CONFIRMED':('FP_DAYE_CONFIRMATION_ADAPTER@1.0.0',{'result_id':'DCR-1','candidate_id':'DCC-1','observation_id':'DHO-1','opportunity_id':'OP-1','outcome':1,'side':2,'hunter_canonical_symbol':'USTEC','protected_canonical_symbol':'US500','host_bar_open_utc':20000,'host_bar_close_utc':23600,'confirmation_endpoint_price':6305.0,'is_final':True,'is_immutable':True,'is_replay_safe':True,'status':1,'reason_code':'CONFIRMED'}),
 'DAYE_LIFECYCLE_SURVIVES':('FP_DAYE_LIFECYCLE_ADAPTER@1.0.0',{'reference_id':'REF-1','side':2,'protected_canonical_symbol':'US500','first_hunter_canonical_symbol':'USTEC','state':'PROTECTED_SURVIVES','is_retired':False,'accepted_use_count':2,'duplicate_use_count':1,'rejected_use_count':0,'activation_event_time_utc':20000,'retirement_event_time_utc':0,'is_immutable':True,'is_replay_safe':True,'status':1,'reason_code':'PROTECTED_SURVIVES'}),
 }
