from __future__ import annotations
STATE_TRANSITIONS={
 "DISCOVERED":{"INVENTORIED"},"INVENTORIED":{"OWNED"},"OWNED":{"CHARACTERIZED"},
 "CHARACTERIZED":{"CANONICAL_SPECIFIED"},"CANONICAL_SPECIFIED":{"ADAPTED"},
 "ADAPTED":{"PARITY_VERIFIED"},"PARITY_VERIFIED":{"DUAL_RUN"},"DUAL_RUN":{"CUTOVER_APPROVED"},
 "CUTOVER_APPROVED":{"CUTOVER"},"CUTOVER":{"QUARANTINED"},"QUARANTINED":{"DELETE_ELIGIBLE"},
 "DELETE_ELIGIBLE":{"RETIRED"},"RETIRED":set()
}
HARD_DIMENSIONS=("event_type","event_time","available_at","bar_index","state_before","state_after","decision","direction","invalidation","expiry","reason_codes","no_trade","treatment_request","drawing_anchor_time","drawing_anchor_price")
SOFT_DIMENSIONS=("visual_color","visual_width","latency_us","memory_bytes")
ADAPTER_TYPES=("CONTEXT","SETUP","TREATMENT","VISUALIZER")
REDIRECT_TYPES=("MQL_INCLUDE_WRAPPER","OBSIDIAN_REDIRECT_STUB","PYTHON_IMPORT_SHIM")
PACKET_STATUSES=("VALID_REFERENCE","INVALID","BLOCKED_UNKNOWN","BLOCKED_AMBIGUITY","BLOCKED_SECURITY_REVIEW")
COMPARISON_STATUSES=("PASS","HARD_MISMATCH","SOFT_MISMATCH","UNKNOWN_EVIDENCE")
DELETION_GATES=(
 "CANONICAL_SUCCESSOR_OR_ARCHIVE_DECISION","LEGACY_MAPPING_COMPLETE","ZERO_ACTIVE_REFERENCES",
 "PARITY_VERIFIED","DOMAIN_OWNER_APPROVED","INDEPENDENT_REVIEWER_APPROVED","QUARANTINE_PERIOD_COMPLETE",
 "ROLLBACK_TAG_PRESENT","SOURCE_EVIDENCE_PRESERVED","DOCUMENTATION_UPDATED","CLEAN_CLONE_VERIFIED","POST_DELETE_MANIFEST_PLANNED")
REASON_CODES=(
 "PACKET_VALID","PACKET_FIELDS_MISSING","PACKET_DIGEST_INVALID","OWNER_MISSING","OWNER_ROLE_MISSING","IDENTITY_AMBIGUOUS","IDENTITY_KIND_UNKNOWN","IDENTITY_RESOLUTION_UNKNOWN","FUTURE_AWARE_EVIDENCE_BLOCKED","KNOWN_TIME_EVIDENCE_UNKNOWN","SECURITY_REVIEW_REQUIRED","SECURITY_REVIEW_STATUS_INVALID",
 "INVALID_STATE_TRANSITION","SOURCE_NOT_IN_TOPOLOGY","SOURCE_HASH_MISMATCH","SOURCE_HASH_FORMAT_INVALID","EVIDENCE_REFERENCES_INCOMPLETE","UNSAFE_PATH","CLAIM_CEILING_EXCEEDED","AUTHORITY_ESCALATION",
 "ALIAS_RESOLVED","ALIAS_AMBIGUOUS","ALIAS_NOT_FOUND","TRACE_HARD_PARITY","TRACE_HARD_MISMATCH",
 "TRACE_SOFT_MISMATCH","TRACE_EVIDENCE_UNKNOWN","ADAPTER_AUTHORITY_DENIED","MOVE_PLAN_REFERENCE_ONLY",
 "REDIRECT_PREVIEW_REFERENCE_ONLY","QUARANTINE_READY_HUMAN_EXECUTION_REQUIRED","QUARANTINE_EVIDENCE_INCOMPLETE","DELETION_ELIGIBLE_HUMAN_EXECUTION_STILL_REQUIRED","DELETION_GATES_INCOMPLETE")
def registry(registry_id,values):
    from .canonical import digest_object
    out={"schema_version":"1.0.0","registry_id":registry_id,"values":list(values),"closed":True,"registry_digest":None}
    out["registry_digest"]=digest_object(out,"registry_digest");return out
