#ifndef __FP_I14_REGISTRY_MQH__
#define __FP_I14_REGISTRY_MQH__
#define FP_I14_PHASE_ID "FP-I14"
#define FP_I14_PHASE_VERSION "1.0.0"
#define FP_I14_TRACE_CONTRACT_VERSION "1.0.0"
#define FP_I14_RUNTIME_AUTHORITY "NONE"
#endif
