#ifndef AL_ACL04_TYPES_MQH
#define AL_ACL04_TYPES_MQH

enum ENUM_AL_ACL04_LANE
  {
   AL_ACL04_LANE_HUMAN=0,
   AL_ACL04_LANE_AI=1,
   AL_ACL04_LANE_BASELINE=2
  };

enum ENUM_AL_ACL04_CANDIDATE_STATE
  {
   AL_ACL04_CANDIDATE_DRAFT=0,
   AL_ACL04_CANDIDATE_CANONICAL=1,
   AL_ACL04_CANDIDATE_REJECTED=2,
   AL_ACL04_CANDIDATE_DIAGNOSTIC_ONLY=3,
   AL_ACL04_CANDIDATE_HANDED_OFF=4
  };

enum ENUM_AL_ACL04_CLAUSE_KIND
  {
   AL_ACL04_ENTRY=0,
   AL_ACL04_INVALIDATION=1,
   AL_ACL04_EXIT=2,
   AL_ACL04_MANAGEMENT=3,
   AL_ACL04_EXPIRY=4,
   AL_ACL04_ABSTENTION=5
  };

enum ENUM_AL_ACL04_FINDING_SEVERITY
  {
   AL_ACL04_INFO=0,
   AL_ACL04_WARNING=1,
   AL_ACL04_BLOCKER=2
  };

#endif
