from tools.repository_paths import find_repository_root
from pathlib import Path
BASE=find_repository_root(__file__)
REGISTRY_ROOT=BASE/'registry/acl_os/acl_09'
SCHEMA_ROOT=REGISTRY_ROOT/'schemas/v1'
POLICY_ROOT=REGISTRY_ROOT/'policies/v1'
HANDOFF_IN='ACL08_TO_ACL09'
HANDOFF_OUT='ACL09_TO_ACL10'
REQUIRED_UPSTREAM_ACTIONS={'INGEST_REPORT_PACKAGE','INDEX_EXPERIENCE_RECORDS','DETECT_RESEARCH_DUPLICATES','PROPOSE_BOUNDED_RESEARCH_QUESTIONS'}
FORBIDDEN_UPSTREAM_ACTIONS={'MUTATE_VALIDATION_DECISIONS','PROMOTE_REPORTING_OUTPUT','INFER_ALPHA_FROM_SUMMARY','AUTHORIZE_EXECUTION','ACTIVATE_CAPITAL','AMEND_DOCTRINE_WITHOUT_APPROVAL'}
REQUIRED_ACTION='ACL09_GOVERN_MEMORY_AND_PLAN'
CLAIM_CEILING='MEMORY_AND_ACTIVE_PLANNING_REFERENCE_ONLY'
SERVICE_VERSION='1.0.0'
ADMISSION_STATUSES={'ADMITTED_NEW','LINKED_BATCH_DUPLICATE','LINKED_PRIOR_DUPLICATE','QUARANTINED_DIAGNOSTIC','REJECTED_POLICY'}
PROPOSAL_STATUSES={'SELECTED_PROPOSAL_NOT_AUTHORIZED','DEFERRED_BUDGET','SUPPRESSED_DUPLICATE','REJECTED_POLICY'}
