#ifndef DECISION_ALPHA_LAB_SAED_V4_14_VERSION_MQH
#define DECISION_ALPHA_LAB_SAED_V4_14_VERSION_MQH
#define SAED_V4_14_PHASE "SAED_V4_14"
#define SAED_V4_14_VERSION "1.0.0"
#define SAED_V4_14_RUNTIME_AUTHORITY false
#endif
