from enum import Enum
class ReplayMode(str,Enum): FULL='FULL';INCREMENTAL='INCREMENTAL';RESTART='RESTART'
class ReplayEventType(str,Enum): SEMANTIC_UPSERT='SEMANTIC_UPSERT';SEMANTIC_STATUS='SEMANTIC_STATUS';VISUAL_FACT='VISUAL_FACT';ALERT_FACT='ALERT_FACT';EXPORT_FACT='EXPORT_FACT';HEALTH_FACT='HEALTH_FACT'
class ReplayDisposition(str,Enum): APPLIED='APPLIED';DUPLICATE_IGNORED='DUPLICATE_IGNORED'
class CheckpointDisposition(str,Enum): RESTORED='RESTORED';REJECT_VERSION='REJECT_VERSION';REJECT_FIXTURE='REJECT_FIXTURE';REJECT_CONFIG='REJECT_CONFIG';REJECT_INSTANCE='REJECT_INSTANCE';REJECT_HASH='REJECT_HASH';REBUILD_REQUIRED='REBUILD_REQUIRED'
class ParityStatus(str,Enum): PASS='PASS';FAIL='FAIL'
class IsolationStatus(str,Enum): PASS='PASS';FAIL='FAIL'
class BudgetStatus(str,Enum): PASS='PASS';DEGRADED='DEGRADED';BLOCKED='BLOCKED'
class ReleaseProfileId(str,Enum): TRADING_30D='TRADING_30D';AUDIT_90D='AUDIT_90D';PERFORMANCE_7D='PERFORMANCE_7D';SAFE_DIAGNOSTIC='SAFE_DIAGNOSTIC'
class AcceptanceStatus(str,Enum): SOURCE_ACCEPTED_EXTERNAL_COMPILE_PENDING='SOURCE_ACCEPTED_EXTERNAL_COMPILE_PENDING';ACCEPTED='ACCEPTED';REJECTED='REJECTED'
class GateStatus(str,Enum): PASS='PASS';PENDING='PENDING';FAIL='FAIL';NOT_AVAILABLE='NOT_AVAILABLE'
class HealthState(str,Enum): READY='READY';DEGRADED='DEGRADED';BLOCKED='BLOCKED'
class ObjectPriority(int,Enum): CRITICAL=0;IMPORTANT=1;NORMAL=2;HISTORICAL=3
