#ifndef ALPHALAB_ACL11_PARITY_STATUS_MQH
#define ALPHALAB_ACL11_PARITY_STATUS_MQH
enum ENUM_ACL11_PARITY_STATUS { ACL11_PARITY_SATISFIED=0, ACL11_PARITY_UNSATISFIED=1, ACL11_PARITY_UNKNOWN=2, ACL11_PARITY_NOT_APPLICABLE=3 };
#endif
