#ifndef SAEDV417CLAIMCEILING_MQH
#define SAEDV417CLAIMCEILING_MQH
#include "SAEDV417Types.mqh"
bool SAEDV417ClaimAllowed(const ENUM_SAED_V4_17_CLAIM_TIER tier){return tier<=SAED_V417_SYNTHETIC_MECHANISM_COMPATIBLE;}
#endif
