from __future__ import annotations
from .canonical import content_hash,stable_id

def build_certificate(evidence:dict)->dict:
    authority=evidence["authority"]
    gates={"upstream_verified":evidence["upstream"]["verified"],"finite_model_compiled":evidence["model"]["model_id"]==evidence["graph"]["model_id"],"reachable_state_space_complete":evidence["graph"]["complete_for_reachable_finite_state_space"],"invariants_passed":evidence["invariant_report"]["passed"],"bounded_temporal_properties_passed":evidence["temporal_report"]["passed"],"mutation_adequacy_passed":evidence["mutation_scorecard"]["passed"],"all_counterexamples_preserved":evidence["counterexample_ledger"]["all_failures_preserved"],"all_proof_obligations_discharged":evidence["proof_ledger"]["all_discharged"],"all_hazards_controlled":evidence["mitigation_coverage"]["all_hazards_controlled"],"residual_risk_within_reference_threshold":evidence["residual_risk"]["all_within_threshold"],"assurance_case_valid":evidence["assurance_case"]["valid"],"evidence_traceability_complete":evidence["traceability"]["complete"],"contract_closure_passed":evidence["contract_closure"]["closed"],"known_time_passed":evidence["known_time"]["passed"],"security_passed":evidence["security"]["passed"],"model_risk_passed":evidence["model_risk"]["passed"],"independent_reproduction_exact":evidence["reproduction"]["exact_match"],"deterministic_replay":evidence["replay"]["deterministic"],"authority_zero":not any(authority["authority"].values())}
    body={"phase":"SAED_V4_31","version":"1.0.0","claim_class":"finite_formal_verification_and_safety_case_closed_reference_implementation","accepted_for_formal_verification_safety_case_research_reference":all(gates.values()),"gates":gates,"evidence_hashes":{k:content_hash(v) for k,v in evidence.items()},"authority_boundary":authority,"research_only":True,"finite_synthetic_model_claim":True,"bounded_temporal_semantics_claim":True,"general_program_correctness_claim":False,"arbitrary_python_proof_claim":False,"arbitrary_mql5_proof_claim":False,"external_theorem_prover_certification_claim":False,"real_market_correctness_claim":False,"real_alpha_claim":False,"prospective_success_claim":False,"promotion_authority":False,"runtime_executable":False,"risk_allocation_authority":False,"execution_authority":False,"production_authority":False,"online_learning_authority":False,"live_trading_authority":False}
    body["certificate_id"]=stable_id("v431_safety_case_certificate",body); body["certificate_hash"]=content_hash(body); return body

def handoff(certificate:dict)->dict:
    body={"phase":"SAED_V4_31","next_phase":"SAED_V4_32","certificate_id":certificate["certificate_id"],"certificate_hash":certificate["certificate_hash"],"entry_gates":{"formal_verification_reference_accepted":certificate["accepted_for_formal_verification_safety_case_research_reference"],"proof_obligations_discharged":certificate["gates"]["all_proof_obligations_discharged"],"safety_case_valid":certificate["gates"]["assurance_case_valid"],"authority_zero":certificate["gates"]["authority_zero"],"research_only":True},"allowed_next_work":["multi_agent_role_constitution","agent_authority_lattice","proposal_review_execution_separation","debate_and_dissent_protocol","agent_evidence_provenance","formal_safety_constraint_binding","human_approval_boundary"],"forbidden_next_work":["grant_execution_authority_to_agent","grant_promotion_authority_to_agent","agent_self_modification_in_production","suppress_counterexamples","waive_residual_risk","runtime_compilation","risk_allocation","order_submission","production_release"],"authority":{"promotion":False,"runtime":False,"risk_allocation":False,"execution":False,"production":False,"online_learning":False,"live_trading":False},"research_only":True}
    body["handoff_id"]=stable_id("v4_31_to_v4_32",body); body["handoff_hash"]=content_hash(body); return body
