from __future__ import annotations
from .canonical import content_hash, stable_id

def build(evidence,authority):
    gates={"upstream_verified":evidence["upstream_receipt"]["hash_verified"],"anytime_registry_complete":evidence["anytime_evidence_registry"]["record_count"]>0,"known_time_enforced":evidence["anytime_evidence_registry"]["known_time_enforced"],"family_allocation_frozen":evidence["family_allocation"]["frozen"],"family_weights_normalized":abs(evidence["family_allocation"]["weight_sum"]-1.0)<1e-12,"wealth_ledger_verified":evidence["wealth_ledger"]["chain_verification"]["verified"],"wealth_nonnegative":evidence["wealth_ledger"]["all_wealth_nonnegative"],"rejection_ledger_verified":evidence["rejection_ledger"]["chain_verification"]["verified"],"stopping_rules_safe":evidence["stopping_rule_audit"]["all_rules_predictable"] and evidence["stopping_rule_audit"]["no_rule_uses_future_data"],"online_fdr_audit_passed":evidence["online_fdr_audit"]["passed"],"security_passed":evidence["security_review"]["passed"],"authority_zero":not any(authority["authority"].values())}
    payload={"phase":"SAED_V4_28","version":"1.0.0","claim_class":"anytime_valid_online_fdr_closed_reference_implementation","gates":gates,"accepted_for_online_fdr_research_reference":all(gates.values()),"research_only":True,"online_fdr_reference_implementation_claim":True,"anytime_valid_evidence_contract_claim":True,"synthetic_fixture_control_claim":True,"real_world_fdr_guarantee_claim":False,"real_alpha_claim":False,"prospective_success_claim":False,"hidden_evaluation_air_gap_claim":False,"independent_replication_claim":False,"promotion_authority":False,"runtime_executable":False,"risk_allocation_authority":False,"execution_authority":False,"production_authority":False,"online_learning_authority":False,"authority_boundary":authority,"evidence_hashes":{k:content_hash(v) for k,v in evidence.items()}}
    payload["certificate_id"]=stable_id("anytime_valid_online_fdr_certificate",payload); payload["certificate_hash"]=content_hash(payload); return payload

def handoff(certificate):
    payload={"phase":"SAED_V4_28","next_phase":"SAED_V4_29","certificate_id":certificate["certificate_id"],"certificate_hash":certificate["certificate_hash"],"entry_gates":{"online_fdr_reference_accepted":True,"anytime_evidence_contract_frozen":True,"wealth_chain_verified":True,"rejection_chain_verified":True,"stopping_rules_verified":True,"protected_evidence_access_zero":True,"research_only":True},"allowed_next_work":["hidden_evaluation_air_gap_policy","sealed_evaluator_identity","one_shot_query_token","protected_dataset_custody","air_gap_transport_receipt","result_redaction_policy","evaluation_budget_zero_by_default","irreversible_query_commit"],"forbidden_next_work":["promotion_authorization","runtime_compilation","risk_allocation","order_submission","online_policy_mutation","unsealed_hidden_evaluation_access"],"research_only":True,"authority":{"decision":False,"promotion":False,"runtime":False,"risk_allocation":False,"execution":False,"production":False,"hidden_evaluation_access":False}}
    payload["handoff_id"]=stable_id("v4_28_to_v4_29",payload); payload["handoff_hash"]=content_hash(payload); return payload
