from __future__ import annotations
from .canonical import content_hash, stable_id
from .registry import admitted_checkpoint_hash

def build_v4_12_handoff(registry,checkpoint,tokenizer,corpus_manifest,split_manifest,training_receipt,dossier,integrity_receipt):
    admitted=admitted_checkpoint_hash(registry)
    if admitted!=checkpoint['checkpoint_hash']: raise ValueError('registry/checkpoint mismatch')
    payload={"phase":"SAED_V4_11","next_phase":"SAED_V4_12","encoder_checkpoint_id":checkpoint['checkpoint_id'],"encoder_checkpoint_hash":checkpoint['checkpoint_hash'],"checkpoint_registry_id":registry['registry_id'],"checkpoint_registry_hash":registry['registry_hash'],"tokenizer_id":tokenizer['tokenizer_id'],"tokenizer_hash":tokenizer['tokenizer_hash'],"corpus_manifest_id":corpus_manifest['manifest_id'],"corpus_manifest_hash":corpus_manifest['manifest_hash'],"split_manifest_id":split_manifest['split_manifest_id'],"split_manifest_hash":split_manifest['split_manifest_hash'],"training_receipt_id":training_receipt['receipt_id'],"training_receipt_hash":training_receipt['receipt_hash'],"representation_dossier_id":dossier['dossier_id'],"representation_dossier_hash":dossier['dossier_hash'],"integrity_receipt_hash":integrity_receipt['receipt_hash'],"entry_gates":{"reference_checkpoint_admitted":True,"contamination_audit_passed":True,"membership_audit_passed":True,"deterministic_replay_passed":True,"baseline_registry_preserved":True,"outcome_supervision_absent":True,"future_suffix_forbidden":True},"authority":{"read_frozen_encoder":True,"build_reference_sequence_state_space_challengers":True,"fine_tune_on_protected_or_live_data":False,"predict_outcomes":False,"rank_treatments":False,"select_treatment":False,"allocate_risk":False,"activate_runtime":False,"send_order":False},"limitations":["Encoder was trained on a synthetic reference corpus.","V4-12 must preserve exact tokenizer and checkpoint hashes.","Any real-corpus or protected-role training requires a separate evidence-bearing admission."]}
    payload['handoff_id']=stable_id('v411to12',payload);payload['handoff_hash']=content_hash(payload);return payload
