from enum import Enum
class StrEnum(str, Enum):
    def __str__(self): return self.value
class BarFinality(StrEnum):
    CLOSED='CLOSED'; PROVISIONAL='PROVISIONAL'
class MinuteCellState(StrEnum):
    PRESENT='PRESENT'; MISSING='MISSING'; OUT_OF_COVERAGE='OUT_OF_COVERAGE'; CONFLICT='CONFLICT'; REVISED='REVISED'
class CoverageState(StrEnum):
    COMPLETE='COMPLETE'; PARTIAL='PARTIAL'; EMPTY='EMPTY'; CONFLICTED='CONFLICTED'; BLOCKED='BLOCKED'
class SynchronizationHealth(StrEnum):
    READY='READY'; DEGRADED='DEGRADED'; BLOCKED='BLOCKED'
class DuplicateDisposition(StrEnum):
    UNIQUE='UNIQUE'; IDENTICAL_DEDUPLICATED='IDENTICAL_DEDUPLICATED'; CONFLICT='CONFLICT'
class RevisionKind(StrEnum):
    INITIAL='INITIAL'; APPEND='APPEND'; LATE_INSERT='LATE_INSERT'; VALUE_CORRECTION='VALUE_CORRECTION'; DELETE='DELETE'; CONFLICT='CONFLICT'; NO_CHANGE='NO_CHANGE'
class GapReason(StrEnum):
    SOURCE_MISSING='SOURCE_MISSING'; BEFORE_COVERAGE='BEFORE_COVERAGE'; AFTER_COVERAGE='AFTER_COVERAGE'; CALENDAR_EXCLUDED='CALENDAR_EXCLUDED'; DUPLICATE_CONFLICT='DUPLICATE_CONFLICT'
class ExpectedMinutePolicy(StrEnum):
    ALL_REQUESTED_MINUTES='ALL_REQUESTED_MINUTES'; NY_TRADING_SESSIONS_ONLY='NY_TRADING_SESSIONS_ONLY'
class CursorState(StrEnum):
    EMPTY='EMPTY'; ACTIVE='ACTIVE'; EXHAUSTED='EXHAUSTED'; INVALIDATED='INVALIDATED'
class BackfillAction(StrEnum):
    NONE='NONE'; FETCH_RANGE='FETCH_RANGE'; FULL_REBUILD='FULL_REBUILD'; BLOCK='BLOCK'
class SourceQuality(StrEnum):
    CANONICAL='CANONICAL'; ACCEPTED='ACCEPTED'; SUSPECT='SUSPECT'; REJECTED='REJECTED'
class DataAuthority(StrEnum):
    M1_CLOSED_BARS='M1_CLOSED_BARS'
