#ifndef __UCEI04_PATH_STATE_MACHINE_MQH__
#define __UCEI04_PATH_STATE_MACHINE_MQH__
#include "UCEI04_Compiler.mqh"
class CUCEI04PathStateMachine{
private:
 bool Next(const ENUM_UCEI04_PATH_STATE s,const ENUM_UCEI04_EVENT_TYPE e,ENUM_UCEI04_PATH_STATE &n){n=s;if(s==UCEI04_DRAFT&&(e==UCEI04_SUBMIT||e==UCEI04_REJECT)){n=(e==UCEI04_SUBMIT?UCEI04_PENDING:UCEI04_REJECTED);return true;}if(s==UCEI04_PENDING&&(e==UCEI04_TRIGGER||e==UCEI04_FILL||e==UCEI04_CANCEL||e==UCEI04_TIMEOUT||e==UCEI04_REJECT)){if(e==UCEI04_TRIGGER)n=UCEI04_TRIGGERED;else if(e==UCEI04_FILL)n=UCEI04_PARTIALLY_FILLED;else if(e==UCEI04_CANCEL)n=UCEI04_CANCELED;else if(e==UCEI04_TIMEOUT)n=UCEI04_TIMED_OUT;else n=UCEI04_REJECTED;return true;}if((s==UCEI04_TRIGGERED||s==UCEI04_PARTIALLY_FILLED||s==UCEI04_OPEN||s==UCEI04_SCALED||s==UCEI04_PARTIALLY_EXITED||s==UCEI04_TRAILED)){if(e==UCEI04_FILL){n=UCEI04_PARTIALLY_FILLED;return true;}if(e==UCEI04_SCALE){n=UCEI04_SCALED;return true;}if(e==UCEI04_PARTIAL_EXIT){n=UCEI04_PARTIALLY_EXITED;return true;}if(e==UCEI04_TRAIL_UPDATE){n=UCEI04_TRAILED;return true;}if(e==UCEI04_STOP_HIT){n=UCEI04_STOPPED;return true;}if(e==UCEI04_TARGET_HIT){n=UCEI04_TARGETED;return true;}if(e==UCEI04_TIMEOUT){n=UCEI04_TIMED_OUT;return true;}if(e==UCEI04_CLOSE){n=UCEI04_CLOSED;return true;}if(e==UCEI04_CANCEL&&s==UCEI04_PARTIALLY_FILLED){n=s;return true;}}if((s==UCEI04_STOPPED||s==UCEI04_TARGETED||s==UCEI04_TIMED_OUT||s==UCEI04_CANCELED||s==UCEI04_REJECTED)&&e==UCEI04_CLOSE){n=UCEI04_CLOSED;return true;}return false;}
public:
 void Initial(const UCEI04_CompiledTreatment &t,UCEI04_PathSnapshot &s){s.treatment_id=t.treatment_id;s.state=UCEI04_DRAFT;s.last_sequence=0;s.last_event_time_ms=t.decision_time_ms;s.last_known_time_ms=t.decision_time_ms;s.filled_fraction=0.0;s.open_fraction=0.0;s.exited_fraction=0.0;s.has_average_entry=false;s.average_entry_price=0.0;s.has_active_stop=t.stop.has_price_stop;s.active_stop_price=t.stop.stop_price;s.has_last_trail=false;s.last_trail_price=0.0;s.terminal_reason="";s.transition_count=0;UCEI04_SealSnapshot(s);}
 bool Apply(const UCEI04_PathSnapshot &s,const UCEI04_PathEvent &e,UCEI04_PathSnapshot &out,string &error){if(e.sequence!=s.last_sequence+1){error="sequence_gap";return false;}if(e.event_time_ms<s.last_event_time_ms){error="event_time_regression";return false;}if(e.known_time_ms<s.last_known_time_ms||e.known_time_ms<e.event_time_ms){error="known_time_violation";return false;}ENUM_UCEI04_PATH_STATE next;if(!Next(s.state,e.event_type,next)){error="illegal_transition";return false;}out=s;out.state=next;out.last_sequence=e.sequence;out.last_event_time_ms=e.event_time_ms;out.last_known_time_ms=e.known_time_ms;out.transition_count=s.transition_count+1;if(e.event_type==UCEI04_FILL||e.event_type==UCEI04_SCALE){if(e.quantity_fraction<=0.0||s.filled_fraction+e.quantity_fraction>1.0000001){error="invalid_fill_fraction";return false;}double old_notional=(s.has_average_entry?s.average_entry_price*s.open_fraction:0.0);out.filled_fraction=s.filled_fraction+e.quantity_fraction;out.open_fraction=s.open_fraction+e.quantity_fraction;if(e.has_price&&out.open_fraction>0.0){out.average_entry_price=(old_notional+e.price*e.quantity_fraction)/out.open_fraction;out.has_average_entry=true;}if(out.filled_fraction>=0.9999999)out.state=UCEI04_OPEN;}else if(e.event_type==UCEI04_PARTIAL_EXIT){if(e.quantity_fraction<=0.0||e.quantity_fraction>s.open_fraction+1e-9){error="invalid_exit_fraction";return false;}out.open_fraction=s.open_fraction-e.quantity_fraction;out.exited_fraction=s.exited_fraction+e.quantity_fraction;if(out.open_fraction<=1e-9){out.state=UCEI04_CLOSED;out.terminal_reason=e.reason;}}else if(e.event_type==UCEI04_TRAIL_UPDATE){if(!e.has_price){error="missing_trail_price";return false;}out.has_last_trail=true;out.last_trail_price=e.price;}else if(e.event_type==UCEI04_STOP_HIT||e.event_type==UCEI04_TARGET_HIT||e.event_type==UCEI04_TIMEOUT||e.event_type==UCEI04_CLOSE){out.exited_fraction=s.exited_fraction+s.open_fraction;out.open_fraction=0.0;out.terminal_reason=e.reason!=""?e.reason:UCEI04_EventTypeName(e.event_type);}UCEI04_SealSnapshot(out);error="";return true;}
};
#endif
