#ifndef __UCEI04_ENUMS_MQH__
#define __UCEI04_ENUMS_MQH__
enum ENUM_UCEI04_PATH_STATE{UCEI04_DRAFT=0,UCEI04_PENDING=1,UCEI04_TRIGGERED=2,UCEI04_PARTIALLY_FILLED=3,UCEI04_OPEN=4,UCEI04_SCALED=5,UCEI04_PARTIALLY_EXITED=6,UCEI04_TRAILED=7,UCEI04_STOPPED=8,UCEI04_TARGETED=9,UCEI04_TIMED_OUT=10,UCEI04_CANCELED=11,UCEI04_REJECTED=12,UCEI04_CLOSED=13};
enum ENUM_UCEI04_EVENT_TYPE{UCEI04_SUBMIT=0,UCEI04_TRIGGER=1,UCEI04_FILL=2,UCEI04_SCALE=3,UCEI04_PARTIAL_EXIT=4,UCEI04_TRAIL_UPDATE=5,UCEI04_STOP_HIT=6,UCEI04_TARGET_HIT=7,UCEI04_TIMEOUT=8,UCEI04_CANCEL=9,UCEI04_REJECT=10,UCEI04_CLOSE=11};
enum ENUM_UCEI04_AMBIGUITY_POLICY{UCEI04_STOP_FIRST=0,UCEI04_TARGET_FIRST=1,UCEI04_NEAREST_FIRST=2,UCEI04_WORST_CASE=3,UCEI04_BEST_CASE=4,UCEI04_REJECT_AMBIGUOUS=5};
enum ENUM_UCEI04_GAP_POLICY{UCEI04_FILL_AT_OPEN=0,UCEI04_FILL_AT_LEVEL=1,UCEI04_WORST_EXECUTABLE=2,UCEI04_REJECT_GAP=3};
enum ENUM_UCEI04_STALE_POLICY{UCEI04_REJECT_STALE=0,UCEI04_HOLD_STALE=1,UCEI04_USE_LAST=2};
enum ENUM_UCEI04_COMPILER_MODE{UCEI04_RESEARCH=0,UCEI04_MANUAL=1,UCEI04_AI_SEARCH=2,UCEI04_RUNTIME=3};
string UCEI04_PathStateName(const ENUM_UCEI04_PATH_STATE v){string names[]={"draft","pending","triggered","partially_filled","open","scaled","partially_exited","trailed","stopped","targeted","timed_out","canceled","rejected","closed"};int i=(int)v;return (i>=0&&i<ArraySize(names))?names[i]:"unknown";}
string UCEI04_EventTypeName(const ENUM_UCEI04_EVENT_TYPE v){string names[]={"submit","trigger","fill","scale","partial_exit","trail_update","stop_hit","target_hit","timeout","cancel","reject","close"};int i=(int)v;return (i>=0&&i<ArraySize(names))?names[i]:"unknown";}
#endif
