#ifndef __UCEI04_COMPILER_MQH__
#define __UCEI04_COMPILER_MQH__
#include "UCEI04_Compatibility.mqh"
class CUCEI04TreatmentCompiler{
private:CUCEI04Compatibility m_compat;
 int FindRole(const UCEI04_TreatmentDraft &d,const ENUM_UCEI03_ATOM_KIND role){for(int i=0;i<ArraySize(d.selections);i++)if(d.selections[i].role==role)return i;return -1;}
 void AddAction(UCEI04_CompiledTreatment &t,const string phase,const string type,const string key,const string plan_id,const int priority,const string payload){int n=ArraySize(t.actions);ArrayResize(t.actions,n+1);t.actions[n].sequence=n+1;t.actions[n].phase=phase;t.actions[n].action_type=type;t.actions[n].source_exact_key=key;t.actions[n].source_plan_id=plan_id;t.actions[n].priority=priority;t.actions[n].payload_json=payload;}
 bool BuildReferencePlans(const UCEI04_TreatmentDraft &d,const UCEI03_BuildContext &c,UCEI04_CompiledTreatment &t,string &error){int ie=FindRole(d,UCEI03_ENTRY),is=FindRole(d,UCEI03_STOP),it=FindRole(d,UCEI03_TARGET),ir=FindRole(d,UCEI03_TRAILING),iz=FindRole(d,UCEI03_SIZING);if(ie<0||is<0||it<0||ir<0||iz<0){error="missing required role";return false;}UCEI03_Invocation inv;UCEI03_MakeFixtureInvocation(d.side,inv);inv.context_occurrence_id=c.context_occurrence_id;inv.feature_frame_hash=c.feature_frame_hash;inv.decision_time_ms=c.decision_time_ms;inv.parameters=d.selections[ie].parameters;UCEI03_SealInvocation(inv);double entry=UCEI03_EntryExecutable(c.price,d.side);if(!UCEI03_BuildImmediateMarket(c,inv,t.entry,error))return false;double risk_points=UCEI03_GetDouble(d.selections[is].parameters,"distance_points",100.0);if(d.selections[is].exact_key=="stop.structural@1.0.0"){if(!UCEI03_BuildStructuralStop(c,inv,UCEI03_GetDouble(d.selections[is].parameters,"buffer_points",2.0),t.stop,error))return false;}else if(!UCEI03_BuildFixedDistanceStop(c,inv,risk_points,t.stop,error))return false;double risk_distance_points=MathAbs(entry-t.stop.stop_price)/c.price.point;if(d.selections[it].exact_key=="target.runner@1.0.0")UCEI03_BuildRunnerTarget(inv,t.target);else if(!UCEI03_BuildFixedRTarget(c,inv,risk_distance_points,UCEI03_GetDouble(d.selections[it].parameters,"reward_multiple",2.0),t.target,error))return false;if(d.selections[ir].exact_key=="trailing.none@1.0.0")UCEI03_BuildNoTrail(inv,t.trailing);else UCEI03_BuildBreakEvenTrail(c,inv,UCEI03_GetDouble(d.selections[ir].parameters,"activation_r",1.0),UCEI03_GetDouble(d.selections[ir].parameters,"buffer_points",0.0),t.trailing);UCEI03_BuildFixedCashSizing(c,inv,UCEI03_GetDouble(d.selections[iz].parameters,"cash_amount",100.0),t.sizing);ArrayResize(t.management,0);for(int i=0;i<ArraySize(d.selections);i++)if(d.selections[i].role==UCEI03_MANAGEMENT){int n=ArraySize(t.management);ArrayResize(t.management,n+1);UCEI03_BuildPartialExit(inv,UCEI03_GetDouble(d.selections[i].parameters,"activation_r",1.0),UCEI03_GetDouble(d.selections[i].parameters,"quantity_fraction",0.0),t.management[n]);}
 AddAction(t,"risk","reserve_sizing_budget",d.selections[iz].exact_key,t.sizing.plan_id,0,"{}");AddAction(t,"protection","install_initial_stop",d.selections[is].exact_key,t.stop.plan_id,10,"{}");AddAction(t,"entry","submit_entry_leg",d.selections[ie].exact_key,t.entry.plan_id,100,"{}");AddAction(t,"exit","install_target_leg",d.selections[it].exact_key,t.target.plan_id,300,"{}");AddAction(t,"management","configure_trailing",d.selections[ir].exact_key,t.trailing.plan_id,500,"{}");error="";return true;}
public:
 bool Compile(UCEI04_TreatmentDraft &d,const UCEI03_BuildContext &c,CUCEI03Catalog &catalog,UCEI04_CompiledTreatment &t,string &error){if(d.draft_id=="")UCEI04_SealDraft(d);UCEI04_RuleFinding findings[];if(!m_compat.Evaluate(d,c,catalog,findings,error))return false;t.draft_id=d.draft_id;t.context_occurrence_id=c.context_occurrence_id;t.feature_frame_hash=c.feature_frame_hash;t.side=d.side;t.decision_time_ms=c.decision_time_ms;t.compiler_version="3.1.0";t.manual_baseline=d.pinned;t.intrabar=d.intrabar;t.metadata_json="{\"economics\":\"deferred_to_uce_i05\"}";ArrayResize(t.findings,ArraySize(findings));for(int i=0;i<ArraySize(findings);i++)t.findings[i]=findings[i];ArrayResize(t.actions,0);if(!BuildReferencePlans(d,c,t,error))return false;string material=UCEI03_SideName(d.side)+"|"+IntegerToString((long)d.runtime_mode)+"|"+d.intrabar.definition_id+"|"+c.context_occurrence_id+"|"+c.feature_frame_hash+"|"+IntegerToString(c.decision_time_ms)+"|"+t.entry.plan_id+"|"+t.stop.plan_id+"|"+t.target.plan_id+"|"+t.trailing.plan_id+"|"+t.sizing.plan_id;for(int i=0;i<ArraySize(d.selections);i++)material+="|"+UCEI04_SelectionMaterial(d.selections[i]);t.treatment_id="ucet_"+UCE03_Fnv1a64HexUtf8(material);error="";return true;}
};
#endif
