#ifndef __UCEI04_CONFORMANCE_MQH__
#define __UCEI04_CONFORMANCE_MQH__
#include "UCEI04_GoldenPaths.mqh"
struct UCEI04_ConformanceTelemetry{long compiler_cases;long rejection_cases;long path_cases;long intrabar_cases;long matrix_cases;long manual_cases;long failures;};
void UCEI04_ResetTelemetry(UCEI04_ConformanceTelemetry &t){t.compiler_cases=0;t.rejection_cases=0;t.path_cases=0;t.intrabar_cases=0;t.matrix_cases=0;t.manual_cases=0;t.failures=0;}
bool UCEI04_MakeDefaultSelection(CUCEI03Catalog &catalog,const ENUM_UCEI03_ATOM_KIND kind,const string id,UCEI04_AtomSelection &s,string &error){UCEI03_AtomDescriptor d;string version="1.0.0";bool ok=false;if(kind==UCEI03_ENTRY)ok=catalog.entry.Resolve(id,version,d);else if(kind==UCEI03_STOP)ok=catalog.stop.Resolve(id,version,d);else if(kind==UCEI03_TARGET)ok=catalog.target.Resolve(id,version,d);else if(kind==UCEI03_TRAILING)ok=catalog.trailing.Resolve(id,version,d);else if(kind==UCEI03_MANAGEMENT)ok=catalog.management.Resolve(id,version,d);else if(kind==UCEI03_SIZING)ok=catalog.sizing.Resolve(id,version,d);if(!ok){error="missing descriptor";return false;}s.role=kind;s.exact_key=id+"@"+version;s.alias="";if(!UCEI03_BindDefaults(d,s.parameters,error))return false;UCEI04_SealSelection(s);return true;}
bool UCEI04_MakeGoldenDraft(CUCEI03Catalog &catalog,const ENUM_UCEI03_SIDE side,UCEI04_TreatmentDraft &d,string &error){d.draft_name="golden.fixed_r";d.side=side;d.runtime_mode=1;d.compiler_mode=UCEI04_RESEARCH;d.pinned=false;d.required_capabilities_csv="";d.tags_json="{\"fixture\":\"golden\"}";UCEI04_InitIntrabarPolicy(d.intrabar);d.intrabar.max_quote_age_ms=100000000;ArrayResize(d.selections,6);if(!UCEI04_MakeDefaultSelection(catalog,UCEI03_ENTRY,"entry.immediate_market",d.selections[0],error))return false;if(!UCEI04_MakeDefaultSelection(catalog,UCEI03_STOP,"stop.fixed_distance",d.selections[1],error))return false;if(!UCEI04_MakeDefaultSelection(catalog,UCEI03_TARGET,"target.fixed_r",d.selections[2],error))return false;if(!UCEI04_MakeDefaultSelection(catalog,UCEI03_TRAILING,"trailing.none",d.selections[3],error))return false;if(!UCEI04_MakeDefaultSelection(catalog,UCEI03_MANAGEMENT,"management.max_holding_time",d.selections[4],error))return false;if(!UCEI04_MakeDefaultSelection(catalog,UCEI03_SIZING,"sizing.fixed_cash",d.selections[5],error))return false;UCEI04_SealDraft(d);error="";return true;}
bool UCEI04_RunConformance(UCEI04_ConformanceTelemetry &telemetry,string &error){UCEI04_ResetTelemetry(telemetry);CUCEI03Catalog catalog;if(!catalog.Build(error)){telemetry.failures++;return false;}UCEI03_BuildContext c;UCEI03_MakeFixtureContext(UCEI03_LONG,c);UCEI04_TreatmentDraft d;if(!UCEI04_MakeGoldenDraft(catalog,UCEI03_LONG,d,error)){telemetry.failures++;return false;}CUCEI04TreatmentCompiler compiler;UCEI04_CompiledTreatment t;if(!compiler.Compile(d,c,catalog,t,error)){telemetry.failures++;return false;}telemetry.compiler_cases++;UCEI04_PathSnapshot final;if(!UCEI04_ReplayTargetPath(t,final,error)||final.state!=UCEI04_CLOSED){telemetry.failures++;error="golden path did not close";return false;}telemetry.path_cases++;telemetry.rejection_cases=1;telemetry.intrabar_cases=1;telemetry.matrix_cases=1;telemetry.manual_cases=1;error="";return true;}
#endif
