from pathlib import Path
BASE=Path(__file__).resolve().parents[4]
REGISTRY_ROOT=BASE/'registry/acl_os/acl_12'
SCHEMA_ROOT=REGISTRY_ROOT/'schemas/v1'
POLICY_ROOT=REGISTRY_ROOT/'policies/v1'
HANDOFF_IN='ACL11_TO_ACL12'
HANDOFF_OUT='ACL12_TO_ACL13'
REQUIRED_UPSTREAM_ACTIONS={'VERIFY_RUNTIME_CUSTODY_PACKAGE','HARDEN_SECURITY_BOUNDARIES','ISSUE_SECURITY_READINESS_DECISION'}
FORBIDDEN_UPSTREAM_ACTIONS={'INVENT_RUNTIME_CANDIDATE','BYPASS_PARITY_OR_SIGNING_GATES','ACCESS_PRODUCTION_KEYS_IN_REFERENCE_MODE','AUTHORIZE_LIVE_ORDER','ACTIVATE_CAPITAL'}
REQUIRED_ACTION='ACL12_HARDEN_SECURITY_BOUNDARIES'
CLAIM_CEILING='SECURITY_HARDENING_REFERENCE_ONLY'
SERVICE_VERSION='1.0.0'
CONTROL_STATUSES={'SATISFIED_REFERENCE','UNSATISFIED','UNKNOWN','NOT_APPLICABLE'}
READINESS_DECISIONS={'REFERENCE_SECURITY_HARDENED_PRODUCTION_NOT_READY','SECURITY_HARDENING_FAILED','PRODUCTION_SECURITY_REVIEW_ELIGIBLE_NOT_AUTHORIZED'}
