#ifndef ALPHALAB_ACL06_TASK_TYPES_MQH
#define ALPHALAB_ACL06_TASK_TYPES_MQH
enum ENUM_ACL06_TASK_TYPE { ACL06_VERIFY_FROZEN_BATCH=0, ACL06_MATERIALIZE_DATASET=1, ACL06_COMPILE_MATURE_LABELS=2, ACL06_ASSIGN_PURGED_SPLITS=3, ACL06_EVALUATE_CANDIDATE_SEGMENT=4, ACL06_AGGREGATE_CANDIDATE=5, ACL06_PACKAGE_RESULTS=6, ACL06_BUILD_ACL07_HANDOFF=7 };
#endif
