class SAEDV437Error(Exception): pass
class ContractError(SAEDV437Error): pass
class UpstreamError(SAEDV437Error): pass
class ConstitutionError(SAEDV437Error): pass
class InstrumentError(SAEDV437Error): pass
class FXError(SAEDV437Error): pass
class CostError(SAEDV437Error): pass
class LiquidityError(SAEDV437Error): pass
class ImpactError(SAEDV437Error): pass
class DependenceError(SAEDV437Error): pass
class PortfolioError(SAEDV437Error): pass
class CapacityError(SAEDV437Error): pass
class AllocationError(SAEDV437Error): pass
class SchedulingError(SAEDV437Error): pass
class EconomicsError(SAEDV437Error): pass
class StressError(SAEDV437Error): pass
class LedgerError(SAEDV437Error): pass
class ReconciliationError(SAEDV437Error): pass
class GovernanceError(SAEDV437Error): pass
class AuthorityError(SAEDV437Error): pass
