#ifndef __UCEI12_ENUMS_MQH__
#define __UCEI12_ENUMS_MQH__

enum UCEI12_GATE_OUTCOME
  {
   UCEI12_GATE_REJECT=0,
   UCEI12_GATE_CHALLENGE=1,
   UCEI12_GATE_PROMOTE=2
  };

enum UCEI12_EVIDENCE_STATUS
  {
   UCEI12_EVIDENCE_PASS=0,
   UCEI12_EVIDENCE_WARN=1,
   UCEI12_EVIDENCE_FAIL=2,
   UCEI12_EVIDENCE_MISSING=3,
   UCEI12_EVIDENCE_NOT_APPLICABLE=4
  };

enum UCEI12_SEVERITY
  {
   UCEI12_SEVERITY_CRITICAL=0,
   UCEI12_SEVERITY_HIGH=1,
   UCEI12_SEVERITY_MEDIUM=2,
   UCEI12_SEVERITY_LOW=3,
   UCEI12_SEVERITY_INFO=4
  };

enum UCEI12_TRIAL_DISPOSITION
  {
   UCEI12_TRIAL_ATTEMPTED=0,
   UCEI12_TRIAL_SKIPPED=1,
   UCEI12_TRIAL_INVALID=2,
   UCEI12_TRIAL_PRUNED=3,
   UCEI12_TRIAL_FAILED=4,
   UCEI12_TRIAL_TIMED_OUT=5,
   UCEI12_TRIAL_CANCELLED=6,
   UCEI12_TRIAL_SELECTED=7,
   UCEI12_TRIAL_ENSEMBLED=8,
   UCEI12_TRIAL_MANUAL_OVERRIDE=9
  };

#endif
