#ifndef __FP_I09_ENUMS_MQH__
#define __FP_I09_ENUMS_MQH__
enum ENUM_FP_I09_LEDGER_DISPOSITION { FP_I09_OBSERVED=0, FP_I09_ELIGIBLE_CONTENDER=1, FP_I09_QUOTA_WINNER=2, FP_I09_SUPPRESSED_BY_QUOTA=3, FP_I09_SUPPRESSED_BY_WW=4, FP_I09_BLOCKED=5 };
enum ENUM_FP_I09_RESERVATION_FINALITY { FP_I09_PROVISIONAL=0, FP_I09_FINAL=1 };
enum ENUM_FP_I09_SESSION_SEAL { FP_I09_SESSION_OPEN=0, FP_I09_SESSION_SEALED=1 };
#endif
