#ifndef __FP_I09_REGISTRY_MQH__
#define __FP_I09_REGISTRY_MQH__
#define FP_I09_PHASE_VERSION "1.0.0"
#define FP_I09_QUOTA_SCOPE "PAIR_GLOBAL_FIRST_ENTRY_PER_SESSION"
#define FP_I09_WINNER_POLICY "EARLIEST_HUNT_M1_TIME_WINS"
#define FP_I09_CONSUMPTION_POLICY "UNSET"
#endif
