#ifndef __FP_INDICATOR_PANEL_MQH__
#define __FP_INDICATOR_PANEL_MQH__
#include <AlphaLab/EXP0019/FaerieProtocol/I10/FP_I10_Contracts.mqh>
#include "FP_I12_Contracts.mqh"
#include "FP_I12_Hash.mqh"
class FP_I12_IndicatorPanel {
 private:
  long m_chart;SFP_I12_Config m_cfg;SFP_I12_PanelState m_state;string m_prefix;long m_updates;
  int Corner()const{if(m_cfg.dock==FP_I12_TOP_LEFT)return CORNER_LEFT_UPPER;if(m_cfg.dock==FP_I12_TOP_RIGHT)return CORNER_RIGHT_UPPER;if(m_cfg.dock==FP_I12_BOTTOM_LEFT)return CORNER_LEFT_LOWER;return CORNER_RIGHT_LOWER;}
  void Background(const int height){string n=m_prefix+"bg";if(ObjectFind(m_chart,n)<0)ObjectCreate(m_chart,n,OBJ_RECTANGLE_LABEL,0,0,0);ObjectSetInteger(m_chart,n,OBJPROP_CORNER,Corner());ObjectSetInteger(m_chart,n,OBJPROP_XDISTANCE,6);ObjectSetInteger(m_chart,n,OBJPROP_YDISTANCE,6);ObjectSetInteger(m_chart,n,OBJPROP_XSIZE,242);ObjectSetInteger(m_chart,n,OBJPROP_YSIZE,height);ObjectSetInteger(m_chart,n,OBJPROP_BGCOLOR,ColorToARGB(clrBlack,210));ObjectSetInteger(m_chart,n,OBJPROP_BORDER_COLOR,clrDimGray);ObjectSetInteger(m_chart,n,OBJPROP_BACK,false);ObjectSetInteger(m_chart,n,OBJPROP_SELECTABLE,false);}
  void Label(const string key,const string text,const int x,const int y,const color c,const int size=9){string n=m_prefix+key;if(ObjectFind(m_chart,n)<0)ObjectCreate(m_chart,n,OBJ_LABEL,0,0,0);ObjectSetInteger(m_chart,n,OBJPROP_CORNER,Corner());ObjectSetInteger(m_chart,n,OBJPROP_XDISTANCE,x);ObjectSetInteger(m_chart,n,OBJPROP_YDISTANCE,y);ObjectSetInteger(m_chart,n,OBJPROP_COLOR,c);ObjectSetInteger(m_chart,n,OBJPROP_FONTSIZE,size);ObjectSetString(m_chart,n,OBJPROP_FONT,"Arial");ObjectSetString(m_chart,n,OBJPROP_TEXT,text);ObjectSetInteger(m_chart,n,OBJPROP_SELECTABLE,false);}
  void Button(const string key,const string text,const int x,const int y,const int width,const bool active=true){string n=m_prefix+key;if(ObjectFind(m_chart,n)<0)ObjectCreate(m_chart,n,OBJ_BUTTON,0,0,0);ObjectSetInteger(m_chart,n,OBJPROP_CORNER,Corner());ObjectSetInteger(m_chart,n,OBJPROP_XDISTANCE,x);ObjectSetInteger(m_chart,n,OBJPROP_YDISTANCE,y);ObjectSetInteger(m_chart,n,OBJPROP_XSIZE,width);ObjectSetInteger(m_chart,n,OBJPROP_YSIZE,20);ObjectSetInteger(m_chart,n,OBJPROP_BGCOLOR,active?clrDarkSlateGray:clrDimGray);ObjectSetInteger(m_chart,n,OBJPROP_COLOR,active?clrWhite:clrSilver);ObjectSetString(m_chart,n,OBJPROP_TEXT,text);ObjectSetInteger(m_chart,n,OBJPROP_FONTSIZE,8);}
 public:
  FP_I12_IndicatorPanel(){m_chart=0;m_updates=0;}
  bool Initialize(const long chart,const SFP_I12_Config &cfg){m_chart=chart;m_cfg=cfg;m_prefix="FP12::"+FP_I12_Hash(cfg.instance_id)+"::P::";m_state.state=FP_I12_EXPANDED;m_state.mode=cfg.mode;m_state.page=0;m_state.page_count=1;m_state.selected_semantic_id="";m_state.state_hash="";return true;}
  void Render(const SFP_I10_EngineSnapshot &s,const SFP_I12_Filter &f){if(!m_cfg.panel_enabled||m_state.state==FP_I12_HIDDEN)return;Background(m_state.state==FP_I12_COLLAPSED?58:270);string health=(s.health.overall==FP_I10_HEALTH_READY?"READY":s.health.overall==FP_I10_HEALTH_DEGRADED?"DEGRADED":"BLOCKED");Label("title","FAERIE PROTOCOL  |  "+health,12,12,(s.health.overall==FP_I10_HEALTH_READY?clrLime:s.health.overall==FP_I10_HEALTH_DEGRADED?clrGold:clrTomato),10);Button("toggle",m_state.state==FP_I12_COLLAPSED?"EXPAND":"COLLAPSE",12,34,70);Button("mode","MODE: "+IntegerToString((int)m_state.mode),86,34,78);if(m_state.state==FP_I12_COLLAPSED){m_updates++;ChartRedraw(m_chart);return;}Label("pair","Instance: "+s.instance.instance_id,12,61,clrWhite);Label("data","Data: "+IntegerToString((int)s.health.data_readiness)+"  Rev: "+IntegerToString((int)s.output.source_revision_sequence),12,78,clrSilver);Label("ww","WW: "+DoubleToString(s.output.active_ww_direction,0),12,95,clrDeepSkyBlue);Label("sig","Confirmed: "+DoubleToString(s.output.confirmed_signal_count,0)+"  Allowed: "+DoubleToString(s.output.allowed_signal_count,0),12,112,clrWhite);Label("supp","Supp WW: "+DoubleToString(s.output.suppressed_by_ww_count,0)+"  Quota: "+DoubleToString(s.output.suppressed_by_quota_count,0),12,129,clrSilver);Label("quota","Quota winner: "+(s.output.quota_winner_present>0?"YES":"NO"),12,146,clrWhite);Label("decision","FP-DEC-012: "+m_cfg.open_decision_state,12,163,m_cfg.open_decision_state=="UNSET"?clrGold:clrLime);Label("filters","Projection Filters",12,184,clrSilver,8);Button("f_al","AL",12,201,26,f.show_al);Button("f_an","AN",40,201,26,f.show_an);Button("f_ln","LN",68,201,26,f.show_ln);Button("f_na","NA",96,201,26,f.show_na);Button("f_nl","NL",124,201,26,f.show_nl);Button("f_nn","NN",152,201,26,f.show_nn);Button("f_ww","WW",180,201,28,f.show_ww);Button("f_bull","BULL",12,224,46,f.show_bullish);Button("f_bear","BEAR",60,224,46,f.show_bearish);Button("f_supp","SUPP",108,224,46,f.show_suppressed);Button("f_hist","HIST",156,224,46,f.show_historical);Button("prev","<",12,247,28);Button("next",">",44,247,28);Button("export","EXPORT",76,247,58);Button("ack","ACK",138,247,42);m_updates++;ChartRedraw(m_chart);}
  ENUM_FP_I12_ACTION Handle(const int id,const string sparam){if(id!=CHARTEVENT_OBJECT_CLICK)return FP_I12_ACTION_NONE;if(sparam==m_prefix+"toggle"){m_state.state=(m_state.state==FP_I12_EXPANDED?FP_I12_COLLAPSED:FP_I12_EXPANDED);return FP_I12_ACTION_TOGGLE;}if(sparam==m_prefix+"mode"){m_state.mode=(ENUM_FP_I12_PANEL_MODE)(((int)m_state.mode+1)%4);return FP_I12_ACTION_MODE;}if(sparam==m_prefix+"prev"){if(m_state.page>0)m_state.page--;return FP_I12_ACTION_PREV;}if(sparam==m_prefix+"next"){m_state.page++;return FP_I12_ACTION_NEXT;}if(sparam==m_prefix+"export")return FP_I12_ACTION_EXPORT;if(sparam==m_prefix+"ack")return FP_I12_ACTION_ACK;if(StringFind(sparam,m_prefix+"f_")==0)return FP_I12_ACTION_FILTER;return FP_I12_ACTION_NONE;}
  bool FilterKey(const string sparam,string &key)const{string base=m_prefix+"f_";if(StringFind(sparam,base)!=0)return false;key=StringSubstr(sparam,StringLen(base));return key!="";}
  SFP_I12_PanelState State()const{return m_state;}long Updates()const{return m_updates;}
  void Shutdown(const bool remove=true){if(remove)ObjectsDeleteAll(m_chart,m_prefix);}
};
#endif
