#ifndef __SF18_RETCODE_MAP_MQH__
#define __SF18_RETCODE_MAP_MQH__
#include "SF18_LiveEnums.mqh"
ENUM_SF18_RETCODE_CLASS SF18_ClassifyRetcode(const uint code)
{
   if(code==0||code==TRADE_RETCODE_PLACED||code==TRADE_RETCODE_DONE||code==TRADE_RETCODE_DONE_PARTIAL)return SF18_RETCODE_SUCCESS;
   if(code==TRADE_RETCODE_REQUOTE||code==TRADE_RETCODE_TIMEOUT||code==TRADE_RETCODE_PRICE_CHANGED||code==TRADE_RETCODE_PRICE_OFF||code==TRADE_RETCODE_TOO_MANY_REQUESTS)return SF18_RETCODE_TRANSIENT;
   if(code==TRADE_RETCODE_MARKET_CLOSED)return SF18_RETCODE_MARKET;
   if(code==TRADE_RETCODE_NO_MONEY)return SF18_RETCODE_ACCOUNT;
   if(code==TRADE_RETCODE_CONNECTION)return SF18_RETCODE_CONNECTION;
   if(code==TRADE_RETCODE_TRADE_DISABLED||code==TRADE_RETCODE_SERVER_DISABLES_AT||code==TRADE_RETCODE_CLIENT_DISABLES_AT||code==TRADE_RETCODE_ONLY_REAL||code==TRADE_RETCODE_LIMIT_ORDERS||code==TRADE_RETCODE_LIMIT_VOLUME||code==TRADE_RETCODE_LIMIT_POSITIONS)return SF18_RETCODE_POLICY;
   if(code==TRADE_RETCODE_REJECT||code==TRADE_RETCODE_CANCEL||code==TRADE_RETCODE_ERROR||code==TRADE_RETCODE_INVALID||code==TRADE_RETCODE_INVALID_VOLUME||code==TRADE_RETCODE_INVALID_PRICE||code==TRADE_RETCODE_INVALID_STOPS||code==TRADE_RETCODE_INVALID_FILL||code==TRADE_RETCODE_INVALID_ORDER)return SF18_RETCODE_REQUEST;
   return SF18_RETCODE_UNKNOWN;
}
bool SF18_RetcodeSuccess(const uint code){return SF18_ClassifyRetcode(code)==SF18_RETCODE_SUCCESS;}
#endif
