#ifndef ALPHALAB_PORTFOLIO_CATALOG_MQH
#define ALPHALAB_PORTFOLIO_CATALOG_MQH
#define AL_PORTFOLIO_SCHEMA_VERSION "1.0.0"
#define AL_PORTFOLIO_CONTEXT_MINIMUM 2
#define AL_PORTFOLIO_ORDER_AUTHORITY false
#define AL_PORTFOLIO_BROKER_AUTHORITY false
#define AL_PORTFOLIO_NETWORK_AUTHORITY false
#endif
