#ifndef ALPHALAB_PORTFOLIO_ENUMS_MQH
#define ALPHALAB_PORTFOLIO_ENUMS_MQH
enum ALPortfolioDecision { AL_PORTFOLIO_REJECT=0, AL_PORTFOLIO_ABSTAIN=1, AL_PORTFOLIO_ALLOCATE=2 };
enum ALReservationState { AL_RESERVATION_REJECTED=0, AL_RESERVATION_RESERVED=1, AL_RESERVATION_CONSUMED=2, AL_RESERVATION_RELEASED=3 };
#endif
