#ifndef AL_ACL04_CLAIM_CEILING_MQH
#define AL_ACL04_CLAIM_CEILING_MQH

#define AL_ACL04_PHASE_ID                         "ACL-04"
#define AL_ACL04_CLAIM_CEILING                    "SETUP_DEFINITION_REFERENCE_ONLY"
#define AL_ACL04_LIVE_ORDER_SUBMISSION_ALLOWED    false
#define AL_ACL04_CAPITAL_ACTIVATION_ALLOWED       false
#define AL_ACL04_PRODUCTION_AUTHORIZED            false
#define AL_ACL04_RUNTIME_EXECUTION_AUTHORIZED      false

#endif
