#ifndef AL_ACL04_REASON_CODES_MQH
#define AL_ACL04_REASON_CODES_MQH

#define AL_ACL04_RC_HANDOFF_DIGEST_MISMATCH             "ACL04_HANDOFF_DIGEST_MISMATCH"
#define AL_ACL04_RC_SEARCH_AUTHORITY_DENIED             "ACL04_SEARCH_AUTHORITY_DENIED"
#define AL_ACL04_RC_AI_CANDIDATE_BUDGET_EXCEEDED       "ACL04_AI_CANDIDATE_BUDGET_EXCEEDED"
#define AL_ACL04_RC_AI_COMPUTE_BUDGET_EXCEEDED         "ACL04_AI_COMPUTE_BUDGET_EXCEEDED"
#define AL_ACL04_RC_AI_GENERATOR_OUTSIDE_AUTHORITY     "ACL04_AI_GENERATOR_OUTSIDE_SEARCH_AUTHORITY"
#define AL_ACL04_RC_TREATMENT_FAMILY_FORBIDDEN         "ACL04_TREATMENT_FAMILY_FORBIDDEN"
#define AL_ACL04_RC_REQUIRED_CLAUSE_MISSING             "ACL04_REQUIRED_CLAUSE_KIND_MISSING"
#define AL_ACL04_RC_PROTECTIVE_REFERENCE_REQUIRED       "ACL04_PROTECTIVE_REFERENCE_REQUIRED"
#define AL_ACL04_RC_FUTURE_DERIVED_ATOM_FORBIDDEN       "ACL04_FUTURE_DERIVED_ATOM_FORBIDDEN"
#define AL_ACL04_RC_ACTION_OUTSIDE_AUTHORITY             "ACL04_ACTION_OUTSIDE_AUTHORITY"
#define AL_ACL04_RC_RISK_OUTSIDE_ENVELOPE                "ACL04_RISK_OUTSIDE_TREATMENT_ENVELOPE"
#define AL_ACL04_RC_EXECUTION_SCOPE_FORBIDDEN            "ACL04_EXECUTION_SCOPE_FORBIDDEN"

#endif
