from __future__ import annotations
from .canonical import content_hash,stable_id

def build_certificate(evidence:dict,authority:dict,accepted:bool)->dict:
    gates={"upstream_verified":evidence["upstream"]["verified"],"protocol_frozen":True,"package_identity_verified":True,"minimum_labs_satisfied":evidence["registry"]["eligible_lab_count"]>=3,"pairwise_independence_verified":evidence["independence"]["all_pairs_independent"],"preregistration_ordering_verified":evidence["preregistration"]["all_pre_run"],"environment_default_deny":evidence["environments"]["default_deny_verified"],"one_run_per_lab":evidence["runs"]["one_run_per_lab"],"run_chain_verified":evidence["runs"]["chain_verification"]["verified"],"result_chain_verified":evidence["results"]["chain_verification"]["verified"],"semantic_hashes_reconciled":evidence["semantic"]["all_match"],"metrics_reconciled":evidence["metrics"]["all_within_tolerance"],"no_unresolved_disagreement":evidence["disagreement"]["unresolved_disagreements"]==0,"known_time_passed":evidence["known_time"]["passed"],"security_passed":evidence["security"]["passed"],"model_risk_passed":evidence["model_risk"]["passed"],"authority_zero":not any(authority["authority"].values())}
    body={"phase":"SAED_V4_30","version":"1.0.0","claim_class":"independent_multi_lab_replication_closed_reference_implementation","accepted_for_independent_multi_lab_replication_research_reference":accepted and all(gates.values()),"gates":gates,"evidence_hashes":{k:v.get(next((x for x in v if x.endswith('_hash')),''),content_hash(v)) if isinstance(v,dict) else content_hash(v) for k,v in evidence.items()},"authority_boundary":authority,"research_only":True,"synthetic_laboratory_fixture_claim":True,"real_external_lab_independence_claim":False,"external_institutional_replication_claim":False,"external_signature_claim":False,"physical_separation_claim":False,"real_alpha_claim":False,"prospective_success_claim":False,"promotion_authority":False,"runtime_executable":False,"risk_allocation_authority":False,"execution_authority":False,"production_authority":False,"online_learning_authority":False,"live_trading_authority":False}
    body["certificate_id"]=stable_id("v430_replication_certificate",body); body["certificate_hash"]=content_hash(body); return body

def handoff(certificate:dict)->dict:
    body={"phase":"SAED_V4_30","next_phase":"SAED_V4_31","certificate_id":certificate["certificate_id"],"certificate_hash":certificate["certificate_hash"],"entry_gates":{"independent_multi_lab_reference_accepted":certificate["accepted_for_independent_multi_lab_replication_research_reference"],"semantic_reconciliation_verified":certificate["gates"]["semantic_hashes_reconciled"],"metric_reconciliation_verified":certificate["gates"]["metrics_reconciled"],"authority_zero":certificate["gates"]["authority_zero"],"research_only":True,"synthetic_labs_only":True},"allowed_next_work":["formal_invariant_catalog","safety_property_specification","model_checking_reference","proof_obligation_registry","assurance_case_graph","hazard_and_mitigation_ledger","external_replication_evidence_attachment"],"forbidden_next_work":["claim_external_replication_from_synthetic_fixture","promotion_authorization","runtime_compilation","risk_allocation","order_submission","production_release","online_policy_mutation"],"authority":{"promotion":False,"runtime":False,"risk_allocation":False,"execution":False,"production":False,"online_learning":False},"research_only":True}
    body["handoff_id"]=stable_id("v4_30_to_v4_31",body); body["handoff_hash"]=content_hash(body); return body
