#ifndef __ACL09CONSTANTS_MQH__
#define __ACL09CONSTANTS_MQH__
#define ACL09_SCHEMA_VERSION "1.0.0"
#define ACL09_CLAIM_CEILING "MEMORY_AND_ACTIVE_PLANNING_REFERENCE_ONLY"
#define ACL09_RESEARCH_EXECUTION_ALLOWED false
#define ACL09_LIVE_ORDER_SUBMISSION_ALLOWED false
#define ACL09_CAPITAL_ACTIVATION_ALLOWED false
#endif
