from __future__ import annotations
from enum import IntEnum
class GenerationState(IntEnum): DRAFT=0; COMPILED=1; VALIDATED=2; WARMED=3; ACTIVE=4; RETIRED=5; FAILED=6
class SinkMode(IntEnum): MEMORY=0; JSONL=1; COMPOSITE=2
class FileScope(IntEnum): TERMINAL_LOCAL=0; COMMON=1
class RecordType(IntEnum): UNKNOWN=0; RUN_MANIFEST=1; GENERATION=2; ANATOMY_EVENT=10; FEATURE_SNAPSHOT=20; HEARTBEAT=30; GENERATION_ACTIVATED=40; GENERATION_RETIRED=41; GENERATION_ROLLBACK=42; SINK_ERROR=90
