from tools.repository_paths import find_repository_root
from pathlib import Path
BASE=find_repository_root(__file__)
REGISTRY_ROOT=BASE/'registry/history/acl/acl_11'
SCHEMA_ROOT=REGISTRY_ROOT/'schemas/v1'
POLICY_ROOT=REGISTRY_ROOT/'policies/v1'
HANDOFF_IN='ACL10_TO_ACL11'
HANDOFF_OUT='ACL11_TO_ACL12'
REQUIRED_UPSTREAM_ACTIONS={'VERIFY_PROMOTION_STATE_PACKAGE','ASSESS_RUNTIME_PARITY_PREREQUISITES','ISSUE_NON_EXECUTABLE_RUNTIME_CUSTODY_DECISION'}
FORBIDDEN_UPSTREAM_ACTIONS={'GENERATE_RUNTIME_FOR_INELIGIBLE_SUBJECT','MUTATE_PROMOTION_DECISIONS','BYPASS_RUNTIME_PARITY_GATES','AUTHORIZE_LIVE_ORDER','ACTIVATE_CAPITAL'}
REQUIRED_ACTION='ACL11_ASSESS_RUNTIME_CUSTODY'
CLAIM_CEILING='RUNTIME_CUSTODY_DECISION_REFERENCE_ONLY'
SERVICE_VERSION='1.0.0'
PARITY_STATUSES={'SATISFIED','UNSATISFIED','UNKNOWN','NOT_APPLICABLE'}
CUSTODY_DECISIONS={'NON_EXECUTABLE_NO_RUNTIME_CANDIDATES','NON_EXECUTABLE_PARITY_INCOMPLETE','ELIGIBLE_FOR_SIGNED_RUNTIME_BUILD_NOT_AUTHORIZED'}
