#ifndef __EXP0019_FP_I02_REASON_CODES_MQH__
#define __EXP0019_FP_I02_REASON_CODES_MQH__

#define FP_RC_CONFIRMED_ACTIVE "FP_RC_CONFIRMED_ACTIVE"
#define FP_RC_SUPPRESSED_BY_WW "FP_RC_SUPPRESSED_BY_WW"
#define FP_RC_SUPPRESSED_BY_QUOTA "FP_RC_SUPPRESSED_BY_QUOTA"
#define FP_RC_WW_NONE_ALLOW_BOTH "FP_RC_WW_NONE_ALLOW_BOTH"
#define FP_RC_WW_DATA_INCOMPLETE "FP_RC_WW_DATA_INCOMPLETE"
#define FP_RC_WW_NEUTRALIZED "FP_RC_WW_NEUTRALIZED"
#define FP_RC_CONFIRMATION_DEADLINE_MISSED "FP_RC_CONFIRMATION_DEADLINE_MISSED"
#define FP_RC_SYMMETRIC_SAME_M1 "FP_RC_SYMMETRIC_SAME_M1"
#define FP_RC_REFERENCE_INCOMPLETE "FP_RC_REFERENCE_INCOMPLETE"
#define FP_RC_REFERENCE_CONSUMED "FP_RC_REFERENCE_CONSUMED"
#define FP_RC_SELL_SPREAD_UNAVAILABLE "FP_RC_SELL_SPREAD_UNAVAILABLE"
#define FP_RC_GEOMETRY_INVALID "FP_RC_GEOMETRY_INVALID"
#define FP_RC_QUOTA_POLICY_UNSET "FP_RC_QUOTA_POLICY_UNSET"
#define FP_RC_CANCELLED_BY_SECOND_TOUCH "FP_RC_CANCELLED_BY_SECOND_TOUCH"
#define FP_RC_NON_CANONICAL_PROFILE "FP_RC_NON_CANONICAL_PROFILE"
#define FP_RC_READY "FP_RC_READY"
#define FP_RC_INVALID_CONFIG "FP_RC_INVALID_CONFIG"
#define FP_RC_UNKNOWN_ENUM "FP_RC_UNKNOWN_ENUM"
#define FP_RC_INVALID_SHA256 "FP_RC_INVALID_SHA256"
#define FP_RC_INVALID_SEMVER "FP_RC_INVALID_SEMVER"
#define FP_RC_INVALID_IDENTIFIER "FP_RC_INVALID_IDENTIFIER"
#define FP_RC_NONFINITE_NUMBER "FP_RC_NONFINITE_NUMBER"
#define FP_RC_IDENTITY_CONFLICT "FP_RC_IDENTITY_CONFLICT"
#define FP_RC_ILLEGAL_TRANSITION "FP_RC_ILLEGAL_TRANSITION"
#define FP_RC_DUPLICATE_EVENT_DEDUPED "FP_RC_DUPLICATE_EVENT_DEDUPED"
#define FP_RC_CHECKPOINT_VERSION_MISMATCH "FP_RC_CHECKPOINT_VERSION_MISMATCH"
#define FP_RC_SOURCE_REVISION_MISMATCH "FP_RC_SOURCE_REVISION_MISMATCH"
#define FP_RC_DEPENDENCY_HASH_MISMATCH "FP_RC_DEPENDENCY_HASH_MISMATCH"
#define FP_RC_OPEN_DECISION_BLOCKS_LIVE "FP_RC_OPEN_DECISION_BLOCKS_LIVE"
#define FP_RC_PROJECTION_ONLY_CHANGE "FP_RC_PROJECTION_ONLY_CHANGE"
#define FP_RC_SEMANTIC_CONFIG_CHANGED "FP_RC_SEMANTIC_CONFIG_CHANGED"
#define FP_RC_WINDOW_INTERVAL_INVALID "FP_RC_WINDOW_INTERVAL_INVALID"
#define FP_RC_SYMBOL_PAIR_INVALID "FP_RC_SYMBOL_PAIR_INVALID"
#define FP_RC_RELATION_DESCRIPTOR_INVALID "FP_RC_RELATION_DESCRIPTOR_INVALID"
#define FP_RC_LIVE_AUTHORITY_FORBIDDEN "FP_RC_LIVE_AUTHORITY_FORBIDDEN"

int FP_I02_ReasonCodeCount() { return 35; }

bool FP_I02_IsKnownReasonCode(const string code)
  {
   string values[35]={
      FP_RC_CONFIRMED_ACTIVE,FP_RC_SUPPRESSED_BY_WW,FP_RC_SUPPRESSED_BY_QUOTA,FP_RC_WW_NONE_ALLOW_BOTH,
      FP_RC_WW_DATA_INCOMPLETE,FP_RC_WW_NEUTRALIZED,FP_RC_CONFIRMATION_DEADLINE_MISSED,FP_RC_SYMMETRIC_SAME_M1,
      FP_RC_REFERENCE_INCOMPLETE,FP_RC_REFERENCE_CONSUMED,FP_RC_SELL_SPREAD_UNAVAILABLE,FP_RC_GEOMETRY_INVALID,
      FP_RC_QUOTA_POLICY_UNSET,FP_RC_CANCELLED_BY_SECOND_TOUCH,FP_RC_NON_CANONICAL_PROFILE,FP_RC_READY,
      FP_RC_INVALID_CONFIG,FP_RC_UNKNOWN_ENUM,FP_RC_INVALID_SHA256,FP_RC_INVALID_SEMVER,FP_RC_INVALID_IDENTIFIER,
      FP_RC_NONFINITE_NUMBER,FP_RC_IDENTITY_CONFLICT,FP_RC_ILLEGAL_TRANSITION,FP_RC_DUPLICATE_EVENT_DEDUPED,
      FP_RC_CHECKPOINT_VERSION_MISMATCH,FP_RC_SOURCE_REVISION_MISMATCH,FP_RC_DEPENDENCY_HASH_MISMATCH,
      FP_RC_OPEN_DECISION_BLOCKS_LIVE,FP_RC_PROJECTION_ONLY_CHANGE,FP_RC_SEMANTIC_CONFIG_CHANGED,
      FP_RC_WINDOW_INTERVAL_INVALID,FP_RC_SYMBOL_PAIR_INVALID,FP_RC_RELATION_DESCRIPTOR_INVALID,
      FP_RC_LIVE_AUTHORITY_FORBIDDEN
   };
   for(int i=0;i<35;i++) if(values[i]==code) return true;
   return false;
  }

#endif
