#ifndef __EXP0019_FP_I02_ENUMS_MQH__
#define __EXP0019_FP_I02_ENUMS_MQH__

enum FP_I02_HealthState { FP_HEALTH_READY=0, FP_HEALTH_DEGRADED=1, FP_HEALTH_BLOCKED=2 };
enum FP_I02_ContextProfile { FP_PROFILE_CANONICAL_RESEARCH=0, FP_PROFILE_CANONICAL_PAPER=1, FP_PROFILE_CANONICAL_LIVE=2, FP_PROFILE_NON_CANONICAL_EXPERIMENT=3 };
enum FP_I02_ExecutionAuthority { FP_AUTHORITY_NONE=0, FP_AUTHORITY_PAPER_ONLY=1, FP_AUTHORITY_LIVE=2 };
enum FP_I02_WindowKind { FP_WINDOW_A=0, FP_WINDOW_L=1, FP_WINDOW_N=2, FP_WINDOW_W=3 };
enum FP_I02_WindowScope { FP_SCOPE_SAME_TRADING_DAY=0, FP_SCOPE_CURRENT_TRADING_DAY=1, FP_SCOPE_EXACT_PRIOR_CALENDAR_OFFSET=2, FP_SCOPE_PREVIOUS_COMPLETED_NY_WEEK=3, FP_SCOPE_CURRENT_NY_WEEK=4 };
enum FP_I02_RelationCode { FP_REL_AL=0, FP_REL_AN=1, FP_REL_LN=2, FP_REL_NA=3, FP_REL_NL=4, FP_REL_NN=5, FP_REL_WW=6 };
enum FP_I02_Direction { FP_DIRECTION_BULLISH=0, FP_DIRECTION_BEARISH=1 };
enum FP_I02_SymbolRole { FP_ROLE_HUNTER=0, FP_ROLE_PROTECTED=1 };
enum FP_I02_PriceSide { FP_SIDE_HIGH=0, FP_SIDE_LOW=1 };
enum FP_I02_DataState { FP_DATA_COMPLETE=0, FP_DATA_INCOMPLETE=1, FP_DATA_MISSING=2, FP_DATA_STALE=3, FP_DATA_INVALID=4 };
enum FP_I02_ReferenceState { FP_REF_FRESH=0, FP_REF_HUNTER_SEEN=1, FP_REF_CONSUMED_BY_PROTECTED_TOUCH=2, FP_REF_EXPIRED=3, FP_REF_SUPERSEDED=4 };
enum FP_I02_CandidateState { FP_CAND_OBSERVED=0, FP_CAND_RAW=1, FP_CAND_CONFIRMED=2, FP_CAND_CANCELLED_SECOND_TOUCH=3, FP_CAND_EXPIRED_SESSION_DEADLINE=4, FP_CAND_INVALID_DATA=5 };
enum FP_I02_WWState { FP_WW_RAW=0, FP_WW_CONFIRMED=1, FP_WW_NEUTRALIZED=2, FP_WW_EXPIRED=3, FP_WW_INVALID_DATA=4 };
enum FP_I02_QuotaState { FP_QUOTA_AVAILABLE=0, FP_QUOTA_RESERVED=1, FP_QUOTA_CONSUMED=2, FP_QUOTA_RELEASED=3 };
enum FP_I02_EligibilityState { FP_ELIGIBLE=0, FP_SUPPRESSED=1, FP_BLOCKED=2, FP_NOT_APPLICABLE=3 };
enum FP_I02_QuotaConsumptionPolicy { FP_QUOTA_POLICY_UNSET=0, FP_QUOTA_PLAN_CREATED=1, FP_QUOTA_ORDER_ATTEMPTED=2, FP_QUOTA_ORDER_ACCEPTED=3, FP_QUOTA_FILLED=4, FP_QUOTA_TWO_STAGE=5 };
enum FP_I02_Severity { FP_SEVERITY_INFO=0, FP_SEVERITY_WARNING=1, FP_SEVERITY_ERROR=2, FP_SEVERITY_CRITICAL=3 };

#endif
