#ifndef __SF07_CONTEXT_ENUMS_MQH__
#define __SF07_CONTEXT_ENUMS_MQH__

enum ENUM_SF07_UPDATE_SCOPE
{
   SF07_UPDATE_STATIC = 0,
   SF07_UPDATE_EVENT = 1,
   SF07_UPDATE_TICK = 2,
   SF07_UPDATE_NEW_BAR = 3,
   SF07_UPDATE_TIMER = 4
};

enum ENUM_SF07_MISSING_POLICY
{
   SF07_MISSING_FAIL = 0,
   SF07_MISSING_DEFAULT = 1,
   SF07_MISSING_ZERO = 2
};

enum ENUM_SF07_CONTEXT_STATUS
{
   SF07_CONTEXT_EMPTY = 0,
   SF07_CONTEXT_COMPILING = 1,
   SF07_CONTEXT_READY = 2,
   SF07_CONTEXT_BUILDING = 3,
   SF07_CONTEXT_DEGRADED = 4,
   SF07_CONTEXT_FAILED = 5
};

enum ENUM_SF07_INVALIDATION_REASON
{
   SF07_INVALIDATE_NONE = 0,
   SF07_INVALIDATE_EVENT = 1,
   SF07_INVALIDATE_TICK = 2,
   SF07_INVALIDATE_NEW_BAR = 3,
   SF07_INVALIDATE_TIMER = 4,
   SF07_INVALIDATE_DEPENDENCY = 5,
   SF07_INVALIDATE_GENERATION = 6,
   SF07_INVALIDATE_MANUAL = 7
};

string SF07_UpdateScopeToString(const ENUM_SF07_UPDATE_SCOPE value)
{
   if(value == SF07_UPDATE_STATIC) return "STATIC";
   if(value == SF07_UPDATE_EVENT) return "EVENT";
   if(value == SF07_UPDATE_TICK) return "TICK";
   if(value == SF07_UPDATE_NEW_BAR) return "NEW_BAR";
   if(value == SF07_UPDATE_TIMER) return "TIMER";
   return "UNKNOWN";
}

string SF07_MissingPolicyToString(const ENUM_SF07_MISSING_POLICY value)
{
   if(value == SF07_MISSING_FAIL) return "FAIL";
   if(value == SF07_MISSING_DEFAULT) return "DEFAULT";
   if(value == SF07_MISSING_ZERO) return "ZERO";
   return "UNKNOWN";
}

#endif
