#ifndef ALPHALAB_ACL10_PREREQUISITE_STATUS_MQH
#define ALPHALAB_ACL10_PREREQUISITE_STATUS_MQH
enum ENUM_ACL10_PREREQUISITE_STATUS { ACL10_PREREQ_SATISFIED=0, ACL10_PREREQ_UNSATISFIED=1, ACL10_PREREQ_UNKNOWN=2, ACL10_PREREQ_NOT_APPLICABLE=3 };
#endif
