#ifndef ALPHALAB_ACL10_STATE_IDS_MQH
#define ALPHALAB_ACL10_STATE_IDS_MQH
enum ENUM_ACL10_STATE { ACL10_RESEARCH_HOLD=0, ACL10_VALIDATION_FAILED_ARCHIVED=1, ACL10_BASELINE_REFERENCE_ONLY=2, ACL10_DIAGNOSTIC_QUARANTINED=3, ACL10_PROMOTION_REVIEW_ELIGIBLE=4, ACL10_PAPER_CANDIDATE=5, ACL10_SHADOW_CANDIDATE=6, ACL10_MICRO_LIVE_CANDIDATE=7, ACL10_CHAMPION=8, ACL10_SUSPENDED=9, ACL10_RETIRED=10 };
#endif
