from enum import Enum,IntFlag
class PluginKind(str,Enum): ANATOMY="ANATOMY";FEATURE="FEATURE";CANDIDATE="CANDIDATE";MODEL="MODEL";RISK="RISK";EXECUTION="EXECUTION"
class UpdateScope(IntFlag): NONE=0;TICK=1;NEW_BAR=2;TIMER=4;HISTORY_REBUILD=8;REPLAY=16
class Capability(IntFlag): NONE=0;TICK_INPUT=1;CLOSED_BAR_INPUT=2;MULTI_SYMBOL=4;MULTI_TIMEFRAME=8;TIMER_INPUT=16;HISTORY_REBUILD=32;REPLAY_SAFE=64;DETERMINISTIC=128;FAST_PATH_SAFE=256;STATEFUL=512;EMITS_PARENT_LINKS=1024;EMITS_CLUSTER_ID=2048;REQUIRES_SYMBOL_SPEC=4096;REQUIRES_SYNCHRONIZATION=8192
class RequirementKind(str,Enum): TICK="TICK";CLOSED_BARS="CLOSED_BARS";SYMBOL_SPEC="SYMBOL_SPEC"
class RequirementStrength(str,Enum): OPTIONAL="OPTIONAL";REQUIRED="REQUIRED"
class QueueOverflowPolicy(str,Enum): REJECT_NEW="REJECT_NEW";DROP_OLDEST="DROP_OLDEST";FAIL_PLUGIN="FAIL_PLUGIN"
class PluginStatus(str,Enum): CREATED="CREATED";BOUND="BOUND";INITIALIZED="INITIALIZED";RUNNING="RUNNING";STOPPED="STOPPED";FAILED="FAILED"
