#ifndef __SF09_OUTCOME_ENUMS_MQH__
#define __SF09_OUTCOME_ENUMS_MQH__

enum ENUM_SF09_OBSERVATION_KIND
{
   SF09_OBSERVATION_TICK=1,
   SF09_OBSERVATION_CLOSED_BAR=2
};

enum ENUM_SF09_DATA_FIDELITY
{
   SF09_FIDELITY_UNKNOWN=0,
   SF09_FIDELITY_BAR_APPROXIMATION=1,
   SF09_FIDELITY_SYNTHETIC_TICK=2,
   SF09_FIDELITY_REAL_TICK=3
};

enum ENUM_SF09_RUNTIME_STATE
{
   SF09_STATE_EMPTY=0,
   SF09_STATE_REGISTERED=1,
   SF09_STATE_WAITING_ACTIVATION=2,
   SF09_STATE_PENDING_FILL=3,
   SF09_STATE_FILLED=4,
   SF09_STATE_PARTIAL=5,
   SF09_STATE_CLOSED=6,
   SF09_STATE_EXPIRED=7,
   SF09_STATE_INVALIDATED=8,
   SF09_STATE_AMBIGUOUS=9,
   SF09_STATE_REJECTED=10
};

enum ENUM_SF09_EXIT_REASON
{
   SF09_EXIT_NONE=0,
   SF09_EXIT_TARGET=1,
   SF09_EXIT_STOP=2,
   SF09_EXIT_TIME=3,
   SF09_EXIT_ENTRY_EXPIRED=4,
   SF09_EXIT_INVALIDATED_BEFORE_FILL=5,
   SF09_EXIT_AMBIGUOUS_BAR=6,
   SF09_EXIT_DATA_FAILURE=7,
   SF09_EXIT_MANUAL_TEST=8,
   SF09_EXIT_PARTIAL_TARGET_THEN_STOP=9,
   SF09_EXIT_PARTIAL_TARGET_THEN_TIME=10
};

enum ENUM_SF09_AMBIGUITY_POLICY
{
   SF09_AMBIGUITY_STOP_FIRST=1,
   SF09_AMBIGUITY_TARGET_FIRST=2,
   SF09_AMBIGUITY_EXCLUDE=3,
   SF09_AMBIGUITY_REQUIRE_LOWER_FIDELITY=4
};

enum ENUM_SF09_GAP_POLICY
{
   SF09_GAP_AT_TRIGGER=1,
   SF09_GAP_AT_OBSERVED_OPEN_CONSERVATIVE=2,
   SF09_GAP_REJECT=3
};

enum ENUM_SF09_MARKET_FILL_POLICY
{
   SF09_MARKET_FILL_AT_FIRST_OBSERVATION=1,
   SF09_MARKET_FILL_AT_REQUESTED_PRICE=2,
   SF09_MARKET_FILL_CONSERVATIVE_SIDE=3
};

enum ENUM_SF09_COST_COMPONENT
{
   SF09_COST_ENTRY_SPREAD=1,
   SF09_COST_EXIT_SPREAD=2,
   SF09_COST_ENTRY_SLIPPAGE=3,
   SF09_COST_EXIT_SLIPPAGE=4,
   SF09_COST_COMMISSION=5,
   SF09_COST_OTHER=6
};

enum ENUM_SF09_PATH_EVENT_KIND
{
   SF09_PATH_REGISTERED=1,
   SF09_PATH_ACTIVATED=2,
   SF09_PATH_FILLED=3,
   SF09_PATH_FAVORABLE_EXTREME=4,
   SF09_PATH_ADVERSE_EXTREME=5,
   SF09_PATH_TARGET_TOUCH=6,
   SF09_PATH_STOP_TOUCH=7,
   SF09_PATH_PARTIAL_EXIT=8,
   SF09_PATH_TIME_EXIT=9,
   SF09_PATH_EXPIRED=10,
   SF09_PATH_AMBIGUOUS=11,
   SF09_PATH_CLOSED=12
};

enum ENUM_SF09_QUEUE_OVERFLOW_POLICY
{
   SF09_QUEUE_REJECT_NEW=1,
   SF09_QUEUE_DROP_OLDEST=2,
   SF09_QUEUE_FAIL_ENGINE=3
};

#define SF09_MAX_ACTIVE_CANDIDATES 256
#define SF09_MAX_OUTCOME_QUEUE 256
#define SF09_MAX_PATH_EVENTS 96
#define SF09_MAX_COST_MODELS 32

#endif
