from tools.strategy_factory.acl_os.acl_15.static_validation import validate_registry
from tools.strategy_factory.acl_os.acl_15.delivery_validation import validate_delivery
def test_registry(root): assert validate_registry(root)['passed']
def test_delivery(root): assert validate_delivery(root)['passed']
def test_schema_volume(root): assert validate_registry(root)['schema_count']>=20
def test_policy_volume(root): assert validate_registry(root)['policy_count']>=20
def test_mql5_no_forbidden_api(root): assert validate_registry(root)['mql5_forbidden_hits']==[]
def test_phase_docs(root): assert (root/'docs/alpha_lab_master_architecture/context_lifecycle_os/12_PHASE_DELIVERIES/ACL_15/00_MOC.md').is_file()
def test_atomic_docs(root): assert (root/'docs/alpha_lab_master_architecture/context_lifecycle_os/13_ATOMIC_CONCEPTS/ACL_15/001_FLEET_ID.md').is_file()
