from __future__ import annotations
from collections import Counter
from typing import Any
from .canonical import stable_id,with_digest,digest_object
MAP={'BASELINE_REFERENCE_ONLY':('BASELINE_REFERENCE','NEUTRAL_REFERENCE'),'EVIDENCE_INSUFFICIENT':('INSUFFICIENT_EVIDENCE','UNKNOWN'),'VALIDATION_FAILED':('NEGATIVE_VALIDATION','NEGATIVE'),'VALIDATION_ELIGIBLE_FOR_REPORTING':('REPORTABLE_EVIDENCE','PROVISIONAL_EVIDENCE'),'DIAGNOSTIC_EXCLUDED':('DIAGNOSTIC_EXCLUSION','NON_SELECTABLE_DIAGNOSTIC')}
QUESTION_MAP={'EXECUTION_ECONOMICS':'COLLECT_EXECUTION_COST_EVIDENCE','OOD_AND_ABSTENTION':'BUILD_OOD_AND_ABSTENTION_EVIDENCE','PROSPECTIVE_EVIDENCE':'RUN_PROSPECTIVE_SHADOW_EVALUATION','INDEPENDENT_REPLICATION':'SCHEDULE_INDEPENDENT_REPLICATION','DISTRIBUTIONAL_ROBUSTNESS':'COLLECT_TAIL_PATH_EVIDENCE','MINIMUM_SUPPORT':'INCREASE_MATURE_SUPPORT','TEMPORAL_GENERALIZATION':'ADD_TEMPORAL_HOLDOUT_EVIDENCE','OVERFIT_CONTROL':'ADD_OVERFIT_CONTROL_EVIDENCE','MULTIPLE_TESTING':'REDUCE_OR_REFREEZE_TESTING_FAMILY','STATISTICAL_SIGNIFICANCE':'COLLECT_SIGNIFICANCE_EVIDENCE','EFFECT_SIZE':'CLARIFY_DECISION_RELEVANT_EFFECT'}
def extract_record(report_id:str,candidate_report:dict[str,Any])->dict[str,Any]:
    cls,polarity=MAP[candidate_report['decision_status']]
    unknown=[g['gate_id'] for g in candidate_report['gates'] if g['status']=='UNKNOWN']; failed=[g['gate_id'] for g in candidate_report['gates'] if g['status']=='FAIL']; passed=[g['gate_id'] for g in candidate_report['gates'] if g['status']=='PASS']
    questions=sorted({QUESTION_MAP[x] for x in unknown if x in QUESTION_MAP})
    fingerprint=digest_object({'decision_status':candidate_report['decision_status'],'reason_codes':candidate_report['reason_codes'],'gate_statuses':[(g['gate_id'],g['status']) for g in candidate_report['gates']]})
    body={'schema_version':'1.0.0','experience_id':stable_id('EXP08',report_id,candidate_report['setup_id'],fingerprint),'report_id':report_id,'setup_id':candidate_report['setup_id'],'candidate_id':candidate_report['candidate_id'],'lane':candidate_report['lane'],'origin':candidate_report['origin'],'experience_class':cls,'knowledge_polarity':polarity,'decision_status':candidate_report['decision_status'],'reason_codes':candidate_report['reason_codes'],'passed_gate_ids':passed,'failed_gate_ids':failed,'unknown_gate_ids':unknown,'bounded_research_questions':questions,'duplicate_fingerprint':fingerprint,'source_decision_digest':candidate_report['source_decision_digest'],'source_candidate_report_digest':candidate_report['candidate_report_digest'],'semantic_interpretation_added':False,'doctrine_amendment_allowed':False,'promotion_allowed':False,'live_order_submission_allowed':False,'capital_activation_allowed':False}
    return with_digest(body,'experience_digest')
def build_bundle(report_id:str,records:list[dict[str,Any]])->dict[str,Any]:
    counts=dict(Counter(x['experience_class'] for x in records)); unknown=sum(bool(x['unknown_gate_ids']) for x in records); negative=sum(x['experience_class']=='NEGATIVE_VALIDATION' for x in records)
    return with_digest({'schema_version':'1.0.0','report_id':report_id,'record_count':len(records),'experience_counts':counts,'records':[{'experience_id':x['experience_id'],'experience_digest':x['experience_digest'],'setup_id':x['setup_id'],'experience_class':x['experience_class']} for x in records],'records_with_unknown_evidence':unknown,'negative_validation_records':negative,'diagnostic_records_selectable':False,'memory_ingestion_status':'NOT_INGESTED','active_planning_status':'NOT_RUN','promotion_allowed':False,'live_order_submission_allowed':False,'capital_activation_allowed':False},'experience_bundle_digest')
