from __future__ import annotations
import re
from .canonical import content_hash,seal
from .errors import CodegenError

def _ident(x:str)->str:return re.sub(r"[^A-Za-z0-9_]","_",x)
def generate_mql5_sources(bundle:dict,feature_abi:dict,policy:dict,model:dict,numeric:dict)->dict:
 names=[f["name"] for f in feature_abi["fields"]]
 enum_lines=[f"   SAEDV438_FEATURE_{_ident(n).upper()} = {i}" for i,n in enumerate(names)]
 weight_lines=[f"   {float(w):.12g}" for w in model["weights"]]
 header=f'''#ifndef SAED_V4_38_COMPILED_RUNTIME_MQH\n#define SAED_V4_38_COMPILED_RUNTIME_MQH\n// SAED_V4_38 research-only immutable generated runtime.\n#define SAED_V4_38_BUNDLE_HASH \"{bundle['bundle_hash']}\"\n#define SAED_V4_38_POLICY_HASH \"{policy['frozen_graph_hash']}\"\n#define SAED_V4_38_MODEL_HASH \"{model['frozen_model_hash']}\"\n#define SAED_V4_38_FEATURE_COUNT {len(names)}\n#define SAED_V4_38_ORDER_SUBMISSION_ALLOWED 0\n#define SAED_V4_38_CAPITAL_ACTIVATION_ALLOWED 0\nenum SAEDV438FeatureIndex {{\n{',\n'.join(enum_lines)}\n}};\nstatic const double SAEDV438Weights[{len(weight_lines)}]={{\n{',\n'.join(weight_lines)}\n}};\nstatic const double SAEDV438Bias={float(model['bias']):.12g};\ndouble SAEDV438Quantize(const double x){{return MathRound(x*100000000.0)/100000000.0;}}\ndouble SAEDV438LinearScore(const double &features[]){{double s=SAEDV438Bias; for(int i=0;i<{len(weight_lines)};i++) s+=SAEDV438Weights[i]*features[i]; return SAEDV438Quantize(s);}}\nbool SAEDV438Evaluate(const double &f[],string &decision,string &treatment,double &confidence,double &net_edge,double &size_fraction){{\n if(ArraySize(f)!={len(names)}){{decision=\"ABSTAIN\";treatment=\"BASELINE\";confidence=0;net_edge=0;size_fraction=0;return false;}}\n const double model_score=SAEDV438LinearScore(f);\n net_edge=SAEDV438Quantize(f[6]-f[7]);\n const bool allowed=(f[11]<=0.20 && f[8]<=0.80 && net_edge>=3.0 && f[9]>=0.05 && f[9]<=0.95 && f[10]<=0.70 && model_score>=0.55);\n if(!allowed){{decision=\"ABSTAIN\";treatment=\"BASELINE\";confidence=0;size_fraction=0;return false;}}\n decision=\"SELECT\";treatment=\"TRT_RUNTIME_REFERENCE\";confidence=SAEDV438Quantize(MathMax(0.0,MathMin(1.0,model_score)));size_fraction=SAEDV438Quantize(confidence*0.25);return true;\n}}\n#endif\n'''
 expert=f'''#property strict\n#include <StrategyFactory/SAED/V4_38/SAEDV438CompiledRuntime.mqh>\n// SAED_V4_38 parity harness only. No orders, no capital activation.\nint OnInit(){{Print(\"SAED V4-38 research-only parity harness: \",SAED_V4_38_BUNDLE_HASH);return(INIT_SUCCEEDED);}}\nvoid OnTick(){{/* intentionally non-executable */}}\n'''
 if 'OrderSend(' in header+expert or 'CTrade' in header+expert:raise CodegenError("authority token in generated source")
 files=[{"path":"mql5/Include/StrategyFactory/SAED/V4_38/SAEDV438CompiledRuntime.mqh","role":"COMPILED_RUNTIME","content":header,"content_hash":content_hash(header),"size_bytes":len(header.encode()),"executable":False,"research_only":True},{"path":"mql5/Experts/StrategyFactory/SAED/V4_38/SAEDV438ParityHarness.mq5","role":"PARITY_HARNESS","content":expert,"content_hash":content_hash(expert),"size_bytes":len(expert.encode()),"executable":False,"research_only":True}]
 return seal({"phase":"SAED_V4_38","generator_version":"1.0.0","files":files,"source_count":len(files),"bundle_hash":bundle["bundle_hash"],"research_only":True,"production_authorized":False},"v438_codegen","codegen_id","codegen_hash")
