class SAEDV438Error(Exception): pass
class ContractError(SAEDV438Error): pass
class UpstreamError(SAEDV438Error): pass
class ConstitutionError(SAEDV438Error): pass
class ABIError(SAEDV438Error): pass
class NumericProfileError(SAEDV438Error): pass
class ClockProfileError(SAEDV438Error): pass
class CompilerError(SAEDV438Error): pass
class IntegrityError(SAEDV438Error): pass
class RuntimeError438(SAEDV438Error): pass
class StateError(SAEDV438Error): pass
class FallbackError(SAEDV438Error): pass
class ParityError(SAEDV438Error): pass
class CodegenError(SAEDV438Error): pass
class ExternalEvidenceError(SAEDV438Error): pass
class ReleaseError(SAEDV438Error): pass
class GovernanceError(SAEDV438Error): pass
class AuthorityError(SAEDV438Error): pass
