from __future__ import annotations
from typing import Protocol
from .models import *
from .enums import PolicyDecision
class EntryPolicy(Protocol):
    descriptor: PolicyDescriptor
    def admissible(self,event:AnatomyEvent,snapshot:FeatureSnapshot,frame:ContextFrame,params:PolicyParameters)->tuple[PolicyDecision,str]:...
    def build(self,event:AnatomyEvent,snapshot:FeatureSnapshot,frame:ContextFrame,params:PolicyParameters)->EntryPlan:...
class StopPolicy(Protocol):
    descriptor: PolicyDescriptor
    def admissible(self,event:AnatomyEvent,snapshot:FeatureSnapshot,frame:ContextFrame,params:PolicyParameters)->tuple[PolicyDecision,str]:...
    def build(self,event:AnatomyEvent,snapshot:FeatureSnapshot,frame:ContextFrame,params:PolicyParameters)->StopPlan:...
class ExitPolicy(Protocol):
    descriptor: PolicyDescriptor
    def admissible(self,event:AnatomyEvent,snapshot:FeatureSnapshot,frame:ContextFrame,params:PolicyParameters)->tuple[PolicyDecision,str]:...
    def build(self,event:AnatomyEvent,snapshot:FeatureSnapshot,frame:ContextFrame,params:PolicyParameters)->ExitPlan:...
