#ifndef ALPHALAB_ACL06_CONSTANTS_MQH
#define ALPHALAB_ACL06_CONSTANTS_MQH
#define ACL06_PHASE_ID "ACL-06"
#define ACL06_CLAIM_CEILING "BOUNDED_RESEARCH_EXECUTION_REFERENCE_ONLY"
#define ACL06_HANDOFF_IN "ACL05_TO_ACL06"
#define ACL06_HANDOFF_OUT "ACL06_TO_ACL07"
#endif
