#ifndef __FP_AUDIT_MQH__
#define __FP_AUDIT_MQH__
#property strict

#include "FP_Renderer.mqh"

void FP_PrintSummary(const string symbol,
                     const ENUM_TIMEFRAMES period,
                     const int bars,
                     const int scale_count,
                     const FP_DetectResult &result,
                     const int drawn)
{
   string msg = "FP_SUMMARY";
   msg += " symbol=" + symbol;
   msg += " tf=" + EnumToString(period);
   msg += " bars=" + IntegerToString(bars);
   msg += " scales=" + IntegerToString(scale_count);
   msg += " raw_nodes=" + IntegerToString(result.raw_nodes_total);
   msg += " canonical_nodes=" + IntegerToString(result.nodes_total);
   msg += " confirmed_nodes=" + IntegerToString(result.confirmed_nodes_total);
   msg += " pending_nodes=" + IntegerToString(result.pending_nodes_total);
   msg += " hooks=" + IntegerToString(result.hooks_total);
   msg += " nd=" + IntegerToString(result.nd_total);
   msg += " hook_contexts=" + IntegerToString(result.hook_contexts_total);
   msg += " hook_rejected=" + IntegerToString(result.hook_contexts_rejected_total);
   msg += " hook_branch_scans=" + IntegerToString(result.hook_branch_scans_total);
   msg += " hook_len5plus=" + IntegerToString(result.hook_branch_len5plus_total);
   msg += " hook_retrace_rejected=" + IntegerToString(result.hook_retrace_rejected_total);
   msg += " hook_seed_f1=" + IntegerToString(result.hooks_seed_visible_f1_total);
   msg += " body_attempts=" + IntegerToString(result.body_attempts_total);
   msg += " body_complete=" + IntegerToString(result.body_complete_total);
   msg += " body_invalid=" + IntegerToString(result.body_invalid_total);
   msg += " body_extended=" + IntegerToString(result.body_extended_total);
   msg += " body_leg1_ext=" + IntegerToString(result.body_leg1_extensions_total);
   msg += " body_waist_deep=" + IntegerToString(result.body_waist_deepenings_total);
   msg += " body_leg2_equal=" + IntegerToString(result.body_leg2_equal_touches_total);
   msg += " internal_packs=" + IntegerToString(result.internal_packs_total);
   msg += " internal_valid12=" + IntegerToString(result.internal_valid12_total);
   msg += " internal_confirm_ready=" + IntegerToString(result.internal_confirm_ready_total);
   msg += " internal_invalidated=" + IntegerToString(result.internal_invalidated_total);
   msg += " internal_pre_ext=" + IntegerToString(result.internal_pre_extensions_total);
   msg += " internal_f1_mid_rejected=" + IntegerToString(result.internal_f1_middle_rejected_total);
   msg += " internal_c0=" + IntegerToString(result.internal_count0_total);
   msg += " internal_c1=" + IntegerToString(result.internal_count1_total);
   msg += " internal_c2=" + IntegerToString(result.internal_count2_total);
   msg += " internal_c3=" + IntegerToString(result.internal_count3_total);
   msg += " internal_c4=" + IntegerToString(result.internal_count4_total);
   msg += " f1_lc_attempts=" + IntegerToString(result.f1_lifecycle_attempts_total);
   msg += " f1_lc_phase_attempts=" + IntegerToString(result.f1_lifecycle_phase_attempts_total);
   msg += " f1_lc_failopen_attempts=" + IntegerToString(result.f1_lifecycle_failopen_attempts_total);
   msg += " f1_lc_gate_pass=" + IntegerToString(result.f1_lifecycle_gate_pass_total);
   msg += " f1_lc_gate_reject=" + IntegerToString(result.f1_lifecycle_gate_reject_total);
   msg += " f1_lc_body_missing=" + IntegerToString(result.f1_lifecycle_body_missing_total);
   msg += " f1_lc_body_complete=" + IntegerToString(result.f1_lifecycle_body_complete_total);
   msg += " f1_lc_candidate=" + IntegerToString(result.f1_lifecycle_candidate_total);
   msg += " f1_lc_post_flag=" + IntegerToString(result.f1_lifecycle_post_flag_total);
   msg += " f1_lc_confirmed=" + IntegerToString(result.f1_lifecycle_confirmed_total);
   msg += " f1_lc_invalidated=" + IntegerToString(result.f1_lifecycle_invalidated_total);
   msg += " f1_lc_extended=" + IntegerToString(result.f1_lifecycle_extended_total);
   msg += " f1_lc_visible=" + IntegerToString(result.f1_lifecycle_visible_total);
   msg += " f1_lc_hidden=" + IntegerToString(result.f1_lifecycle_hidden_total);
   msg += " f1_lc_f2_ready=" + IntegerToString(result.f1_lifecycle_f2_ready_total);
   msg += " f1_lc_duplicate_rejected=" + IntegerToString(result.f1_lifecycle_duplicate_rejected_total);
   msg += " f1_lc_emitted_roots=" + IntegerToString(result.f1_lifecycle_emitted_roots_total);
   msg += " f2_lc_parent_attempts=" + IntegerToString(result.f2_lifecycle_parent_attempts_total);
   msg += " f2_lc_parent_ready=" + IntegerToString(result.f2_lifecycle_parent_ready_total);
   msg += " f2_lc_parent_rejected=" + IntegerToString(result.f2_lifecycle_parent_rejected_total);
   msg += " f2_lc_origin_scans=" + IntegerToString(result.f2_lifecycle_origin_scans_total);
   msg += " f2_lc_origin_found=" + IntegerToString(result.f2_lifecycle_origin_found_total);
   msg += " f2_lc_origin_missing=" + IntegerToString(result.f2_lifecycle_origin_missing_total);
   msg += " f2_lc_body_missing=" + IntegerToString(result.f2_lifecycle_body_missing_total);
   msg += " f2_lc_body_complete=" + IntegerToString(result.f2_lifecycle_body_complete_total);
   msg += " f2_lc_size_pass=" + IntegerToString(result.f2_lifecycle_size_pass_total);
   msg += " f2_lc_size_reject=" + IntegerToString(result.f2_lifecycle_size_reject_total);
   msg += " f2_lc_candidate=" + IntegerToString(result.f2_lifecycle_candidate_total);
   msg += " f2_lc_post_flag=" + IntegerToString(result.f2_lifecycle_post_flag_total);
   msg += " f2_lc_confirmed=" + IntegerToString(result.f2_lifecycle_confirmed_total);
   msg += " f2_lc_invalidated=" + IntegerToString(result.f2_lifecycle_invalidated_total);
   msg += " f2_lc_extended=" + IntegerToString(result.f2_lifecycle_extended_total);
   msg += " f2_lc_visible=" + IntegerToString(result.f2_lifecycle_visible_total);
   msg += " f2_lc_hidden=" + IntegerToString(result.f2_lifecycle_hidden_total);
   msg += " f2_lc_f3_ready=" + IntegerToString(result.f2_lifecycle_f3_ready_total);
   msg += " f2_lc_emitted_children=" + IntegerToString(result.f2_lifecycle_emitted_children_total);
   msg += " f2_lc_duplicate_rejected=" + IntegerToString(result.f2_lifecycle_duplicate_rejected_total);
   msg += " f3_lc_parent_attempts=" + IntegerToString(result.f3_lifecycle_parent_attempts_total);
   msg += " f3_lc_parent_ready=" + IntegerToString(result.f3_lifecycle_parent_ready_total);
   msg += " f3_lc_parent_rejected=" + IntegerToString(result.f3_lifecycle_parent_rejected_total);
   msg += " f3_lc_origin_scans=" + IntegerToString(result.f3_lifecycle_origin_scans_total);
   msg += " f3_lc_origin_found=" + IntegerToString(result.f3_lifecycle_origin_found_total);
   msg += " f3_lc_origin_missing=" + IntegerToString(result.f3_lifecycle_origin_missing_total);
   msg += " f3_lc_body_missing=" + IntegerToString(result.f3_lifecycle_body_missing_total);
   msg += " f3_lc_body_complete=" + IntegerToString(result.f3_lifecycle_body_complete_total);
   msg += " f3_lc_size_pass=" + IntegerToString(result.f3_lifecycle_size_pass_total);
   msg += " f3_lc_L_pass=" + IntegerToString(result.f3_lifecycle_L_pass_total);
   msg += " f3_lc_or_pass=" + IntegerToString(result.f3_lifecycle_or_pass_total);
   msg += " f3_lc_or_reject=" + IntegerToString(result.f3_lifecycle_or_reject_total);
   msg += " f3_lc_completed=" + IntegerToString(result.f3_lifecycle_completed_total);
   msg += " f3_lc_locked=" + IntegerToString(result.f3_lifecycle_locked_total);
   msg += " f3_lc_visible=" + IntegerToString(result.f3_lifecycle_visible_total);
   msg += " f3_lc_hidden=" + IntegerToString(result.f3_lifecycle_hidden_total);
   msg += " f3_lc_emitted_children=" + IntegerToString(result.f3_lifecycle_emitted_children_total);
   msg += " f3_lc_duplicate_rejected=" + IntegerToString(result.f3_lifecycle_duplicate_rejected_total);
   msg += " f3_lc_lock_scans=" + IntegerToString(result.f3_lifecycle_lock_scans_total);
   msg += " f3_lc_lock_found=" + IntegerToString(result.f3_lifecycle_lock_found_total);
   msg += " f3_lc_lock_missing=" + IntegerToString(result.f3_lifecycle_lock_missing_total);
   msg += " ownership_phases=" + IntegerToString(result.ownership_phases_total);
   msg += " ownership_owner_roots=" + IntegerToString(result.ownership_owner_roots_total);
   msg += " ownership_competing_roots=" + IntegerToString(result.ownership_competing_roots_total);
   msg += " ownership_resets=" + IntegerToString(result.ownership_resets_total);
   msg += " ownership_hidden_roots=" + IntegerToString(result.ownership_hidden_roots_total);
   msg += " ownership_hidden_descendants=" + IntegerToString(result.ownership_hidden_descendants_total);
   msg += " ownership_orphans_hidden=" + IntegerToString(result.ownership_orphans_hidden_total);
   msg += " ownership_phase_safe_duplicate_hides=" + IntegerToString(result.ownership_phase_safe_duplicate_hides_total);
   msg += " canonical_visible_before=" + IntegerToString(result.canonical_visible_before_total);
   msg += " canonical_visible_after=" + IntegerToString(result.canonical_visible_after_total);
   msg += " canonical_hidden_before=" + IntegerToString(result.canonical_hidden_before_total);
   msg += " canonical_hidden_after=" + IntegerToString(result.canonical_hidden_after_total);
   msg += " canonical_duplicates_hidden=" + IntegerToString(result.canonical_duplicates_hidden_total);
   msg += " canonical_orphans_hidden=" + IntegerToString(result.canonical_orphans_hidden_total);
   msg += " canonical_invalid_hidden=" + IntegerToString(result.canonical_invalid_hidden_total);
   msg += " canonical_missing_body_hidden=" + IntegerToString(result.canonical_missing_body_hidden_total);
   msg += " canonical_hidden_reason_repaired=" + IntegerToString(result.canonical_hidden_reason_repaired_total);
   msg += " canonical_parent_ids_repaired=" + IntegerToString(result.canonical_parent_ids_repaired_total);
   msg += " canonical_invariant_failures=" + IntegerToString(result.canonical_invariant_failures_total);
   msg += " canonical_visible_dup_after=" + IntegerToString(result.canonical_visible_duplicate_after_total);
   msg += " canonical_parent_missing_after=" + IntegerToString(result.canonical_parent_missing_after_total);
   msg += " events=" + IntegerToString(result.events_total);
   msg += " visible=" + IntegerToString(result.visible_events_total);
   msg += " hidden=" + IntegerToString(result.hidden_events_total);
   msg += " identity_events=" + IntegerToString(result.identity_assigned_events);
   msg += " f1=" + IntegerToString(result.f1_total);
   msg += " f2=" + IntegerToString(result.f2_total);
   msg += " f3=" + IntegerToString(result.f3_total);
   msg += " export_attempted=" + IntegerToString(result.export_attempted_total);
   msg += " export_ok=" + IntegerToString(result.export_ok_total);
   msg += " export_files=" + IntegerToString(result.export_files_written_total);
   msg += " export_errors=" + IntegerToString(result.export_file_errors_total);
   msg += " export_events=" + IntegerToString(result.export_events_written_total);
   msg += " export_events_visible=" + IntegerToString(result.export_visible_events_written_total);
   msg += " export_events_hidden=" + IntegerToString(result.export_hidden_events_written_total);
   msg += " export_hooks=" + IntegerToString(result.export_hooks_written_total);
   msg += " export_hooks_visible=" + IntegerToString(result.export_visible_hooks_written_total);
   msg += " export_hooks_hidden=" + IntegerToString(result.export_hidden_hooks_written_total);
   msg += " render_attempted=" + IntegerToString(result.render_attempted_total);
   msg += " render_ok=" + IntegerToString(result.render_ok_total);
   msg += " render_objects=" + IntegerToString(result.render_objects_total);
   msg += " render_errors=" + IntegerToString(result.render_object_errors_total);
   msg += " render_deleted=" + IntegerToString(result.render_deleted_objects_total);
   msg += " render_events=" + IntegerToString(result.render_events_drawn_total);
   msg += " render_hooks=" + IntegerToString(result.render_hooks_drawn_total);
   msg += " render_event_filtered=" + IntegerToString(result.render_event_filtered_total);
   msg += " render_hook_filtered=" + IntegerToString(result.render_hook_filtered_total);
   msg += " render_duplicate_names=" + IntegerToString(result.render_duplicate_names_total);
   msg += " render_fallback_curves=" + IntegerToString(result.render_fallback_curves_total);
   msg += " validation_attempted=" + IntegerToString(result.validation_attempted_total);
   msg += " validation_ok=" + IntegerToString(result.validation_ok_total);
   msg += " validation_checks=" + IntegerToString(result.validation_checks_total);
   msg += " validation_pass=" + IntegerToString(result.validation_pass_total);
   msg += " validation_fail=" + IntegerToString(result.validation_fail_total);
   msg += " validation_warn=" + IntegerToString(result.validation_warn_total);
   msg += " validation_skipped=" + IntegerToString(result.validation_skipped_total);
   msg += " validation_file_errors=" + IntegerToString(result.validation_file_errors_total);
   msg += " release_attempted=" + IntegerToString(result.release_attempted_total);
   msg += " release_ok=" + IntegerToString(result.release_ok_total);
   msg += " release_gate_pass=" + IntegerToString(result.release_gate_pass_total);
   msg += " release_gate_fail=" + IntegerToString(result.release_gate_fail_total);
   msg += " release_overrides=" + IntegerToString(result.release_overrides_total);
   msg += " release_files=" + IntegerToString(result.release_files_written_total);
   msg += " release_errors=" + IntegerToString(result.release_file_errors_total);
   msg += " release_cleanup=" + IntegerToString(result.release_cleanup_requested_total);
   msg += " release_export_forced=" + IntegerToString(result.release_export_forced_total);
   msg += " release_render_suppressed=" + IntegerToString(result.release_render_suppressed_total);
   msg += " release_validation_forced=" + IntegerToString(result.release_validation_forced_total);
   msg += " release_rollback_safe=" + IntegerToString(result.release_rollback_safe_total);
   msg += " interface_attempted=" + IntegerToString(result.interface_attempted_total);
   msg += " interface_ok=" + IntegerToString(result.interface_ok_total);
   msg += " interface_checks=" + IntegerToString(result.interface_checks_total);
   msg += " interface_pass=" + IntegerToString(result.interface_pass_total);
   msg += " interface_fail=" + IntegerToString(result.interface_fail_total);
   msg += " interface_warn=" + IntegerToString(result.interface_warn_total);
   msg += " interface_skipped=" + IntegerToString(result.interface_skipped_total);
   msg += " interface_file_errors=" + IntegerToString(result.interface_file_errors_total);
   msg += " interface_missing_ids=" + IntegerToString(result.interface_missing_ids_total);
   msg += " interface_parent_errors=" + IntegerToString(result.interface_parent_errors_total);
   msg += " interface_negative_counters=" + IntegerToString(result.interface_negative_counter_errors_total);
   msg += " interface_partition_errors=" + IntegerToString(result.interface_partition_errors_total);
   msg += " acceptance_attempted=" + IntegerToString(result.acceptance_attempted_total);
   msg += " acceptance_ok=" + IntegerToString(result.acceptance_ok_total);
   msg += " acceptance_checks=" + IntegerToString(result.acceptance_checks_total);
   msg += " acceptance_pass=" + IntegerToString(result.acceptance_pass_total);
   msg += " acceptance_fail=" + IntegerToString(result.acceptance_fail_total);
   msg += " acceptance_warn=" + IntegerToString(result.acceptance_warn_total);
   msg += " acceptance_skipped=" + IntegerToString(result.acceptance_skipped_total);
   msg += " acceptance_file_errors=" + IntegerToString(result.acceptance_file_errors_total);
   msg += " acceptance_hard_gates=" + IntegerToString(result.acceptance_hard_gates_total);
   msg += " acceptance_hard_gate_fail=" + IntegerToString(result.acceptance_hard_gate_fail_total);
   msg += " acceptance_order_errors=" + IntegerToString(result.acceptance_order_errors_total);
   msg += " acceptance_dependency_errors=" + IntegerToString(result.acceptance_dependency_errors_total);
   msg += " acceptance_matrix_errors=" + IntegerToString(result.acceptance_matrix_errors_total);
   msg += " acceptance_invariant_errors=" + IntegerToString(result.acceptance_invariant_errors_total);
   msg += " ambiguity_attempted=" + IntegerToString(result.ambiguity_attempted_total);
   msg += " ambiguity_ok=" + IntegerToString(result.ambiguity_ok_total);
   msg += " ambiguity_checks=" + IntegerToString(result.ambiguity_checks_total);
   msg += " ambiguity_pass=" + IntegerToString(result.ambiguity_pass_total);
   msg += " ambiguity_fail=" + IntegerToString(result.ambiguity_fail_total);
   msg += " ambiguity_warn=" + IntegerToString(result.ambiguity_warn_total);
   msg += " ambiguity_skipped=" + IntegerToString(result.ambiguity_skipped_total);
   msg += " ambiguity_file_errors=" + IntegerToString(result.ambiguity_file_errors_total);
   msg += " ambiguity_decisions_locked=" + IntegerToString(result.ambiguity_decisions_locked_total);
   msg += " ambiguity_decisions_unlocked=" + IntegerToString(result.ambiguity_decisions_unlocked_total);
   msg += " ambiguity_diagnostic_variants=" + IntegerToString(result.ambiguity_diagnostic_variants_total);
   msg += " ambiguity_release_blockers=" + IntegerToString(result.ambiguity_release_blockers_total);
   msg += " ambiguity_conflicts=" + IntegerToString(result.ambiguity_conflicts_total);
   msg += " invalid=" + IntegerToString(result.invalid_total);
   msg += " drawn=" + IntegerToString(drawn);
   Print(msg);
}

string FP_NodeAudit(const FP_Node &n)
{
   if(n.id < 0) return "none";
   return FP_NodeKindName(n.kind) + "#" + IntegerToString(n.id) +
          " L" + IntegerToString(n.L) +
          " i" + IntegerToString(n.index_anchor) +
          " p" + DoubleToString(n.price, _Digits) +
          " src" + FP_NodeSourceName(n.source) +
          " pending" + FP_BoolName(n.is_live_pending);
}

void FP_PrintEventAudit(const FP_FlagEvent &e)
{
   string msg = "FP_EVENT";
   msg += " id=" + IntegerToString(e.event_id);
   msg += " seq=" + IntegerToString(e.sequence_id);
   msg += " parent=" + IntegerToString(e.parent_event_id);
   msg += " level=" + FP_LevelName(e.level);
   msg += " dir=" + FP_DirectionName(e.direction);
   msg += " L=" + IntegerToString(e.scale_L);
   msg += " status=" + FP_StatusName(e.status);
   msg += " body_status=" + FP_BodyStatusName(e.body_status);
   msg += " body_id=" + e.body_id;
   msg += " body_ext=" + IntegerToString(e.leg2_extension_count);
   msg += " body_reason=" + e.body_reason;
   msg += " lifecycle_status=" + FP_F1LifecycleStatusName(e.lifecycle_status);
   msg += " lifecycle_id=" + e.lifecycle_id;
   msg += " lifecycle_gate=" + FP_BoolName(e.lifecycle_phase_gate_passed);
   msg += " lifecycle_body=" + FP_BoolName(e.lifecycle_body_complete);
   msg += " lifecycle_internal=" + FP_BoolName(e.lifecycle_internal_ready);
   msg += " lifecycle_f2_ready=" + FP_BoolName(e.lifecycle_can_spawn_f2);
   msg += " lifecycle_reason=" + e.lifecycle_reason;
   msg += " f2_status=" + FP_F2LifecycleStatusName(e.f2_lifecycle_status);
   msg += " f2_id=" + e.f2_lifecycle_id;
   msg += " f2_parent_ready=" + FP_BoolName(e.f2_parent_ready);
   msg += " f2_origin_found=" + FP_BoolName(e.f2_origin_found);
   msg += " f2_body=" + FP_BoolName(e.f2_body_complete);
   msg += " f2_size_gate=" + FP_BoolName(e.f2_size_gate_passed);
   msg += " f2_ratio=" + DoubleToString(e.f2_parent_size_ratio, 4);
   msg += " f2_internal=" + FP_BoolName(e.f2_internal_ready);
   msg += " f2_f3_ready=" + FP_BoolName(e.f2_can_spawn_f3);
   msg += " f2_reason=" + e.f2_lifecycle_reason;
   msg += " f3_status=" + FP_F3LifecycleStatusName(e.f3_lifecycle_status);
   msg += " f3_id=" + e.f3_lifecycle_id;
   msg += " f3_parent_ready=" + FP_BoolName(e.f3_parent_ready);
   msg += " f3_origin_found=" + FP_BoolName(e.f3_origin_found);
   msg += " f3_body=" + FP_BoolName(e.f3_body_complete);
   msg += " f3_size_gate=" + FP_BoolName(e.f3_size_gate_passed);
   msg += " f3_L_gate=" + FP_BoolName(e.f3_leg1_L_gate_passed);
   msg += " f3_or_gate=" + FP_BoolName(e.f3_or_gate_passed);
   msg += " f3_size_ratio=" + DoubleToString(e.f3_parent_size_ratio, 4);
   msg += " f3_L_ratio=" + DoubleToString(e.f3_parent_leg1_L_ratio, 4);
   msg += " f3_terminal=" + FP_BoolName(e.f3_terminal_complete);
   msg += " f3_lock_ready=" + FP_BoolName(e.f3_lock_ready);
   msg += " f3_locked=" + FP_BoolName(e.f3_locked);
   msg += " f3_lock_event=" + IntegerToString(e.f3_lock_event_id);
   msg += " f3_reason=" + e.f3_lifecycle_reason;
   msg += " phase_dir=" + FP_DirectionName(e.phase_direction);
   msg += " phase_owner=" + IntegerToString(e.phase_owner_root_id);
   msg += " chain_state=" + FP_OwnershipChainStateName(e.chain_state);
   msg += " next_expected=" + FP_LevelName(e.next_expected_f_level);
   msg += " phase_reset=" + e.phase_reset_reason;
   msg += " owner_rank=" + IntegerToString(e.owner_rank_score);
   msg += " losing_candidates=" + e.losing_candidate_ids;
   msg += " hidden_descendants=" + e.hidden_descendant_ids;
   msg += " canonical_id=" + e.canonical_id;
   msg += " canonical_state=" + FP_CanonicalStateName(e.canonical_state);
   msg += " canonical_rank_final=" + IntegerToString(e.canonical_rank_final);
   msg += " canonical_conflict_group=" + e.canonical_conflict_group_id;
   msg += " canonical_invariant_flags=" + IntegerToString(e.canonical_invariant_flags);
   msg += " canonical_reason=" + e.canonical_reason;
   msg += " visible=" + FP_BoolName(e.visible_main);
   msg += " hidden_reason=" + e.hidden_reason;
   msg += " rank=" + DoubleToString(e.canonical_rank_score, 4);
   msg += " structural_id=" + e.structural_id;
   msg += " visual_id=" + e.visual_id;
   msg += " phase_id=" + e.phase_id;
   msg += " chain_id=" + e.chain_id;
   msg += " audit_id=" + e.audit_id;
   msg += " size=" + DoubleToString(e.flag_size, _Digits);
   msg += " ratio=" + DoubleToString(e.size_ratio, 4);
   msg += " O=" + FP_NodeAudit(e.origin);
   msg += " A=" + FP_NodeAudit(e.leg1);
   msg += " W=" + FP_NodeAudit(e.waist);
   msg += " B=" + FP_NodeAudit(e.leg2);
   msg += " C=" + FP_NodeAudit(e.confirm);
   msg += " internal_pack_id=" + e.internal_pack.internal_pack_id;
   msg += " internal_count=" + IntegerToString(e.internal_pack.count);
   msg += " internal_valid12=" + FP_BoolName(e.internal_pack.valid12 || e.internal_pack.has_valid12);
   msg += " internal_first12=" + IntegerToString(e.internal_pack.first_valid12_pos);
   msg += " internal_confirm_pos=" + IntegerToString(e.internal_pack.confirm_pos);
   msg += " internal_invalid_pos=" + IntegerToString(e.internal_pack.invalid_pos);
   msg += " internal_pre_ext=" + FP_NodeAudit(e.internal_pack.pre_internal_leg2_extension_node);
   msg += " reason=" + e.reason;
   Print(msg);
}

void FP_PrintHookAudit(const FP_HookBranch &h)
{
   string msg = "FP_HOOK";
   msg += " id=" + IntegerToString(h.branch_id);
   msg += " dir=" + FP_DirectionName(h.direction);
   msg += " L=" + IntegerToString(h.scale_L);
   msg += " nodes=" + IntegerToString(h.node_count);
   msg += " side=" + FP_NodeKindName(h.side_kind);
   msg += " max_branch_len=" + IntegerToString(h.max_branch_len);
   msg += " nd=" + FP_BoolName(h.is_nd);
   msg += " nd_qualified=" + FP_BoolName(h.nd_qualified);
   msg += " cycle_broken=" + FP_BoolName(h.is_cycle_start_broken);
   msg += " seeds_visible_f1=" + FP_BoolName(h.seeds_visible_f1);
   msg += " visible=" + FP_BoolName(h.visible_main);
   msg += " hidden_reason=" + h.hidden_reason;
   msg += " structural_id=" + h.structural_id;
   msg += " visual_id=" + h.visual_id;
   msg += " phase_id=" + h.phase_id;
   msg += " audit_id=" + h.audit_id;
   msg += " retrace=" + DoubleToString(h.retrace_ratio, 4);
   msg += " start=" + FP_NodeAudit(h.start_node);
   msg += " cycle_start=" + FP_NodeAudit(h.cycle_start_node);
   msg += " has_cycle_start=" + FP_BoolName(h.has_cycle_start);
   msg += " extreme=" + FP_NodeAudit(h.extreme_node);
   msg += " resolve=" + FP_NodeAudit(h.resolve_node);
   msg += " reason=" + h.reason;
   Print(msg);
}

#endif // __FP_AUDIT_MQH__
