#property strict
#property version "1.00"
#property description "Strategy Factory Phase 04 static anatomy-plugin host"
#include <AlphaLab\StrategyFactory\Runtime\SF02_AllRuntime.mqh>
#include <AlphaLab\StrategyFactory\Adapters\Null\SF02_PrintResultSink.mqh>
#include <AlphaLab\StrategyFactory\Adapters\Null\SF02_NoSendExecutionBoundary.mqh>
#include <AlphaLab\StrategyFactory\Market\SF03_AllMarket.mqh>
#include <AlphaLab\StrategyFactory\Plugins\SF04_AllPlugins.mqh>
input string InpPluginId="sf04.fixture.pulse";input string InpPluginVersion="1.0.0";input string InpStrategyId="sf04_fixture_strategy";input string InpStrategyVersion="1.0.0";input string InpRunId="run_sf04_host";input string InpPrimarySymbol="EURUSD";input ENUM_TIMEFRAMES InpTimeframe=PERIOD_M1;input int InpLookbackBars=64;input int InpTicksPerEvent=25;input int InpTimerPeriodMs=250;input int InpBrokerUtcOffsetMinutes=0;input bool InpStrictFailClosed=true;
CSF03MarketServiceBundle g_market_services;CSF04FixturePulseFactory g_factory;CSF04PluginRegistry g_registry;ISF04AnatomyPlugin *g_plugin=NULL;CSF04PluginMetadataFeatureProvider g_features;CSF02PrintResultSink g_sink;CSF02NoSendExecutionBoundary g_execution;CSF02StrategyRuntime g_runtime;CSF04PluginStartupValidator g_validator;SF04_StartupValidationReport g_report;SF04_PluginDescriptor g_descriptor;SF02_RuntimeConfig g_config;
bool PreparePlugin(string &e){g_factory.Configure(InpPrimarySymbol,PeriodSeconds(InpTimeframe),InpLookbackBars,InpTicksPerEvent);if(!g_registry.RegisterFactory(&g_factory,e)||!g_registry.ValidateAll(e))return false;SF04_PluginSelection s;s.plugin_id=InpPluginId;s.exact_version=InpPluginVersion;s.required_capabilities=SF04_CAP_DETERMINISTIC|SF04_CAP_EMITS_CLUSTER_ID;s.expected_descriptor_hash="";if(!g_registry.Create(s,g_plugin,g_descriptor,e))return false;if(!g_plugin.BindSharedServices(g_market_services.Clock(),g_market_services.Market(),g_market_services.Specs(),e))return false;g_validator.Bind(g_market_services.Market(),g_market_services.Specs(),g_market_services.Clock());if(!g_validator.ValidateAndPrepare(g_plugin,g_report,e))return false;g_features.BindPlugin(g_plugin);return true;}
int OnInit(){g_config=SF02_DefaultRuntimeConfig();g_config.strategy_id=InpStrategyId;g_config.strategy_version=InpStrategyVersion;g_config.run_id=InpRunId;g_config.run_mode=SF02_MODE_ANATOMY_AUDIT;g_config.timer_period_ms=InpTimerPeriodMs;g_config.max_events_per_cycle=64;g_config.strict_fail_closed=InpStrictFailClosed;SF03_ClockConfig cc;cc.mode=SF03_CLOCK_SERVER_FIXED_OFFSET;cc.fixed_server_utc_offset_minutes=InpBrokerUtcOffsetMinutes;cc.source_timezone_id="broker_fixed";cc.source_clock_id="terminal";string e="";if(!g_market_services.Initialize(g_config,cc,e)||!g_market_services.Start(e)){Print("SF04 market startup failed: ",e);return INIT_FAILED;}if(!PreparePlugin(e)){Print("SF04 plugin preparation failed: ",e);return INIT_FAILED;}g_runtime.BindClock(g_market_services.Clock());g_runtime.BindAnatomy(g_plugin);g_runtime.BindFeatures(&g_features);g_runtime.BindSink(&g_sink);g_runtime.BindExecutionBoundary(&g_execution);if(!g_runtime.Initialize(g_config,e)||!g_runtime.Start(e)){Print("SF04 runtime startup failed: ",e);return INIT_FAILED;}if(!EventSetMillisecondTimer(InpTimerPeriodMs)){Print("SF04 timer failed: ",GetLastError());return INIT_FAILED;}Print("SF04 host started plugin=",g_descriptor.plugin_id," version=",g_descriptor.version," descriptor_hash=",g_plugin.DescriptorHash()," requirements_hash=",g_report.requirements_hash," live_authority=",g_execution.HasLiveOrderAuthority());return INIT_SUCCEEDED;}
void OnTick(){string e="";if(!g_market_services.Market().RefreshTick(InpPrimarySymbol,e)){if(InpStrictFailClosed)Print("SF04 tick refresh failed: ",e);return;}MqlTick tick;if(!g_market_services.Market().LatestTick(InpPrimarySymbol,tick,e))return;if(!g_runtime.OnTick(tick,e))Print("SF04 runtime tick failed: ",e);}
void OnTimer(){string e="";g_market_services.Market().RefreshSeries(InpPrimarySymbol,PeriodSeconds(InpTimeframe),InpLookbackBars,e);if(!g_runtime.OnTimer(e))Print("SF04 runtime timer failed: ",e);}
void OnDeinit(const int reason){EventKillTimer();string e="";g_runtime.Stop(e);g_runtime.Shutdown();if(CheckPointer(g_plugin)!=POINTER_INVALID){delete g_plugin;g_plugin=NULL;}g_market_services.Stop();g_market_services.Shutdown();Print("SF04 host stopped reason=",reason," events=",g_runtime.ProcessedEvents()," snapshots=",g_runtime.CreatedSnapshots()," rejected=",g_runtime.RejectedEvents());}
