#property strict
#property version "1.00"
#property description "Strategy Factory Phase 05 immutable runtime generation host"
#include <AlphaLab\StrategyFactory\Runtime\SF02_AllRuntime.mqh>
#include <AlphaLab\StrategyFactory\Adapters\Null\SF02_NoSendExecutionBoundary.mqh>
#include <AlphaLab\StrategyFactory\Market\SF03_AllMarket.mqh>
#include <AlphaLab\StrategyFactory\Plugins\SF04_AllPlugins.mqh>
#include <AlphaLab\StrategyFactory\Generation\SF05_AllGeneration.mqh>
input string InpPluginId="sf04.fixture.pulse";input string InpPluginVersion="1.0.0";input string InpStrategyId="sf05_fixture_strategy";input string InpStrategyVersion="1.0.0";input string InpRunId="run_sf05_host";input long InpGenerationId=1;input string InpPrimarySymbol="EURUSD";input ENUM_TIMEFRAMES InpTimeframe=PERIOD_M1;input int InpLookbackBars=64;input int InpTicksPerEvent=25;input int InpTimerPeriodMs=250;input int InpBrokerUtcOffsetMinutes=0;input string InpGitCommit="git_unknown";input string InpBuildId="build_local";input bool InpUseCommonFiles=false;input bool InpMirrorRecordsToPrint=false;
CSF03MarketServiceBundle g_market;CSF04FixturePulseFactory g_factory;CSF04PluginRegistry g_registry;CSF04PluginStartupValidator g_validator;CSF05GenerationCompiler g_compiler;CSF05GenerationManager g_manager;CSF02NoSendExecutionBoundary g_execution;CSF02StrategyRuntime g_runtime;SF02_RuntimeConfig g_config;CSF05JsonlResultSink *g_sink=NULL;CSF04PluginMetadataFeatureProvider g_features;
SF05_RunManifest MakeManifest(){SF05_RunManifest m;m.schema="alpha_lab.strategy_factory/run_manifest@1.0.0";m.manifest_id="";m.run_id=InpRunId;m.strategy_id=InpStrategyId;m.strategy_version=InpStrategyVersion;m.run_mode=SF02_MODE_ANATOMY_AUDIT;m.requested_generation_id=InpGenerationId;m.plugin_selection.plugin_id=InpPluginId;m.plugin_selection.exact_version=InpPluginVersion;m.plugin_selection.required_capabilities=SF04_CAP_DETERMINISTIC|SF04_CAP_EMITS_CLUSTER_ID;m.plugin_selection.expected_descriptor_hash="";m.plugin_configuration_hash=SF01_StableId("cfg",InpPrimarySymbol+"|"+IntegerToString(PeriodSeconds(InpTimeframe))+"|"+IntegerToString(InpLookbackBars)+"|"+IntegerToString(InpTicksPerEvent));m.market_configuration_hash=SF01_StableId("mkt",InpPrimarySymbol+"|"+IntegerToString(InpBrokerUtcOffsetMinutes));m.sink_config=SF05_DefaultResultSinkConfig();m.sink_config.file_scope=InpUseCommonFiles?SF05_FILE_COMMON:SF05_FILE_TERMINAL_LOCAL;m.sink_config.mirror_to_print=InpMirrorRecordsToPrint;m.git_commit=InpGitCommit;m.build_id=InpBuildId;m.environment_id="terminal";m.terminal_instance_id="mt5_local";m.strict_fail_closed=true;m.created_at=SF01_MakeUtcMilliseconds(g_market.Clock().UtcNowMilliseconds(),"UTC",0,"terminal",SF01_TIME_MILLISECONDS);m.manifest_id=SF05_DeriveRunManifestId(m);return m;}
int OnInit(){g_config=SF02_DefaultRuntimeConfig();g_config.strategy_id=InpStrategyId;g_config.strategy_version=InpStrategyVersion;g_config.run_id=InpRunId;g_config.generation_id=InpGenerationId;g_config.run_mode=SF02_MODE_ANATOMY_AUDIT;g_config.timer_period_ms=InpTimerPeriodMs;SF03_ClockConfig cc;cc.mode=SF03_CLOCK_SERVER_FIXED_OFFSET;cc.fixed_server_utc_offset_minutes=InpBrokerUtcOffsetMinutes;cc.source_timezone_id="broker_fixed";cc.source_clock_id="terminal";string e="";if(!g_market.Initialize(g_config,cc,e)||!g_market.Start(e)){Print("SF05 market failed: ",e);return INIT_FAILED;}g_factory.Configure(InpPrimarySymbol,PeriodSeconds(InpTimeframe),InpLookbackBars,InpTicksPerEvent);if(!g_registry.RegisterFactory(&g_factory,e)){Print("SF05 registry failed: ",e);return INIT_FAILED;}g_validator.Bind(g_market.Market(),g_market.Specs(),g_market.Clock());g_compiler.Bind(&g_registry,&g_validator,g_market.Clock(),g_market.Market(),g_market.Specs());SF05_RunManifest manifest=MakeManifest();ISF04AnatomyPlugin *plugin=NULL;SF04_PluginDescriptor descriptor;SF04_StartupValidationReport startup;SF05_RuntimeGenerationRecord generation;SF05_CompilationReport report;if(!g_compiler.Compile(manifest,plugin,descriptor,startup,generation,report,e)){Print("SF05 compile failed: ",e);return INIT_FAILED;}g_sink=new CSF05JsonlResultSink();CSF05GenerationBundle *bundle=new CSF05GenerationBundle();bundle.Adopt(manifest,generation,descriptor,plugin,g_sink,true,true);if(!g_manager.Stage(bundle,e)){Print("SF05 stage failed: ",e);return INIT_FAILED;}SF01_MarketTimestamp now=SF01_MakeUtcMilliseconds(g_market.Clock().UtcNowMilliseconds(),"UTC",0,"terminal",SF01_TIME_MILLISECONDS);if(!g_manager.Activate(now,e)){Print("SF05 activate failed: ",e);return INIT_FAILED;}CSF05GenerationBundle *active=g_manager.Active();if(!g_sink.Configure(manifest,active.Generation(),manifest.sink_config,e)){Print("SF05 sink config failed: ",e);return INIT_FAILED;}g_runtime.BindClock(g_market.Clock());g_runtime.BindAnatomy(active.Plugin());g_features.BindPlugin(active.Plugin());g_runtime.BindFeatures(&g_features);g_runtime.BindSink(active.Sink());g_runtime.BindExecutionBoundary(&g_execution);if(!g_runtime.Initialize(g_config,e)||!g_runtime.Start(e)){Print("SF05 runtime failed: ",e);return INIT_FAILED;}if(!EventSetMillisecondTimer(InpTimerPeriodMs)){Print("SF05 timer failed");return INIT_FAILED;}Print("SF05 active generation=",active.Generation().generation_uid," manifest=",manifest.manifest_id," ledger=",g_sink.Path());return INIT_SUCCEEDED;}
void OnTick(){string e="";if(!g_market.Market().RefreshTick(InpPrimarySymbol,e))return;MqlTick tick;if(g_market.Market().LatestTick(InpPrimarySymbol,tick,e)&&!g_runtime.OnTick(tick,e))Print("SF05 tick error: ",e);}
void OnTimer(){string e="";g_market.Market().RefreshSeries(InpPrimarySymbol,PeriodSeconds(InpTimeframe),InpLookbackBars,e);if(!g_runtime.OnTimer(e))Print("SF05 timer error: ",e);}
void OnDeinit(const int reason){EventKillTimer();string e="";g_runtime.Stop(e);SF01_MarketTimestamp now=SF01_MakeUtcMilliseconds(g_market.Clock().UtcNowMilliseconds(),"UTC",0,"terminal",SF01_TIME_MILLISECONDS);if(CheckPointer(g_sink)!=POINTER_INVALID)g_sink.Seal(now,e);g_runtime.Shutdown();g_manager.RetireActive(now,e);g_market.Stop();g_market.Shutdown();Print("SF05 stopped reason=",reason);}
