#property strict
#property version "20.000"
#property description "EXP0017 temporal intermarket divergence pilot integration. Audit and shadow only."
#include <AlphaLab/StrategyFactory/Market/SF03_AllMarket.mqh>
#include <AlphaLab/StrategyFactory/Integration/SF20_AllIntegration.mqh>
input string InpSymbolA="SPXUSD";input string InpSymbolB="NDXUSD";input int InpBrokerUtcOffsetHours=3;input bool InpAutoNewYorkDst=true;input int InpManualNewYorkUtcOffsetHours=-5;input int InpTimerMilliseconds=1000;input int InpM1LookbackBars=1600;input bool InpPilotShadowMode=false;
CSF03MarketServiceBundle g_market;CSF20EXP0017Factory g_factory;ISF04AnatomyPlugin *g_plugin=NULL;CSF20EXP0017PilotCoordinator g_pilot;SF02_RuntimeConfig g_runtime;
int OnInit()
{
 g_runtime=SF02_DefaultRuntimeConfig();g_runtime.strategy_id="exp0017_cycle_group_divergence";g_runtime.strategy_version="1.0.0";g_runtime.run_id="sf20_exp0017_pilot";g_runtime.run_mode=SF02_MODE_ANATOMY_AUDIT;g_runtime.timer_period_ms=InpTimerMilliseconds;g_runtime.strict_fail_closed=true;SF03_ClockConfig clock;clock.mode=SF03_CLOCK_SERVER_FIXED_OFFSET;clock.fixed_server_utc_offset_minutes=InpBrokerUtcOffsetHours*60;clock.source_timezone_id="broker_fixed";clock.source_clock_id="terminal";string error;if(!g_market.Initialize(g_runtime,clock,error)||!g_market.Start(error)){Print("SF20 market startup failed: ",error);return INIT_FAILED;}
 SF20_EXP0017Config config=SF20_DefaultEXP0017Config();config.symbol_a=InpSymbolA;config.symbol_b=InpSymbolB;config.broker_utc_offset_hours=InpBrokerUtcOffsetHours;config.use_auto_new_york_dst=InpAutoNewYorkDst;config.manual_new_york_utc_offset_hours=InpManualNewYorkUtcOffsetHours;config.m1_lookback_bars=InpM1LookbackBars;config.mode=InpPilotShadowMode?SF20_MODE_PILOT_SHADOW:SF20_MODE_AUDIT_ONLY;config.live_authority=false;g_factory.Configure(config);g_plugin=g_factory.Create(error);if(CheckPointer(g_plugin)==POINTER_INVALID){Print("SF20 factory failed: ",error);return INIT_FAILED;}if(!g_plugin.BindSharedServices(g_market.Clock(),g_market.Market(),g_market.Specs(),error)||!g_plugin.Initialize(g_runtime,error)||!g_plugin.Start(error)||!g_pilot.Configure(g_runtime,error)){Print("SF20 pilot startup failed: ",error);return INIT_FAILED;}if(!EventSetMillisecondTimer(MathMax(100,InpTimerMilliseconds))){Print("SF20 timer failed: ",GetLastError());return INIT_FAILED;}Print("SF20 EXP0017 pilot started. Live authority is disabled.");return INIT_SUCCEEDED;
}
void OnTimer(){if(CheckPointer(g_plugin)==POINTER_INVALID)return;long now=g_market.Clock().UtcNowMilliseconds();g_plugin.ProcessTimer(now);SF01_AnatomyEvent event;while(g_plugin.PopEvent(event)){SF20_EXP0017StageEvidence stages[];int candidates=0;string error;if(!g_pilot.Route(event,stages,candidates,error))Print("SF20 route failed: ",error);else Print("SF20 event=",event.event_id," symbol=",event.symbol," candidates=",candidates," inference=GATED live=GATED");}}
void OnTick(){}
void OnDeinit(const int reason){EventKillTimer();if(CheckPointer(g_plugin)!=POINTER_INVALID){g_plugin.Stop();g_plugin.Shutdown();delete g_plugin;g_plugin=NULL;}g_market.Stop();g_market.Shutdown();Print("SF20 EXP0017 pilot stopped reason=",reason);}
