#ifndef SAED_V4_37_AUTHORITY_MQH
#define SAED_V4_37_AUTHORITY_MQH
// SAED_V4_37 denies live authority.
#define SAED_V4_37_RESEARCH_ONLY 1
#define SAED_V4_37_ORDER_SUBMISSION_ALLOWED 0
#define SAED_V4_37_CAPITAL_ACTIVATION_ALLOWED 0
#define SAED_V4_37_PRODUCTION_AUTHORIZED 0
#endif
