#ifndef __SF13_LABEL_CONTRACT_MQH__
#define __SF13_LABEL_CONTRACT_MQH__
#include "SF13_FeatureColumn.mqh"
struct SF13_LabelContract{string contract_id;string contract_version;ENUM_SF13_LABEL_KIND kind;double positive_threshold_r;double regression_floor_r;double regression_cap_r;ENUM_SF13_AMBIGUOUS_POLICY ambiguous_policy;bool require_filled;bool require_terminal;string label_hash;};
string SF13_LabelContractCanonical(const SF13_LabelContract &v){return "alpha_lab.strategy_factory/label_contract@1.0.0|"+v.contract_id+"|"+v.contract_version+"|"+IntegerToString((int)v.kind)+"|"+SF01_CanonicalDouble(v.positive_threshold_r,10)+"|"+SF01_CanonicalDouble(v.regression_floor_r,10)+"|"+SF01_CanonicalDouble(v.regression_cap_r,10)+"|"+IntegerToString((int)v.ambiguous_policy)+"|"+SF01_CanonicalBool(v.require_filled)+"|"+SF01_CanonicalBool(v.require_terminal);}
string SF13_DeriveLabelHash(const SF13_LabelContract &v){return SF01_StableId("lblc",SF13_LabelContractCanonical(v));}
bool SF13_ValidateLabelContract(const SF13_LabelContract &v,string &error){if(!SF01_IsSafeIdentifier(v.contract_id,128)||v.contract_version==""||v.regression_floor_r>=v.regression_cap_r){error="invalid label contract";return false;}if(v.label_hash!=""&&v.label_hash!=SF13_DeriveLabelHash(v)){error="label hash mismatch";return false;}error="";return true;}
bool SF13_DeriveLabel(const SF13_LabelContract &v,const double net_r,const bool ambiguous,const bool filled,const bool terminal,double &label,bool &available,string &reason){available=false;label=0.0;if(v.require_filled&&!filled){reason="not_filled";return true;}if(v.require_terminal&&!terminal){reason="non_terminal";return true;}if(ambiguous&&v.ambiguous_policy==SF13_AMBIGUOUS_EXCLUDE){reason="ambiguous_excluded";return true;}if(ambiguous&&v.ambiguous_policy==SF13_AMBIGUOUS_ZERO_UTILITY){label=0.0;available=true;reason="ambiguous_zero_utility";return true;}if(v.kind==SF13_LABEL_BINARY_NET_R){label=(net_r>v.positive_threshold_r?1.0:0.0);available=true;reason="binary_net_r";return true;}label=MathMax(v.regression_floor_r,MathMin(v.regression_cap_r,net_r));available=true;reason="continuous_net_r";return true;}
#endif
