#ifndef __SF13_DATASET_ROW_MQH__
#define __SF13_DATASET_ROW_MQH__
#include "SF13_LabelContract.mqh"
struct SF13_DatasetRow{string dataset_id;string fold_id;ENUM_SF13_DATASET_ROLE role;string event_id;string cluster_id;string candidate_id;string outcome_id;string feature_snapshot_id;long known_time_utc_msc;long decision_time_utc_msc;long resolved_time_utc_msc;int feature_count;double feature_values[SF13_MAX_FEATURES];bool feature_missing[SF13_MAX_FEATURES];double label_value;bool label_available;bool ambiguous;string source_manifest_hash;string source_artifact_hash;string row_id;string row_hash;};
string SF13_DatasetRowIdentity(const SF13_DatasetRow &v){return v.dataset_id+"|"+v.fold_id+"|"+IntegerToString((int)v.role)+"|"+v.event_id+"|"+v.cluster_id+"|"+v.candidate_id+"|"+v.outcome_id+"|"+v.feature_snapshot_id+"|"+IntegerToString(v.known_time_utc_msc)+"|"+IntegerToString(v.decision_time_utc_msc);}
string SF13_DeriveDatasetRowId(const SF13_DatasetRow &v){return SF01_StableId("drow",SF13_DatasetRowIdentity(v));}
string SF13_DatasetRowCanonical(const SF13_DatasetRow &v){string features="";for(int i=0;i<v.feature_count;i++){if(i>0)features+=",";features+=(v.feature_missing[i]?"NA":SF01_CanonicalDouble(v.feature_values[i],10));}string label=(v.label_available?SF01_CanonicalDouble(v.label_value,10):"NA");return "alpha_lab.strategy_factory/dataset_row@1.0.0|"+v.row_id+"|"+SF13_DatasetRowIdentity(v)+"|"+IntegerToString(v.resolved_time_utc_msc)+"|"+features+"|"+label+"|"+SF01_CanonicalBool(v.label_available)+"|"+SF01_CanonicalBool(v.ambiguous)+"|"+v.source_manifest_hash+"|"+v.source_artifact_hash;}
string SF13_DeriveDatasetRowHash(const SF13_DatasetRow &v){return SF01_StableId("drowh",SF13_DatasetRowCanonical(v));}
bool SF13_ValidateDatasetRow(const SF13_DatasetRow &v,string &error){if(v.dataset_id==""||v.fold_id==""||v.event_id==""||v.cluster_id==""||v.candidate_id==""||v.outcome_id==""||v.feature_snapshot_id==""||v.source_manifest_hash==""||v.source_artifact_hash==""){error="missing dataset row lineage";return false;}if(v.feature_count<1||v.feature_count>SF13_MAX_FEATURES||v.known_time_utc_msc<0||v.decision_time_utc_msc<v.known_time_utc_msc||v.resolved_time_utc_msc<v.decision_time_utc_msc){error="invalid dataset row bounds";return false;}for(int i=0;i<v.feature_count;i++)if(!v.feature_missing[i]&&!MathIsValidNumber(v.feature_values[i])){error="non-finite feature";return false;}if((v.role==SF13_ROLE_PURGED||v.role==SF13_ROLE_EMBARGO)&&v.label_available){error="excluded row carries label";return false;}if(v.row_id!=""&&v.row_id!=SF13_DeriveDatasetRowId(v)){error="dataset row id mismatch";return false;}if(v.row_hash!=""&&v.row_hash!=SF13_DeriveDatasetRowHash(v)){error="dataset row hash mismatch";return false;}error="";return true;}
#endif
