from tools.repository_paths import find_repository_root
from pathlib import Path
REPO_ROOT=find_repository_root(__file__)
REGISTRY_ROOT=REPO_ROOT/'registry/history/acl/acl_07'
SCHEMA_ROOT=REGISTRY_ROOT/'schemas/v1'
POLICY_ROOT=REGISTRY_ROOT/'policies/v1'
PHASE_ID='ACL-07'; PHASE_VERSION='1.0.0'; VALIDATOR_VERSION='1.0.0'
CLAIM_CEILING='VALIDATION_DECISION_REFERENCE_ONLY'
HANDOFF_IN='ACL06_TO_ACL07'; HANDOFF_OUT='ACL07_TO_ACL08'
AUTHORITY_ACTION='ACL07_APPLY_UNIFIED_VALIDATION_GATES'
REQUIRED_UPSTREAM_ACTIONS={'VERIFY_RESEARCH_EVIDENCE','APPLY_UNIFIED_VALIDATION_GATES','ISSUE_NON_PROMOTIONAL_VALIDATION_DECISION'}
FORBIDDEN_UPSTREAM_ACTIONS={'MUTATE_RESEARCH_RESULTS','MUTATE_FROZEN_BATCH','PROMOTE_DIAGNOSTIC_LANE','INFER_ALPHA_WITHOUT_GATES','AUTHORIZE_EXECUTION','ACTIVATE_CAPITAL'}
GATE_IDS=(
 'INPUT_INTEGRITY','DATA_QUALITY_AND_LEAKAGE','DIAGNOSTIC_ISOLATION','MINIMUM_SUPPORT','EFFECT_SIZE',
 'STATISTICAL_SIGNIFICANCE','MULTIPLE_TESTING','BASELINE_DOMINANCE','TEMPORAL_GENERALIZATION',
 'OVERFIT_CONTROL','DISTRIBUTIONAL_ROBUSTNESS','EXECUTION_ECONOMICS','OOD_AND_ABSTENTION',
 'PROSPECTIVE_EVIDENCE','INDEPENDENT_REPLICATION')
GATE_STATUSES=('PASS','FAIL','UNKNOWN','NOT_APPLICABLE')
DECISION_STATUSES=('VALIDATION_ELIGIBLE_FOR_REPORTING','EVIDENCE_INSUFFICIENT','VALIDATION_FAILED','BASELINE_REFERENCE_ONLY','DIAGNOSTIC_EXCLUDED')
