from __future__ import annotations
from .errors import ContractViolation
ARTIFACT_ROLES=['CONTEXT', 'SETUP', 'TREATMENT', 'VISUALIZER', 'PLATFORM_ADAPTER', 'EXECUTION_ADAPTER', 'SHARED_PRIMITIVE', 'RESEARCH', 'DIAGNOSTIC', 'PLATFORM_KERNEL', 'GENERATED_PROJECTION', 'SOURCE_EVIDENCE', 'RELEASE_METADATA', 'GOVERNANCE_CONTROL', 'CONFIGURATION_CONTRACT', 'TEST_FIXTURE', 'TEST_CODE', 'DOCUMENTATION', 'ARCHIVE', 'UNKNOWN_ROLE']
PRIMARY_DISPOSITIONS=['KEEP_CANONICAL', 'MOVE_WITHOUT_SEMANTIC_CHANGE', 'WRAP_LEGACY', 'REWRITE_WITH_PARITY', 'EXTRACT_SHARED_LOGIC', 'MERGE_AFTER_EQUIVALENCE_PROOF', 'ARCHIVE_REFERENCE_ONLY', 'QUARANTINE_UNCERTAIN', 'DELETE_AFTER_PROOF', 'SECURITY_RESTRICTED']
ACTIVITY_STATUSES=['ACTIVE_PLATFORM', 'ACTIVE_RUNTIME_CANDIDATE', 'ACTIVE_RESEARCH', 'TEST_ONLY', 'DOCUMENTATION_ONLY', 'GENERATED', 'ARCHIVED', 'RELEASE_HISTORY', 'CONFIGURATION', 'UNKNOWN_ACTIVITY']
AUTHORITY_SURFACES=['ORDER_REQUEST', 'CAPITAL', 'BROKER_STATE', 'FILE_PERSISTENCE', 'NETWORK_EGRESS', 'EXTERNAL_MODEL', 'DYNAMIC_CODE', 'GLOBAL_STATE', 'CHART_STATE', 'TIME_SEMANTICS']
PROTECTED_FAMILIES={'ACL_OS_PLATFORM','STRATEGY_FACTORY_PLATFORM','LCM_CONTROL_PLANE','REPOSITORY_GOVERNANCE','REPOSITORY_ROOT_CONTROL'}
SECURITY_CAPABILITIES={'ORDER_API','NETWORK_API','SECRET_GENERATION_INDICATOR','SUBPROCESS','DYNAMIC_EVAL','DYNAMIC_COMPILE','DYNAMIC_IMPORT'}
def require_member(value: str, registry: list[str], name: str) -> str:
    if value not in registry: raise ContractViolation(f'unknown {name}: {value}')
    return value
