#ifndef __SF14_PROMOTION_EVALUATION_MQH__
#define __SF14_PROMOTION_EVALUATION_MQH__
#include "SF14_PromotionPolicy.mqh"
#include "SF14_RegistryScope.mqh"
#include "SF14_ModelEvidenceBundle.mqh"
struct SF14_PromotionMeasurements{bool phase12_accepted;bool test_oos_only;int test_sample_count;double validation_score;double test_score;double calibration_error;double stress_pass_ratio;bool lineage_valid;bool inventory_valid;bool model_card_no_capital_authority;bool attestation_verified;};
struct SF14_PromotionGateResult{string gate_id;ENUM_SF14_GATE_STATUS status;string reason_code;};
struct SF14_PromotionEvaluation{string evaluation_id;string model_artifact_hash;string scope_id;string evidence_bundle_hash;string policy_hash;int gate_count;SF14_PromotionGateResult gates[SF14_MAX_GATES];ENUM_SF14_PROMOTION_VERDICT verdict;long evaluated_at_utc_msc;string evaluator_id;bool no_execution_authority;string evaluation_hash;};
void SF14_AddGate(SF14_PromotionEvaluation &v,const string id,const bool passed,const string reason){if(v.gate_count>=SF14_MAX_GATES)return;v.gates[v.gate_count].gate_id=id;v.gates[v.gate_count].status=(passed?SF14_GATE_PASS:SF14_GATE_FAIL);v.gates[v.gate_count].reason_code=(passed?"PASS":reason);v.gate_count++;}
string SF14_PromotionEvaluationCanonical(const SF14_PromotionEvaluation &v){string gates="";for(int i=0;i<v.gate_count;i++)gates+="|"+v.gates[i].gate_id+":"+IntegerToString((int)v.gates[i].status)+":"+v.gates[i].reason_code;return "alpha_lab.strategy_factory/promotion_evaluation@1.0.0|"+v.evaluation_id+"|"+v.model_artifact_hash+"|"+v.scope_id+"|"+v.evidence_bundle_hash+"|"+v.policy_hash+gates+"|"+IntegerToString((int)v.verdict)+"|"+IntegerToString(v.evaluated_at_utc_msc)+"|"+v.evaluator_id+"|"+SF01_CanonicalBool(v.no_execution_authority);}
string SF14_DerivePromotionEvaluationHash(const SF14_PromotionEvaluation &v){return SF01_StableId("peval",SF14_PromotionEvaluationCanonical(v));}
bool SF14_EvaluatePromotion(const SF14_ModelEvidenceBundle &e,const SF14_RegistryScope &scope,const SF14_PromotionPolicy &p,const SF14_PromotionMeasurements &m,const long at,const string evaluator,SF14_PromotionEvaluation &out,string &error){if(!SF14_ValidateModelEvidence(e,error)||!SF14_ValidateRegistryScope(scope,error)||!SF14_ValidatePromotionPolicy(p,error))return false;if(e.feature_schema_hash!=scope.feature_schema_hash||e.label_contract_hash!=scope.label_contract_hash){error="registry scope schema mismatch";return false;}out.evaluation_id=SF01_StableId("peval",e.model_artifact_hash+"|"+scope.scope_id+"|"+p.policy_hash+"|"+IntegerToString(at)+"|"+evaluator);out.model_artifact_hash=e.model_artifact_hash;out.scope_id=scope.scope_id;out.evidence_bundle_hash=e.bundle_hash;out.policy_hash=p.policy_hash;out.gate_count=0;SF14_AddGate(out,"phase12_acceptance",(!p.require_phase12_acceptance||m.phase12_accepted),"PHASE12_REJECTED");SF14_AddGate(out,"test_oos_only",(!p.require_test_oos_only||m.test_oos_only),"NON_OOS_PREDICTIONS");SF14_AddGate(out,"test_sample_count",m.test_sample_count>=p.min_test_samples,"INSUFFICIENT_TEST_SAMPLE");SF14_AddGate(out,"validation_score",m.validation_score>=p.min_validation_score,"VALIDATION_SCORE_BELOW_FLOOR");SF14_AddGate(out,"test_score",m.test_score>=p.min_test_score,"TEST_SCORE_BELOW_FLOOR");SF14_AddGate(out,"generalization_gap",MathAbs(m.validation_score-m.test_score)<=p.max_generalization_gap,"GENERALIZATION_GAP_TOO_LARGE");SF14_AddGate(out,"calibration_error",m.calibration_error<=p.max_calibration_error,"CALIBRATION_ERROR_TOO_LARGE");SF14_AddGate(out,"stress_pass_ratio",m.stress_pass_ratio>=p.min_stress_pass_ratio,"STRESS_COVERAGE_TOO_WEAK");SF14_AddGate(out,"lineage_integrity",(!p.require_lineage_valid||m.lineage_valid),"LINEAGE_INVALID");SF14_AddGate(out,"artifact_inventory",(!p.require_inventory_valid||m.inventory_valid),"ARTIFACT_INVENTORY_INVALID");SF14_AddGate(out,"model_card_authority",(!p.require_model_card_no_capital_authority||m.model_card_no_capital_authority),"MODEL_CARD_AUTHORITY_VIOLATION");SF14_AddGate(out,"authenticity_attestation",(!p.require_verified_attestation||m.attestation_verified),"ATTESTATION_NOT_VERIFIED");bool passed=true;for(int i=0;i<out.gate_count;i++)if(out.gates[i].status==SF14_GATE_FAIL)passed=false;out.verdict=(passed?SF14_VERDICT_ELIGIBLE:SF14_VERDICT_INELIGIBLE);out.evaluated_at_utc_msc=at;out.evaluator_id=evaluator;out.no_execution_authority=true;out.evaluation_hash=SF14_DerivePromotionEvaluationHash(out);error="";return true;}
#endif
