#ifndef __SF14_MODEL_REGISTRY_MQH__
#define __SF14_MODEL_REGISTRY_MQH__
#include "SF14_GovernanceDecision.mqh"
class CSF14ModelRegistry
{
private:
 SF14_ModelRegistryEntry m_entries[SF14_MAX_ENTRIES];int m_entry_count;
 SF14_GovernanceDecision m_decisions[SF14_MAX_DECISIONS];int m_decision_count;
 int Find(const string id)const{for(int i=0;i<m_entry_count;i++)if(m_entries[i].entry_id==id)return i;return -1;}
 bool Allowed(const ENUM_SF14_REGISTRY_STATE from,const ENUM_SF14_REGISTRY_STATE to)const{if(from==SF14_STATE_DRAFT)return(to==SF14_STATE_REGISTERED||to==SF14_STATE_REJECTED);if(from==SF14_STATE_REGISTERED)return(to==SF14_STATE_EVIDENCE_VALIDATED||to==SF14_STATE_REJECTED);if(from==SF14_STATE_EVIDENCE_VALIDATED)return(to==SF14_STATE_CANDIDATE||to==SF14_STATE_REJECTED);if(from==SF14_STATE_CANDIDATE)return(to==SF14_STATE_CHALLENGER||to==SF14_STATE_REJECTED||to==SF14_STATE_RETIRED);if(from==SF14_STATE_CHALLENGER)return(to==SF14_STATE_CHAMPION||to==SF14_STATE_SUSPENDED||to==SF14_STATE_RETIRED||to==SF14_STATE_REJECTED);if(from==SF14_STATE_CHAMPION)return(to==SF14_STATE_SUSPENDED||to==SF14_STATE_RETIRED);if(from==SF14_STATE_SUSPENDED)return(to==SF14_STATE_CHALLENGER||to==SF14_STATE_RETIRED||to==SF14_STATE_REJECTED);return false;}
 bool AppendDecision(const ENUM_SF14_DECISION_TYPE type,const SF14_ModelRegistryEntry &entry,const ENUM_SF14_REGISTRY_STATE from,const ENUM_SF14_REGISTRY_STATE to,const string actor,const string reason,const string evidence,const long at,string &error){if(m_decision_count>=SF14_MAX_DECISIONS){error="governance ledger capacity exceeded";return false;}SF14_GovernanceDecision d;d.sequence=m_decision_count+1;d.decision_type=type;d.entry_id=entry.entry_id;d.scope_id=entry.scope_id;d.from_state=from;d.to_state=to;d.actor_id=actor;d.reason_code=reason;d.evidence_hash=evidence;d.previous_decision_hash=(m_decision_count>0?m_decisions[m_decision_count-1].decision_hash:"");d.decided_at_utc_msc=at;d.decision_id=SF14_DeriveDecisionId(d);d.decision_hash=SF14_DeriveDecisionHash(d);m_decisions[m_decision_count++]=d;error="";return true;}
public:
 CSF14ModelRegistry(){m_entry_count=0;m_decision_count=0;}
 int EntryCount()const{return m_entry_count;}int DecisionCount()const{return m_decision_count;}
 bool Get(const string id,SF14_ModelRegistryEntry &out)const{int i=Find(id);if(i<0)return false;out=m_entries[i];return true;}
 bool Register(const SF14_ModelEvidenceBundle &e,const SF14_RegistryScope &scope,const long at,SF14_ModelRegistryEntry &out,string &error){if(m_entry_count>=SF14_MAX_ENTRIES){error="registry capacity exceeded";return false;}for(int i=0;i<m_entry_count;i++)if(m_entries[i].model_id==e.model_id&&m_entries[i].model_version==e.model_version&&m_entries[i].scope_id==scope.scope_id){error="duplicate exact model version";return false;}out.entry_id=SF01_StableId("mentry",e.model_id+"|"+e.model_version+"|"+e.model_artifact_hash+"|"+scope.scope_id);out.model_id=e.model_id;out.model_version=e.model_version;out.model_artifact_hash=e.model_artifact_hash;out.scope_id=scope.scope_id;out.evidence_bundle_hash=e.bundle_hash;out.evaluation_hash="";out.state=SF14_STATE_REGISTERED;out.revision=1;out.created_at_utc_msc=at;out.updated_at_utc_msc=at;out.supersedes_entry_id="";out.no_execution_authority=true;out.entry_hash=SF14_DeriveRegistryEntryHash(out);m_entries[m_entry_count++]=out;return AppendDecision(SF14_DECISION_REGISTER,out,SF14_STATE_DRAFT,SF14_STATE_REGISTERED,"registry","REGISTERED",e.bundle_hash,at,error);}
 bool Transition(const string id,const ENUM_SF14_REGISTRY_STATE to,const ENUM_SF14_DECISION_TYPE type,const string actor,const string reason,const string evidence,const long at,const string evaluation_hash,string &error){int i=Find(id);if(i<0){error="unknown registry entry";return false;}SF14_ModelRegistryEntry current=m_entries[i];if(!Allowed(current.state,to)){error="invalid registry transition";return false;}if((to==SF14_STATE_EVIDENCE_VALIDATED||to==SF14_STATE_CANDIDATE||to==SF14_STATE_CHALLENGER||to==SF14_STATE_CHAMPION)&&evaluation_hash==""&&current.evaluation_hash==""){error="governed transition requires evaluation";return false;}m_entries[i].state=to;m_entries[i].revision++;m_entries[i].updated_at_utc_msc=at;if(evaluation_hash!="")m_entries[i].evaluation_hash=evaluation_hash;m_entries[i].entry_hash=SF14_DeriveRegistryEntryHash(m_entries[i]);return AppendDecision(type,m_entries[i],current.state,to,actor,reason,evidence,at,error);}
 int ChampionIndex(const string scope_id)const{int found=-1;for(int i=0;i<m_entry_count;i++)if(m_entries[i].scope_id==scope_id&&m_entries[i].state==SF14_STATE_CHAMPION){if(found>=0)return -2;found=i;}return found;}
 bool PromoteChampion(const string id,const long at,string &error){int i=Find(id);if(i<0){error="unknown registry entry";return false;}int old=ChampionIndex(m_entries[i].scope_id);if(old==-2){error="multiple champion invariant violation";return false;}if(old>=0&&old!=i){string ignored;if(!Transition(m_entries[old].entry_id,SF14_STATE_RETIRED,SF14_DECISION_SUPERSEDE,"governance","SUPERSEDED_BY_NEW_CHAMPION",m_entries[i].evaluation_hash,at,"",ignored)){error=ignored;return false;}m_entries[i].supersedes_entry_id=m_entries[old].entry_id;}return Transition(id,SF14_STATE_CHAMPION,SF14_DECISION_PROMOTE_CHAMPION,"governance","CHAMPION_PROMOTED",m_entries[i].evaluation_hash,at,"",error);}
 string DecisionChainHash()const{string payload="";for(int i=0;i<m_decision_count;i++)payload+=m_decisions[i].decision_hash+"|";return SF01_StableId("gchain",payload);}
};
#endif
