#ifndef __SF14_PROMOTION_POLICY_MQH__
#define __SF14_PROMOTION_POLICY_MQH__
#include "SF14_GovernanceEnums.mqh"
#include "../Contracts/SF01_AllContracts.mqh"
struct SF14_PromotionPolicy{string policy_id;string policy_version;int min_test_samples;double min_validation_score;double min_test_score;double max_generalization_gap;double max_calibration_error;double min_stress_pass_ratio;bool require_phase12_acceptance;bool require_test_oos_only;bool require_lineage_valid;bool require_inventory_valid;bool require_model_card_no_capital_authority;bool require_verified_attestation;int max_challengers_per_scope;string policy_hash;};
string SF14_PromotionPolicyCanonical(const SF14_PromotionPolicy &v){return "alpha_lab.strategy_factory/promotion_policy@1.0.0|"+v.policy_id+"|"+v.policy_version+"|"+IntegerToString(v.min_test_samples)+"|"+SF01_CanonicalDouble(v.min_validation_score,10)+"|"+SF01_CanonicalDouble(v.min_test_score,10)+"|"+SF01_CanonicalDouble(v.max_generalization_gap,10)+"|"+SF01_CanonicalDouble(v.max_calibration_error,10)+"|"+SF01_CanonicalDouble(v.min_stress_pass_ratio,10)+"|"+SF01_CanonicalBool(v.require_phase12_acceptance)+"|"+SF01_CanonicalBool(v.require_test_oos_only)+"|"+SF01_CanonicalBool(v.require_lineage_valid)+"|"+SF01_CanonicalBool(v.require_inventory_valid)+"|"+SF01_CanonicalBool(v.require_model_card_no_capital_authority)+"|"+SF01_CanonicalBool(v.require_verified_attestation)+"|"+IntegerToString(v.max_challengers_per_scope);}
string SF14_DerivePromotionPolicyHash(const SF14_PromotionPolicy &v){return SF01_StableId("ppol",SF14_PromotionPolicyCanonical(v));}
bool SF14_ValidatePromotionPolicy(const SF14_PromotionPolicy &v,string &error){if(v.policy_id==""||v.policy_version==""||v.min_test_samples<=0||v.max_generalization_gap<0.0||v.max_calibration_error<0.0||v.min_stress_pass_ratio<0.0||v.min_stress_pass_ratio>1.0||v.max_challengers_per_scope<1||v.max_challengers_per_scope>SF14_MAX_ENTRIES){error="invalid promotion policy";return false;}if(v.policy_hash!=""&&v.policy_hash!=SF14_DerivePromotionPolicyHash(v)){error="promotion policy hash mismatch";return false;}error="";return true;}
#endif
