from enum import Enum
class StrEnum(str, Enum):
    def __str__(self): return self.value
class RelationInstanceState(StrEnum):
    COMPILED="COMPILED"; ACTIVE="ACTIVE"; COMPLETE="COMPLETE"; BLOCKED="BLOCKED"; SUPERSEDED="SUPERSEDED"
class SidePlanState(StrEnum):
    ELIGIBLE="ELIGIBLE"; REFERENCE_UNAVAILABLE="REFERENCE_UNAVAILABLE"; REFERENCE_CONSUMED="REFERENCE_CONSUMED"; DATA_BLOCKED="DATA_BLOCKED"; DEFERRED="DEFERRED"
class ContactState(StrEnum):
    LEFT_ONLY="LEFT_ONLY"; RIGHT_ONLY="RIGHT_ONLY"; BOTH_SAME_M1="BOTH_SAME_M1"; NONE="NONE"; DATA_BLOCKED="DATA_BLOCKED"
class SweepOutcome(StrEnum):
    LEFT_FIRST="LEFT_FIRST"; RIGHT_FIRST="RIGHT_FIRST"; SYMMETRIC_SAME_M1="SYMMETRIC_SAME_M1"; NO_CONTACT="NO_CONTACT"; DATA_BLOCKED="DATA_BLOCKED"
class CandidateState(StrEnum):
    RAW_ACTIVE="RAW_ACTIVE"; CANCELLED_SECOND_TOUCH="CANCELLED_SECOND_TOUCH"; INVALID_DATA="INVALID_DATA"; CHECK_WINDOW_ENDED="CHECK_WINDOW_ENDED"
class CandidateTransition(StrEnum):
    CREATED="CREATED"; SECOND_TOUCH_CANCELLED="SECOND_TOUCH_CANCELLED"; DATA_INVALIDATED="DATA_INVALIDATED"; WINDOW_ENDED="WINDOW_ENDED"
class ScanMode(StrEnum):
    BATCH="BATCH"; INCREMENTAL="INCREMENTAL"
class RelationFamily(StrEnum):
    SAME_DAY="SAME_DAY"; PRIOR_N_CALENDAR_OFFSET="PRIOR_N_CALENDAR_OFFSET"; WEEKLY_DEFERRED="WEEKLY_DEFERRED"
class EngineHealth(StrEnum):
    READY="READY"; DEGRADED="DEGRADED"; BLOCKED="BLOCKED"
