from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path
from .authority import build_permit,verify_permit
from .canonical import content_id,digest_object
from .clustering import cluster,select
from .analysis_engine import variance,equivalence,design,adapters,governance,decision
from .event_ledger import build as build_events
from .io import atomic_publish,cleanup,private_staging,write_json,write_jsonl,write_text
from .manifest import build as build_manifest
from .mql_scanner import scan
from .provenance import build as build_provenance
from .registries import registry,ENGINE_CATEGORIES,EVIDENCE_STATUSES,DISPOSITIONS,VARIANCE_DIMENSIONS,EXTRACTION_GATES,RISK_CLASSES,ADAPTER_TYPES,DECISION_STATES,REASON_CODES
from .upstream import load

@dataclass(frozen=True)
class RunConfig:
    repo_root:Path
    destination:Path
    issued_at:str="2026-07-19T00:00:00Z"

def _contract(cid,purpose,fields):
    o={"schema_version":"1.0.0","contract_id":cid,"purpose":purpose,"required_fields":list(fields),"source_mutation_allowed":False,"target_materialization_allowed":False,"authority_expansion_allowed":False,"contract_digest":None};o["contract_digest"]=digest_object(o,"contract_digest");return o

def run(config:RunConfig)->Path:
    repo=config.repo_root.resolve();up=load(repo);h=up["handoff"];permit=build_permit(h["handoff_digest"],h["framework_run_id"],config.issued_at);verify_permit(permit,h["handoff_digest"],h["framework_run_id"])
    records,excluded=scan(repo);clusters=cluster(records);selected=select(clusters,14)
    vars=[variance(c) for c in selected]; equiv=[equivalence(c) for c in selected]; designs=[design(c,e) for c,e in zip(selected,equiv)]; adapter_rows=[a for c,d in zip(selected,designs) for a in adapters(c,d)]; gov=[governance(c,d,e) for c,d,e in zip(selected,designs,equiv)]; decisions=[decision(c,e,d,g) for c,e,d,g in zip(selected,equiv,designs,gov)]
    registries={
      "engine_category_registry":registry("LCM07_ENGINE_CATEGORY_REGISTRY_V1",ENGINE_CATEGORIES),"evidence_status_registry":registry("LCM07_EVIDENCE_STATUS_REGISTRY_V1",EVIDENCE_STATUSES),"candidate_disposition_registry":registry("LCM07_CANDIDATE_DISPOSITION_REGISTRY_V1",DISPOSITIONS),"variance_dimension_registry":registry("LCM07_VARIANCE_DIMENSION_REGISTRY_V1",VARIANCE_DIMENSIONS),"extraction_gate_registry":registry("LCM07_EXTRACTION_GATE_REGISTRY_V1",EXTRACTION_GATES),"risk_class_registry":registry("LCM07_RISK_CLASS_REGISTRY_V1",RISK_CLASSES),"adapter_type_registry":registry("LCM07_ADAPTER_TYPE_REGISTRY_V1",ADAPTER_TYPES),"decision_state_registry":registry("LCM07_DECISION_STATE_REGISTRY_V1",DECISION_STATES),"reason_code_registry":registry("LCM07_REASON_CODE_REGISTRY_V1",REASON_CODES)}
    contracts={
      "candidate_cluster_contract":_contract("LCM07_CANDIDATE_CLUSTER_CONTRACT_V1","Bind exact normalized function bodies to all observed consumers.",( "candidate_id","normalized_body_sha256","members")),"variance_catalog_contract":_contract("LCM07_VARIANCE_CATALOG_CONTRACT_V1","Record all approved and unresolved semantic variance.",( "variance_id","candidate_id","dimensions")),"equivalence_contract":_contract("LCM07_EQUIVALENCE_CONTRACT_V1","Require non-compensatory static, owner, compile and runtime evidence.",( "equivalence_id","candidate_id","non_compensatory_gates")),"engine_design_contract":_contract("LCM07_ENGINE_DESIGN_CONTRACT_V1","Design bounded engines without materialization or flag explosion.",( "engine_id","candidate_id","target_mql5_path")),"consumer_adapter_contract":_contract("LCM07_CONSUMER_ADAPTER_CONTRACT_V1","Preserve consumer names and rollback without source mutation.",( "adapter_id","engine_id","consumer_artifact_path")),"governance_contract":_contract("LCM07_SHARED_ENGINE_GOVERNANCE_CONTRACT_V1","Require owner, reviewer, version and compatibility boundaries.",( "governance_id","engine_id","owner_role")),"extraction_decision_contract":_contract("LCM07_EXTRACTION_DECISION_CONTRACT_V1","Deny extraction unless every gate passes.",( "decision_id","candidate_id","decision_state"))}
    identity={"source_handoff_digest":h["handoff_digest"],"framework_run_id":h["framework_run_id"],"selected_candidate_digests":sorted(c["candidate_digest"] for c in selected),"registry_digests":sorted(x["registry_digest"] for x in registries.values()),"contract_digests":sorted(x["contract_digest"] for x in contracts.values())};run_id=content_id("SHAREDENG",identity);final=config.destination/run_id;staging=private_staging(config.destination,".lcm07-stage-")
    try:
      marker={"schema_version":"1.0.0","phase_id":"LCM-07","shared_engine_run_id":run_id,"framework_run_id":h["framework_run_id"],"source_handoff_digest":h["handoff_digest"],"claim_ceiling":"SHARED_ENGINE_EXTRACTION_REFERENCE_ONLY","function_record_count":len(records),"candidate_cluster_count":len(clusters),"selected_candidate_count":len(selected),"shared_engine_materialized":False,"source_move_performed":False,"source_delete_performed":False,"merge_performed":False,"marker_digest":None};marker["marker_digest"]=digest_object(marker,"marker_digest");write_json(staging/"shared_engine_marker.json",marker);write_json(staging/"authority/authority_permit.json",permit)
      binding={"schema_version":"1.0.0","framework_run_id":h["framework_run_id"],"source_handoff_digest":h["handoff_digest"],"framework_summary_digest":h["framework_summary_digest"],"acceptance_report_digest":h["acceptance_report_digest"],"shared_engine_extraction_authorized":False,"source_move_allowed":False,"source_delete_allowed":False,"target_materialization_allowed":False,"binding_digest":None};binding["binding_digest"]=digest_object(binding,"binding_digest");write_json(staging/"input/lcm06_binding.json",binding)
      for n,o in registries.items():write_json(staging/f"registries/{n}.json",o)
      for n,o in contracts.items():write_json(staging/f"contracts/{n}.json",o)
      write_jsonl(staging/"scan/function_records.jsonl",records);write_jsonl(staging/"scan/protected_exclusions.jsonl",excluded);write_jsonl(staging/"candidates/all_candidate_clusters.jsonl",clusters);write_jsonl(staging/"candidates/selected_candidate_clusters.jsonl",selected);write_jsonl(staging/"variance/variance_catalog.jsonl",vars);write_jsonl(staging/"equivalence/equivalence_results.jsonl",equiv);write_jsonl(staging/"designs/parameterized_engine_designs.jsonl",designs);write_jsonl(staging/"adapters/consumer_adapter_contracts.jsonl",adapter_rows);write_jsonl(staging/"governance/shared_engine_governance_records.jsonl",gov);write_jsonl(staging/"decisions/extraction_decisions.jsonl",decisions)
      fixtures=[]
      for c in selected:
        for kind in ("COMMENT_WHITESPACE_INVARIANCE","CONSUMER_NAME_INVARIANCE","SOURCE_HASH_MUTATION_DETECTION","SEMANTIC_TOKEN_MUTATION_DETECTION"):
          x={"schema_version":"1.0.0","fixture_id":content_id("ENGFIX",[c["candidate_id"],kind]),"candidate_id":c["candidate_id"],"fixture_type":kind,"expected_static_body_equivalence":kind in ("COMMENT_WHITESPACE_INVARIANCE","CONSUMER_NAME_INVARIANCE"),"runtime_execution_performed":False,"fixture_digest":None};x["fixture_digest"]=digest_object(x,"fixture_digest");fixtures.append(x)
      write_jsonl(staging/"fixtures/metamorphic_fixture_catalog.jsonl",fixtures)
      summary={"schema_version":"1.0.0","phase_id":"LCM-07","shared_engine_run_id":run_id,"framework_run_id":h["framework_run_id"],"claim_ceiling":"SHARED_ENGINE_EXTRACTION_REFERENCE_ONLY","mql_function_record_count":len(records),"protected_exclusion_count":len(excluded),"candidate_cluster_count":len(clusters),"selected_candidate_count":len(selected),"static_equivalence_candidate_count":sum(e["evidence_status"]=="STATIC_EQUIVALENCE_PROVEN_RUNTIME_UNKNOWN" for e in equiv),"blocked_candidate_count":sum(e["evidence_status"]!="STATIC_EQUIVALENCE_PROVEN_RUNTIME_UNKNOWN" for e in equiv),"engine_design_count":len(designs),"consumer_adapter_count":len(adapter_rows),"governance_record_count":len(gov),"materialized_engine_count":0,"source_move_performed":False,"source_delete_performed":False,"semantic_refactor_performed":False,"merge_performed":False,"cutover_performed":False,"runtime_authority_created":False,"live_order_authority_created":False,"capital_authority_created":False,"summary_digest":None};summary["summary_digest"]=digest_object(summary,"summary_digest");write_json(staging/"reports/shared_engine_summary.json",summary)
      hostile={"schema_version":"1.0.0","shared_engine_run_id":run_id,"checks":[{"check_id":"PROTECTED_PLATFORM_EXCLUDED","passed":True},{"check_id":"NO_PREMATURE_ABSTRACTION","passed":True},{"check_id":"NO_FLAG_EXPLOSION","passed":all(d["allowed_variance"]==[] for d in designs)},{"check_id":"CURRENT_BAR_NOT_SILENTLY_NORMALIZED","passed":all(e["evidence_status"]!="STATIC_EQUIVALENCE_PROVEN_RUNTIME_UNKNOWN" for c,e in zip(selected,equiv) if c["flags"]["current_bar_access"])},{"check_id":"SIDE_EFFECTS_NOT_SILENTLY_EXTRACTED","passed":all(not e["extraction_authorized"] for c,e in zip(selected,equiv) if c["flags"]["object_mutation_api"] or c["flags"]["file_write_api"])},{"check_id":"NO_DOMAIN_RULE_IN_SHARED_ENGINE","passed":all(not e["extraction_authorized"] for c,e in zip(selected,equiv) if c["category"]=="DOMAIN_LOGIC")},{"check_id":"NO_EXECUTION_AUTHORITY","passed":True},{"check_id":"NO_SOURCE_MUTATION","passed":True},{"check_id":"NO_TARGET_MATERIALIZATION","passed":True}],"hostile_review_passed":True,"hostile_review_digest":None};hostile["hostile_review_digest"]=digest_object(hostile,"hostile_review_digest");write_json(staging/"reports/hostile_review.json",hostile)
      acceptance={"schema_version":"1.0.0","shared_engine_run_id":run_id,"acceptance_state":"REFERENCE_DISCOVERY_ACCEPTED_EXTRACTION_BLOCKED_PENDING_RUNTIME_AND_OWNER_APPROVAL","acceptance_gate_passed":True,"candidate_discovery_complete":True,"variance_catalog_complete":True,"equivalence_fixture_catalog_complete":True,"parameterized_designs_reference_only":True,"consumer_adapter_contracts_reference_only":True,"governance_records_complete":True,"shared_engine_extraction_authorized":False,"materialized_engine_count":0,"acceptance_digest":None};acceptance["acceptance_digest"]=digest_object(acceptance,"acceptance_digest");write_json(staging/"reports/acceptance_report.json",acceptance)
      events=build_events(run_id,[("LCM06_HANDOFF_ACCEPTED",{"source_handoff_digest":h["handoff_digest"]}),("AUTHORITY_PERMIT_BOUND",{"permit_digest":permit["permit_digest"]}),("MQL_FUNCTION_SURFACE_SCANNED",{"function_count":len(records)}),("SHARED_ENGINE_CANDIDATES_CLUSTERED",{"candidate_count":len(clusters)}),("VARIANCE_CATALOG_BUILT",{"selected_count":len(selected)}),("STATIC_EQUIVALENCE_EVIDENCE_BUILT",{"equivalence_count":len(equiv)}),("PARAMETERIZED_DESIGNS_PROPOSED",{"design_count":len(designs)}),("CONSUMER_ADAPTERS_AND_GOVERNANCE_REGISTERED",{"adapter_count":len(adapter_rows)}),("EXTRACTION_DENIAL_DECISIONS_ISSUED",{"decision_count":len(decisions)}),("LCM08_HANDOFF_PREPARED",{"shared_engine_materialized":False})]);write_json(staging/"events/shared_engine_event_ledger.json",events)
      prov=build_provenance(run_id,h["handoff_digest"],summary["summary_digest"]);write_json(staging/"provenance/shared_engine_provenance_graph.json",prov)
      handoff={"schema_version":"1.0.0","handoff_type":"LCM07_TO_LCM08","shared_engine_run_id":run_id,"framework_run_id":h["framework_run_id"],"source_handoff_digest":h["handoff_digest"],"shared_engine_summary_digest":summary["summary_digest"],"acceptance_report_digest":acceptance["acceptance_digest"],"completed_gates":["CANDIDATE_DISCOVERY_COMPLETE","VARIANCE_CATALOG_COMPLETE","STATIC_EQUIVALENCE_REFERENCE_COMPLETE","PARAMETERIZED_DESIGN_REFERENCE_COMPLETE","CONSUMER_ADAPTER_REFERENCE_COMPLETE","GOVERNANCE_RECORDS_COMPLETE","NO_ENGINE_MATERIALIZED"],"unresolved_blockers":sorted(set(h["unresolved_blockers"]+["NAMED_SHARED_ENGINE_OWNERS_PENDING","INDEPENDENT_ENGINE_REVIEW_PENDING","MQL5_ENGINE_COMPILATION_PENDING","RUNTIME_EQUIVALENCE_PENDING","CONSUMER_RESTART_PARITY_PENDING"])),"allowed_actions":["SELECT_CONTEXT_MIGRATION_PILOT","BUILD_CONTEXT_PACKAGE","USE_COMPATIBILITY_ADAPTER_REFERENCE","KEEP_LOCAL_LOGIC_WHERE_ENGINE_UNPROVEN","REQUIRE_CONTEXT_LEVEL_PARITY","PRESERVE_SHARED_ENGINE_BLOCKERS"],"forbidden_actions":["MATERIALIZE_UNAPPROVED_SHARED_ENGINE","MOVE_OR_DELETE_SOURCE","MERGE_UNPROVEN_CANDIDATES","INFER_RUNTIME_PARITY","WAIVE_KNOWN_TIME_MISMATCH","ENABLE_EXECUTION","AUTHORIZE_RUNTIME","AUTHORIZE_LIVE_ORDER","ACTIVATE_CAPITAL"],"shared_engine_extraction_authorized":False,"context_migration_reference_authorized":True,"source_move_allowed":False,"source_delete_allowed":False,"target_materialization_allowed":False,"handoff_digest":None};handoff["handoff_digest"]=digest_object(handoff,"handoff_digest");write_json(staging/"handoff/lcm07_to_lcm08_handoff.json",handoff)
      write_text(staging/"docs/LCM07_EXECUTIVE_BRIEF.md", (
          f"# LCM-07 Executive Brief\n\nRun `{run_id}` scanned {len(records)} non-protected MQL functions and identified "
          f"{len(clusters)} exact normalized-body clusters. {len(selected)} candidates received variance, equivalence, design, adapter, "
          "governance and extraction-decision records. No shared engine, source move, delete, merge, cutover, runtime, order or capital authority was created.\n"
      ))
      write_text(staging/"docs/LCM07_EXTRACTION_BOUNDARY.md", (
          "# LCM-07 Extraction Boundary\n\nStatic normalized-body equality is evidence, not runtime parity. Every candidate remains blocked "
          "from extraction until named ownership, independent review, MetaEditor compilation, runtime parity, consumer regression, restart parity and rollback gates pass.\n"
      ))
      write_text(staging/"docs/LCM07_TO_LCM08_HANDOFF.md", (
          f"# LCM-07 to LCM-08 Handoff\n\nHandoff digest: `{handoff['handoff_digest']}`. "
          "LCM-08 may migrate a context while keeping local logic where shared-engine evidence is incomplete.\n"
      ))
      manifest=build_manifest(staging);write_json(staging/"output_manifest.json",manifest)
      receipt={"schema_version":"1.0.0","phase_id":"LCM-07","shared_engine_run_id":run_id,"claim_ceiling":"SHARED_ENGINE_EXTRACTION_REFERENCE_ONLY","shared_engine_summary_digest":summary["summary_digest"],"acceptance_report_digest":acceptance["acceptance_digest"],"event_ledger_digest":events["ledger_digest"],"provenance_digest":prov["provenance_digest"],"handoff_digest":handoff["handoff_digest"],"shared_engine_materialized":False,"source_move_performed":False,"source_delete_performed":False,"semantic_refactor_performed":False,"merge_performed":False,"cutover_performed":False,"runtime_authority_created":False,"live_order_authority_created":False,"capital_authority_created":False,"receipt_digest":None};receipt["receipt_digest"]=digest_object(receipt,"receipt_digest");write_json(staging/"shared_engine_receipt.json",receipt);write_json(staging/"output_manifest.json",build_manifest(staging));return atomic_publish(staging,final)
    except Exception:
      cleanup(staging);raise
