from __future__ import annotations
import json,subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
cmds=[[sys.executable,'-m','pytest','-q','lab/11_strategy_factory/tests/phase_saed_v4_41_continuous_surveillance_retirement'],[sys.executable,'tools/strategy_factory/saed_v4_41/validate_schemas.py'],[sys.executable,'tools/strategy_factory/saed_v4_41/validate_mql5_static.py'],[sys.executable,'tools/strategy_factory/saed_v4_41/validate_docs.py'],[sys.executable,'tools/strategy_factory/saed_v4_41/validate_authority.py']]
for c in cmds:subprocess.run(c,cwd=ROOT,check=True)
out=json.loads((ROOT/'lab/11_strategy_factory/examples/saed_v4_41/reference_output.json').read_text())
report={'phase':'SAED_V4_41','passed':True,'python_tests':'passed','closed_schema_pairs':len(list((ROOT/'lab/11_strategy_factory/schemas/saed_v4_41').glob('*.schema.json'))),'phase_documents':len(list((ROOT/'docs/strategy_factory_sovereign_context_intelligence_v4/62_PHASE_DELIVERIES_V4/V4_41').glob('*.md'))),'atomic_documents':len(list((ROOT/'docs/strategy_factory_sovereign_context_intelligence_v4/63_ATOMIC_CONCEPTS_V4/V4_41').glob('*.md'))),'mql5_static_files':len(list((ROOT/'mql5/Include/StrategyFactory/SAED/V4_41').glob('*')))+len(list((ROOT/'mql5/Experts/StrategyFactory/SAED/V4_41').glob('*'))),'reference_context_cells':128,'reference_metric_count':12,'reference_window_count':6,'reference_observation_count':out['ledger']['observation_count'],'reference_retired_count':out['retirement']['retired_count'],'reference_pending_retirement_count':out['retirement']['pending_count'],'saed_v4_reference_roadmap_complete':True,'actual_production_telemetry':'pending_external','actual_metaeditor_compile_matrix':'pending_external','actual_mt5_retirement_replay':'pending_external','actual_broker_retirement_reconciliation':'pending_external','actual_incident_retirement_drills':'pending_external','capital_activation_allowed':False,'production_authorized':False}
(ROOT/'releases/history/saed/reports/SAED_V4_41_QA_REPORT.json').write_text(json.dumps(report,indent=2,sort_keys=True)+'\n')
status={'phase':'SAED_V4_41','status':'accepted_reference_roadmap_complete_external_operations_gates_open','qa_passed':True,'continuous_surveillance_reference_passed':True,'retirement_reference_passed':True,'saed_v4_numbered_roadmap_complete':True,'actual_external_operations_passed':False,'production_authorized':False}
(ROOT/'lab/11_strategy_factory/phase_status/SAED_V4_41.json').write_text(json.dumps(status,indent=2,sort_keys=True)+'\n')
print(json.dumps(report,indent=2))
