#ifndef ALPHALAB_UCEI06_OUTCOME_CUBE_MQH
#define ALPHALAB_UCEI06_OUTCOME_CUBE_MQH
#include "UCEI06_Contracts.mqh"
#include "UCEI06_Identity.mqh"
#include "UCEI06_MaturityEngine.mqh"
class CUCEI06OutcomeCubeKernel{
private: CUCEI06MaturityEngine m_maturity;
 double EntryQuote(const UCEI06_PathObservation &p,const int side)const{return side>0?p.ask:p.bid;}
 double ExitQuote(const UCEI06_PathObservation &p,const int side)const{return side>0?p.bid:p.ask;}
public:
 bool Evaluate(const UCEI06_OpportunityAnchor &a,const UCEI06_TreatmentSibling &t,const UCEI06_EconomicScenario &s,const UCEI06_PathObservation &path[],const long horizon_ms,UCEI06_OutcomeCell &out,string &reason)const{
  reason="";int n=ArraySize(path);if(n<=0){reason="empty_path";return false;}out.opportunity_id=a.opportunity_id;out.treatment_id=t.treatment_id;out.scenario_key=s.scenario_id+"@"+s.version;out.horizon_ms=horizon_ms;out.path_hash=UCEI06_StableId("ucepath",IntegerToString((long)n)+"|"+IntegerToString(path[0].event_time_ms)+"|"+IntegerToString(path[n-1].event_time_ms));out.economic_envelope_hash=t.economic_envelope_hash;
  if(!t.admissible){out.state=UCEI06_REJECTED;out.terminal_reason=UCEI06_TERM_NONE;out.maturity=m_maturity.Evaluate(out.state,out.terminal_reason,path[n-1].event_time_ms,a.decision_time_ms+horizon_ms);out.cell_id=UCEI06_StableId("ucecell",a.opportunity_id+"|"+t.treatment_id+"|"+out.scenario_key+"|"+IntegerToString(horizon_ms));return true;}
  bool filled=false;double entry=0.0;long et=0;double best=0.0,worst=0.0,peak=0.0,maxdd=0.0;double active_stop=t.stop_price;double exitp=0.0;long xt=0;UCEI06_TERMINAL_REASON terminal=UCEI06_TERM_NONE;
  for(int i=0;i<n;i++){if(path[i].event_time_ms<a.decision_time_ms||path[i].event_time_ms>a.decision_time_ms+horizon_ms||path[i].gap)continue;double q=EntryQuote(path[i],t.side);if(!filled){bool hit=(t.entry_style==0)||(t.has_entry_price&&((t.side>0&&((t.entry_style==1&&q<=t.entry_price)||(t.entry_style==2&&q>=t.entry_price)))||(t.side<0&&((t.entry_style==1&&q>=t.entry_price)||(t.entry_style==2&&q<=t.entry_price)))));if(hit){filled=true;entry=(t.entry_style==0?q:t.entry_price)+(t.side>0?s.slippage_price:-s.slippage_price);et=path[i].event_time_ms;}continue;}double ex=ExitQuote(path[i],t.side);double move=t.side>0?ex-entry:entry-ex;double r=move*t.volume*t.cash_per_price_unit/t.maximum_loss_cash;if(r>best)best=r;if(r<worst)worst=r;if(r>peak)peak=r;if(peak-r>maxdd)maxdd=peak-r;if(t.has_trail){double candidate=t.side>0?ex-t.trail_distance:ex+t.trail_distance;if((t.side>0&&candidate>active_stop)||(t.side<0&&candidate<active_stop))active_stop=candidate;}bool stop_hit=t.side>0?ex<=active_stop:ex>=active_stop;bool target_hit=t.has_target&&(t.side>0?ex>=t.target_price:ex<=t.target_price);if(stop_hit||target_hit){exitp=stop_hit?active_stop:t.target_price;exitp+=(t.side>0?-s.slippage_price:s.slippage_price);xt=path[i].event_time_ms;terminal=stop_hit?(active_stop==t.stop_price?UCEI06_TERM_STOP:UCEI06_TERM_TRAIL):UCEI06_TERM_TARGET;break;}}
  if(!filled){out.state=UCEI06_UNFILLED;out.terminal_reason=UCEI06_TERM_ENTRY_EXPIRED;out.maturity=m_maturity.Evaluate(out.state,out.terminal_reason,path[n-1].event_time_ms,a.decision_time_ms+horizon_ms);out.cell_id=UCEI06_StableId("ucecell",a.opportunity_id+"|"+t.treatment_id+"|"+out.scenario_key+"|"+IntegerToString(horizon_ms));return true;}
  if(exitp==0.0){exitp=ExitQuote(path[n-1],t.side);xt=path[n-1].event_time_ms;out.state=path[n-1].event_time_ms>=a.decision_time_ms+horizon_ms?UCEI06_CENSORED:UCEI06_OPEN;terminal=UCEI06_TERM_TIME;}else out.state=UCEI06_RESOLVED;
  out.entry_time_ms=et;out.exit_time_ms=xt;out.entry_price=entry;out.exit_price=exitp;out.filled_fraction=1.0;out.gross_pnl_cash=(t.side>0?exitp-entry:entry-exitp)*t.volume*t.cash_per_price_unit;out.total_cost_cash=(t.estimated_cost_cash+s.commission_cash+s.financing_cash+s.gap_reserve_cash)*s.cost_multiplier;out.net_pnl_cash=out.gross_pnl_cash-out.total_cost_cash;out.net_r=out.net_pnl_cash/t.maximum_loss_cash;out.mfe_r=best;out.mae_r=worst;out.max_drawdown_r=maxdd;out.time_to_fill_ms=et-a.decision_time_ms;out.time_to_exit_ms=xt-et;out.terminal_reason=terminal;out.tail_loss=out.net_r<=-1.0;out.maturity=m_maturity.Evaluate(out.state,out.terminal_reason,path[n-1].event_time_ms,a.decision_time_ms+horizon_ms);out.cell_id=UCEI06_StableId("ucecell",a.opportunity_id+"|"+t.treatment_id+"|"+out.scenario_key+"|"+IntegerToString(horizon_ms)+"|"+out.path_hash);return true;}
};
#endif
