#ifndef __SF06_ANATOMY_ENUMS_MQH__
#define __SF06_ANATOMY_ENUMS_MQH__
enum ENUM_SF06_OBSERVATION_KIND{SF06_OBS_UNKNOWN=0,SF06_OBS_REFERENCE_SWEEP_HIGH=1,SF06_OBS_REFERENCE_SWEEP_LOW=2,SF06_OBS_CONFIRMATION=3,SF06_OBS_INVALIDATION=4};
enum ENUM_SF06_LIFECYCLE_STATE{SF06_LIFE_UNKNOWN=0,SF06_LIFE_OBSERVED=1,SF06_LIFE_CONFIRMED=2,SF06_LIFE_EMITTED=3,SF06_LIFE_REJECTED=4,SF06_LIFE_RETIRED=5};
enum ENUM_SF06_LEDGER_RECORD_KIND{SF06_LEDGER_OBSERVATION=1,SF06_LEDGER_LIFECYCLE=2,SF06_LEDGER_EVENT=3,SF06_LEDGER_REJECTION=4,SF06_LEDGER_GOLDEN_CHECK=5};
string SF06_LifecycleStateToString(const ENUM_SF06_LIFECYCLE_STATE v){if(v==SF06_LIFE_OBSERVED)return "OBSERVED";if(v==SF06_LIFE_CONFIRMED)return "CONFIRMED";if(v==SF06_LIFE_EMITTED)return "EMITTED";if(v==SF06_LIFE_REJECTED)return "REJECTED";if(v==SF06_LIFE_RETIRED)return "RETIRED";return "UNKNOWN";}
#endif
