#ifndef __SAEDV440AUTHORITY_MQH__
#define __SAEDV440AUTHORITY_MQH__
// SAEDV440 static mirror. Reference control-plane contract only.
#define SAEDV440_LIVE_ORDER_SUBMISSION_ALLOWED 0
#define SAEDV440_CAPITAL_ACTIVATION_ALLOWED 0
#define SAEDV440_PRODUCTION_AUTHORIZED 0
#define SAEDV440_CROSS_TENANT_ROUTING_ALLOWED 0
#endif
