#ifndef __SF15_INFERENCE_ENUMS_MQH__
#define __SF15_INFERENCE_ENUMS_MQH__
enum ENUM_SF15_OUTPUT_SEMANTICS { SF15_OUTPUT_SCALAR_SCORE=1, SF15_OUTPUT_BINARY_LOGIT=2, SF15_OUTPUT_BINARY_PROBABILITY=3 };
enum ENUM_SF15_CALIBRATION_METHOD { SF15_CALIBRATION_IDENTITY=0, SF15_CALIBRATION_SIGMOID=1, SF15_CALIBRATION_PLATT=2 };
enum ENUM_SF15_INFERENCE_STATUS { SF15_INFERENCE_ACCEPTED=1, SF15_INFERENCE_REJECTED=2, SF15_INFERENCE_RUNTIME_ERROR=3, SF15_INFERENCE_NON_FINITE=4, SF15_INFERENCE_LINEAGE_MISMATCH=5 };
enum ENUM_SF15_RUNTIME_BACKEND { SF15_BACKEND_REFERENCE=1, SF15_BACKEND_ONNX=3 };
enum ENUM_SF15_PARITY_VERDICT { SF15_PARITY_PASS=1, SF15_PARITY_FAIL=2, SF15_PARITY_NOT_RUN=3 };
#endif
