from pathlib import Path
PHASE_ID='LCM-15B'
MASTER_PHASE='LCM-15'
CLAIM_CEILING='LCM_15B_REFERENCE_ONLY'
SCHEMA_VERSION='1.0.0'
REORGANIZATION_ID='ROOTREORG_1D879F480AD3B6F4C6EDC307D43AA381'
PACKAGE_RELATIVE=Path("registry/legacy_context_migration/root_release_reorganizations")/REORGANIZATION_ID
