from enum import Enum
class StrEnum(str,Enum):
    def __str__(self): return self.value
class WWLifecycleState(StrEnum):
    RAW="RAW"; CONFIRMED="CONFIRMED"; NEUTRALIZED="NEUTRALIZED"; EXPIRED="EXPIRED"; INVALID_DATA="INVALID_DATA"
class WWStackDisposition(StrEnum):
    ACTIVE_WINNER="ACTIVE_WINNER"; ACTIVE_SHADOWED="ACTIVE_SHADOWED"; NEUTRALIZED="NEUTRALIZED"; EXPIRED="EXPIRED"; INVALID="INVALID"
class WWDataState(StrEnum):
    COMPLETE="COMPLETE"; INCOMPLETE="INCOMPLETE"; UNAVAILABLE="UNAVAILABLE"
class GateEligibility(StrEnum):
    ALLOWED="ALLOWED"; SUPPRESSED="SUPPRESSED"; BLOCKED="BLOCKED"; NOT_APPLICABLE="NOT_APPLICABLE"
class NeutralizationOutcome(StrEnum):
    UNAFFECTED="UNAFFECTED"; NEUTRALIZED="NEUTRALIZED"; TOO_EARLY="TOO_EARLY"; WRONG_SYMBOL="WRONG_SYMBOL"; WRONG_SIDE="WRONG_SIDE"; NO_CONTACT="NO_CONTACT"; DATA_BLOCKED="DATA_BLOCKED"
class WWTransition(StrEnum):
    CREATED="CREATED"; CONFIRMED="CONFIRMED"; SECOND_SYMBOL_NEUTRALIZED="SECOND_SYMBOL_NEUTRALIZED"; WEEK_EXPIRED="WEEK_EXPIRED"; DATA_INVALIDATED="DATA_INVALIDATED"; SUPERSEDED_IN_STACK="SUPERSEDED_IN_STACK"
class EngineHealth(StrEnum):
    READY="READY"; DEGRADED="DEGRADED"; BLOCKED="BLOCKED"
