"""Frozen UCE-I10 algorithm catalog.

Native entries are dependency-free deterministic reference floors. Adapter
entries describe optional high-capacity implementations and remain unavailable
until their dependency, admission, multi-seed, export, and ablation gates pass.
"""

from __future__ import annotations

from .contracts import DeepAlgorithmDescriptor
from .enums import DeepFamily, ExportPath


def _descriptor(
    algorithm_id,
    family,
    formulation,
    views,
    tasks,
    required_fields,
    outputs,
    *,
    native=True,
    dependency_profile="",
    exports=(ExportPath.NATIVE_JSON,),
    parameters=None,
    limitations=(),
):
    return DeepAlgorithmDescriptor(
        algorithm_id=algorithm_id,
        algorithm_version="1.0.0",
        family=family,
        formulation=formulation,
        view_kinds=tuple(views),
        tasks=tuple(tasks),
        native=bool(native),
        determinism="bit_exact" if native else "numeric_tolerance",
        required_fields=tuple(required_fields),
        output_semantics=tuple(outputs),
        dependency_profile=dependency_profile,
        export_paths=tuple(exports),
        default_parameters=parameters or {},
        limitations=tuple(limitations),
    )


CATALOG = (
    _descriptor(
        "causal_temporal_conv_ridge",
        DeepFamily.SEQUENCE,
        "causal_fixed_tcn_plus_ridge",
        ("sequence",),
        ("binary_classification", "regression", "multi_task"),
        ("time_major_tensor", "causal_mask", "known_time_cut"),
        ("score", "probability", "value"),
        parameters={"kernel_sizes": (2, 3), "dilations": (1, 2), "alpha": 0.001},
        exports=(ExportPath.NATIVE_JSON, ExportPath.DISTILLED_MQL5),
        limitations=("Deterministic reference floor; not a learned deep representation.",),
    ),
    _descriptor(
        "compact_gru_adapter",
        DeepFamily.SEQUENCE,
        "masked_compact_gru",
        ("sequence",),
        ("binary_classification", "regression", "multi_task"),
        ("masked_sequence", "known_time_cut", "seed_control"),
        ("score", "probability", "value"),
        native=False,
        dependency_profile="ucee-deep",
        exports=(ExportPath.ONNX,),
        parameters={"hidden_size": 32, "layers": 1, "dropout": 0.0},
        limitations=("Optional torch dependency.", "Multi-seed qualification is mandatory."),
    ),
    _descriptor(
        "small_transformer_adapter",
        DeepFamily.SEQUENCE,
        "causal_small_transformer",
        ("sequence", "event_set"),
        ("binary_classification", "regression", "ranking", "multi_task"),
        ("causal_attention_mask", "position_encoding", "known_time_cut"),
        ("score", "probability", "value", "rank_score"),
        native=False,
        dependency_profile="ucee-deep",
        exports=(ExportPath.ONNX,),
        parameters={"model_width": 32, "heads": 4, "layers": 2},
        limitations=("Attention mask and position encoding are identity-bearing.",),
    ),
    _descriptor(
        "deterministic_chart_raster_conv",
        DeepFamily.VISION,
        "deterministic_raster_fixed_conv_plus_ridge",
        ("image",),
        ("binary_classification", "regression"),
        ("ohlc_cut", "raster_spec", "pixel_audit"),
        ("score", "probability", "value"),
        parameters={"height": 32, "channels": 3, "alpha": 0.001},
        exports=(ExportPath.NATIVE_JSON, ExportPath.DISTILLED_MQL5),
        limitations=("Raster semantics are fixed; visual decoration is prohibited."),
    ),
    _descriptor(
        "compact_image_cnn_adapter",
        DeepFamily.VISION,
        "small_causal_chart_cnn",
        ("image",),
        ("binary_classification", "regression"),
        ("deterministic_raster", "augmentation_policy", "pixel_audit"),
        ("score", "probability", "value"),
        native=False,
        dependency_profile="ucee-deep",
        exports=(ExportPath.ONNX,),
        parameters={"channels": (8, 16), "kernel_size": 3},
        limitations=("Augmentation must preserve known-time semantics."),
    ),
    _descriptor(
        "deterministic_graph_message_passing",
        DeepFamily.GRAPH,
        "fixed_message_passing_plus_ridge",
        ("graph",),
        ("binary_classification", "regression"),
        ("node_features", "edges", "topology_version", "node_known_times"),
        ("score", "probability", "value"),
        parameters={"rounds": 2, "alpha": 0.001},
        exports=(ExportPath.NATIVE_JSON, ExportPath.DISTILLED_MQL5),
        limitations=("Reference mean-aggregation baseline.",),
    ),
    _descriptor(
        "graph_neural_network_adapter",
        DeepFamily.GRAPH,
        "graph_neural_network",
        ("graph",),
        ("binary_classification", "regression", "ranking"),
        ("graph_batch", "topology_version", "node_masks"),
        ("score", "probability", "value", "rank_score"),
        native=False,
        dependency_profile="ucee-graph",
        exports=(ExportPath.ONNX,),
        parameters={"message_passing": "sage", "hidden_size": 32, "layers": 2},
        limitations=("Explicit non-graph and deterministic graph baselines are required."),
    ),
    _descriptor(
        "deterministic_regime_kmeans",
        DeepFamily.REGIME_ANOMALY,
        "deterministic_kmeans",
        ("tabular", "multi_view"),
        ("regime_gating", "novelty"),
        ("features", "cluster_support", "ordered_rows"),
        ("regime", "probability", "fallback"),
        parameters={"k": 3, "minimum_support": 10},
    ),
    _descriptor(
        "cusum_change_point",
        DeepFamily.REGIME_ANOMALY,
        "two_sided_cusum",
        ("sequence", "tabular"),
        ("novelty", "regime_gating"),
        ("ordered_values", "known_time_cut"),
        ("change_score", "alarm_index"),
    ),
    _descriptor(
        "distance_novelty",
        DeepFamily.REGIME_ANOMALY,
        "standardized_distance",
        ("tabular", "multi_view"),
        ("novelty", "regime_gating"),
        ("train_only_center_scale",),
        ("novelty_score", "abstention"),
        parameters={"quantile": 0.95},
    ),
    _descriptor(
        "gaussian_hmm_adapter",
        DeepFamily.REGIME_ANOMALY,
        "gaussian_hmm",
        ("sequence", "tabular"),
        ("regime_gating",),
        ("ordered_features", "state_count", "seed_control"),
        ("regime_probability", "transition_state"),
        native=False,
        dependency_profile="ucee-deep",
        exports=(ExportPath.NATIVE_JSON,),
        limitations=("State-identity stability and transition audits are mandatory."),
    ),
    _descriptor(
        "autoencoder_novelty_adapter",
        DeepFamily.REGIME_ANOMALY,
        "compact_autoencoder",
        ("tabular", "sequence", "image"),
        ("novelty",),
        ("train_only_representation", "reconstruction_error"),
        ("novelty_score", "abstention"),
        native=False,
        dependency_profile="ucee-deep",
        exports=(ExportPath.ONNX,),
        limitations=("Novelty threshold must be fitted without final-test access."),
    ),
    _descriptor(
        "late_weighted_fusion",
        DeepFamily.MULTI_VIEW_FUSION,
        "validation_weighted_late_fusion",
        ("multi_view",),
        ("binary_classification", "regression", "ranking"),
        ("view_predictions", "missing_view_policy"),
        ("fused_value", "uncertainty", "abstention"),
        parameters={"missing_policy": "abstain"},
    ),
    _descriptor(
        "stacked_linear_fusion",
        DeepFamily.MULTI_VIEW_FUSION,
        "oof_only_stacking",
        ("multi_view",),
        ("binary_classification", "regression"),
        ("oof_view_predictions", "missing_view_policy"),
        ("fused_value",),
        parameters={"alpha": 0.001},
        limitations=("Base predictions must be out-of-fold."),
    ),
    _descriptor(
        "gated_cross_attention_adapter",
        DeepFamily.MULTI_VIEW_FUSION,
        "gated_cross_attention",
        ("multi_view",),
        ("binary_classification", "regression", "multi_task"),
        ("view_masks", "view_identity", "known_time_cut"),
        ("fused_representation", "uncertainty"),
        native=False,
        dependency_profile="ucee-deep",
        exports=(ExportPath.ONNX,),
        limitations=("Admitted only after late-fusion uplift and view-ablation evidence."),
    ),
    _descriptor(
        "linear_teacher_student_distillation",
        DeepFamily.TRANSFER_COMPRESSION,
        "teacher_student_linear_distillation",
        ("tabular", "multi_view"),
        ("regression", "binary_classification"),
        ("teacher_oof_predictions", "student_features"),
        ("student_state", "fidelity_report"),
        exports=(ExportPath.DISTILLED_MQL5,),
        limitations=("Fidelity does not replace economic qualification."),
    ),
    _descriptor(
        "symmetric_int8_quantization",
        DeepFamily.TRANSFER_COMPRESSION,
        "symmetric_int8",
        ("sequence", "image", "graph", "multi_view"),
        ("runtime_compression",),
        ("frozen_weights",),
        ("quantized_weights", "parity_report"),
        exports=(ExportPath.DISTILLED_MQL5,),
    ),
)

BY_KEY = {descriptor.key: descriptor for descriptor in CATALOG}
BY_FAMILY = {
    family: tuple(descriptor for descriptor in CATALOG if descriptor.family is family)
    for family in DeepFamily
}
